### ISSUE TITLE
The notification(s) doesn't send to "Owner" 

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#1000]
**Steps to reproduce:**

1. Open the nonconformity  (6-step workflow)
2. Indicate the relevant standard ( standard has the relevant owner)
3. Complete it and check the owner's (of the standard)  email 

**Expected result:**

The notification message is sent to an email address of the owner

**Actual result:**

An owner of the standard didn't receive the notification message  "to remind them to update standards"

https://drive.google.com/file/d/1gLbRA643VIDeUwFQkMC9MMzBgoE2v6Gc/view?usp=sharing

**Comment by RustamJS** [comment]
@Dartv if I understand correctly, nope. I didn't receive the message. Can you send me an example of this message, please/ if you have ( had received it previously) of course )

**Comment by Praxie** [comment]
Hi Steve, could you specify messages, that should be sent to the Owner of the risk/nonconformity/pg for the following scenarios:

Final approval to close this nonconformity.
Final approval to close this risk.
Final approval to close this potential gain.

**Comment by Dartv** [comment]
@sives 

- Should this notification be sent as both email and desktop notification?
- Should the standard's owner receive this notification if he's the same person who approved the document?

**Comment by sives** [comment]
@Praxie  The issue reported by RustamJS seems to relate to a very specific situation where an Owner of a Standard doesn't receive a notification to remind him to update that Standard.

Here are my specifications of notification details to deal with this:


Email title:
Notification to update <SOP33> <title of standard>
Email text:
You are the Owner of standard <SOP33> <title of standard>, linked to nonconformity <NC44>.  Actions related to this nonconformity have now been completed and <NC44> has now been closed.  Please take this opportunity to update the standard.  This update should include any changes to relevant policies or processes that would improve the quality of the outputs in the future. 

Go to this standard (note to developer - this is a clickable link)


Desktop notification title:
Notification to update <SOP33> <title of standard>

Desktop notification text:
You are the Owner of standard <SOP33> <title of standard>, linked to nonconformity <NC44>.  Actions related to this nonconformity have now been completed and <NC44> has now been closed.  Please take this opportunity to update the standard

Go to this standard (note to developer - this is a clickable link)

@Dartv Yes, this notification should be sent as both email and desktop notification (in common with all other short notifications in Plio).  The standard owner should receive the notifications even if he is the same person that approved the final action and closed the nonconformity.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1120

**Comment by Praxie** [comment]
![screen shot 2018-05-30 at 8 07 51 pm](https://user-images.githubusercontent.com/2095940/40735912-25f8d5a0-6445-11e8-9fc8-bb6feeb54668.png)

**Comment by sives** [comment]
Mike - you need to remove the bracket characters in the actual email text.  I only included these to show that the text contained within the brackets was variable.

**Comment by Dartv** [comment]
We need come up with something common for all variables. I suggest `{variable}` because it's close to js syntax.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1149

**Comment by sives** [comment]
{variable} works for me.  Will use this naming standard in future spec documents

**Comment by Praxie** [comment]
@sives e.g. "...of standard {standard type abbreviation} {name of standard}, linked to..."

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/07/18 - 05/31/18
Work session total: 8:38:32

Grand total: 8:38:32
