### ISSUE TITLE
The text appears again in "Standards Types" subform after deletion 

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#1001]
**Steps to reproduce:**

1. Open the Org settings after that "Standards types"
2. Add the standard type with short name
3. Click to another one standard 
4. To delete the short name of the previous standard and click to another one

**Expected result:**

The "Short name" field empty after deletion  

**Actual result:**

Text recovers in the "Standards Types" subform after deletion 

https://drive.google.com/file/d/1VZzi1Wt_8VGkKhBClNLAwt2YBGM_5PCR/view?usp=sharing

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1139

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/07/18 - 05/29/18
Work session total: 10:33:17

Grand total: 10:33:17
