### ISSUE TITLE
The letters are deleted automatically in the "Standards sections" sub card

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#1002]
**Steps to reproduce:**

1. Open the Org settings and after that "Standards sections" sub card
2. Add several new sections
3. Try to add the new letters to every standard section  

**Expected result:**

The entered letters have not be deleted 

**Actual result:**

The letters are deleted automatically, and after first activating the field.

https://drive.google.com/file/d/1YAEsch1KEuq5d2UNh4DSSXDSIVv0qBJo/view?usp=sharing

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1063

**Comment by Praxie** [comment]
I still can reproduce this issue. https://gyazo.com/8bc06c8b842951d43db5cddae5b36de2

Though it doesn't happen during normal behavior, so I'm keen to close this issue.

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/15/18 - 05/15/18
Work session total: 4:50:00

Grand total: 4:50:00
