### ISSUE TITLE
User is able to create the nonconformity without "Title" 

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#1003]
**Steps to reproduce:**

1. Open the "Add nonconformity" form 
2. Enter some text in the "Title" field after that in the "Description" field
3. Delete the title text and click "Save" button 

**Expected result:**

The error message appears that "Title" field is mandatory

**Actual result:**

User can create the nonconformity without a title, and after creating, the "Title" field contains previously entered text
The same effect with risk and potential gain

https://drive.google.com/file/d/1XILIrxDwasDZa4FvVCAglh2uUz13jo9a/view?usp=sharing

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1027

**Comment by Praxie** [comment]
![screen shot 2018-05-17 at 10 27 19 pm](https://user-images.githubusercontent.com/2095940/40199228-7c6ef104-5a21-11e8-8cc6-dd5d1d6f6361.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/07/18 - 05/07/18
Work session total: 1:36:50

Grand total: 1:36:50
