### ISSUE TITLE
Incorrect messsage error in the Edit form

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#1009]
**Steps to reproduce:**

1. Open the "Edit user" form after that "Contact details" sub-card
2. Click to "Add another phone number" button and add the phone
3. Clouse and again open the "Contact details" sub-card
4. Delete the "Number" and try to save it

**Expected result:**

Have to be the correct message error

**Actual result:**

Appears: "Unknown validation error" message 

![image 3](https://user-images.githubusercontent.com/34645257/39700996-26beadc4-5208-11e8-9817-4db5d09e1c5c.png)
**Video:**
https://drive.google.com/file/d/1Lj00-_raTee1DrX7mX2cEdsrbv5rXg3V/view?usp=sharing

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1018

**Comment by Praxie** [comment]
@sives can we use this message in case the phone number will be set to a blank value?
![screen shot 2018-05-17 at 10 33 47 pm](https://user-images.githubusercontent.com/2095940/40199513-6a39b450-5a22-11e8-8288-e70ffa391ec5.png)

**Comment by sives** [comment]
No, this message is too confusing to the user.  A user should expect to be able to enter a new phone number in this field and then remove the number directly from that field, and then close the card without any problems.  Therefore, we should allow the user to save a blank value.  I suggest we treat a blank value as a valid value.

**Comment by sives** [comment]
@dartv OK I understand. So we need a better solution for the user than “” is not a valid phone number. This is a rather cryptic and unfriendly message for the typical business user.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1133

**Comment by Praxie** [comment]
![screen shot 2018-05-30 at 8 12 50 pm](https://user-images.githubusercontent.com/2095940/40736143-d85c88ea-6445-11e8-8549-1ba1c0c6f8bc.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/07/18 - 05/24/18
Work session total: 1:20:39

Grand total: 1:20:39
