### ISSUE TITLE
The "email address" field doesn't have a validation 

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#1011]
**Steps to reproduce:**

1. Open the "Invite users" form 
2. Enter invalid email address (for example: "a@a")

**Expected result:**

The error message appears about the valid email address 

**Actual result:**

Can invite user with invalid email address ,

![image 7](https://user-images.githubusercontent.com/34645257/39702666-403f34de-520e-11e8-8852-d3c7ad308d8b.png)

**Comment by Dartv** [comment]
I agree, RFC compliant email regex is too big and slow and as Mike said the validation is there already.
I just modernized the form and fixed a few bugs with it and online users section https://github.com/Pliohub/Plio/pull/1021

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/08/18 - 05/08/18
Work session total: 3:27:07

Grand total: 3:27:07
