### ISSUE TITLE
The link "	Go to this action" for  PA, CA doesn't redirect 

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#1013]
**Steps to reproduce:**

1. Open the notification letter from "Plio" about CA or PA in your email
2. Click to "Go to this action" 

**Expected result:**

The links have to redirect to a relevant page of the CA or PA

**Actual result:**

The link doesn't redirect to CA or PA 

https://drive.google.com/file/d/1bcKNjdZwb-GqNKPKmBq6EfLXkSZ7g5J1/view?usp=sharing

**Comment by Dartv** [comment]
Works fine for me. Are you testing this on staging or live app? Because it redirects you to app.pliohub.com

**Comment by RustamJS** [comment]
@Dartv  Exactly, I tested on staging, but link wants to redirect to "app" .

**Comment by Dartv** [comment]
That's because we have no deployed instance for background app, which sends emails, for staging. Should be fine on live
