### ISSUE TITLE
The "New risk" sub-card hides after clicking the "Save" button

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#1014]
**Steps to reproduce:**

1. Open the  "Create Standard" form, fill in with valid data and click "Save" button
2. Open the "Risk" sub-card 
3. Click to "Add a new risk" and click "Save" button

**Expected result:**

The error message appears (like "Title is required")

**Actual result:**

A sub-card is closed after clicking to "Save" button

https://drive.google.com/file/d/113wy0NaRbsW1t-nOMwl3cD7kiQdjE1MK/view?usp=sharing

**Comment by Dartv** [comment]
Already fixed

**Comment by Praxie** [comment]
https://gyazo.com/69ca41ffc76d0be0ed396ad8ba3e8f99
