### ISSUE TITLE
The lessons do not display in the nonconformity page

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#1020]
**Steps to reproduce:**

1. Open the nonconformity 
2. Open the  "Edit" form of the nonconformity
3. Add the several "Lessons learned" 
4. Come back to nonconformity page

**Expected result:**

The lessons should have displayed on the nonconformity page
 
**Actual result:**

The lessons didn't display on the nonconformity page

https://drive.google.com/file/d/1nD0Eg7D3uXFfJgN_gzdDtXThm3UuF7ss/view?usp=sharing

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1022

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/08/18 - 05/08/18
Work session total: 0:10:41

Grand total: 0:10:41
