### ISSUE TITLE
Should make a drop-down dialog more obvious.

### ISSUE THREAD

**Issue by Ulfhar** [Pliohub/Plio#1023]
It very hard for users to guess that this object is a drop-down.

![plio](https://user-images.githubusercontent.com/25507879/39760298-a47ccb30-52dd-11e8-9c16-ba9819d0626e.png)

**Comment by Dartv** [comment]
There is an arrow to indicate dropdown... I think we can close this @Praxie

**Comment by Ulfhar** [comment]
@Dartv Yes, but this arrow positioned near the right edge of the page, just this fact indicate on some problem with visual perception + we have the gray arrow on the gray background, I guess you understand what I'm talking about. 
I just inform, that for UX it would be fine to make this feature more visible. 
@Praxie fyi

**Comment by Dartv** [comment]
Plio also has help center for these
https://app.pliohub.com/help-center/ugedahGqwcY84fSKh
