### ISSUE TITLE
Doesn't display as a pointer  UI [Safari]

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#1025]
**Steps to reproduce:**

1. Open the Org settings and open the "Nonconformity guidelines" sub-card 
2. Try to scale the size of any text window 

**Expected result:**

Have to change from text pointer to active pointer

**Active result:**

A text pointer didn't change to active pointer

https://drive.google.com/file/d/1W5zg0I7oAGYy_G9Xyqj6EvXG0fPOfO0l/view?usp=sharing

**Comment by Dartv** [comment]
This is rendered by the browser itself and is not part of HTML, therefore it cannot be styled via CSS
No reason to bother with js also...
