### ISSUE TITLE
Can't change owner [Create Standard]

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#1026]
![image](https://user-images.githubusercontent.com/34645257/39766577-48ebeeee-52ed-11e8-85b7-e926eb69d4a9.png)

**Steps to reproduce:**

1. Open the create form of "Standards"
2. Try to change the "Owner" field

**Expected result:**

A selection works rightly from drop-down 

**Actual result:**

User can not select the owner of the standard from the first time, please see below

https://drive.google.com/file/d/1tFxphJFvqf-godNHatEFX6hm6tcI-JMO/view?usp=sharing

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1037

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/09/18 - 05/09/18
Work session total: 2:02:58

Grand total: 2:02:58
