### ISSUE TITLE
Notification disappear too fast

### ISSUE THREAD

**Issue by Ulfhar** [Pliohub/Plio#1030]
Actual result:
To read notification is impossible in fact. Notification disappear too fast
![plio pngapolasdpol png](https://user-images.githubusercontent.com/25507879/39813588-b2dae07e-5399-11e8-820f-b92435520baa.png)

Expected Result:
Notification time is too short, users don't have time to read, it would be great to make this behavior similar to validation errors.  I guess in this case timing has been selected very comfortable.
![aaaa](https://user-images.githubusercontent.com/25507879/39813203-2bf7f67e-5398-11e8-8dc2-9663fd00d937.png)

**Comment by sives** [comment]
@Praxie haven't we seen this issue before with browser notifications?  Is there a way that we can display the notification messages on screen for longer before they automatically disappear?

**Comment by Dartv** [comment]
@sives can we close this?

**Comment by sives** [comment]
Let's increase to 6 seconds, and then we can close it

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1141

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/29/18 - 05/29/18
Work session total: 0:16:25

Grand total: 0:16:25
