### ISSUE TITLE
Should decrease clickable area for top drop-down

### ISSUE THREAD

**Issue by Ulfhar** [Pliohub/Plio#1031]
And it would be nice to increase the area of "Back Arrow" button

![1](https://user-images.githubusercontent.com/25507879/39813777-79740b5c-539a-11e8-8933-1cbd98c5b373.png)

**Video Attachment**
https://drive.google.com/file/d/1pCkYCQqHJRVe2hzMkAn6dqafd8dPZQov/view

**Comment by Dartv** [comment]
@Praxie @sives

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1051

**Comment by sives** [comment]
This issue is incorrectly titled - surely it should be "Should increase clickable area....." Or am I misunderstanding something?

**Comment by Dartv** [comment]
The title is correct. it means that the clickable area for dropdown is too wide. "Standards - by section" in this case

**Comment by sives** [comment]
OK, I was just focussing on the red box on the left hand side of the header bar

**Comment by Dartv** [comment]
@sives is this okay? Green and blue areas are clickable:
![](https://i.gyazo.com/0e2725b6bf5b5813e7a7f1c75a4646a0.png)
![](https://i.gyazo.com/18751985adff1687dc4e23bfe365d742.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1052

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/10/18 - 05/10/18
Work session total: 0:40:45

Grand total: 0:40:45
