### ISSUE TITLE
A workflow doesn't change after changing the magnitude [Nonconformity]

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#1033]
**Steps to reproduce:**

1. Create the nonconformity with "Critical" magnitude (6 steps work flow) 
2. Open the edit form of this nonconformity 
3. Change the magnitude to " Major" (3 steps work flow)

**Expected result:**

Have to change a workflow from three steps to six steps workflow

**Actual result:**

A nonconformity didn't change a workflow to six steps workflow,

https://drive.google.com/file/d/1Ed1qEzN2BSiIjxog_D985pxt5XXgu7oO/view?usp=sharing

**Comment by Dartv** [comment]
@sives this is quite heavy actually. Should we waste time on this? The easiest solution I can think of is just disabling editing of magnitude for ncs and Initial categorization for risks.

**Comment by sives** [comment]
@Dartv I agree with you.  Disabling the editing of magnitude is a nice way to side-step the problem.  The user can always delete the NC or Risk and start over again with a different magnitude.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1053

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/10/18 - 05/10/18
Work session total: 0:28:14

Grand total: 0:28:14
