### ISSUE TITLE
The fields are not changed to non editable (hidden) after approval [Nonconformity]

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#1034]
**Steps to reproduce:**

1. Create the nonconformity (six steps workflow)
2. Complete the "Root cause analysis" 

**Expected result:**

The "Root cause analysis" fields have to be hidden after completion it (RCA)

**Actual result:**

The  "Root cause analysis" fields are editable by users after completion 

![image](https://user-images.githubusercontent.com/34645257/39816205-3fbf7776-53a3-11e8-98c9-2e3628e506c9.png)

**Comment by Dartv** [comment]
This has always been like . There is no code for that so it's not even a bug. @sives is this necessary?

**Comment by Dartv** [comment]
@sives can we close this?

**Comment by sives** [comment]
Yes, it's fine to leave this, we can close it
