### ISSUE TITLE
Duplicating of Key Goals

### ISSUE THREAD

**Issue by Ulfhar** [Pliohub/Plio#1035]
**Steps to reproduce:**

1. Open Create Key Goal menu
2. Fill all required fields
3. Click few times on Save button

![sdfdasfa](https://user-images.githubusercontent.com/25507879/39816658-89adb0f4-53a4-11e8-8004-662c1008b009.png)

**Video Attachment**
https://drive.google.com/file/d/1HVfVObiRM4k91FjszlML7gntJGM5-Rx1/view

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/09/18 - 05/09/18
Work session total: 0:28:53

Grand total: 0:28:53
