### ISSUE TITLE
The Key Goals buttons are displayed  by far shorter on the workspace

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#1036]
**Actual result:**

1. Create the key goals with time interval between start and end date a few days ( 2 days for instance)
2. Open the workspace 
3. Click to created key goal

**Expected result:**

 The "Key Goals" button's names are displayed fully ( for example: "Add action", "Add milestone" and "Edit key goal" )

**Actual result:**

The "Add action", "Add milestone" and "Edit key goal" buttons are displayed  by far shorte, see below 

![image](https://user-images.githubusercontent.com/34645257/39816908-55c47ba0-53a5-11e8-9f12-1e99e4dc6568.png)

**Comment by Dartv** [comment]
Note that this can also happen: ![](https://i.gyazo.com/7862c5993debee1ad565582ce4bd5014.png)
Idk what we can do about that honestly

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1049

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/10/18 - 05/10/18
Work session total: 0:23:12

Grand total: 0:23:12
