### ISSUE TITLE
Duplicateing of Departments. 

### ISSUE THREAD

**Issue by Ulfhar** [Pliohub/Plio#1038]
**Steps to reproduce**

1. Open Edit standard dialog
2. Create a new department
3. Click a few time on Create button

**Video Attachment**

https://drive.google.com/file/d/16htXLOtK2U4kJYRTWc0E5c65EOkC3poa/view

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1044

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/09/18 - 05/09/18
Work session total: 1:02:56

Grand total: 1:02:56
