### ISSUE TITLE
List of users aren't shown [ Key Goal, Action]

### ISSUE THREAD

**Issue by Ulfhar** [Pliohub/Plio#1041]
**Steps to reproduce:**

Click on Name of Key Goal
Click Add action
Click on  "To be completed by"/"Owner" drop-downs

**Actual result**:

![asdasdasdasdasdasda](https://user-images.githubusercontent.com/25507879/39820801-55100bf2-53af-11e8-80cb-9e326f5335b2.png)

https://drive.google.com/file/d/1s8-4U51LXhD0Fv_9voeYCA_q25Eu1Cg5/view

**Comment by Dartv** [comment]
Works fine for me. Can you check the network tab in chrome after opening the dropdown to see if there's errors? One of the requests should be red ![](https://i.gyazo.com/8d9b78021d7d4627b22b357df885518f.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1045

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/09/18 - 05/10/18
Work session total: 1:57:03

Grand total: 1:57:03
