### ISSUE TITLE
Can't disable sound (as notification)

### ISSUE THREAD

**Issue by Ulfhar** [Pliohub/Plio#1042]
Steps to reproduce:
1.In browser setting, block all permitions from Plio

**Actual result**

If user blocks notification from Plio, the notification sound will stay.

**Expected result:**
Any notification should be disabled

> Environment:
> Google Chrome: 66.0.3359.139

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1047

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/10/18 - 05/10/18
Work session total: 0:23:32

Grand total: 0:23:32
