### ISSUE TITLE
Redesign the "Completed or deleted goals" section according to the prototype 

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1056]
The "Completed or deleted goals" section should be nested in the Key goals section and have a chevron icon instead of "View all items" link.

https://gyazo.com/840db8fa191aa4aad58372a0df075648

**Comment by Praxie** [comment]
@sives if there will be no active Key goals and the user will have a superpower to create Key goals, then there will be something like that:

![2018-05-14 13 06 28](https://user-images.githubusercontent.com/2095940/39991276-a469ff66-5777-11e8-9812-ec9daf65e309.jpg)

If there will be no active Key goals and the user won't have a superpower to create Key goals, then the whole Key goals section will be hidden and it won't be possible to view Completed & deleted key goals. 

What should we do? Should we write in the header "Key goals (0 open, 4 completed, 3 deleted)" and display a chevron?

**Comment by Praxie** [comment]
Also, we have a default number of Key goals in Org settings. Do we need to count all Key goals? (Open, deleted and completed)

**Comment by Praxie** [comment]
@sives 

"For the default number of Key goals to display on the Home screen in Org settings, this is intended to refer only to Open Key goals."

Please note that chevron is used to not only expand open Key goals, but also to show/hide Completed&deleted Key Goals. If the default number of Key goals won't be reached then there will be no way to open Completed&deleted Key goals. It's a UI/UX bug.

**Comment by sives** [comment]
The default number of Key goals should be displayed by default i.e. the user should not need to click on a chevron to be able to see the first several Key goals.  

 Opening the Completed & deleted goals is a separate subsection and expansion of this subsection is triggered by clicking on a different chevron, shown at the bottom of the default list of Key goals.  Let's discuss on Skype if this is not clear.

**Comment by Dartv** [comment]
This was really hard to implement https://github.com/Pliohub/Plio/pull/1062

**Comment by sives** [comment]
@Dartv Yes, I can believe it. I'm trying hard to avoid distracting users with less-important information on this screen, hence my focus removing non-informative information.  Apologies for making extra work.

**Comment by Praxie** [comment]
![screen shot 2018-05-25 at 11 57 45 am](https://user-images.githubusercontent.com/2095940/40535815-dc945c80-6012-11e8-83f6-7439976458a2.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/11/18 - 05/15/18
Work session total: 8:45:55

Grand total: 8:45:55
