### ISSUE TITLE
Update styles of the Key Goals section according to the prototype

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1057]
Fonts and paddings are bigger. Please check css properties here http://ui2.isometrica.io/ui1-3/#/deletedGoals

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/11/18 - 05/11/18
Work session total: 0:59:33

Grand total: 0:59:33
