### ISSUE TITLE
Update the Overdue actions section according to the prototype

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1058]
Actually, only link colors are updated.
![screen shot 2018-05-11 at 12 00 03 pm](https://user-images.githubusercontent.com/2095940/39916344-de816098-5512-11e8-8a05-61fbec477cce.png)

http://ui2.isometrica.io/ui1-3/#/deletedGoals

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1061

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/11/18 - 05/11/18
Work session total: 0:25:00

Grand total: 0:25:00
