### ISSUE TITLE
Critical bug. Some organization homepages are broken on the staging server

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1059]
![screen shot 2018-05-11 at 1 14 13 pm](https://user-images.githubusercontent.com/2095940/39919728-40e5f5dc-551d-11e8-93d3-f28fd77b5247.png)
![screen shot 2018-05-11 at 1 14 26 pm](https://user-images.githubusercontent.com/2095940/39919730-4234097e-551d-11e8-95bc-808355913f77.png)

**Comment by Dartv** [comment]
Just run migrations to the latest version
