### ISSUE TITLE
PG 6-step status stuck at Open - analysis completed, action(s) need to be added

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1064]
![screen shot 2018-05-16 at 2 07 50 pm](https://user-images.githubusercontent.com/2095940/40113616-be374ae2-5912-11e8-812d-85e031c91f28.png)
![screen shot 2018-05-16 at 2 09 30 pm](https://user-images.githubusercontent.com/2095940/40113625-c4b0a9cc-5912-11e8-90c5-096b5d61b436.png)

Test it here:
https://staging.pliohub.com/184/non-conformities/LoFJL2xLmkzkYzC6i

**Comment by Dartv** [comment]
@sives @Praxie potential gain can only have general actions. General actions are 3-step workflow only. It means potential gain cannot have a 6-step workflow.

**Comment by sives** [comment]
@Dartv You are absolutely correct, this part of the Screen Spec v1.32 specification document is incorrect. Potential gains can only use the 3-step workflow process.  I will correct this error in Screen Spec v1.33.

**Comment by sives** [comment]
Is there still a problem with adding General actions to a PG?

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1128

**Comment by Praxie** [comment]
![screen shot 2018-05-30 at 8 34 13 pm](https://user-images.githubusercontent.com/2095940/40737237-d750596a-6448-11e8-9056-fb7b85745c29.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/23/18 - 05/24/18
Work session total: 2:46:05

Grand total: 2:46:05
