### ISSUE TITLE
User is undefined in browser/email notifications 

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1065]
![screen shot 2018-05-16 at 2 04 22 pm](https://user-images.githubusercontent.com/2095940/40113680-efeaa070-5912-11e8-9dbd-b494a8cf125e.png)

**Comment by Praxie** [comment]
![screen shot 2018-05-30 at 8 39 19 pm](https://user-images.githubusercontent.com/2095940/40737487-8f992da8-6449-11e8-8fed-ab634c979a7c.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/23/18 - 05/23/18
Work session total: 0:04:10

Grand total: 0:04:10
