### ISSUE TITLE
Month labels (June, July etc) incorrect abbreviation

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1069]
Labels should use normal 3 letter abbreviation pattern e.g. Jun, Jul, Aug as in rest of Plio system

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1090

**Comment by Dartv** [comment]
@sives wait, where is it wrong?

**Comment by sives** [comment]
The screen sketches and UI prototype display the month names in the format Oct, Jan, Apr, Jul, etc.
The staging system displays the months with the full name e.g. June, July, August

**Comment by Dartv** [comment]
The logic behind these labels are actually quite complex. For example, they skip duplicate months for shorter time scale, render next year instead of month, display the actual date for 1 month time scale, etc. We'll have to reinvent the wheel to simply format the label. Is it worth the effort?

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/17/18 - 05/17/18
Work session total: 1:28:01

Grand total: 1:28:01
