### ISSUE TITLE
Month labels placement on Home screen

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1070]
It would be better to place these labels above the list of Key goals, to the right hand side of the "9 goals" label, instead of underneath the list of Key goals

**Comment by Dartv** [comment]
@sives We can't place them to the right of "9 goals" label. However, we can place them underneath it.

**Comment by sives** [comment]
OK, then let's leave this as it is for now, that's fine.

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/17/18 - 05/17/18
Work session total: 0:17:15

Grand total: 0:17:15
