### ISSUE TITLE
Remove the "Plan in place" field from the General action card

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1071]
After entering 20 or more real General actions into Shift Bioscience organisation, I realised that this field is really not needed at all for General actions.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1091

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/17/18 - 05/17/18
Work session total: 0:45:54

Grand total: 0:45:54
