### ISSUE TITLE
Missing IDs for General actions

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1072]
In the spec, there is a requirement to create unique IDs for General actions and - once the action has been created - to display these IDs in a box at the left hand side of the Title text box in the edit mode of the General action card.  

(To see how this works already in Plio, just add a Corrective action to a nonconformity in Plio.  The corrective action is always numbered with a unique ID which is displayed in a box at the left hand side of the Corrective action card).

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1092

**Comment by Praxie** [comment]
![screen shot 2018-05-18 at 6 58 31 pm](https://user-images.githubusercontent.com/2095940/40245162-7b0b85f0-5acd-11e8-90a2-1751209a22de.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/17/18 - 05/17/18
Work session total: 0:47:10

Grand total: 0:47:10
