### ISSUE TITLE
Milestone symbol colour problem

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1074]
The amber colour for an open milestone (orange diamond symbol) is currently identical to the amber colour for an open action.  This causes problems when adding actions and milestones to a Key goal timeline.  The milestone symbol is quite likely to overlap one of the action symbols (see image) making it hard for the user to figure out what is going on.

I suggest making a amber colour of an open milestone always a shade darker than the amber colour for an action, so that when the action overlaps the milestone it is possible to see the two different objects.

![screen shot 2018-05-16 at 16 08 31](https://user-images.githubusercontent.com/2330529/40125755-958f7a54-5923-11e8-857e-c0ab6172ee35.png)

**Comment by Dartv** [comment]
@Praxie I need that color's hex value

**Comment by Dartv** [comment]
@sives what are the colors for action timeline symbols? I can't find them on basecamp

**Comment by Dartv** [comment]
https://i.gyazo.com/e9d0584b037487b15d848a3419ebe2f8.png

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1125

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/18/18 - 05/23/18
Work session total: 1:42:07

Grand total: 1:42:07
