### ISSUE TITLE
Moving from field to field when entering data

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1075]
It would be nice if the tab key could be used to step quickly from one field to the next when entering data into a card or subcard

**Comment by Dartv** [comment]
Works fine for me aside from the colorpicker because it's a custom component. What browser are you using? When does this happen?

**Comment by sives** [comment]
@Dartv Sorry, forgot to mention which browser.  I was testing on latest version of Safari.   The tab key works fine when using Chrome.

**Comment by Praxie** [comment]
@sives it works in Safari Version 11.1. It's the latest version.

**Comment by Praxie** [comment]
https://i.gyazo.com/71a658391eadb1581312eb041d38fc17.gif

**Comment by sives** [comment]
@Dartv It's working for me too now.
