### ISSUE TITLE
Extend max length of a General action title to 120 characters

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1076]
After entering more than 20 real General actions in the system it became apparent that 80 characters is too short a max length.  Please extend this to 120 characters

**Comment by sives** [comment]
General actions are a bit of a special case because of the way they are used on the Home screen.  I would not increase the limit for the other ones.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1095

**Comment by Praxie** [comment]
@Dartv there is still a 80 chars limit for GA title.
Also, Key Goal name input should have a maxlength html property.

**Comment by Dartv** [comment]
No, there isn't. I just tested

**Comment by Praxie** [comment]
@Dartv I meant the Work inbox screen. You're probably testing the Key goals section that uses a React component for adding actions. Also, there's no maxlength property too.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1143

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/17/18 - 05/30/18
Work session total: 1:14:32

Grand total: 1:14:32
