### ISSUE TITLE
Change the default completion date for an action to next day

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1077]
After entering a lot of real actions into the system, it became annoying to have to keep changing the default completion date for a general action.  Many actions are of short completion duration, and it is best to default to tomorrow's date for these actions rather than today's date.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1105

**Comment by Praxie** [comment]
![screen shot 2018-05-30 at 8 28 39 pm](https://user-images.githubusercontent.com/2095940/40736942-13aa4e12-6448-11e8-9e1d-8c24e01a551c.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/18/18 - 05/18/18
Work session total: 1:02:44

Grand total: 1:02:44
