### ISSUE TITLE
Incorrect "N goals" text label on home screen

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1078]
The "N goals" text label (at the top left hand side of the list of Key goals timelines) should be labelled as "N Key goals" as specified in the requirements document and  UI screen sketches.

**Comment by Praxie** [comment]
![screen shot 2018-05-29 at 11 04 22 pm](https://user-images.githubusercontent.com/2095940/40682521-a57840f6-6394-11e8-8a35-6ba63d650e8d.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/17/18 - 05/17/18
Work session total: 0:09:37

Grand total: 0:09:37
