### ISSUE TITLE
"Org settings" label is confusing to users

### ISSUE THREAD

**Issue by unplugged** [Pliohub/Plio#108]
Users don't understand what "Org" means.  Let's change the label to just "Settings" in the LHS dropdown on the Home screen, and also in the header bar of the Org settings screen.

**Comment by Praxie** [comment]
@sives Maybe, "Organization settings" is a better choice. "Settings" sounds like something global that convers the whole Plio application, but not the organization itself.

**Comment by sives** [comment]
I agree - lets go with "Organization settings"

**Comment by Praxie** [comment]
Resolved in the current release
