### ISSUE TITLE
Incorrect text labels in Key goals subcard in Org settings

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1080]
As specified in the Standard subcard spec:

2nd field should not be "Number of key goals" but should be "Key goals displayed by default"

3rd field should not be "Number of completed & deleted goals" but should be "Completed/deleted goals displayed by default"

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1100

**Comment by Praxie** [comment]
![screen shot 2018-05-30 at 8 14 27 pm](https://user-images.githubusercontent.com/2095940/40736215-136b6bc2-6446-11e8-8958-71c90f25843a.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/17/18 - 05/17/18
Work session total: 0:15:39

Grand total: 0:15:39
