### ISSUE TITLE
Defaults for workflow steps in Org settings are incorrect

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1082]
Nonconformities categorised as Major or Critical should default to a 6-step workflow in the Workflow steps subcard in Org settings.  Currently they default to a 3-step workflow, is only appropriate for minor Nonconformities.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1107

**Comment by Dartv** [comment]
Note: this will only work for new organizations

**Comment by sives** [comment]
OK, that's fine

**Comment by Praxie** [comment]
![screen shot 2018-05-30 at 8 13 38 pm](https://user-images.githubusercontent.com/2095940/40736179-f4ae2d46-6445-11e8-8232-297855cbc9b6.png)
