### ISSUE TITLE
Blank entry in left hand side list view in Work inbox

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1084]
After entering 20 or more actions into the Shift Bioscience organisation, nonconformities and risks and then opening the Work inbox, I noticed that there was one blank item in the "My current" left hand side list view (see image).  This item is dated 18 May 2018 but has no traffic light symbol and no title. 

The full dataset needs to be displayed for each item, there should be no blank fields.

![screen shot 2018-05-16 at 16 29 37](https://user-images.githubusercontent.com/2330529/40127326-06555f80-5927-11e8-99af-9ed3b17f6de1.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1109

**Comment by Praxie** [comment]
![screen shot 2018-05-29 at 10 45 26 pm](https://user-images.githubusercontent.com/2095940/40681533-1353cba2-6392-11e8-9c53-ef3b987c031f.png)
![screen shot 2018-05-29 at 10 45 58 pm](https://user-images.githubusercontent.com/2095940/40681535-14dd1ee2-6392-11e8-864c-e6ad008c44d6.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/18/18 - 05/18/18
Work session total: 1:07:54

Grand total: 1:07:54
