### ISSUE TITLE
Incorrect colour for milestone symbol on Key goals timeline

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1086]
When a milestone is first entered, its status will be "open - awaiting completion".

In the specification, the colour for open milestones is null i.e. the milestone diamond should be the same colour as the Key goal timeline on which it sits.  It should only change colour to amber on the day that it is scheduled for completion.

![screen shot 2018-05-16 at 16 41 47](https://user-images.githubusercontent.com/2330529/40127967-75111a80-5928-11e8-92b8-d9c2f9b555ac.png)

**Comment by Dartv** [comment]
When was the second option added? We have 3 statuses in the system right now.

**Comment by sives** [comment]
This requirement went in on 23rd March after an early review of the UI prototype for the Key goals timelines.  

See the change control list at the top of the Standard subcard spec document: 
"23 Mar 2018 - 1.41 - added an extra status of 'Awaiting completion today' to Milestone statuses (SC43 sub card) and clarified colour coding of statuses."

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1124

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/18/18 - 05/23/18
Work session total: 2:13:22

Grand total: 2:13:22
