### ISSUE TITLE
Default notification sound in User preferences

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1087]
Currently the default value for the notification sound in "My preferences" is none.  It should be the first items on the selection list i.e. Arpeggio.   This will ensure that the default behaviour is to always play a sound when a notification event happens.

**Comment by Dartv** [comment]
I just created a new user and the default option is set to "Graceful"

**Comment by sives** [comment]
@Praxie I tested it again and it seems to be working fine now
