### ISSUE TITLE
List of active Plio organisations - date problem

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1088]
This list is a master admin feature which is accessed by first selecting the Plio organisation, then clicking on the LHS dropdown in the header bar, then clicking on "Plio organisations".

The "Created date" is sometimes more recent than the "Last accessed" date, which is a logical impossibility.  (for examples, go to CU196 - Kangaroo Travel and CU198 - baay).

Also, it would be nice to add another category called "Past customer" to the list of customer types, so that I can correctly categorise any customers that stop their subscriptions.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1122

**Comment by Praxie** [comment]
![screen shot 2018-05-29 at 10 55 26 pm](https://user-images.githubusercontent.com/2095940/40682020-675a61a6-6393-11e8-9626-b58681b25487.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/23/18 - 05/23/18
Work session total: 0:40:56

Grand total: 0:40:56
