### ISSUE TITLE
Simplified completion of own actions - default value

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1089]
In the Workflow steps subcard in Org settings, the option labelled "Simplified completion of own actions" should default to selected (i.e. "On") as written in the Step 4 specification document.  Currently the default value is set to non-selected (i.e. "Off").

**Comment by Dartv** [comment]
It defaults to "On" for new organizations

**Comment by sives** [comment]
OK, that's great

**Comment by Praxie** [comment]
![screen shot 2018-05-30 at 8 13 38 pm](https://user-images.githubusercontent.com/2095940/40737296-fb170042-6448-11e8-8a75-b7aef93e20a3.png)
