### ISSUE TITLE
6 step workflow not working correctly

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1097]
I created a new Nonconformity in Plio, called "Test 3", linked to Standards document "1.1 Scope", which was owned by myself.  I carried out a Root Cause Analysis.  I added 2 Corrective actions and 1 Preventative action to this Nonconformity, all assigned to myself.  I completed all the Corrective and Preventative actions, everything was working as expected.  

I then received a notification for "NC6 - Request for approval to close this non-conformity".  I opened this item in the Work inbox.  Instead of seeing the red To DO panel with an expected prompt of  "To do    Closing of nonconformity to be approved by Steve Ives by 20 May 2018" I saw a different and incorrect
 prompt relating to update of the linked standard (see attached image).

The notification to update the standard (which comes after the final step in a 6-step workflow) should come one step later in the workflow, after the owner of the nonconformity has given approval to close it (see Screen sketch 1.2a Problem & corrective action workflow - full 6 steps v1.24 on Basecamp in  Files). The red To Do panel should be worded as follows:

 "To Do  (Standard owner) to update the standard titled "(standard title)" by 20 May 2018 to incorporate any identified improvements following on from the closing of (NC44)"   

Underneath this red To Do panel, the relevant standard document should be displayed.

![screen shot 2018-05-17 at 13 53 15](https://user-images.githubusercontent.com/2330529/40179387-19782da8-59dc-11e8-8c70-a9b338469087.png)

**Comment by sives** [comment]
@Dartv @Praxie  Sorry but the wording of your feedback is not clear, so it's hard for me to comment on it.  Which notifications are there?  The correct ones or the incorrect ones?  When you say there were never such work items in the work inbox, this cannot be correct because the screenshot shows the specific work item I am describing that is incorrect. 

I can't just close this issue because the behaviour of the system is clearly incorrect vs the intended behaviour and the Plio spec documents.  I don't understand why this is such a lot of work to fix.  Perhaps you could explain to Mike, and then I will discuss possible options in our Friday call

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1135

**Comment by Praxie** [comment]
@sives we decided that the Update of standard notification should open the Standards screen with a proper standard selected. Can we keep it this way or move it to Step 5?

**Comment by Dartv** [comment]
Notifications are correct. The text in to do panel was incorrect.

**Comment by sives** [comment]
OK great, that's an easy fix then

**Comment by Praxie** [comment]
![screen shot 2018-05-30 at 8 36 38 pm](https://user-images.githubusercontent.com/2095940/40737364-3075e366-6449-11e8-9af4-3083c5013526.png)

**Comment by sives** [comment]
The text in the to do panel isn't quite right.  It should read as "Closing of nonconformity {NC12} to be approved by {Mike Rokosh} by {date}.

**Comment by Praxie** [comment]
@sives unfortunately, it's pretty hard to do this because we don't load the sequential ID of documents there. It's one of small changes that cause a lot of problems.

**Comment by sives** [comment]
@Praxie  Can we insert the nonconformity title instead?  i.e. "Closing of nonconformity titled {NC title text} to be approved by {user} by {date}"

**Comment by Praxie** [comment]
@sives it won't change the complexity. I'd estimate it in 6 hours.

**Comment by sives** [comment]
@Praxie OK, then let's stick with the information that's already contained in the text string but change the wording slightly:

To do panel:
Closing of this nonconformity to be approved by {Mike Rokosh} by {date].

Email/desktop notification title:
Please approve closing of this nonconformity

Email/desktop notification text:
Please approve the closing of this nonconformity, which is owned by {user}, by {date}.  
(*note to developer: provide button near this text for the user to click to go directly to that nonconformity)

**Comment by Praxie** [comment]
I've updated the texting a bit.
![screen shot 2018-06-15 at 4 55 38 pm](https://user-images.githubusercontent.com/2095940/41471685-0449077a-70bd-11e8-89ba-18f7d6bd7634.png)

**Comment by Praxie** [comment]
Email/desktop:

title: "Please approve closing of {Document ID} {Document Name}"
text: "{Assigner Full Name} assigned you to approve closing of {Type of document e.g. 'nonconformity'} {Document ID} {Document Name}"

**Comment by Praxie** [comment]
![screen shot 2018-06-15 at 5 17 25 pm](https://user-images.githubusercontent.com/2095940/41472904-730bda90-70c0-11e8-919f-62085665879d.png)

**Comment by Praxie** [comment]
The problem with this text
"Please approve the closing of this nonconformity, by {date}."

...is that we can't access the {date} property. With no data property, it'll look the same as the title. That's why I changed it.

**Comment by Praxie** [comment]
@sives can we close it?

**Comment by sives** [comment]
The treatment you propose above is fine for Step 4a (I'm a bit confused though, because you already have the date displayed in the screenshot above!)

**Comment by sives** [comment]
Email/desktop:

title: "Please approve closing of {Document ID} {Document Name}"
text: "{Assigner Full Name} assigned you to approve the closing of {Type of document e.g. 'nonconformity'} {Document ID} {Document Name}"

**Comment by sives** [comment]
Inserted the extra word "the" between approve and closing

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/24/18 - 06/15/18
Work session total: 2:21:06

Grand total: 2:21:06
