### ISSUE TITLE
No margins between notify changes users in the Key Goal card

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1101]
![screen shot 2018-05-17 at 10 04 37 pm](https://user-images.githubusercontent.com/2095940/40198218-6a26af76-5a1e-11e8-9862-13001f85915e.png)

It should be like this:

![screen shot 2018-05-17 at 10 06 08 pm](https://user-images.githubusercontent.com/2095940/40198248-8971875c-5a1e-11e8-82e0-3974657da58a.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1103

**Comment by Praxie** [comment]
![screen shot 2018-05-29 at 10 56 42 pm](https://user-images.githubusercontent.com/2095940/40682082-9291bef0-6393-11e8-9b79-9acfd4ca9391.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/18/18 - 05/18/18
Work session total: 0:23:32

Grand total: 0:23:32
