### ISSUE TITLE
Standards screen - word search bug

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1102]
In Chrome I go into the Southwind organisation and look at the Standards documents by Type, selecting the "Standards - by type" view from the header bar dropdown menu.

I search for "management".  3 results come up.  One is a COB document, one is a POL document, one is a PRO document.  I can only click on the first result.  If I click on the 2nd or the 3rd, the focus immediately jumps back to the first.

In Safari I see the same behaviour.

**Comment by Dartv** [comment]
Unfortunately, the LHS section is full of legacy code and the redirect and search logic is quite complex, so we'll have to trade-off auto redirect to the first search result if the currently selected item is not present in the search results.
If we want a reliable and easy to maintain LHS section, we'd have to rewrite it completely.

**Comment by sives** [comment]
The most important thing is to display the correct number of results and not miss out any documents that include the search word, even if we have to make trade-offs in less significant areas e.g. auto redirect to the first search result

**Comment by Praxie** [comment]
![screen shot 2018-05-30 at 8 20 18 pm](https://user-images.githubusercontent.com/2095940/40736510-e5089b82-6446-11e8-8254-487807f7d6a5.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/18/18 - 05/21/18
Work session total: 1:38:44

Grand total: 1:38:44
