### ISSUE TITLE
Month labels under Key goals timelines getting chopped

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1106]
The month labels that are displayed just underneath the Key goals timelines on the Home screen are not displaying correctly.  The descenders (e.g. the lowest portion of the "g" character in "August") are getting chopped off.

This problem can be seen in both Safari and Chrome.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1136

**Comment by Praxie** [comment]
![screen shot 2018-05-29 at 11 05 32 pm](https://user-images.githubusercontent.com/2095940/40682770-48952d1c-6395-11e8-884b-66c7941bb462.png)
