### ISSUE TITLE
Org name is missing from notification emails

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1111]
@Praxie @Dartv   Previously all notifications included information on which Plio organisation the notification related to (org name in brackets in the email sender field).  I noticed today that this stopped happening on 20th April.  Now it is not possible to tell which organisation a notification relates to.  (This is also a problem for browser desktop notifications as well). I've attached screenshots showing the old correct behaviour and the new incorrect behaviour.  This is a top priority issue because it is affecting the live system as well as the staging system.

![screen shot 2018-05-21 at 11 20 07](https://user-images.githubusercontent.com/2330529/40302990-f83c1752-5ce8-11e8-840d-fbb6269105da.png)

![screen shot 2018-05-21 at 11 13 28](https://user-images.githubusercontent.com/2330529/40302930-bb2dee62-5ce8-11e8-8d62-5b82dee70e67.png)

**Comment by Dartv** [comment]
The name is stripped because it's not valid.
> from - The e-mail address of the sender. All e-mail addresses can be plain 'sender@server.com' or formatted 'Sender Name <sender@server.com>'

https://github.com/nodemailer/mailcomposer/blob/v4.0.1/README.md

**Comment by Dartv** [comment]
We can wrap it in quotes, however: `From: "Plio (TEST)" <noreply@pliohub.com>`

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1115

**Comment by Praxie** [comment]
@Dartv  There's no Org name:
![screen shot 2018-05-30 at 8 15 24 pm](https://user-images.githubusercontent.com/2095940/40736260-38642a2c-6446-11e8-8717-c730c4df01b8.png)

**Comment by Praxie** [comment]
![screen shot 2018-05-30 at 8 40 54 pm](https://user-images.githubusercontent.com/2095940/40737559-c9b440e0-6449-11e8-8017-177b25555317.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/21/18 - 05/21/18
Work session total: 1:18:10

Grand total: 1:18:10
