### ISSUE TITLE
Shift Bioscience work inbox is empty in the Live app

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1114]
@Dartv  Could you investigate why work items aren't shown in the live application? I understand that GAs/PAs aren't supported but there are no NCs/PAs, and this is strange.

Staging: 
![screen shot 2018-05-21 at 2 25 30 pm](https://user-images.githubusercontent.com/2095940/40305382-07595df2-5d03-11e8-8843-0cc462f7ace7.png)

Live:
![screen shot 2018-05-21 at 2 25 37 pm](https://user-images.githubusercontent.com/2095940/40305388-0f1155e0-5d03-11e8-875d-e14b673489fc.png)

**Comment by Dartv** [comment]
@Praxie I have no access to this organization

**Comment by sives** [comment]
@Praxie Seems to be working fine now

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/21/18 - 05/21/18
Work session total: 1:05:20

Grand total: 1:05:20
