### ISSUE TITLE
Better labels needed for tooltips linked to Key goals symbols

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1117]
The tooltips labels need to be give more information about what they represent.  

Taking the user interface prototype labels (see http://ui2.isometrica.io/ui1-3/index.html) as examples:

Milestones:
Instead of "Find someone to run ad campaign" the label should be "Milestone: Find someone to run ad campaign - 15 Apr 2018"

Actions:
Instead of "Start campaign on Medium" the label should be "Action: Start campaign on Medium - 18 Apr 2018"

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1121

**Comment by Praxie** [comment]
![screen shot 2018-05-30 at 8 23 18 pm](https://user-images.githubusercontent.com/2095940/40736663-4ef70862-6447-11e8-9b3a-64521da8cd0e.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/22/18 - 05/23/18
Work session total: 0:38:03

Grand total: 0:38:03
