### ISSUE TITLE
Better help text needed in Org settings for Workflow steps

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1127]
Current help text:
Indicate whether you want Plio to use simple (3-step) or full (6-step) workflows for your nonconformity and risk-handling processes. If you wish, you can set simpler workflows for your less critical nonconformities and risks.

Desired help text:
Indicate whether you want Plio to use simple (3-step) or full (6-step) workflows for your nonconformity and risk-handling processes. If you wish, you can set simpler workflows for your less critical nonconformities and risks.  Plio always uses a 3-step workflow process for managing potential gains.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1130

**Comment by Praxie** [comment]
![screen shot 2018-05-30 at 8 31 56 pm](https://user-images.githubusercontent.com/2095940/40737121-83386c28-6448-11e8-92a7-455903327f8d.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/24/18 - 05/24/18
Work session total: 0:40:48

Grand total: 0:40:48
