### ISSUE TITLE
Support email address needs to be changed

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1129]
One of the Plio login screens contains my personal email address (steve.ives@pliohub.com) under the login fields.  This needs to be changed to "hello@pliohub.com".

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1132

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/24/18 - 05/24/18
Work session total: 0:13:41

Grand total: 0:13:41
