### ISSUE TITLE
General action cards respond very slowly in Work inbox

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1134]
Often when I go to the Work inbox on the staging system, and go to a General action item and click on "Edit", it will take 10 - 20 seconds to respond.  Other items in the Work inbox respond much faster.  I also see this problem sometimes when clicking on a General action work item link in an email notification.

**Comment by Dartv** [comment]
It definitely is strange. Doesn't happen locally though. Try testing this after next release
