### ISSUE TITLE
Statuses change with a delay

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1137]
@Dartv we already discussed this issue. Could you suggest a solution please?

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1140

**Comment by Dartv** [comment]
Statuses are handled in background app. There will always be a delay for the status to change.

**Comment by Praxie** [comment]
We agreed to not upgrade Meteor to 1.7 right away. We'll do that once it'll be a stable release.
Though we need to think of a workaround. Maybe there is one. @Dartv what do you think?

**Comment by Dartv** [comment]
We didn't have `MONGO_OPLOG_URL` set in staging settings. I think that was the problem.

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/29/18 - 06/01/18
Work session total: 3:16:23

Grand total: 3:16:23
