### ISSUE TITLE
Wrong alignment of icons on a timeline

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1138]
![screen shot 2018-05-25 at 12 27 48 pm](https://user-images.githubusercontent.com/2095940/40537220-0f3dbfce-6017-11e8-85f4-873fd689ee63.png)
The current day is 25/05/2018. The Milestone icon should be on the vertical line that means the current date, not after it.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1169

**Comment by sives** [comment]
@Praxie This seems to be a tricky issue to to fix, so I suggest we don't worry about it in Step 4a

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/29/18 - 05/30/18
Work session total: 3:26:50

Grand total: 3:26:50
