### ISSUE TITLE
Wrong behaviour of deleted actions

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1142]
@sives please take a look.
![screen shot 2018-05-29 at 7 04 03 pm](https://user-images.githubusercontent.com/2095940/40671142-b6c65cc4-6373-11e8-86f3-1db494e2b7f6.png)

**Comment by sives** [comment]
Looking at the Apiko QA comments, "My deleted actions" are actions that were assigned to me and were deleted - it doesn't really matter who deleted them, they should be in my deleted actions view if they were assigned to me at the time point of deletion.  So the QA person is correct, the action should be in the Team deleted actions under the Bogdan collapsible panel and not in the My deleted actions view.

**Comment by Dartv** [comment]
Why can't this be a step 5 issue?

**Comment by sives** [comment]
Because it is an incorrect behaviour of an existing feature which will definitely cause problems for users

**Comment by Dartv** [comment]
it's been like that from the beginning...

**Comment by sives** [comment]
Agreed. This is just the first time that it has been spotted in testing.  How many hours work is required to fix and re-test?

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1262

**Comment by Dartv** [comment]
@sives @Praxie This one is tricky. What do "actions that were assigned to me" mean? Remember, corrective and preventative actions can not only be assigned to "to be completed by" user but also "to be verified by". Also, if the item is completed user cannot see who this action was assigned to.

**Comment by sives** [comment]
@Dartv You make a good point.  Let's leave the system behaviour as it is and close the issue, no user has ever complained about it.
