### ISSUE TITLE
Key goals timeline - problem with very overdue actions

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1146]
An action that has become very overdue starts to move so far to the left on the Key goal timeline that the red action symbol is now only partially visible or not visible at all.   A not-yet-completed action symbol should always be displayed as a complete (not partial) symbol at the left hand side of the timeline, no matter how many days or weeks overdue it is.

For examples of partial symbols, see screenshot below, Key goals 6 and 9.

![screen shot 2018-05-31 at 16 18 56](https://user-images.githubusercontent.com/2330529/40791170-c009b746-64ee-11e8-8409-e66fe9c8b5f4.png)

**Comment by Dartv** [comment]
How is this a bug? Nothing in specification is written about that behavior. I could be wrong, though.
Same goes for milestones. Any milestone or action symbol that is not inside horizontal scale (3 month, 6 month, etc.) will not be rendered on the timeline.

**Comment by sives** [comment]
Yes, I would call it an "unforeseen UI issue" rather than a bug.  I will re-classify it as a UI enhancement request.

**Comment by Praxie** [comment]
@Dartv @Serhiy91 We identified a UI solution with the 2X-size red arrowhead on the left hand side of the Key goal line.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1170

**Comment by Praxie** [comment]
![screen shot 2018-06-14 at 7 32 05 pm](https://user-images.githubusercontent.com/2095940/41425529-b69734ec-7009-11e8-92d0-ffd7578ca8d8.png)

**Comment by Praxie** [comment]
@sives does it look good? 2x arrow is too big imo.

**Comment by Praxie** [comment]
Right now it's about x1.5

**Comment by sives** [comment]
OK let's go with 1.5x, it looks fine

**Comment by Serhiy91** [comment]
via Hubstaff
User: Serhiy Zinchuk

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 06/14/18 - 06/14/18
Work session total: 2:23:01

Grand total: 2:23:01
