### ISSUE TITLE
Notification emails contain superfluous quotation marks

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1147]
There should be no quotation marks around dates in notification emails (see example below: the beginning date and end date have quotation marks around them).

![screen shot 2018-05-31 at 16 24 29](https://user-images.githubusercontent.com/2330529/40791415-55a7917e-64ef-11e8-96d7-f4f25216a043.png)

**Comment by Dartv** [comment]
All other notifications have quotation marks around dates, not just goals

**Comment by sives** [comment]
OK, then this needs to be fixed.  I'm not sure why there should be quote marks.  I suspect that in one of my specification documents I used quote marks to specify variable contents of the field, and this was misinterpreted.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1148

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/31/18 - 05/31/18
Work session total: 1:03:20

Grand total: 1:03:20
