### ISSUE TITLE
Home screen icon panels not displaying at all - top priority bug

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1150]
In the latest 0.3.32 release, the icon panels are no longer displaying on the home screen, so it is not possible to access the main functions of the system.   I've labelled this as top priority because it stops me testing the rest of the system.  This happens with both Safari and Chrome, but with Chrome there is an additional problem - small rectangle symbols are being displayed instead of the proper symbols (see below - first image is with Safari, second with Chrome).

![safari - missing home screen icons bug](https://user-images.githubusercontent.com/2330529/40873642-4513122a-665c-11e8-90e0-eb1e36638c46.png)

![chrome - missing home screen icons bug](https://user-images.githubusercontent.com/2330529/40873644-498b2f7c-665c-11e8-946b-e1faec916729.png)

**Comment by Dartv** [comment]
@sives this is not a bug. The GraphQL server is down for some reason @Praxie. We can make it so even when the GraphQL server is down, users can use the rest of the system. Only home screen icons, goals and few other parts of the system are being handled in the GraphQL server, but we can just display default icons if we receive an error indicating that the server is down.

**Comment by sives** [comment]
@dartv @Praxie  is this GraphQL server managed manually by you and Mike, or is it part of the Galaxy platform-as-a-service system?  Is it possible to get diagnostic info to indicate why it might have gone down?

**Comment by sives** [comment]
Making the GraphQL server responsible for the home screen icons introduces a very undesirable fragility into the system.  Since GraphQL is relatively young software compared to the core Meteor platform it may be significantly less reliable. I will research online to see what other developers' experiences are with reliability

**Comment by Dartv** [comment]
I think the server is running but the settings Mike used when deploying new version are incorrect. And no, I have no access.

**Comment by Dartv** [comment]
Yep, I just checked. The browser tries to make the request to the wrong url. We changed our graphql endpoint a while ago.

**Comment by sives** [comment]
OK, good to know it's a simple fix!
