### ISSUE TITLE
Milestone and action labels on Key goals timelines

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1151]
Some labels on milestones and actions on the left hand side of Key goals timelines cannot be read properly, because the left hand edge of the label is situated outside the browser window boundary.

![screen shot 2018-06-07 at 21 16 20](https://user-images.githubusercontent.com/2330529/41123892-1bb4c8ca-6a98-11e8-8aec-d83e86403a8a.png)

**Comment by sives** [comment]
@Praxie I suggest that labels on the left hand side of the timeline are left-aligned to the edge of the corresponding symbol, labels in the middle are centre-aligned and labels on the right hand side of the timeline are right-aligned.  At the moment it looks as if labels are always centre-aligned to the symbol.

**Comment by sives** [comment]
Agreed to set max width of tooltip so that the long text strings break onto 2 or more lines

**Comment by Praxie** [comment]
![screen shot 2018-06-15 at 6 02 37 pm](https://user-images.githubusercontent.com/2095940/41475091-75178ad6-70c6-11e8-8091-97d432e8b460.png)
@sives can we just truncate the string? It's not a perfect solution, but it's not possible to set the mac width and break the string onto 2 lines. In Step 5 we can com up with a better solution.

**Comment by sives** [comment]
Yes, fine
