### ISSUE TITLE
Clicking on Key goal timeline should display modal

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1152]
In the prototype, clicking on the Key goal timeline displays the Key goals modal.  In the 0.3.35 system currently deployed, when you click on the timeline nothing happens. The Key goals modal is displayed only when you click on the circular symbol at the beginning of the time line.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1161

**Comment by sives** [comment]
@Praxie Looks good

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 06/08/18 - 06/08/18
Work session total: 1:20:04

Grand total: 1:20:04
