### ISSUE TITLE
Key goals don't always display in alphabetical order

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1153]
In the Shift Bioscience organisation, I added 2 test goals to the existing list of 9 key goals.  They were inserted between existing goal 8 and existing goal 9.  According the Step 4 requirements spec all Key goals should be displayed in alphabetical order.  If this rule was followed, then the 2 test goals (titled "Test goal" and "Test goal 2") should have been displayed after existing goal 9 (titled "9. Other")

![screen shot 2018-06-07 at 21 29 46](https://user-images.githubusercontent.com/2330529/41124471-f306caf2-6a99-11e8-8133-de5ad43dc878.png)

**Comment by Dartv** [comment]
They are sorted by priority and end date. That's what you asked for before.

**Comment by sives** [comment]
@Dartv   Sorry, you are absolutely right, I mis-remembered the specification
