### ISSUE TITLE
Potential fragility if Apollo GraphQL server becomes unresponsive

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1154]
Currently all our server processes are actively monitored so that if they go down or freeze for any reason, this is detected and they can be automatically restarted.  The Galaxy service handles this for the Meteor servers, and we have written some code to detect when our own background process code stops working.  However the new Apollo server does not have any such protection.  This will make our operational system significantly more fragile than previously, leading to increased unscheduled downtime.  We need to implement some kind of detection and restart capability.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1167

**Comment by Praxie** [comment]
![screen shot 2018-06-13 at 3 14 47 pm](https://user-images.githubusercontent.com/2095940/41350951-807117bc-6f1d-11e8-8332-4ac3e8e7b482.png)

**Comment by sives** [comment]
Do not include James Ives as a recipient any more when sending out this type of notification (status of background process notifications) since his email account has been deleted.

**Comment by Praxie** [comment]
Done

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 06/12/18 - 06/12/18
Work session total: 1:03:23

Grand total: 1:03:23
