### ISSUE TITLE
Deleting actions from Work inbox freezes UI

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1155]
When I deleted the General actions "Test 2" and "Test 3" in the "Work - my current" view, the user interface froze displaying the blue progress animation whilst in the act of deleting.  Reloading the page by using the browser's page reload function re-displayed the screen correctly, now without the deleted items.   When I went to the "Work - team current" view the delete function worked fine.  When I came back to the "Work- my current" view, the delete function worked fine again.   

![screen shot 2018-06-07 at 21 46 00](https://user-images.githubusercontent.com/2330529/41125549-b1c73a42-6a9c-11e8-9104-74bc14422613.png)

**Comment by Dartv** [comment]
Couldn't reproduce this. Maybe you lost internet connection during the process?

**Comment by sives** [comment]
The session wasn't lost in any irreversible way because I continued working with the system shortly after. I wonder if there is some kind of fragility in the way that this process is working between the browser and server?  For example there may be a very large number of transits between the browser and server to complete the task and if any one of these goes wrong for any reason then the task freezes.

**Comment by Dartv** [comment]
Should not happen anymore https://github.com/Pliohub/Plio/pull/1166

**Comment by Praxie** [comment]
@sives we've been able to reproduce this issue. It doesn't happen any more.

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 06/12/18 - 06/12/18
Work session total: 1:56:53

Grand total: 1:56:53
