### ISSUE TITLE
"Notify changes" section is in wrong place in cards

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1156]
The "Notify changes" section has been moved to the bottom of the list of subcard in the Edit mode of the Standards, Risks and Nonconformities cards, but it is still displayed in the old higher position in the Read mode of the cards.  The ordering of sections in the Read mode of the cards should be identical to the ordering in the Edit mode, so the "Notify changes" section should be moved down to the bottom of the card in Read mode also;

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1162

**Comment by sives** [comment]
Looks good

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 06/08/18 - 06/08/18
Work session total: 0:39:39

Grand total: 0:39:39
