### ISSUE TITLE
General action subcards - need to modify titles

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1157]
In the Potential gains card (in the Nonconformities & gains screen) the SC5 General action subcard should be titled "General action" instead of "Action" and the "Add action" text label on the button underneath the subcard should be titled "Add general action".

In the Key goals card the SC5 General action subcard should also be labelled "General action" instead of "Action" and the "Add a new action" text label on the button underneath the subcard should be titled "Add general action", to match the label in the equivalent subcard in the Potential gains card.

The "Actions" subcard title labels in both of these cards should not be changed.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1163

**Comment by Praxie** [comment]
![screen shot 2018-06-13 at 3 36 06 pm](https://user-images.githubusercontent.com/2095940/41351623-a4615dd8-6f1f-11e8-8bb6-ce8c5479d3dd.png)

**Comment by sives** [comment]
@Praxie Looks good

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 06/08/18 - 06/08/18
Work session total: 0:18:25

Grand total: 0:18:25
