### ISSUE TITLE
Top title field in the Risk subcard not displaying the correct dropdown list

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1158]
Referring to the Step 4 specification:

3. Enhancement to Risk subcard (SC5)

Add a selection drop box and button to the Risk name field, allowing the user to scroll through and select from the existing set of Risks, or to type in the first few letters of the risk to narrow the selection down further.  (This enhanced version of the subcard to be used in both the existing Standards card and the new Key event card).

When I go to the Standards screen and add a new Risk to a Standards card, a dropdown selection box is presented to the me but it contains a list of Milestones rather than a list of existing Risks (see below).  It should show the list of titles of previously created Risks.

![screen shot 2018-06-07 at 22 21 36](https://user-images.githubusercontent.com/2330529/41126961-2fab393c-6aa1-11e8-8ddd-b72af518b6d6.png)

**Comment by Dartv** [comment]
What you're seeing is browser's autocompletion. To see existing risks click on the "Existing" tab at the top of the subcard.

**Comment by sives** [comment]
@Dartv thanks, you are right, it works totally correctly
