### ISSUE TITLE
List of superpowers in User details card in wrong order

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1159]
The ordering of the list of superpowers in the User details card does not match the specification (see below)  Also, in Read mode the ordering should be the same as in Edit model.  

The correct order (and capitalisation treatment) should be:

Create & edit standards documents
Create & delete key goals
View all team actions
Can complete any action
Invite users
Delete users
Edit user superpowers
Change organization settings

![screen shot 2018-06-07 at 22 30 16](https://user-images.githubusercontent.com/2330529/41127434-d4fbf68c-6aa2-11e8-88e2-95ee1e4116c9.png)

**Comment by Dartv** [comment]
We decided to rename "Create and edit Key goals" to "Create and delete Key goals" because of the changes to how this role actually works.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1164

**Comment by Praxie** [comment]
![screen shot 2018-06-13 at 3 38 38 pm](https://user-images.githubusercontent.com/2095940/41351701-e1597982-6f1f-11e8-9e92-46f0d9d30c8f.png)
![screen shot 2018-06-13 at 3 38 42 pm](https://user-images.githubusercontent.com/2095940/41351702-e179172e-6f1f-11e8-9e61-4b83fafd22e9.png)

**Comment by sives** [comment]
@Praxie The list is still not quite correct in the read mode of the card.  "View all team actions" should be below "Create & delete key goals":

![screen shot 2018-06-15 at 09 43 29](https://user-images.githubusercontent.com/2330529/41459189-b1adb600-7080-11e8-8db3-f9df0aa51289.png)

**Comment by Praxie** [comment]
@sives the requirement was to keep active superpowers on top of the list.
That's why "View all team actions" is above "Create & delete key goals"

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 06/08/18 - 06/08/18
Work session total: 0:13:27

Grand total: 0:13:27
