### ISSUE TITLE
Incorrect help text in Potential gains guidelines subcard

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1160]
In Org settings, in the Potential gains guidelines subcard, the help text is incorrect.  It should refer to potential gains and not to nonconformities.

The correct wording should be:
"Help users to indicate the magnitude of this potential gain , by giving them some clear guidelines relating to the estimated benefits to be gained."

![screen shot 2018-06-07 at 22 37 21](https://user-images.githubusercontent.com/2330529/41127650-835c64f0-6aa3-11e8-808f-6ba3591b3f1b.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1165

**Comment by Praxie** [comment]
![screen shot 2018-06-13 at 3 40 39 pm](https://user-images.githubusercontent.com/2095940/41357669-5b540b4e-6f2f-11e8-81a0-600f2cd010dc.png)

**Comment by sives** [comment]
OK looks good

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 06/08/18 - 06/08/18
Work session total: 0:27:52

Grand total: 0:27:52
