### ISSUE TITLE
Some message items get deleted from discussion threads

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1168]
I entered a fairly long message item into a discussion thread in the Standards card.  Immediately after clicking on the return key to send the message item, the message disappeared.  I think this may be related to how long the message text is when typed in, because shorter messages seem to work fine.

**Comment by Praxie** [comment]
@sives  ![screen shot 2018-06-13 at 3 18 41 pm](https://user-images.githubusercontent.com/2095940/41350825-11d4ec52-6f1d-11e8-918e-57b0419a7acf.png)

I think that this limitation was part of the Step 2b specification.

**Comment by Praxie** [comment]
@sives I'll set the maximum to 10 000 characters to not cause any vulnerabilities.

**Comment by sives** [comment]
@Praxie OK, good solution
