### ISSUE TITLE
Canvas screen and layout

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1182]
http://ui2.isometrica.io/ui1-3/canvas.html

Acceptance criteria:

1. There should be a new route - {BaseURL}/{OrgID}/canvas.
2. There should be 9 sections on the screen. Each section should take a title as a parameter. The position and order of these sections should be hardcoded because it's a standard.
3. Each section should have a "+" icon on the top RHS.
4. Each section should have a list of items (hardcoded at this stage).
5. Each section should have a list of linked documents at the bottom (hardcoded at this stage).
5. Each section should have a chart icon at the bottom RHS. The chart icon component should take the type of chart as a parameter and display a proper icon (fa-th-large or fa-pie-chart). 
3. The screen should be responsive. Check out the prototype for example.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1204

**Comment by Dartv** [comment]
Note: drag & drop wasn't mentioned in requirements, so I didn't implement it. Same for the navbar.
Navbar needs to be rewritten as it uses blaze right now.

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 07/06/18 - 08/06/18
Work session total: 15:48:37

Grand total: 15:48:37
