### ISSUE TITLE
Add Key partner 

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1184]
Acceptance criteria:

1. The help panel in the header should contain the dummy text with no subcards. We'll implement this later.
2. Title. 80 characters limit. Re-use the existing component. Mandatory.
3. Created by. Select a user within the organization. Re-use the existing component. Mandatory.
4. Color. Re-use the existing component from Key goals with the same colors. Mandatory.
5. Criticality. Mandatory.
6. Level of spend. Mandatory.
7. Notes. Free text. Optional.
8. The "More" panel **shouldn't be displayed at all** because we display it only in the Edit mode.

**Comment by Dartv** [comment]
@Praxie @sives we need to rename "Created by" field because we already use that field at db level for every record. If we override it, then we won't be able to see who actually created the document.

**Comment by sives** [comment]
Let's use the word "Originator", similar to how we label the equivalent fields in the Nonconformities and Risks cards

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1207

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 07/11/18 - 07/16/18
Work session total: 10:19:56

Grand total: 10:19:56
