### ISSUE TITLE
Adding file attachments to documents in the Standards screen

### ISSUE THREAD

**Issue by unplugged** [Pliohub/Plio#119]
When you are adding a lot of documents to this screen with file attachments, the system is quite awkward to operate.

If possible we should move the attachment button selector (the button containing 3 options:  URL link, Attachment, video) to the initial smaller Compliance standard card that first pops up when the user clicks the "Add" button.   It should be positioned below the Status field.   

Also, the ordering of the button options should be changed to Attachment - URL link - video, and the default selection should be Attachment.

The Issue number field should be removed from the initial smaller card, and displayed only in the larger card that the user sees later.   Users will not need to set the issue number at this very first stage.  It should still default to 1 when it is displayed in the larger card.

**Comment by Praxie** [comment]
@sives I think that it makes sense to keep only mandatory fields in the "Add document" card. Attachments aren't mandatory.

**Comment by sives** [comment]
We should make the "Attachment - URL link -video" selection option mandatory, so that it appears on the initial card that is displayed to the user.   This fits in with how the system is intended to be used.

**Comment by Praxie** [comment]
**v0.2.41** feature

**Comment by sives** [comment]
Not working properly.  When you add a Word document, it takes a long time to upload it, and it doesn't convert to HTML.

**Comment by Praxie** [comment]
@sives I think that the current approach is much better because it doesn't block the UI. 
> What should happen is that the file saving progress bar is displayed within the initial (small) Standards card, and then the text icon appears when saving is complete.

In this way the user will need to wait until the file is uploaded and converted to docx (it may take quite a lot time if the file is big)

**Comment by sives** [comment]
Why not at least start the uploading as soon as the user has completed clicked on Add attachment?   I agree that it's good not to block the UI, but can't we have the best of both worlds?  We can show the upload progress happening as soon as the user has clicked on Add attachment, and if the user then clicks on Close, then the process just keeps going.

**Comment by sives** [comment]
The current behaviour is inconsistent between different cards and subcards.  In the Files subcard, when the user adds a file they get an immediate triggering of the upload process and the progress bar.

**Comment by sives** [comment]
We agreed to give the user additional information on what the system is doing.  

After the user clicks on the Add file button, he sees the message "File will be uploaded when you click on the Save button".  This message is displayed in black text immediately underneath the rectangular file icon.  

If the user is adding a Word file, they see this message "File will be uploaded and rendered as  HTML when you click on the Save button"

**Comment by sives** [comment]
There is no visual indication that the conversion of the .docx file to HTML is actually happening.  Nothing seems to be happening and then suddenly the rendered document is displayed.  We used to have a spinner which showed when the system was converting.  

Once you add the .docx source file and click the Save button, the larger version of the Standards card is displayed.  Perhaps we need to add a spinner to the right hand of the Source file icon that starts to spin as soon as the file upload progress bar has completed?

**Comment by Praxie** [comment]
@RevelsGit could you look if it's possible to show a conversion visual indication if this situation?
Currently, the conversion indicator is destroyed if the Edit modal is closed. It doesn't appear after the user re-opens modal window.

**Comment by RevelsGit** [comment]
Yes! It is possible with viewmodel's `share`. https://github.com/Pliohub/Plio/pull/287

**Comment by Praxie** [comment]
**v0.2.51**
