### ISSUE TITLE
Add Value propositions

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1190]
**Acceptance criteria:**

- The help panel in the header should contain the dummy text with no subcards. We'll implement this later.
- Title. 80 characters limit. Re-use the existing component. Mandatory.
- Created by. Select a user within the organization. Re-use the existing component. Mandatory.
- Color. Re-use the existing component from Key goals with the same colors. Mandatory.
- Matched to. The list of customer segments (titles). Optional **(the prototype is wrong)**. There should be a "None" option in the dropdown. If there is no customer segments, then there should be a placeholder saying "No customer segments available".
- Notes. Free text. Optional.
- The "More" panel shouldn't be displayed at all because we display it only in the Edit mode.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1214

**Comment by Dartv** [comment]
@Praxie @sives I propose that we make `Matched to` field as select input (with dropdown). There are a few reasons:
1. We can't load customer segments when user clicks on the normal select. It means that we'll have to load data when user opens the modal which may cause unnecessary data usage.
2. If the list grows big, it will be hard for the user to find specific item. But if we use select input, he can just search for it.

One drawback is that we can't display 'No customer segments available' placeholder, so I suggest we just default to 'None' option and don't display the placeholder.

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 07/19/18 - 07/19/18
Work session total: 0:30:00

Grand total: 0:30:00
