### ISSUE TITLE
Add Customer relationships

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1191]
**Acceptance criteria:**

The help panel in the header should contain the dummy text with no subcards. We'll implement this later.
Title. 80 characters limit. Re-use the existing component. Mandatory.
Created by. Select a user within the organization. Re-use the existing component. Mandatory.
Color. Re-use the existing component from Key goals with the same colors. Mandatory.
Notes. Free text. Optional.
The "More" panel shouldn't be displayed at all because we display it only in the Edit mode

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1212
