### ISSUE TITLE
Add Customer segments

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1193]
**Acceptance criteria:**

- The help panel in the header should contain the dummy text with no subcards. We'll implement this later.
- Title. 80 characters limit. Re-use the existing component. Mandatory.
- Created by. Select a user within the organization. Re-use the existing component. Mandatory.
- Color. Re-use the existing component from Key goals with the same colors. Mandatory.
- Matched to. The list of value propositions (titles). Optional **(the prototype is wrong)**. There should be a "None" option in the dropdown. If there is no value propositions, then there should be a placeholder saying "No value propositions available".
- % of market size. Number (0-100). Mandatory.
- Notes. Free text. Optional.
- The "More" panel shouldn't be displayed at all because we display it only in the Edit mode.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1215

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 07/19/18 - 07/20/18
Work session total: 3:15:47

Grand total: 3:15:47
