### ISSUE TITLE
Add Revenue streams

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1194]
**Acceptance criteria:**

- The help panel in the header should contain the dummy text with no subcards. We'll implement this later.
- Title. 80 characters limit. Re-use the existing component. Mandatory.
- Created by. Select a user within the organization. Re-use the existing component. Mandatory.
- Color. Re-use the existing component from Key goals with the same colors. Mandatory.
- % of revenue. **Number (0-100) validation**. Mandatory.
- % of profit. **Number (0-100) validation**. Mandatory.
- Notes. Free text. Optional.
- The "More" panel shouldn't be displayed at all because we display it only in the Edit mode

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1216

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 07/21/18 - 07/21/18
Work session total: 1:11:03

Grand total: 1:11:03
