### ISSUE TITLE
Edit Key partner

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1195]
**Acceptance criteria:**

- The main form at the top should stay the same as in the Add modal.
- There should be More/Less switcher.
- Actively manage subcard. **No need to implement the functionality for now, let's do this later on.**
- Files subcard. Re-use the existent component.
- Notify changes. Re-use the existent component. **No need to implement the notification feature now, let's implement it for all sections at once later on.**

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1252

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 07/31/18 - 08/01/18
Work session total: 3:46:02

Grand total: 3:46:02
