### ISSUE TITLE
Edit Channels

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1201]
**Acceptance criteria:**

- The main form at the top should stay the same as in the Add modal.
- There should be More/Less switcher.
- Actively manage. **No need to implement the functionality for now, let's do this later on.**
- Files subcard. Re-use the existent component.
- Notify changes. Re-use the existent component. **No need to implement the notification feature now, let's implement it for all sections at once later on.**

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1267
