### ISSUE TITLE
Drag & Drop for reordering section items

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1205]
**Acceptance criteria:**

It should be possible to reorder items **within** each section.
It should have the same ui effects as in the prototype.
The order should be saved into the database and restored after page reloading.

**Comment by Dartv** [comment]
It should be saved for hardcoded items? Makes no sense to me

**Comment by Dartv** [comment]
@sives @Praxie can these lists get big (50+ items)? We may need to implement virtualized lists then to avoid performance issues.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1208

**Comment by Dartv** [comment]
Note: reordering still doesn't work as expected because of hard-coded data. But we have all the functionality needed for it. We should wait until we display the actual data. We just need to pass `onChange` event to `CanvasSectionItems` that receives item's `_id` and a new index and handle server-side update.

**Comment by sives** [comment]
@dartv the lists of items in each canvas section are not expected to exceed 50 items, but some lists may grow as long as 30-40 items

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1240
https://github.com/Pliohub/plio-util/pull/26

**Comment by Serhiy91** [comment]
via Hubstaff
User: Serhiy Zinchuk

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 07/26/18 - 07/27/18
Work session total: 5:41:43

Grand total: 10:36:02

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 07/16/18 - 08/01/18
Work session total: 4:54:19

Grand total: 10:36:02
