### ISSUE TITLE
Slow to enter screens

### ISSUE THREAD

**Issue by unplugged** [Pliohub/Plio#124]
It now takes quite a few seconds (6 to 10 sec) to enter the Standards screen and display the first Standard card on the right hand side.  It doesn't seem to get any faster when you repeat the operation. Hopefully it should be possible to get this down to 2-3 seconds.  

It is also quite slow to enter the Non-conformities and the Risks screens, though not quite as slow as the Standards screen

**Comment by RevelsGit** [comment]
https://trello.com/c/mMlNA1S0/325-i124-slow-to-enter-screens

**Comment by sives** [comment]
Performance is now very good!
