### ISSUE TITLE
Redesign Header header and update the dropdown menu

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1241]
http://ui2.isometrica.io/ui1-3/

**Comment by Praxie** [comment]
Yes we do need the "Org settings" option because in some cases the canvas screen will be the main screen by default. (For users that came from the canvas screen landing page).
"Create new plio organization" is also required in this way. What do you think, @sives? 
@Dartv can we keep the Blaze version of header? Why not?

**Comment by Dartv** [comment]
Because header is the oldest component of them all. It uses bad practices, loads a lot more data than it needs, etc. We really need to rewrite it. We can keep blaze modals like org settings and user preferences for now though.

**Comment by sives** [comment]
@Dartv @Praxie Yes, as Mike points out for some users the canvas screen will be the main screen by default, and they may not even use the dashboard screen.  Happy to consider re-writing it with Reach/GraphQL but there is a fixed price for Step 5 so cost implications have to be considered.

**Comment by Praxie** [comment]
<img width="1440" alt="screen shot 2018-09-03 at 12 59 22 am" src="https://user-images.githubusercontent.com/2095940/44961151-a2c7a600-af14-11e8-9188-dca214d088d8.png">
