### ISSUE TITLE
Update reactstrap to version 5.0.0

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1271]
Current version of reactstrap that we use (5.0.0-alpha4) has critical bug. It throws an error and locks ui when you try to open a modal multiple times.

**Comment by Serhiy91** [comment]
![image](https://user-images.githubusercontent.com/13336284/44083337-658d4b44-9fbc-11e8-8773-f064070c0d49.png)

**Comment by Serhiy91** [comment]
All InputGroupAddon lost styles (see screenshot above)

**Comment by Serhiy91** [comment]
InputGroupAddon has required "addonType" prop in new version of reactstrap.
`addonType: PropTypes.oneOf(['prepend', 'append']).isRequired`

**Comment by Serhiy91** [comment]
![image](https://user-images.githubusercontent.com/13336284/44193156-9b458600-a13a-11e8-8c43-b2c7bc5c4c1d.png)

**Comment by Dartv** [comment]
![](https://i.gyazo.com/c34e2fe4f4953a3a1a2f1239d4e0d8a5.png)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1288
