### ISSUE TITLE
Add a "Description" field to CAs and PAs

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#128]
Add a description field to just below the Corrective action/Preventative action title field, same as description field in Non-conformities.  It's not a mandatory field.

**Comment by Praxie** [comment]
**v0.2.43** fetature

**Comment by sives** [comment]
Sorry - I should have made this clearer - the description field needs to be there when you first start filling in the subcard (even though it is not mandatory), so that the user only has to save/close the subcard once.  At the moment that have to Save and Close a new corrective action in a 2 stage operation.  This is not good, because corrective actions are small things that you want to enter quickly.

**Comment by Praxie** [comment]
@RomanValihura put the "Description" field into the Actions_Create template as well.

**Comment by Praxie** [comment]
https://github.com/Pliohub/Plio/pull/266

**Comment by Praxie** [comment]
@RomanValihura Desciption is not saved after the action is created.
![c6f58dec0f332aa8cf2d9543ae3169fa](https://cloud.githubusercontent.com/assets/2095940/19920521/dee2ff6a-a0e1-11e6-95a7-79c4c691ee05.gif)

**Comment by RomanValihura** [comment]
Fixed https://github.com/Pliohub/Plio/pull/297

**Comment by Praxie** [comment]
**v0.2.51**

**Comment by sives** [comment]
Looks good.
