### ISSUE TITLE
BUG: canvas screen fetches wrong organization

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1283]
@Serhiy91 discovered this bug

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1284

**Comment by Praxie** [comment]
@Serhiy91 I can't reproduce this on the staging server. Canvas is always the same org as the main screen.

**Comment by Praxie** [comment]
Could you explain this bug?

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 08/15/18 - 08/15/18
Work session total: 0:53:12

Grand total: 0:53:12
