### ISSUE TITLE
Dual sign-on paths

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1300]
Look for **6. Dual sign-on paths**.
https://basecamp.com/1896845/projects/11083679/documents/13035477.

URL examples:
https://staging.pliohub.com/sign-up?type=design
https://staging.pliohub.com/sign-up?type=operations

**Comment by Praxie** [comment]
@sives you mentioned that there may be different texting on the sign up screen for each path. Is that right? If so, what should we display?

**Comment by sives** [comment]
@Praxie There are intended to be two different sign-up pathways.  One will take the user from the business operations product page on the web site to the signup screen and then immediately on to the Business operations screen (i.e. the current home screen).  The other will take the user from the business model canvas page on the web site two the sign up screen and then directly to the Business design screen (i.e. the canvas screen).  Actually the sign up screen will be identical in both cases but there are two different signup pathways.

**Comment by Praxie** [comment]
No need to change the sign up screen for different sign-up pathways.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1374

**Comment by Serhiy91** [comment]
@Praxie I have made it for URLs:
https://staging.pliohub.com/sign-up?type=canvas
https://staging.pliohub.com/sign-up?type=implementation
Because docs was changed (5. Enhancements to Org settings of https://basecamp.com/1896845/projects/11083679/documents/13035477). Іs it fine?

**Comment by sives** [comment]
@Serhiy91  My apologies, the naming got changed again in the Basecamp Step 5 requirements document section 5, so that it is now "Canvas view" and "Operations view".  This means that the URLs for the two sign-up paths should be "....type=canvas" and "...type=operations".   These names will NOT change again, I promise.

**Comment by Praxie** [comment]
@Serhiy91 please change the label.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1394

**Comment by Praxie** [comment]
@sives so with the "canvas" parameter, it redirects to the /214/canvas screen after Logging in or email verification. But  /214/ still opens the operational view.

**Comment by sives** [comment]
@Praxie yes, this is correct.  Because we will have users who use the canvas functions and nothing else, there also needs to be a way to save a friendly URL that opens the canvas view e.g.  app.pliohub.com/214/canvas
