### ISSUE TITLE
Creating a Non-conformity without a Root cause analysis

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#132]
When creating a new Non-conformity that is following a 6-step workflow process, it should not be possible to save the Non-conformity without setting a date for Root Cause Analysis and who will do it.

**Comment by Praxie** [comment]
@sives What's the reason to do this? Is this really necessary? I think that this issue is a bit overcomplicated because we will need to add the RCA section to the small modal based on the Standard's workflow type. (And this behaviour is required only for the first NC in the organization)

**Comment by sives** [comment]
Not worth the effort, unless a customer asks for it
