### ISSUE TITLE
BUG: User select input should not show users that didn't accept invite

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1334]
Invite new user, he will appear in user select input as "undefined undefined"

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1344

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1434

**Comment by Dartv** [comment]
@Serhiy91 that's not what was needed. The canvas screen was ok, it means other screens have bug. @Praxie please, confirm. If the user didn't accept invite, he shouldn't be shown in the dropdown. That makes no sense to me.
