### ISSUE TITLE
Reusable slider input

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1356]
![screen shot 2018-09-03 at 2 33 12 pm](https://user-images.githubusercontent.com/2095940/44984737-91b77d00-af86-11e8-8777-1a19ade7e742.png)
https://github.com/brownieboy/react-bootstrap-slider

**Comment by Dartv** [comment]
This package requires bootstrap 3, but we use bootstrap 4 and that could be a problem

**Comment by Praxie** [comment]
@Serhiy91 @Dartv https://www.w3schools.com/howto/howto_js_rangeslider.asp
?

**Comment by Praxie** [comment]
https://github.com/react-component/slider looks like a better option.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1364

**Comment by Dartv** [comment]
@sives do we need to show a tooltip with the current value? Like in the example http://react-component.github.io/slider/examples/handle.html

**Comment by sives** [comment]
@Dartv yes we do.  The tooltip value should transition within the range 0 - 100 as the slider moves from left to right. The labels at each end of the slider should be "Low" and "High" (not Very high)

**Comment by Serhiy91** [comment]
@Dartv ok

**Comment by Praxie** [comment]
It looks nice
