### ISSUE TITLE
Increase completion box comments (NCs, Risks) to 512 characters

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1384]
Currently this is limited to 170 characters which is too short for an extended comment.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1813

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/52821806-9d23de00-30b8-11e9-9e53-81011d7dcc44.png)

**Comment by Serhiy91** [comment]
via Hubstaff
User: Serhiy Zinchuk

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 01/21/19 - 01/22/19
Work session total: 1:59:28

Grand total: 1:59:28
