### ISSUE TITLE
The chart modal window should be bigger

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1387]
![screen shot 2018-09-17 at 12 31 36 pm](https://user-images.githubusercontent.com/2095940/45615593-a7906c00-ba75-11e8-930b-3257e5fb568a.png)

@Serhiy91 take a look if it's easy to do.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1403

**Comment by Praxie** [comment]
![screen shot 2018-09-26 at 8 45 45 pm](https://user-images.githubusercontent.com/2095940/46098496-36675c00-c1cd-11e8-8144-3b9866cce0d5.png)
![screen shot 2018-09-26 at 8 45 54 pm](https://user-images.githubusercontent.com/2095940/46098498-36675c00-c1cd-11e8-8b95-543b45e36fbd.png)
