### ISSUE TITLE
Mandatory and non-mandatory info in Canvas cards

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1402]
Only the card title field right at the top of the card should be mandatory for the user to fill in.  

This is a deliberate design decision intended to remove as much friction as possible from the process of filling in an initial set of canvas cards.  At the initial stage of learning about and filling in the canvas, we don't want the user to have to think about values of fields which are of secondary importance.

The following fields should not be mandatory, and are allowed to have null values:

% of market size (Customer segments card)
Criticality, Level of spend (Key partners card)
% of revenue, % of profit (Revenue streams card)
% of total cost (Cost structure card)

(Currently the system is asking user to fill in a value, and will not allow them to close the card without saving a value)

**Comment by Dartv** [comment]
@siives shouldn't originator be required also?

**Comment by sives** [comment]
@Dartv Yes, originator is a required field, but it is set by default to the current user, so no active user intervention is required to set this field

**Comment by Dartv** [comment]
@sives That's confusing. There could potentially be a possibility when the data fails to load and the user will be able to create document without those fields. So it's the same for color too?

**Comment by sives** [comment]
@Dartv Yes, the same for color.  My requirements were written from the user perspective. My goal is to minimise the number of clicks required for the user to fill in a canvas card.  It should be super-simple and quick, just like writing on a Post-it note and sticking it onto a paper canvas.  Apologies for any confusion.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/commit/ecb954152ce991a1e452cabc069eb5572d5a5dcf

**Comment by sives** [comment]
Looks good.

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 12/18/18 - 12/18/18
Work session total: 1:14:00

Grand total: 1:14:00
