### ISSUE TITLE
Change time of Daily Recap Email Notification

### ISSUE THREAD

**Issue by jives95** [Pliohub/Plio#141]
Change from midnight to 5:00am

**Comment by sives** [comment]
This time should be relative to your time zone.  The general principle is that the best time to send email notifications is very early in the morning of the working day of that user, a few hours before they start work.

**Comment by Praxie** [comment]
@sives @jives95 do you mean Daily Recap email notification?

**Comment by sives** [comment]
Yes, it's the daily recap email.

**Comment by Praxie** [comment]
Current release
