### ISSUE TITLE
Patch meteor versions

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1416]

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pulls

**Comment by Praxie** [comment]
@Dartv 

> https://github.com/Pliohub/Plio/pulls

?

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 09/26/18 - 09/26/18
Work session total: 0:51:18

Grand total: 0:51:18
