### ISSUE TITLE
Select input spinner bad position 

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1419]
![6bee05ff294f8c0694ac043ca3d6e6a3](https://user-images.githubusercontent.com/2095940/46097523-d5d71f80-c1ca-11e8-9f92-e4110ae92463.gif)

Should be like this:

![ce9dc07961842f8103baec2149570593](https://user-images.githubusercontent.com/2095940/46097532-e12a4b00-c1ca-11e8-8aae-e2ee556d44cc.gif)

**Comment by Praxie** [comment]
@Dartv is it completed? You removed the todo label.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1451

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 10/09/18 - 10/09/18
Work session total: 0:23:42

Grand total: 0:23:42
