### ISSUE TITLE
Legend items should be sorted as section items on the bubble chart

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1421]
1. Another partner.
2. New partner.

It should be sync with the section list. If it gets reordered - the legend should be reordered too. 

![screen shot 2018-09-26 at 8 39 20 pm](https://user-images.githubusercontent.com/2095940/46098132-58acaa00-c1cc-11e8-905a-dda253d95bf2.png)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1433
