### ISSUE TITLE
"Invite users" button in the header

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1423]
@sives I don't like the button in the prototype at all.

I'd suggest to do it this way:
![screen shot 2018-09-26 at 9 01 03 pm](https://user-images.githubusercontent.com/2095940/46099609-df16bb00-c1cf-11e8-88be-d390e3074f69.png)

Or at least

![screen shot 2018-09-26 at 9 06 51 pm](https://user-images.githubusercontent.com/2095940/46099699-213ffc80-c1d0-11e8-9ff8-019f37ba4520.png)

**Comment by Serhiy91** [comment]
@Praxie @sives So, What should I do from these three options?

**Comment by sives** [comment]
@Serhiy91 let's implement Jack's treatment at http://ui2.isometrica.io/ui1-3/canvas.html  and then improve it later
