### ISSUE TITLE
The Home screen subcard is not displayed in new organizations

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1424]
![screen shot 2018-09-26 at 9 36 42 pm](https://user-images.githubusercontent.com/2095940/46101342-58b0a800-c1d4-11e8-8fbe-0cde03be2ad7.png)

**Comment by Serhiy91** [comment]
@Praxie I can not reproduce https://drive.google.com/file/d/1M5ZcUWkGnQpc6AU2deRfYEoUgVS1PI1_/view

**Comment by Praxie** [comment]
It was a deployment issue. Fixed in Plio version 0.3.46
