### ISSUE TITLE
DatePickerField should pass timestamp to onChange handler instead of moment object

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1432]
Forms affected (add and edit):
Goal, milestone, action, all canvas forms

**Comment by Fallen1988** [comment]
via Hubstaff
User: Orest Andrusyshyn

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 10/16/18 - 10/19/18
Work session total: 12:08:07

Grand total: 12:08:07
