### ISSUE TITLE
The new Categorize field

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1438]
**The new Categorize function** at
https://basecamp.com/1896845/projects/11083679/documents/13035477

We need to agree on design first.

**Comment by Praxie** [comment]
@Dartv @sives I think that we should stick with the following design:
It'll simplify the field.

![image](https://user-images.githubusercontent.com/2095940/47447869-49b71880-d7c7-11e8-86f2-a49ce9f71d60.png)

**Comment by Dartv** [comment]
Bootstrap and reactstrap don't support sub menus. We'll need to look for a package or write our own.

**Comment by Dartv** [comment]
I don't think this design is good actually. We'll have to deal with lots of problems.
First, we'll have to load relevant documents when sub menu is opened and show loading state somehow.
Second, the user won't be able to search for documents. This could be a problem if he has 100+ documents in the organization.

**Comment by sives** [comment]
@Dartv Can you think of any other good design approach?   In any solution, I want to avoid complicating the top sections of Plio cards by adding 3 buttons to each card (i.e. Departments, Key Goals and Business Model Sections).

Maybe the top section of the card could slide down when the user clicks the "Categorise" button, and show the 3 separate options as buttons (i.e. Departments, Key Goals and Business Model Sections)?

**Comment by Dartv** [comment]
@sives We'll discuss this with Mike today and reply

**Comment by sives** [comment]
@Serhiy91 This looks pretty good.  Just a couple of small issues.  First, the label "Departments/sectors" is incorrect and should be "Departments/teams". (see Step 5 spec section below)  Second, the "+" button should be labelled as "Add new department/team ABC".


![screen shot 2018-11-06 at 22 12 03](https://user-images.githubusercontent.com/2330529/48097273-5436d080-e211-11e8-8809-228a000d7763.png)

**Comment by Praxie** [comment]
We decided to remove Key goals and Canvas sections form the categorize field. 
Keep only Departments/teams and add another entity - projects (https://github.com/Pliohub/Plio/issues/1553)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1552
