### ISSUE TITLE
Help panel extensions

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1440]
![image](https://user-images.githubusercontent.com/2095940/46288363-0f72a680-c58e-11e8-8976-a84ebf7e0fba.png)

@sives as I understand, this is how you will see the help panel as admin. 
Others will see it as a regular help text:

![screen shot 2018-10-01 at 3 25 31 pm](https://user-images.githubusercontent.com/2095940/46288431-4c3e9d80-c58e-11e8-8d43-0481d7b4d659.png)

Also, we'll implement this only for new cards (Canvas view).
Am I right?

**Comment by sives** [comment]
@Praxie Following Jack's UI prototype (click on the question mark icon at the top left hand side of the canvas card) it looks a bit different to what you've shown.

![screen shot 2018-10-01 at 13 31 56](https://user-images.githubusercontent.com/2330529/46288740-aafc1b00-c57e-11e8-8179-c38d891576a1.png)

**Comment by sives** [comment]
@Praxie  In the latest UI prototype the user can click directly on the help item title from the top level canvas box.  So the best design solution would be to provide an editable version of the guidance panel modal (click on an individual guidance text title in the canvas box and you will see this modal), allowing the administrator to edit i) title text string ii) the guidance text string and iii) the best articles URLs

**Comment by Praxie** [comment]
@sives I remember us having a conversation about simplifying the help panel. 
We decided to remove help subcards and add a rich text editor so that you could format text as you need (add subtitles, create lists etc.)
What do you think about this approach?

**Comment by sives** [comment]
@Dartv  I think I'd prefer to stick with Jack's design for the canvas panel guidance text, and leave the old (non-editable) approach in place for all the other cards in the system.   Your simplified approach doesn't allow for a separate guidance text title and body text, which I think is important.  I just want to use to see (and click on) the guidance text titles when they are in the Canvas screen.

**Comment by sives** [comment]
I don't think Jack's design is actually that complicated.

**Comment by Praxie** [comment]
@sives Ok, we can do that.

**Comment by Dartv** [comment]
If we're gonna add rich text editor to guidance panel, we'll need to:
- Add and configure new package `react quill` which means we'll need more time.
- Be extremely cautious because any editable HTML is XSS vulnerable.

**Comment by sives** [comment]
@Dartv OK, let's not do this, it's not an important requirement

**Comment by Praxie** [comment]
@Dartv but we already have a quill editor in the Lessons learned subcard.
How we're going to add Best articles to the help subcard body if there'll be no editor? Custom fields?
![screen shot 2018-10-02 at 11 34 01 am](https://user-images.githubusercontent.com/2095940/46337825-333df700-c637-11e8-8e44-28721e1aa276.png)

**Comment by Dartv** [comment]
We can use blaze editor, but we'll eventually need to move to react one anyway. More places where editor is used means more holes for the attacker to use.

**Comment by Praxie** [comment]
@sives is the Best articles section important?  How do you imagine adding links?

**Comment by sives** [comment]
@Praxie Yes, the Best articles section is important.  As you can see in the screen image from Jack's prototype, there are 2 separate fields at the bottom of the help panel (admin mode) where the user can enter the title and the URL string for each Best Article.


![screen shot 2018-10-02 at 15 30 20](https://user-images.githubusercontent.com/2330529/46355185-3f867c00-c658-11e8-9de2-b301bc44665c.png)

**Comment by Praxie** [comment]
@sives ok thanks.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1492

**Comment by sives** [comment]
I can't see any way to test this new functionality.   As per Jack's prototype, I'm expecting to see some kind of question mark icon (?) to click on to open up the extended help panel, but I don't see this in the Staging system.

**Comment by Dartv** [comment]
@sives I see a question mark icon and it works like it should. Can you be more clear? You should be logged in as an owner of Plio ltd organization to see editable view, e.g. Steve Ives

**Comment by sives** [comment]
@Dartv  These are the current issues that I have with the way this currently works, vs the UI prototype:

1. Help symbol not present on Canvas cards when they are first created (before data entry)

I only see a help symbol when I've created and saved and then re-opened the card, which is too late in the process from the user perspective. The purpose of the help feature is to provide users with convenient guidance on simple business model canvas concepts they need to be aware of as they create and fill in new canvas cards.  This requires that the help icon symbols are present when any new Canvas card is created from an Add button, and users are wondering what to do next.

2. Card header button layout is inconsistent across the system

When help has been added to a Canvas card, the button layout in the header bar reverts to the Plio classic layout i.e. help symbol on the left, Close button on the right.  When there is no help, the header bar layout is Close button on the left, Save button on the right.  This will confuse users. They got used to the Close button (with auto-save) being on the right hand side of the header in the main Plio system.  Now we've added a new layout with Close button on the left (with no auto-save) in the Canvas cards and Key Goals cards.  Then we go back to the old layout (Close button on the right, with auto-save) when a Canvas card gets some help text added to it.  This is non-intuitive and illogical.  Why are we not sticking with one single layout and one single saving behaviour?  The logical layout to use would be the original Plio layout, with the Close button on the right, with auto-saving when the user clicks on Close.

3. Auto-saving is fragile
When I log in with username stephen.ives@gmail.com and pw = 'password' (Plio displays the user as Bryan Abercrombie) and go to Southwind Capital Management, then click on Segment 1a card in Customer Segments, the card opens and goes into an auto-saving loop.  The card is no longer responsive to user input, so I have to close the browser window and login again. (see screenshot below).

4. Cosmetic issues
Guidance text subcards need to be adjacent to each other (see 2nd screenshot below) and not with white space between them (see 3rd screenshot below).


![screenshot 2019-01-16 at 10 00 04](https://user-images.githubusercontent.com/2330529/51242555-28a23600-1978-11e9-9299-c094939f8c2f.png)



![screenshot 2019-01-16 at 09 36 33](https://user-images.githubusercontent.com/2330529/51242575-3788e880-1978-11e9-8a53-3ddc7ae0bba9.png)

![screenshot 2019-01-16 at 10 20 09](https://user-images.githubusercontent.com/2330529/51242634-5c7d5b80-1978-11e9-8be2-06b3472734bd.png)

**Comment by Dartv** [comment]
@sives 
2. The current design is consistent across all screens. We don't have any screen with "old" layout. In fact, we never had one in Plio.
Plus, we can't simply make "old" layout. We can't have "Close" button with auto-save when adding documents. This would mean that the user is unable to cancel creation of new document.
3. I've seen this happen. This started after we implemented "focus on first input" functionality. Probably a bug somewhere.

**Comment by sives** [comment]
@Dartv 
2. I don't understand.  Probably best if I discuss first with @Praxie at our review call on Friday 10am GMT
3. OK great, then we can fix this.

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 10/18/18 - 10/22/18
Work session total: 10:54:10

Grand total: 10:54:10

**Comment by sives** [comment]
@Dartv @Praxie The help system is broken in 0.3.56.  

When I'm logged in as the Org owner (Stephen Ives) I see a big empty panel (see below).  There's no way for me to create multiple guidance text items.

In the Operations view cards, I need to see a help button displayed somewhere on the card when a new card is created (not just for saved cards).  Suggest we put the help button at the LHS of the top section of the card, just under the Cancel button, aligned with the field label for the 1st field.
