### ISSUE TITLE
Risks subcard in standard edit modal broken

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1449]
![](https://i.gyazo.com/3d92421678776ee3ee230faf1132156a.png)

**Comment by Serhiy91** [comment]
@Dartv I can not reproduce it https://drive.google.com/file/d/1AsPXaDpe9kxTmGcDTQ-43oWaZucIMQQ5/view

**Comment by Dartv** [comment]
Same. I think it's already fixed
