### ISSUE TITLE
Replace select with select input in "Risk type" field

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1453]
This will allow us to load data dynamically and for users to search for risk types

**Comment by Dartv** [comment]
@sives this means that when the user is presented with "create risk" form, the type field will be empty. He'll have to choose one to proceed. Is this ok?

**Comment by sives** [comment]
@dartv @Praxie I've looked at the Step 5 Requirements specification and it isn't written down anywhere what the structure of the "create risk" form should be.  So I'm proposing it below, and also for the other "create" subcards created from the Actively manage area, to make sure that the requirements are clear.

1. New Risk subcard

When the user clicks on "Add a Risk" a new Risk subcard gets added to the Canvas item card, below the Actively manage subcard.  This new Risk subcard is a cut down version of the Create risk card in the Risks screen, and contains just the following fields:

Risk name
Description
Originator (defaults to current user)
Owner (defaults to current user)
Magnitude (defaults to Major)

This new Risk subcard doesn't contain the Standards field, nor the Risk type field.

Here are specifications for the other new subcards created from the Actively manage subcard:

2. New Key goal subcard
All the fields in the existing create new Key goal card.

3. New Standard subcard
All the fields in the existing create new Standard card, except the Standards section and Type fields

4. New Nonconformity subcard
All the fields in the existing create new Nonconformity card,  except the Standards field.

5. New Potential gain subcard
All the fields in the existing create new Potential gain card,  except the Standards field.

6. New Lesson learned subcard
All the fields in the existing Lessons learned subcard.

**Comment by Dartv** [comment]
@sives we can't just remove mandatory fields like risk type or standard type. They're required at db-level. User won't be able to create a new subcard without these fields.

I was asking about risk type field specifically. Right now it's a simple select, but it will be better for the users and us developers to have it as select input field with search.

**Comment by sives** [comment]
@Dartv For the new Risk subcard, I can live with having the risk type field in the subcard.  Not a problem.  If I understand you correctly, a select input field with search means that the user can add a new risk type if they don't see an existing risk type that fits the new risk.  I'd be fine with this.

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 01/03/19 - 01/03/19
Work session total: 0:33:21

Grand total: 0:33:21
