### ISSUE TITLE
Refactor files subcard to use final form

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1457]
- Follow notify subcard example.
- Rename `CanvasFilesSubcard` to `FilesSubcardContainer` and move it to `containers` folder.
- Refactor all places where this card is used

**Comment by Fallen1988** [comment]
via Hubstaff
User: Orest Andrusyshyn

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 10/29/18 - 11/15/18
Work session total: 46:36:45

Grand total: 46:36:45
