### ISSUE TITLE
Run tests on push instead of commit

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1461]
With more and more tests they became quite slow for running them on every commit.
Use https://github.com/typicode/husky for that

**Comment by Fallen1988** [comment]
#1476

**Comment by Fallen1988** [comment]
via Hubstaff
User: Orest Andrusyshyn

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 10/15/18 - 10/16/18
Work session total: 1:22:41

Grand total: 1:22:41
