### ISSUE TITLE
Refactor SelectInput fields to use ApolloSelectInputField

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1462]
`StandardsSelectInputField`, `GoalSelectInputContainer` and others need refactoring. See example in `ValuePropositionForm`, `CustomerSegmentForm` and `UserSelectInput` components

**Comment by Dartv** [comment]
@Fallen1988 link your PR and put on `pending review` label

**Comment by Fallen1988** [comment]
#1490

**Comment by Fallen1988** [comment]
via Hubstaff
User: Orest Andrusyshyn

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 10/19/18 - 10/24/18
Work session total: 10:29:38

Grand total: 10:29:38
