### ISSUE TITLE
Tests fail on first run

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1465]
This error is being thrown on first run:
`Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL`

https://jestjs.io/docs/en/jest-object#jestsettimeouttimeout

**Comment by Fallen1988** [comment]
#1502

**Comment by Fallen1988** [comment]
via Hubstaff
User: Orest Andrusyshyn

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 10/24/18 - 10/25/18
Work session total: 1:23:39

Grand total: 1:23:39
