### ISSUE TITLE
Delete DebounceTextarea and remove react-debounce-input dependency

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1468]
It is not used anywhere

**Comment by Fallen1988** [comment]
#1488

**Comment by Fallen1988** [comment]
via Hubstaff
User: Orest Andrusyshyn

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 10/18/18 - 10/19/18
Work session total: 0:39:21

Grand total: 0:39:21
