### ISSUE TITLE
Implement "Root cause analysis" form on React (Nonconformity)

### ISSUE THREAD

**Issue by Serhiy91** [Pliohub/Plio#1495]
![image](https://user-images.githubusercontent.com/13336284/47365967-5cf1b780-d6e5-11e8-8642-8cfda1429cde.png)

**Comment by Dartv** [comment]
We already have `AnalysisForm` component. Look at `RiskEditForm` for the example. If you need to change it, you'll have to change other places where it's used. Is it worth it?

**Comment by Dartv** [comment]
Implemented here: https://github.com/Pliohub/Plio/pull/1541
