### ISSUE TITLE
Create "source" react components

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1498]
Recreate Blaze Sources_Edit and Sources_Create with React. We don't need to recreate the uploader. We can leave it in blaze for now.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1870

**Comment by seniv** [comment]
via Hubstaff
User: Ivan Seniv

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 10/26/18 - 10/26/18
Work session total: 0:10:32

Grand total: 9:54:31

**Comment by Fallen1988** [comment]
via Hubstaff
User: Orest Andrusyshyn

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 11/16/18 - 11/19/18
Work session total: 9:43:59

Grand total: 9:54:31
