### ISSUE TITLE
Behavior after clicking on linked doc of canvas section

### ISSUE THREAD

**Issue by Serhiy91** [Pliohub/Plio#1508]
![image](https://user-images.githubusercontent.com/13336284/47791984-a4022d00-dd23-11e8-8fda-d6d8354858e4.png)

**Comment by Dartv** [comment]
Please, make a single PR for a single type of document

**Comment by Dartv** [comment]
For now, we just need to display an empty modal

**Comment by Dartv** [comment]
ihttps://github.com/Pliohub/Plio/pull/1532
