### ISSUE TITLE
Actively manage subcard RHS header indicator

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1509]
>The subcard displays a Remove icon (circle with x in the middle) on the RHS of the subcard header panel, but only when there are no items linked to the subcard.  When there are items linked to the subcard, this remove icon is replaced by a numeric indicator showing the number of linked items (following our normal design pattern).

**Comment by Serhiy91** [comment]
@Praxie @sives What is the help text for "Lessons"?

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1574
