### ISSUE TITLE
"Canvas screen" subcard in org settings

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1511]
>There will be a new option within Org Settings called "Canvas screen" accessed via a subcard located under the "Operations screen" subcard (which is just a renaming of the existing Workspace subcard).  When opening this subcard, you see a subheading titled "Notify changes list" and a field containing one default entry, the Org owner.  Users who have the Org settings superpower can add additional users to this list, or delete users.

**Comment by Dartv** [comment]
@sives Also, each individual canvas item has notify subcard. How should we handle them both?

**Comment by sives** [comment]
@Dartv This refers to a new subcard that is only used in Org Settings.  I'm calling it a subcard, but that's probably not a technically accurate description, it's just an additional option in the long list of options in Org Settings

**Comment by sives** [comment]
The option in Org Settings lets the Org owner set up a default list of people e.g 3 users that get notified whenever a card is added, edited or removed from the Canvas screen.  This same list of 3 users would appear by default whenever any user opens the Notify subcard within a Canvas item card. The user can then add users or delete users from this list, but it doesn't affect the default user list in Org settings.

**Comment by Dartv** [comment]
@sives I still don't get where to put this option. Can you clarify?

**Comment by sives** [comment]
In Org settings under the existing Workspace subcard (see below).

![screen shot 2018-11-01 at 12 05 19](https://user-images.githubusercontent.com/2330529/47850830-86d66880-ddce-11e8-9f5a-1417d9d24750.png)

**Comment by Dartv** [comment]
@sives is this alright?
![](https://i.gyazo.com/5f1c7ec1958e1c760a4e0436622d28ec.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1521
https://github.com/Pliohub/Plio/pull/1522
https://github.com/Pliohub/Plio/pull/1523
