### ISSUE TITLE
Middleware to check multiple users organization membership

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1518]
We already have `checkOrgMembership` middleware that checks membership of a single user. We need to create customizable version to check multiple users (notify field, for example). We already have `checkDocsAccess` as an example.

Also, use this middleware in every graphql mutation which has `notify` argument. You can check this by searching for `TODO: check notify users access`.
Don't forget about tests!

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1754
