### ISSUE TITLE
Home screen icon panels not displaying properly 

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#152]
On James' MacBook with Chrome (latest version), the home screen icons are displaying very small indeed, see below.  However, when he views the screen in Safari it is OK, and it displays OK on my MacBook with both Safari and Chrome.  

![screen shot 2016-09-26 at 14 19 11](https://cloud.githubusercontent.com/assets/2330529/18846507/1814c2f4-841e-11e6-9830-5ed9e8bdb233.png)

**Comment by Praxie** [comment]
I'll test it on my Macbook Air. But so far no one in our team has noticed this issue.

**Comment by Praxie** [comment]
Version 53.0.2785.143 (64-bit)
Google Chrome is up to date.

**Comment by Praxie** [comment]
![screen shot 2016-10-01 at 12 54 18 pm](https://cloud.githubusercontent.com/assets/2095940/19013334/5f4bfb86-87d6-11e6-994f-73114c5dd463.png)

**Comment by Praxie** [comment]
I have no idea how to reproduce this issue. I tried different window sizes.

**Comment by sives** [comment]
Let's not worry about this problem for now, until I can reproduce it.

**Comment by sives** [comment]
I'm now seeing this problem in the new v0.2.55 release, but only when I'm using Safari on Mac OS.  It's not just the home screen icons that are missing, but all the icons in all the screens.

![screen shot 2016-11-08 at 11 42 18](https://cloud.githubusercontent.com/assets/2330529/20097888/a783c13c-a5a8-11e6-91ce-4cd091dba754.png)

![screen shot 2016-11-08 at 11 42 35](https://cloud.githubusercontent.com/assets/2330529/20097894/ac3e800e-a5a8-11e6-8059-0519932a776f.png)
