### ISSUE TITLE
Render canvas subcards with delay

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1528]
To improve performance of our modals, we'll need to delay rendering of canvas subcards because they're not immediately needed to interact.
Use `libreact/lib/delayed` for that.

**Comment by Fallen1988** [comment]
via Hubstaff
User: Orest Andrusyshyn

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 11/15/18 - 11/15/18
Work session total: 4:44:57

Grand total: 4:44:57
