### ISSUE TITLE
Render canvas nabvar with delay

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1529]
Same as for canvas subcards. Header is not important to interact with immediately.
Use `libreact/lib/delayed` for that

**Comment by Fallen1988** [comment]
#1558

**Comment by Fallen1988** [comment]
via Hubstaff
User: Orest Andrusyshyn

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 11/12/18 - 11/12/18
Work session total: 2:01:44

Grand total: 2:01:44
