### ISSUE TITLE
Slidedown help needs to be implemented in cards

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#153]
I need to provide the team with help text and a list of specific card locations where this is needed.

**Comment by Praxie** [comment]
https://docs.google.com/spreadsheets/d/1bblUYBKj8sLpg70yKeoARuzaz0L-iteORgR5VimwsgY/edit#gid=779525614

**Comment by Praxie** [comment]
@RomanValihura Complience standards help messages are already implemented in i153-help-messages
Checkout to this branch and take a look at the code. 
Basically, the are two types of help sections: 
- in the card header
- in the form field component

**Comment by Praxie** [comment]
**v0.2.51**

**Comment by Praxie** [comment]
https://github.com/Pliohub/Plio/pull/300

**Comment by sives** [comment]
Font size for slidedown help text is too small, increase by a couple of point sizes

**Comment by Praxie** [comment]
**current version**

**Comment by sives** [comment]
Font size is now good.
