### ISSUE TITLE
Files subcard bug on consequent modal open

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1565]
When opening the same modal for more then 1 time, the files will be emptied as a result of `setState` call from the container above.
This seems to be the case with canvas screen only as goals work fine.
Need to try https://github.com/Pliohub/Plio/issues/1528 as potential fix.
Another solution might be to use meteor cached subscriptions

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1739
