### ISSUE TITLE
Cannot upload standard sources

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1579]
Try uploading standard source file from edit modal. You'll see error:
`sources.js:24 Uncaught TypeError: this.standardId is not a function`

**Comment by Serhiy91** [comment]
@Dartv I can not reproduce it

**Comment by Dartv** [comment]
@Serhiy91 I can reproduce it from "Standards" screen

**Comment by Serhiy91** [comment]
@Dartv https://drive.google.com/file/d/1vO7ro5Hp2fz_CfOFJjMTnYTcCQq6SzoR/view

**Comment by Dartv** [comment]
@Serhiy91 Try uploading .docx file

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1615
