### ISSUE TITLE
Search box - search on phrase (enhancement)

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#158]
Users would like to be able to search on a precise phrase in the List view search boxes e.g. "Clifton Consulting".  They want to be able to use quotation marks (single or double) to indicate the phrase.

**Comment by RevelsGit** [comment]
Cannot use single quotation marks because some words can contain them and they will screw up search.

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/279

**Comment by Praxie** [comment]
**v0.2.50**
This feature needs to be tested and requirements should be extended.
Currently it matches all results that are ending with text in quotation marks.

**Comment by Praxie** [comment]
So "Clifton Consulting" will match all documents that are ending with "...Clifton Consulting" but "Clifton Consulting Ltd" string

**Comment by Praxie** [comment]
@sives Our default search works like search on phrase as well. It matches the exact text.  "Clifton Ltd Consulting" won't match the "Clifton Consulting Ltd" document

**Comment by sives** [comment]
Let's discuss in our next call

**Comment by Praxie** [comment]
The default search shouldn't care about the order of words.

**Comment by Praxie** [comment]
**0.2.54**

**Comment by sives** [comment]
The search doesn't care about the order of the words, which is good.  However there is some strange behaviour when typing the search term into the search box (on PC browser and on iOS and Android).  Typing in the first letter - everything is fine.  Type in the second letter - the search box goes grey, then white again and no second letter is displayed.  Type in the third letter - suddenly it works again, but the 3rd letter is displayed as the 2nd letter.

**Comment by Praxie** [comment]
@sives the search is an expensive process. We need to prevent user from entering new symbols after the search started if there is a lot matches. It starts after the user stops entering text (0.5-1 sec after the last character was inserted)
I couldn't reproduce this issue with letter disappearing though.

**Comment by Praxie** [comment]
**0.2.56**
