### ISSUE TITLE
Project list views

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1582]
> To support the new Projects entity, we need to add the following two new list views to their respective screens: 
    Risks - by project 
    NCs & PGs - by project

**Comment by Praxie** [comment]
project-filter 
branch

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1751

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 01/09/19 - 01/09/19
Work session total: 3:14:38

Grand total: 14:37:58
