### ISSUE TITLE
ApolloSelectInputField should support transforming options

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1583]
So instead of adding different transformers to every select component, we will add `transformOptions` prop to `ApolloSelectInputField`.
It should look something like:
```
const ApolloSelectInputField = ({ loadOptions, transformOptions = identity, ...props }) => (
  <ApolloConsumer>
    {client => renderComponent({
      loadOptionsOnOpen: true,
      loadOptions: () => loadOptions(client.query).then(transformOptions),
      ...props,
    })}
  </ApolloConsumer>
);
```

Also, refactor all places where this functionality is needed to reflect on changes.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1637
