### ISSUE TITLE
Canvas daily recap

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1585]
> There is a requirement to update the Plio Daily Summary with any changes that users have made to the canvas (and also any changes made to the Key goals in the Step 4 system).

**Comment by Dartv** [comment]
@sives does it include customer elements (benefits, features, ...) ?

**Comment by sives** [comment]
@Dartv Yes it does include these elements, and also the milestones

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1587
https://github.com/Pliohub/Plio/pull/1600

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 11/22/18 - 11/22/18
Work session total: 2:35:32

Grand total: 2:35:32
