### ISSUE TITLE
Audit config for organization review

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1597]
We don't have audit config for organization review field currently

**Comment by Dartv** [comment]
@sives what are the logs should be for when the user changes review reminders? They should be simple enough.
![](https://i.gyazo.com/572c56568c6d16c8b4d053c9cca047d2.png)

Example: standards review reminders {start} (?) changed from 2 weeks to 4 weeks

**Comment by sives** [comment]
@Dartv  I would construct these as follows:

Standards review reminders {advance notification timing/repeat notification timing} changed from {2}{weeks} to {4}{weeks}.

**Comment by sives** [comment]
@Dartv I've made the message structure slightly clearer, and hopefully easier for you to understand also:

 {Advance notification timing}{Repeat notification timing} for {Standards}{Risks} review reminders changed from {2} {weeks} to {4} {weeks}.

**Comment by Dartv** [comment]
@sives but what's {Advance notification timing}{Repeat notification timing}? Can you provide an example message?

**Comment by sives** [comment]
@Dartv Example messages here:

Advance notification timing for Standards review reminders changed from 2 weeks to 4 weeks.

Repeat notification timing for Risks review reminders changed from 1 week to 2 weeks.

**Comment by Dartv** [comment]
@sives What about "until"?

**Comment by sives** [comment]
@Dartv 

Notification stop timing for Standards review reminders changed from 2 days to 4 days past scheduled review date.

**Comment by Dartv** [comment]
@sives ok, thanks

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1614

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 12/04/18 - 12/04/18
Work session total: 1:52:07

Grand total: 1:52:07
