### ISSUE TITLE
Can't link any "existing" document to value proposition

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1622]
When trying to load any "existing" document in actively manage in value proposition edit modal, an error is thrown

**Comment by Serhiy91** [comment]
@Dartv I can not reproduce it https://drive.google.com/file/d/1N4UZG8ljjzS8qy5hvVmYAkbRB0dK6PER/view

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1638
