### ISSUE TITLE
Canvas: wrong alignment of items

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1640]
Should be 1 item per row
![](https://i.gyazo.com/47c15699b10e3b3a60b738511f55984b.png)

**Comment by Serhiy91** [comment]
@Praxie @sives So, What should be the alignment of items?

**Comment by sives** [comment]
@Serhiy91 It should be exactly as in the UI prototype (preferably use the markup in the prototype without changing it)

http://ui2.isometrica.io/ui1-3/canvas.html

**Comment by sives** [comment]
Currently the spacing varies between different canvas sections, see below:

![screenshot 2018-12-20 at 10 06 14](https://user-images.githubusercontent.com/2330529/50278491-08e22580-043f-11e9-9a37-8de30dd67e41.png)

**Comment by sives** [comment]
In the UI prototype it does not do this

**Comment by Serhiy91** [comment]
![image](https://user-images.githubusercontent.com/13336284/50278566-076d2900-0450-11e9-9925-12139a9b8d43.png)
It is about canvas report

**Comment by Serhiy91** [comment]
http://ui2.isometrica.io/ui1-3/report.html

**Comment by sives** [comment]
@Serhiy91 Sorry Serhiy for any misunderstanding - this feedback item relates to the main canvas and not to the canvas report

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/51196566-12ed2c00-18f8-11e9-83a6-c0689dd88869.png)
