### ISSUE TITLE
Key partners -> adding files

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1652]
Chrome Web
1. Create key partners
2. Open created key partners
3. Add files -> Close key partners
4. Open this key partners 
Expected result: added files displays
Actual: there no added files display (watch video from link) 
https://drive.google.com/open?id=1LLWdDnJ8WEvMm5q_cMUEIg3W7nn_7i0d

**Comment by Dartv** [comment]
Duplicate of https://github.com/Pliohub/Plio/issues/1565
