### ISSUE TITLE
Actively manage -> add key goal 

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1653]
Chrome web
1. Add new key goal
2. Try add color

Expected result: modal with color opens near to key goal color
Actual result: https://drive.google.com/open?id=1ZZcg_HuN4mWFMBqu460i7rpFhIKUiRTf

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1716

**Comment by sives** [comment]
Seems to work fine
