### ISSUE TITLE
Actively manage -> add key goal errors

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1654]
Bug: There incorrect error if there no goal name 
![image](https://user-images.githubusercontent.com/41466462/50152733-268f7d80-02cd-11e9-94d3-692ab3c8f978.png)

**Comment by Dartv** [comment]
What do you mean? This field is required

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1714

**Comment by sives** [comment]
@Serhiy91 Works fine now
