### ISSUE TITLE
Standart creating -> source file

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1655]
Bug: add hint about supported video in source file format (youtube/vimeo)

![image](https://user-images.githubusercontent.com/41466462/50153566-796a3480-02cf-11e9-86b6-dff6a9c0fa55.png)

Beacuse now this happens 

![image](https://user-images.githubusercontent.com/41466462/50153658-b2a2a480-02cf-11e9-9334-7d665baffde6.png)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/compare/i1177-release-step-5...I1655-source-file-video-hint?expand=1

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/51197690-eedf1a00-18fa-11e9-966c-5a2f97980b41.png)

**Comment by Praxie** [comment]
@Serhiy91 please replace the hint with "YouTube or Vimeo URL"

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1816

**Comment by Serhiy91** [comment]
via Hubstaff
User: Serhiy Zinchuk

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 12/28/18 - 12/28/18
Work session total: 0:29:21

Grand total: 0:29:21
