### ISSUE TITLE
Standards -> edit source file

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1656]
Bug: editing source file not working. Watch video 
https://drive.google.com/open?id=1aHaT77y-wYtncJYhjFbosoHY_GQABoDX

**Comment by Serhiy91** [comment]
I can not reproduce it

**Comment by Dartv** [comment]
I can. When there is video source you can't update url source

**Comment by Serhiy91** [comment]
@Dartv https://drive.google.com/file/d/110qObe7AO5X63jikap9TdoXREIkhG9Fq/view

**Comment by Serhiy91** [comment]
@MaxLutkovec Please, retest it.

**Comment by MaxLutkovec** [comment]
Problem in cross. Pay attention to video
https://drive.google.com/open?id=1G5gMS8b_7imSvVwnmI357hRkfj9wXdnp

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1738

**Comment by Praxie** [comment]
https://gyazo.com/ad1afa4295ad0b42f3c815af4c3faa87

**Comment by sives** [comment]
@Praxie I can't gain access to these videos, you need to authorise me

**Comment by sives** [comment]
@Praxie I tested the editing of a source file on 0.3.55 and it works fine
