### ISSUE TITLE
Canvas section scrollbar does not appear on mac 

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1657]
> - within an individual canvas section, if there are too many items to display in the available area, the item is hidden at the bottom of a scrolling list. However, in this case the scroll bar on the right hand side of the canvas section needs to be switched on to show that there are scrollable items.  (see item “Patent filing” at bottom of list of items in Key activities section, Southwind Capital Management)

@sives it's a native MacOS behavior, we can not do anything with it. Well, we can add a library for displaying custom scrollbars, but it's not worth it. Native behavior is often faster, more reliable and doesn't require users to load additional code.

Here's my suggestion, notice how shadow changes in the canvas section:

![49bbcc91bb7cf558adc62e7e6e7c1c1d](https://user-images.githubusercontent.com/2095940/50154375-d9fa7100-02d1-11e9-9189-25b826b2b33e.gif)

It's a CSS trick and this can be done in 1 hour. But I'll add this to the list of enhancements if you approve.

**Comment by Praxie** [comment]
@Praxie please also notice borders that I've added to section footers.

**Comment by Praxie** [comment]
http://dabblet.com/gist/2462915 @Serhiy91

**Comment by sives** [comment]
@Dartv Shadow effect is very nice, presumably it only appears when there are hidden items underneath?   It's definitely worth implementing as an enhancement for 1 hr of work.  (When I was adding many items to a canvas section, it took me a few seconds to work out why a new item didn't get added to the canvas - of course, it had been added, it was just hidden)

**Comment by Praxie** [comment]
"presumably it only appears when there are hidden items underneath?"
Underneath or above.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1689

**Comment by Praxie** [comment]
https://drive.google.com/file/d/1eigqHjmX25cjvlnHtWr0GdIDKDpcycH7/view

**Comment by Dartv** [comment]
@Praxie try using touchpad instead of mouse. No big deal though

**Comment by sives** [comment]
@Dartv It works really nicely.  However, when I adding a long list of new canvas items, it would be better if the last item that I entered was displayed at the bottom of the visible list within the canvas section (rather than falling off the bottom of the section, and being obscured).  Is it possible to reset the list after you've added the new item, so that the items near the bottom of the list are all in view, and the top items are the ones that are obscured?

**Comment by Dartv** [comment]
Why not just sort them by created date (newest first)?

**Comment by sives** [comment]
@Dartv Because the user interprets the order to be a ranking of how important that canvas item is to the business (which is why we let the user move the items up and down within a section)

**Comment by Dartv** [comment]
What about just scrolling the list to the bottom programmatically after adding an item?

**Comment by sives** [comment]
@Dartv Yes, this is what I was thinking.

**Comment by Serhiy91** [comment]
via Hubstaff
User: Serhiy Zinchuk

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 12/20/18 - 12/20/18
Work session total: 1:25:32

Grand total: 1:25:32
