### ISSUE TITLE
Scrolling momentum and bounce behaviour

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1658]
> - scrolling lists (e.g. in the Key Partners section) do not implement the nice momentum and bounce behaviour that can be seen in the scrolling of lists in the UI prototype.

@sives this is a native Safari behavior, we can't change that. I see the same momentum and bounce behavior in the staging application.

**Comment by sives** [comment]
@Dartv OK, understood.  We need to be careful we don't mess up scrolling behaviour when we implement the shadow effect at the bottom of the canvas sections
