### ISSUE TITLE
Cursor should default to the top title field in the card, and not force the user to click into the field

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1661]
It means that we need to set focus on the title input in the modal window to add a section item.
@sives it won't be consistent with other screens and it's an enhancement request, I didn't find any information about this in requirements. 

@Serhiy91 or @Dartv need to confirm that it's possible to do this.

**Comment by sives** [comment]
@Praxie Yes, you're right, we have done this with the other cards.  Ideally, we should do this for all cards if it is possible.  I agree that it is an enhancement.

**Comment by Dartv** [comment]
It's not as simple as setting "autofocus" attribute because it only works on the initial render. But we have to load data and re-render, so we have to set it programmatically

**Comment by Dartv** [comment]
We may have to create form decorator similar to https://github.com/final-form/final-form-focus to achieve consistent behavior

**Comment by sives** [comment]
@Dartv This is only worth doing if:
a) We can do it across the existing Plio cards and the new Canvas cards
b) It does not take a lot of time to implement
c) It doesn't create a lot of technical risk (fragility/breakages in unforeseen circumstances)

**Comment by Serhiy91** [comment]
@Praxie 
1. Yes 
2. About 4 hours

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1709

**Comment by Serhiy91** [comment]
via Hubstaff
User: Serhiy Zinchuk

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 12/26/18 - 12/26/18
Work session total: 0:58:37

Grand total: 0:58:37

**Comment by sives** [comment]
@Serhiy91 There's one small issue with the current implementation of this feature.  If you create a card with a long title that's a few characters longer than can be displayed in the title field, then save and reopen the card, then the cursor is placed at the end of the title text string, and the beginning of the text string is obscured.  This doesn't look good.  The cursor should be placed at the beginning of the text string, and the beginning of the text string should be visible in the title field so that the reader can read it.

**Comment by Dartv** [comment]
@sives what you suggest is counter intuitive. Browser automatically places cursor at the end of the string. I don't know any website that alters this default functionality. This means that the user experience will differ from all of the web.

**Comment by sives** [comment]
@Dartv OK, if this is default functionality across the web, I don't want to go against this. So no need to change the behaviour.
