### ISSUE TITLE
Inconsistent spacing between the item icons and the text label (Canvas items)

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1663]
Inconsistent spacing between the item icons and the text label e.g. no space in front of “Biopharma firms” in Customer segments (should always be a single space - see UI prototype)

It looks like a bug with responsiveness in Safari. Start narrowing the screen and you'll see this:
![image](https://user-images.githubusercontent.com/2095940/50156822-6ad44b00-02d8-11e9-87f8-9ca45cf31262.png)

**Comment by sives** [comment]
@Praxie  It's good now.
