### ISSUE TITLE
Help text for Customer insights & Value components

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1665]
> Matching of Features & Benefits to Wants & Needs needs a help text panel just below the Customer insights subcard header.  This panel should be the same height as the subcard header and contain the following text prompt:  "Click on the arrow symbol to match to one or more elements”

@seniv I don't see it in the prototype so I'll consider this an enhancement.

**Comment by Praxie** [comment]
Well, it's the same one, basically

**Comment by sives** [comment]
@Praxie Sometimes usability problems only come to the surface once the system has been constructed and you try to use it for the first time. This is a good example of that :-)  It's an enhancement, but it's needed to fix a usability problem which got missed in the prototype.

**Comment by sives** [comment]
@Serhiy91 Looks good

**Comment by Praxie** [comment]
@Serhiy91 I don't see a way to close the help section.

**Comment by Dartv** [comment]
Because it is not meant to be closed. Where would you put "?" icon?

**Comment by sives** [comment]
@Praxie @Serhiy91  Yes, it's not meant to be closed.  It's a new type of guidance to the user that intended to be always present.

**Comment by sives** [comment]
Please change the help text to "Click on the arrow symbol to match to one or more elements.  If there are no elements listed then click on the Back button and start adding some Features and/or Benefits."

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1812

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/52447923-f0d37c00-2b3a-11e9-954a-91b83d33b5cc.png)

**Comment by Praxie** [comment]
![screen shot 2019-02-14 at 4 32 13 pm](https://user-images.githubusercontent.com/2095940/52793314-21a13d00-3076-11e9-9f7b-b083c3662155.png)
@Dartv it has to be "Needs and/or Wants."

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1900

**Comment by sives** [comment]
@Serhiy91 Looks good, problem now fixed.

**Comment by Serhiy91** [comment]
via Hubstaff
User: Serhiy Zinchuk

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 12/21/18 - 12/21/18
Work session total: 0:40:25

Grand total: 0:40:25
