### ISSUE TITLE
In the Match subcard, when there are no Needs or Wants entered, then display “None” underneath the Needs & wants column title.

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1666]

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1703

**Comment by Serhiy91** [comment]
![screen shot 2018-12-21 at 5 50 06 pm](https://user-images.githubusercontent.com/13336284/50350788-e4727000-0548-11e9-90dd-89ad006f29ec.png)

**Comment by Praxie** [comment]
@Serhiy91 it should work the same for both columns.
There should be None under Needs & wants as well.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1755

**Comment by sives** [comment]
@Serhiy91 it should work the same for both columns.
There should be None under Needs & wants as well.
This has not been implemented.

**Comment by Dartv** [comment]
This hasn't been deployed

**Comment by sives** [comment]
@Praxie Still not working in 0.3.55

**Comment by Dartv** [comment]
![](https://i.gyazo.com/c71071915e547fe8fb917d507801bf80.png)
Still not deployed

**Comment by sives** [comment]
@Dartv @Serhiy91 Looks good now in the deployed 0.3.56 system
