### ISSUE TITLE
Different invitation message for the Canvas screen

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1668]
> There needs to be a different welcome message, as follows: “Hi there. We’ll be using Plio to create and share a business model canvas.  Please accept this invitation to join Plio as a user. See you there soon.”

It requires some modification of the modal window for inviting users.
@sives Do you approve this enhancement with a 2 hours estimate?

**Comment by sives** [comment]
@Praxie No, because this requirement for a different welcome message was clearly stated in the original requirements specification, so it should be part of the fixed price contract terms.

**Comment by Praxie** [comment]
@sives I can't find this anywhere in the requirements specification. Could you point me in the right direction please?

**Comment by sives** [comment]
It's in Section 8 - Other in the main Step 5 requirements document
![screenshot 2018-12-18 at 13 57 13](https://user-images.githubusercontent.com/2330529/50158825-0fe92680-02cd-11e9-98e6-19e02b2e918b.png)

**Comment by sives** [comment]
@Praxie Actually we can simplify our life just by changing the Invite user welcome message text for the entire system, rather than creating two different behaviours

**Comment by Praxie** [comment]
@Dartv yes, on the Canvas screen we need to have the custom welcome message in the modal window:
![image](https://user-images.githubusercontent.com/2095940/50161567-d3292980-02e4-11e9-9054-aea0adb1507b.png)

**Comment by sives** [comment]
@Praxie If we can pass the Welcome message as a parameter to the modal window this would be the preferred solution.  It's not as easy as I thought to come up with a welcome message that works well for both Plio Canvas and Plio Operations users.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1717

**Comment by Dartv** [comment]
![](https://i.gyazo.com/5fd8487acffcbdf829c8757956a844fd.png)

**Comment by sives** [comment]
Looks good.
