### ISSUE TITLE
Default card takes too long to display

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#167]
When a user enters a screen e.g. the Standards screen, the left hand side List view appears on the screen first, and then the default initial card (document) appears on the right hand side.

The LHS List view is now rendering fairly quickly.  However the rending of the initial card on the RHS is still very slow, and needs to be speeded up to meet the requirements specification.

We need to look at approaches to caching just the initial card data, so that it can load faster.  I am open to loading the last card that was open when the user left the screen, rather than the first card in the data set, if that would make it easier to implement this kind of caching.

**Comment by RevelsGit** [comment]
https://github.com/JSSolutions/Plio/pull/343
