### ISSUE TITLE
Naming of RHS dropdown menu items

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1671]
The Business Design view should be called “Canvas view”
The Business Operations view should be called “Operations view” (see Step 5 spec)
These names should be used in the LHS dropdown menu and in the dropdown menu title at the LHS of the header bar at the top of the Canvas view and Operations view screens.
“View report” should be renamed to “Print report”.
“Org Settings” should be renamed to “Organization settings” (Note the small “s” in settings)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1700

**Comment by sives** [comment]
Looks good !
