### ISSUE TITLE
Organization settings behaviour

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1672]
- in the Home screen subcard, the subtitle “Implementation view defaults” should be changed to “Operations view - defaults” (Note the hyphen character in the middle).  The subtitle “Implementation view titles” should be changed to “Operations view - titles” (Note the hyphen character in the middle).
- there should be no Canvas screen subcard just below the Home screen subcard (in the current staging version, clicking on this Canvas screen subcard generates an error message).

**Comment by Dartv** [comment]
There should be a "Canvas screen" subcard https://github.com/Pliohub/Plio/issues/1511
It's just bugged in the live version (probably needs migration)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1706

**Comment by sives** [comment]
i) When the user enters the Home screen subcard and switches from Operations view to Canvas view as the default home screen, the time for the selection field to display the new selection is unacceptably long (about 10 seconds).  To the user, it appears that the selector function is broken.

ii) Occasionally the default values for the Operations view defaults fail to be displayed, instead showing blank fields (I've been unable to reproduce the exact conditions which trigger this bug)

iii) Replace the field title 'Overdue actions' with 'Overdue items'.

iv) Please replace the current help text (just underneath 'Operations view - titles') with the following:

Plio lets you set different default values for the number of items to be displayed on the Operations view screen.  When this number (N) is exceeded, Plio will display the most recent N items, followed by a 'More' button.

Plio also lets you customize the labels for each of the main icons on your home screen. Just select an icon label you wish to change, click on the selection button and select an alternative name from the options provided, or create an entirely new name.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1821

**Comment by Dartv** [comment]
@sives I'm unable to reproduce this. What organization are you testing?

**Comment by Serhiy91** [comment]
I also cannot reproduce this.

**Comment by sives** [comment]
@Praxie @Serhiy91  It's working fine now.  Must have been a transitory problem.

**Comment by sives** [comment]
@Praxie One of the issues listed above (issue ii) is still problematic. The default set values for the Operations view defaults in Org settings are not being displayed in the Shift Bioscience organisation. However they are displayed correctly in all other organisations.  This is a reproducible bug in both Safari and Chrome, and happens every time you click on Organisation settings from the LHS dropdown in the Shift Bioscience organisation.

**Comment by Dartv** [comment]
@sives I can't test this because I don't have a permission to open org settings

**Comment by sives** [comment]
Dmytro - feel free to use my login credentials.  I will send them via Telegram

**Comment by Dartv** [comment]
@sives does it happen if you set them to something?

**Comment by Dartv** [comment]
This is probably because you've played with these settings while they were still being developed

**Comment by sives** [comment]
@Dartv When I try and set them to something, the entire Home screen subcard disappears from the Org settings modal.  When I exit and reenter the Org settings modal I see the Home screen subcard reappear again, but the missing default values might have been updated.

**Comment by Dartv** [comment]
@sives Shift Bioscience organization specifically lacked some database fields. I directly added them, so it works now

**Comment by sives** [comment]
@Dartv Are there any other Plio organisations that lack these fields?  If this happened in Shift Bioscience it could conceivably happen in one of our customers' organisations.

**Comment by Dartv** [comment]
No, I checked every other organization.

**Comment by Dartv** [comment]
I already explained why this could've happened to Shift Bioscience organization
