### ISSUE TITLE
Error with decimal percents

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1676]
1. Try create ,,cost line,, with decimal percent
Bug: error displays. There must be correct validation for fields with percents

Variable "$input" got invalid value {"_id":"S8EacsBRiYBhQghJj","title":"mitel tintel","notes":null,"color":"#3F51B5","percentOfTotalCost":"99.9","notify":["xASeDQe2vKQAhdEac"],"fileIds":[],"originatorId":"xASeDQe2vKQAhdEac"};
Expected type Int at value.percentOfTotalCost; Int cannot represent non-integer value: 99.9

![image](https://user-images.githubusercontent.com/41466462/50162479-28fed100-02e7-11e9-8d2d-1ee1d72b18ee.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1722

**Comment by sives** [comment]
@Praxie Works fine

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 12/28/18 - 12/28/18
Work session total: 0:23:19

Grand total: 0:23:19

**Comment by vitalii7777** [comment]
Go to Customer segments
Create new or choose existing Potential gains
Input in Financial impact field decimal number 20.2 for example. We will get: $input" got invalid value

Look at the picture:
![input decimal error](https://user-images.githubusercontent.com/47181845/52061250-90f73700-2576-11e9-9458-d740b58157d4.png)

**Comment by Dartv** [comment]
@sives can we make financial impact field as small as other number fields?
![](https://i.gyazo.com/c18e13da478152917ae0895675f37258.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1871

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/06/19 - 02/07/19
Work session total: 3:53:01

Grand total: 4:16:20
