### ISSUE TITLE
Adding action to key goal from board

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1677]
Chrome web

Preconditions: created key goal

1. Open Business operations view
2. Try add action to key goal 

Bug: error displays.  Watch video and screen. (https://drive.google.com/open?id=1fkCebnyNRRGmbmhtpWeVp1JJIVfUgAUJ)

![image](https://user-images.githubusercontent.com/41466462/50207144-46c74700-0376-11e9-81e3-2ebe2811dbf3.png)

**Comment by Dartv** [comment]
Fix is already merged

**Comment by sives** [comment]
@Praxie Works fine
