### ISSUE TITLE
Adding improvement plan to nonconformity 

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1679]
Chrome web

preconditions: created nonconformity

1. Open nonconformity list
2. Edit nonconformity -> add improvement list -> save changes
3. Open edited nonconformity -> verify added improvement list

Bug: added chenges not save. Watch screenshot and video https://drive.google.com/open?id=1NPxY3xtZzkJO9wfDjXE7IkfN9SH5RQAU
![image](https://user-images.githubusercontent.com/41466462/50214588-5a2fdd80-0389-11e9-8550-6eab2643c9fe.png)
![image](https://user-images.githubusercontent.com/41466462/50214604-63b94580-0389-11e9-8621-589c9e0cbb8f.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1723

**Comment by sives** [comment]
@Praxie  It works fine, except that I can't remove a data value for "Target date for desired outcome" once I've set one.  There needs to be a Delete button to the right hand side of the "Target date for desired outcome" field just as there is for the "Improvement plan review dates" fields (see below).

![screenshot 2019-01-31 at 18 03 28](https://user-images.githubusercontent.com/2330529/52074831-abcfa880-2582-11e9-88c3-92b355b2d20f.png)

**Comment by sives** [comment]
@Praxie Working fine now

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 12/28/18 - 12/28/18
Work session total: 0:37:10

Grand total: 0:37:10
