### ISSUE TITLE
Added to discuss photo not displays

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1680]
Chrome web

Preconditions: created nonconformity

![image](https://user-images.githubusercontent.com/41466462/50220425-f4e4e800-039a-11e9-935e-8e482a386b31.png)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1724

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/51342157-c93d4680-1a9b-11e9-95d0-1b961c238350.png)

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/51342200-e96d0580-1a9b-11e9-87d3-4851d633bc81.png)

**Comment by sives** [comment]
@Praxie Works fine
