### ISSUE TITLE
Incorrect revenue percent counting

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1682]
Chrome web
1. Create revenue -> save
2. Edit percents in revenue 

Bug: watch video and screenshot 

https://drive.google.com/open?id=1H4zIBWZjJTjnHfgc67Oi4Op-Vl2RMI2E

![image](https://user-images.githubusercontent.com/41466462/50223009-acc9c380-03a2-11e9-9675-260fe7d6df11.png)

**Comment by Dartv** [comment]
Can't reproduce. Also, you can't add more than 100% across ALL revenue streams

**Comment by MaxLutkovec** [comment]
I added only one item with percents less then 100

**Comment by Dartv** [comment]
@Serhiy91 confirmed reproduction. This only happens for new organizations

**Comment by Dartv** [comment]
@Serhiy91 your middleware tests should cover that case
