### ISSUE TITLE
Risk Edit - > risk evaluation block

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1685]
Chrome web
Preconditions: created Risk
1. Edit risk
2. Add risk evaluation -> save
3. Open this Risk

Bug: risk evalutaion block not saves. https://drive.google.com/open?id=17GPmEZWhZM1y_5ZUL6qwRlRnTB0z6V0g

**Comment by sives** [comment]
@Praxie Works fine

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 12/28/18 - 12/28/18
Work session total: 0:55:33

Grand total: 0:55:33
