### ISSUE TITLE
Canvas screen -> footer color

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1688]
Firefox web
Bug: Check footer color. Must be #000000
![image](https://user-images.githubusercontent.com/41466462/50279444-5a47e000-0452-11e9-9e9b-2e9cc0795517.png)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1719

**Comment by sives** [comment]
@Praxie Looks fine
