### ISSUE TITLE
Android / IOS UI bugs

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1690]
Android 7.0,
diagonal 5.0, Chrome mobile
IOS 12.0
Diagonal 5.8, Safari mobile (There almost the same issue on both devices)
1. Open canvas screen.
Bug: ![image](https://user-images.githubusercontent.com/41466462/50284686-7eabb880-0462-11e9-9643-17206f26240f.png)

2. Open report screen
Bugs: 
![image](https://user-images.githubusercontent.com/41466462/50284775-cf231600-0462-11e9-8ab6-d062308d3c5d.png)
![image](https://user-images.githubusercontent.com/41466462/50284785-d9451480-0462-11e9-8592-a7de087f5805.png)
![image](https://user-images.githubusercontent.com/41466462/50284793-dfd38c00-0462-11e9-81d2-d300dd263004.png)
![image](https://user-images.githubusercontent.com/41466462/50284800-e530d680-0462-11e9-9600-64a4e5eaaa12.png)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1730

**Comment by Praxie** [comment]
@Serhiy91 please, remove the full name from this component at all on mobile because the name of organization is not visible at all. It's get cut.  
Leave just a presence indicator and an arrow.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1814

**Comment by Praxie** [comment]
![img_6b28114420fa-1](https://user-images.githubusercontent.com/2095940/52445804-d1d1eb80-2b34-11e9-8a46-89f7f02a1873.jpeg)

**Comment by sives** [comment]
@Praxie It's fine
