### ISSUE TITLE
Android / IOS -> can't scroll page fully

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1691]
Android 7.0
diagonal 5.0, Chrome web
1. Open business operations view page. Check bottom of the page
BUG:  
![business operations view](https://user-images.githubusercontent.com/41466462/50285265-62a91680-0464-11e9-94f9-1d2f65d0efa3.png)

2. Open standarts, risk, nonconformity detailed page. Check bottom of the page 
BUG: 
![detaild page](https://user-images.githubusercontent.com/41466462/50285328-91bf8800-0464-11e9-9f3c-4d743329c7d5.png)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1730

**Comment by Praxie** [comment]
@Serhiy91 I still can reproduce this. Please contact me if you need more details.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1815

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1883

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1906

**Comment by Praxie** [comment]
The issue is fixed now on iPhone X and Android.

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/20/19 - 02/20/19
Work session total: 1:15:45

Grand total: 1:15:45
