### ISSUE TITLE
Login page not loaded  (IPAD)

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1698]
Safari
Ipad air
![image](https://user-images.githubusercontent.com/41466462/50338031-a579f580-051b-11e9-820f-ce4d5c6b285e.png)

**Comment by Serhiy91** [comment]
It is not reproduced on Ipad air emulator.

**Comment by MaxLutkovec** [comment]
Confirmed

**Comment by Dartv** [comment]
Should be fixed by https://github.com/Pliohub/Plio/pull/1734
Needs retesting

**Comment by Dartv** [comment]
Maybe we should treat mobile safari as legacy similar to edge https://github.com/Pliohub/Plio/issues/1699

**Comment by Praxie** [comment]
@Dartv @Serhiy91 on iPad mini I see the same blank screen.

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/50895875-06f0fe00-1410-11e9-8653-689a2f0b0c1c.png)

**Comment by Praxie** [comment]
@Dartv FYI

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1756

**Comment by Praxie** [comment]
@Dartv still doesn't load on iPad Mini.

**Comment by Dartv** [comment]
Works fine on iPad air. There's no option to simulate ipad mini on macOS

**Comment by Praxie** [comment]
I guess that there is a little chance of somebody using Plio on iPad mini. On iOS simulators and Android tablets it works fine. So I'd close this issue @sives

**Comment by sives** [comment]
@Praxie Works fine on my iPad Air.  No need to worry about iPad Mini

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/08/19 - 02/08/19
Work session total: 0:19:34

Grand total: 0:19:34
