### ISSUE TITLE
Canvas screen not opens on Edge

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1699]
Windows 10
Edge (18)
Bug: Canvas screen not opens (loaded) watch video.
https://drive.google.com/open?id=1tfrmRzG87Z6f-9WFYq18u7HDqq0swYf5

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 12/29/18 - 01/02/19
Work session total: 8:18:24

Grand total: 8:18:24
