### ISSUE TITLE
Data export -> 502

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1710]
Bug: After i try export data i get 502 error.

![data export](https://user-images.githubusercontent.com/41466462/50449372-b10c5880-092f-11e9-9814-63db3acddace.png)
![502](https://user-images.githubusercontent.com/41466462/50449377-b36eb280-092f-11e9-9541-67f5b53e2994.png)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1745

**Comment by sives** [comment]
@Praxie Seems to work fine
