### ISSUE TITLE
NCs&PGs -> incorrect file

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1715]
Bug: There no NCs&PGs text in filter as in all other filters
![correct](https://user-images.githubusercontent.com/41466462/50484459-40317300-09f9-11e9-9e98-932ce7bd20da.png)
![incorrect](https://user-images.githubusercontent.com/41466462/50484465-445d9080-09f9-11e9-8516-078b2360ec9c.png)

**Comment by Dartv** [comment]
I think this was intentional. If we look at the history of the file, it clearly shows that before there was prefix, but it was specifically removed.

**Comment by Praxie** [comment]
Strange. I don't remember any requirements to remove the first part of the filter name from the dropdown. Do you, @sives?

**Comment by Praxie** [comment]
In the live app we have the same dropdown: 

![image](https://user-images.githubusercontent.com/2095940/51198326-a45e9d00-18fc-11e9-8103-6f624d7c9162.png)

**Comment by sives** [comment]
@Praxie @Dartv Dartv is correct, there was a requirement to do this when adding PGs, because otherwise the text strings became too long and complicated.  However we now need to make the filter names in the Standards and Risks screens consistent with this design pattern.

**Comment by sives** [comment]
@Praxie  It would be clearer if we changed the text strings to:

Title: Work - my current work

First 4 items in menu:
My current work
Team current work
My completed work
Team completed work

Last 2 items unchanged.

**Comment by Dartv** [comment]
![](https://i.gyazo.com/2aa27aeaf9cb3697da72c0b39d773736.png)
![](https://i.gyazo.com/28066f07a98c3a53eeae005f7e48a2ca.png)
![](https://i.gyazo.com/a0af6f79c64ca4282a0e27af6f2e5b87.png)

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/52447719-3e9bb480-2b3a-11e9-9fb8-09e01236fdc0.png)
