### ISSUE TITLE
Complete Nonconformity,Risk button absence

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1718]
Bug: If we go to work inbox list and open nonconformity, risk -> there no complete button as on gain. Watch screenshot. 
![image](https://user-images.githubusercontent.com/41466462/50508211-9948e780-0a89-11e9-869c-a55ef8a0153c.png)
![image](https://user-images.githubusercontent.com/41466462/50508273-d7460b80-0a89-11e9-9639-8cd610e69c55.png)
![image](https://user-images.githubusercontent.com/41466462/50508283-e0cf7380-0a89-11e9-871c-fe6febee091c.png)

**Comment by Dartv** [comment]
I think this was also intentional. I remember Steve wanted so that the user needs to open the modal and fill in all of the fields needed to complete root cause analysis manually

**Comment by Praxie** [comment]
@Dartv  I confirm that.
@sives do you confirm this?

**Comment by sives** [comment]
@Dartv @Praxie I can confirm this is correct.  It is to stop users bypassing the need to enter the relevant root cause analysis or risk analysis details

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 12/29/18 - 12/29/18
Work session total: 0:09:26

Grand total: 0:09:26
