### ISSUE TITLE
React error screen should look similar to "Not found page"

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1732]
It should have button "Return to my organization" that redirects to "hello" route

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1742

**Comment by Praxie** [comment]
@Dartv @Serhiy91 how can I test (open) the React Error screen?

**Comment by Dartv** [comment]
@Praxie ![](https://i.gyazo.com/ca46e22ffff38bae64c034dff3b481f2.png)

**Comment by Praxie** [comment]
@Dartv the error message should be more specific.
You have no access to organization ###
or
Failed to load the Canvas screen

**Comment by Dartv** [comment]
This should be done after https://github.com/Pliohub/Plio/issues/1748

**Comment by sives** [comment]
@Dartv I don't know how to test this, so let's assume it is resolved (can always be fixed after go-live)
