### ISSUE TITLE
IPAD,Android tablet -> UI modal bugs

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1733]
Bug: There are UI issue with opened modal windows (NOT FULL SCREEN OPENS)
![image](https://user-images.githubusercontent.com/41466462/50585226-a47e8780-0e7c-11e9-8d28-a661ea2b9223.png)
![image](https://user-images.githubusercontent.com/41466462/50585237-b6602a80-0e7c-11e9-971d-f6e96a1ad335.png)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1735

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/52447759-6428be00-2b3a-11e9-9fad-c1e559258f39.png)
