### ISSUE TITLE
Work inbox - completed filter

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1744]
Preconditions: a few not completed work
1. Complete some work
2. Apply ,,my completed,, or ,,team completed,, filter
Bug: there no completed work, filter not works  
![image](https://user-images.githubusercontent.com/41466462/50688056-750e7d00-102c-11e9-85c6-b684054d78fc.png)
![image](https://user-images.githubusercontent.com/41466462/50688064-7cce2180-102c-11e9-8f9f-2694f1627a77.png)
![image](https://user-images.githubusercontent.com/41466462/50688076-83f52f80-102c-11e9-83bc-2981e76c44db.png)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1749

**Comment by Praxie** [comment]
@Dartv I confirm that the background app is not running. I'll try to update it.
