### ISSUE TITLE
Business operations view - milestone

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1746]
Precondition: created milestone
Bug: when i try mark milestone as complete - there an error in console 
![image](https://user-images.githubusercontent.com/41466462/50691830-9f673700-103a-11e9-9f48-fbb3bbc029bb.png)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1750

**Comment by Praxie** [comment]
https://gyazo.com/da414c4b1dd8bdf5193a4247acb389c8
