### ISSUE TITLE
Scroll canvas section to the bottom after adding an item

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1764]
https://github.com/Pliohub/Plio/issues/1657#issuecomment-454348944

**Comment by Praxie** [comment]
https://gyazo.com/b98d652c28047903c201e7a681900378

**Comment by sives** [comment]
@Praxie Working well

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 01/16/19 - 01/17/19
Work session total: 1:54:36

Grand total: 1:54:36
