### ISSUE TITLE
Linking Value propositions to Customer segments

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1767]
@praxie @Dartv When adding a new Value proposition the user needs to be able to link it to any of the existing Customer segments, and vice versa.  I also need to be able to de-link a Value proposition from a Customer segment and re-link it to a new segment.  This doesn't appear to be working.

**Comment by sives** [comment]
@Praxie I figured out what is going wrong - it's really a usability issue.  The user doesn't realise that they can only match Value propositions to unmatched Customer segments and vice versa.  They don't see the full list of Customer segments they are expecting to see when they click on the Matched to button in the top section of the card.   

We need to change the display of the selection list in the Value propositions card, so that the user understands what they are about to do and what the constraints are.  At the top of the selection list of customer segments we should display a line of guidance text "Unmatched customer segments:".  At the bottom of the selection list we should display a second line of guidance text "Each value proposition can only be matched to a single customer segment".  

We should do the same in the Customer segments card.  At the top of the selection list of value propositions we should display a line of guidance text "Unmatched value propositions:".  At the bottom of the selection list we should display a second line of guidance text "Each customer segment can only be matched to a single value proposition".  

I will upload an image showing the intended UI layout

**Comment by Dartv** [comment]
@sives why not just add this information to guidance panel?

**Comment by sives** [comment]
@Dartv 2 reasons.  First, not all users will want to use the Match to function, so I don't want to describe this in the main guidance, which is higher level guidance.  Second, because this information should be provided in context, otherwise it's a lot harder for the user to see why it isn't working.

**Comment by Praxie** [comment]
Duplicate https://github.com/Pliohub/Plio/issues/1865
