### ISSUE TITLE
Need for real time update after adding or deleting canvas items

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1769]
Unlike other parts of the system, there is no real time update when adding or deleting canvas items.  However, this is the one area of the system where real time update is really important.  Users in different geographical locations will want to collaborate to create canvases, in a collaborative business design session.  If real time update is not provided, users then have to tell each other when to manually reload the screen.  So it needs to be changed.

**Comment by Dartv** [comment]
The easiest solution is to poll periodically. I think 30 seconds interval is fine for this.

**Comment by Dartv** [comment]
Also, we should set network policy for select inputs to "network-only" to always display relevant data

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1793

**Comment by sives** [comment]
@Dartv @praxie It might be the easiest solution technically, but unfortunately this isn't going to be good enough from a user perspective. If I'm in a collaborative design session, I want to any change that anyone else makes within a couple of seconds, just like any normal real-time change in Meteor.  This is one part of the system where real-time behaviour is absolutely crucial to the usability of the feature.

**Comment by Dartv** [comment]
This should've been stated from the very beginning. Now it will take a lot of time to implement it

**Comment by sives** [comment]
I don't think it is reasonable to blame the client on this issue. We are building a system on Meteor, which if used in the normal way gives you real time update for free. All other aspects of Plio UI update in real time. It's entirely reasonable for the client to assume that canvas cards would behave like other aspects of the UI.

**Comment by Dartv** [comment]
Sorry if it seemed like I was blaming you. It's not that bad actually. We can replace main part of ui with meteor I think (probably the easiest way) or implement graphql subscriptions (harder)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1827
https://github.com/Pliohub/Plio/pull/1829
https://github.com/Pliohub/Plio/pull/1830

**Comment by sives** [comment]
@Dartv Looks good, I will test when @Praxie gives me the green light for the next release on Staging

**Comment by sives** [comment]
@Dartv Works really well

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 01/17/19 - 01/29/19
Work session total: 27:12:32

Grand total: 27:12:32
