### ISSUE TITLE
Chart icons in footer areas are stealing too much space

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1770]
Four of the canvas sections (Customer segments, Key partners, Cost structure, Revenue streams) contain chart icons in the section footer area.  These icons are stealing too much space from their canvas section areas, limiting how many items can be displayed in that section.  It would be much better to display the canvas icon in a separate layer in front of the scrolling list in each section, and make sure that the scrolling list then uses the full height of the canvas section.  

(Operational elements e.g. Key goals will still need to be displayed in a dedicated area at the bottom of the canvas section, as they are at the moment).

(If displaying the icon in a separate layer is difficult, I can go back to Jack to ask for alternative ideas to let us use the full height of the canvas section).

A simpler, quicker alternative would be to allow longer lists of items in the Cost structure and Revenue streams sections to extend over into a second column on the right hand side of the section, like they do in the Report view.

**Comment by sives** [comment]
@Dartv The operational elements are stealing space as well.  However, the fundamental problem remains - there is very little space for the item list in the Cost structure and Revenue stream sections because of their limited vertical height.

These sections are also much wider than normal.  Would it be possible to create a 2 column layout, just for these bottom two sections?  Then we can display more items before we are forced to scroll the list.

**Comment by Serhiy91** [comment]
@sives 
1. 2 column layout as you described above hard to implement. It causes a lot of issues (which can take much time to fix) with drag & drop sorting. Also, it is needed some line separator. You can see it on the screencast https://drive.google.com/file/d/1SCKlCTBhdFJTudKWTyW-CjnbLowkP-i_/view .

2. Another way of 2 column layout https://drive.google.com/file/d/15vJ1sQMdzLouD_uE1JYe_2J4CEgQ5a7K/view

3. And also we can make a simple inline list https://drive.google.com/file/d/12_dZS02w2anb25GBon-kcUyK9KuIKnKk/view

So, What is a better way for you?

**Comment by sives** [comment]
@Serhiy91 I like your option 2 - another way of 2 column layout.  It seems to work fine for drag and drop within a section, and it lets us display a good number of items within this section.   Let's implement this just for the Cost structure and Revenue streams sections.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1823

**Comment by Serhiy91** [comment]
via Hubstaff
User: Serhiy Zinchuk

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 01/23/19 - 01/24/19
Work session total: 2:43:56

Grand total: 2:43:56

**Comment by sives** [comment]
In the Cost structure and Revenue streams sections, a partial grey shadow line is displayed even when there are no scrollable items below the bottom of the section, see below. This does not happen with any of the other canvas sections and needs to be removed.

![screenshot 2019-01-31 at 16 17 41](https://user-images.githubusercontent.com/2330529/52068314-55f40400-2574-11e9-81fa-3d92d79b0ffb.png)

**Comment by Praxie** [comment]
@sives as I remember, we couldn't reproduce this.
