### ISSUE TITLE
Report formatting - bullet points needed in Canvas items section

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1776]
Each Canvas item text string in this section (the section titled Shift Bioscience Canvas items (57) i.e. the second section in the report) should have a grey bullet point at the left hand side of the string, using same grey as the subsection titles.  This will help to create more visual separation between the individual items.  

(not sure if bullet points should be grey or black, we should try both and then decide)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1807

**Comment by Serhiy91** [comment]
![image](https://user-images.githubusercontent.com/13336284/51396109-19bdae00-1b47-11e9-99ee-608b2c081846.png)
![image](https://user-images.githubusercontent.com/13336284/51396122-1cb89e80-1b47-11e9-90c5-4abcb532961d.png)

**Comment by Serhiy91** [comment]
@sives So, What color of bullets should be?

**Comment by sives** [comment]
@Serhiy91 Let's go for the black ones

**Comment by Serhiy91** [comment]
via Hubstaff
User: Serhiy Zinchuk

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 01/18/19 - 01/18/19
Work session total: 0:26:08

Grand total: 0:26:08

**Comment by sives** [comment]
@Serhiy91 Bullet points aren't displaying properly on Safari browser, space between bullet point and text is getting deleted

**Comment by sives** [comment]
@Praxie This still has not been done

**Comment by Dartv** [comment]
@Serhiy91 this is because of `margin: -10px` in `CanvasReportItems` component

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1902

**Comment by sives** [comment]
@Serhiy91 Looks good, problem now fixed.
