### ISSUE TITLE
Report printing - default page orientation

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1780]
When the user clicks on 'Print report', then 'Print', then 'Print' again to reach the printer dialog, sometimes the printing function is set to landscape orientation (correct) and sometimes it seems to get set to portrait orientation (incorrect).  

Reports will not print out in a nice way if orientation gets set to portrait.  Is there any way that we can control this programmatically, so that the page orientation is always set to landscape?

**Comment by Serhiy91** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@page/size

**Comment by Praxie** [comment]
@sives it's not possible to have a consistent behaviour in al browsers because the property for the default print page orientation is still experimental.

**Comment by Praxie** [comment]
I'd say to add a line saying "For better rendering choose the landscape print orientation."

![image](https://user-images.githubusercontent.com/2095940/51682847-10be5800-1ff1-11e9-862e-e8e11de79d27.png)

**Comment by sives** [comment]
@Serhiy91 @Praxie Let's follow Mike's suggestion and provide a line of guidance text below the header bar and above the selection options, stating "Make sure page orientation is set to landscape in your print options before printing"

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1874

**Comment by sives** [comment]
@Praxie Looks good
