### ISSUE TITLE
Fuzzy fonts

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1781]
This is a somewhat strange issue.  Some fonts in some of the UI elements are displaying in a fuzzy way i.e. the characters have slightly blurred edges and are not sharp.  This only happens with the Chrome browser and not with Safari, and it only happens with some Plio user interface elements with Chrome, not all user interface elements - so I think it is a bug.

The best example is the LHS dropdown in the Canvas view screen.  Each selection option in the list looks slightly fuzzy when you compare it to the text on the header bar just above and to the text in the RHS dropdown.   (I also see this slight fuzziness when creating or editing Canvas cards, although not as bad as in the LHS dropdown.  I don't see it anywhere else in the system)

![screenshot 2019-01-15 at 17 45 57](https://user-images.githubusercontent.com/2330529/51198974-8ccbe800-18ed-11e9-96d9-c6c481d27b5c.png)

**Comment by Dartv** [comment]
Fonts look fine for me on macOS mojave chrome
![](https://i.gyazo.com/21aa4bf50687437755e8dc57c73a4c8c.png)
I know that chrome optimizes fonts on slow connection, so maybe this is the issue

**Comment by sives** [comment]
@Dartv I don't have a slow connection :-) I am definitely seeing this issue on my latest up-to-date Chrome browser.   Possibly it may be related to our use of a Microsoft font which is no longer well rendered by the current versions of Chrome.  Can we test the effect of switching out the current font for a similar Google font and see if it fixes the problem?

**Comment by sives** [comment]
@Dartv I've had a new idea about what could be causing this.  It would only take a short time to test my hypothesis and we might then be able to find the root cause.

Some versions of Chrome have known issues with displaying certain fonts, making them appear fuzzy. My two different laptops are running different versions of Chrome and different versions of MacOS.  My MacBook Pro is running Chrome Version 71.0.3578.98 and High Sierra 10.13.4.  My MacBook Air is running Chrome Version 72.0.3626.119 and Mojave 10.13.3.  I only see the fuzzy fonts on Chrome on the MacBook Air.  I only see the fuzzy fonts in the LHS dropdown menu in the Operations screen and nowhere else in the system.

My hypothesis is that when the LHS dropdown menu was re-implemented, we accidentally specified a slightly different font, or version of the font, compared to the rest of the system.  It is this difference in the font that is causing the fuzzy fonts effect.

Please can we check whether or not we are using exactly the same font in the LHS dropdown menu in the Operations screen compared to the rest of the system?

**Comment by Dartv** [comment]
@sives It's the same font that we use in the rest of the system "Segoe UI Regular WestEuropean".
I suggest you to use the latest chrome version

**Comment by sives** [comment]
@Dartv I am running the latest Chrome version (73.0.3683.75) and the latest MacOS version (Mojave 10.14.3).  

It may be a coincidence, but I don't see canvas section outline problem #1994 nor this fuzzy font problem on my older MacBook Pro.  The two problems may have a common root cause.  They are both related to rendering of vector objects i.e. lines and fonts.

**Comment by sives** [comment]
@Dartv I will close this issue, we've spent enough time on it for now.
