### ISSUE TITLE
'2019' text is falling off the left hand side of the home screen

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1783]
In the Operations view, the word "2019" is only partially displayed on the left hand side of the screen, on the Key goals timeline.  It should be displayed in full.  Suggestion: add some code that positions the year indicator immediately after the first month in the timeline, as part of the same text string e.g. February 2019.  (Don't fix this if it's too complicated)

![screenshot 2019-01-15 at 18 05 00](https://user-images.githubusercontent.com/2330529/51199979-1c729600-18f0-11e9-9662-3b304f83376e.png)

**Comment by Praxie** [comment]
Unfortunately, it's too complicated because it's handled by the VictoryJS library.

**Comment by Praxie** [comment]
@sives
