### ISSUE TITLE
Error when open Risk or Standard edit Modal

### ISSUE THREAD

**Issue by Serhiy91** [Pliohub/Plio#1824]
Steps to reproduce:
1. Go to standards page
2. Reload page
3. Press the edit button of some standard
![image](https://user-images.githubusercontent.com/13336284/51683017-89251900-1ff1-11e9-98df-2a93dd1cb7c8.png)

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/52500059-ad821780-2be5-11e9-9aed-885ec7931fe3.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/04/19 - 02/04/19
Work session total: 0:27:04

Grand total: 0:27:04
