### ISSUE TITLE
Add help panels to all Add a document modals on the Canvas screen

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1826]
[Screen sketches for canvas card help.pdf](https://github.com/Pliohub/Plio/files/2794019/Screen.sketches.for.canvas.card.help.pdf)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1828

**Comment by sives** [comment]
@Praxie See my comments in #1838

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1907

**Comment by Serhiy91** [comment]
via Hubstaff
User: Serhiy Zinchuk

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 01/25/19 - 01/25/19
Work session total: 4:23:37

Grand total: 4:23:37
