### ISSUE TITLE
Unable to edit other user's canvas items if linked

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1831]
When I'm working in "Test organization" and I try to edit the canvas item titled "customer master" created by Michael Rokosh in the Customer segments section, it will not save my changes.  There is no error message, but my changes to the title field or the notes field are not retained by the system.

When I try and edit another canvas item created by Michael Rokosh e.g. Key partners in the Key partners section,  I can make changes and these are saved and retained by the system.  The only difference seems to be that "customer mastomer" was previously linked to the "value malue" Value proposition, whereas "key partners" is an unlinked item.

**Comment by Dartv** [comment]
The problem was that this item had pink color set from the old palette and db schema was rejecting it. This isn't a problem because users won't be able to set old colors when we go live.
I just changed the color and my changes are being saved just fine

**Comment by sives** [comment]
@Dartv OK that's good
