### ISSUE TITLE
Data export download guidance text needed

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1832]
@Praxie When I try to download data items in the Nonconformities screen where all the Nonconformities are status = closed, the CSV file downloads but contains no data items.

I suggest that we implement a guidance text panel just underneath the Data export card header, with the following text: "By default, only open items will be exported. To change this, go to Advanced Filters".   This text panel should be white, it should be the same height as the card header, and it should have a grey line underneath to separate it from the rest of the card items.

**Comment by Dartv** [comment]
![](https://i.gyazo.com/596a20552b32ced6a4558275eab3e571.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1858

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/52500109-d7d3d500-2be5-11e9-8582-f13689a15cd1.png)

**Comment by sives** [comment]
@Praxie Looks good.

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/04/19 - 02/04/19
Work session total: 0:33:28

Grand total: 0:33:28
