### ISSUE TITLE
End Date < Start Date and impossible to change it later

### ISSUE THREAD

**Issue by vitalii7777** [Pliohub/Plio#1835]
When we creating a new goal, start date could be later than end date for example: start 31-01-2019, end 20-01-2019. Also in this case later impossible to change start or and date.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1850

**Comment by Praxie** [comment]
@sives do you want to change this error message?
![image](https://user-images.githubusercontent.com/2095940/52500190-1073ae80-2be6-11e9-801a-0f38e4076a0b.png)

**Comment by sives** [comment]
@Praxie Yes, I'd like to change it to: "Start date must come before the end date"

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1904

**Comment by sives** [comment]
Tested and works fine
