### ISSUE TITLE
Description and status fields - got error 500 when many input chars

### ISSUE THREAD

**Issue by vitalii7777** [Pliohub/Plio#1836]
Add any Key Goal, go to description or status field and try to input a lot of chars (I got an error when inputted more 490 chars ). Easy to catch this error using copy-paste

![many chars](https://user-images.githubusercontent.com/47181845/52049721-1ff45700-2557-11e9-9c4d-645f43ab2ba4.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1851

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/01/19 - 02/01/19
Work session total: 0:24:51

Grand total: 0:24:51
