### ISSUE TITLE
Editor icons are stacked vertically

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1838]
![image](https://user-images.githubusercontent.com/2095940/52054324-cc890580-2564-11e9-8fb8-f51a3e109a87.png)

**Comment by Dartv** [comment]
The bug was added here https://github.com/Pliohub/Plio/pull/1821

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1847

**Comment by Dartv** [comment]
Also fixed subcards styles:
![](https://i.gyazo.com/f8fa3dce2d2f2b97f86ff4a101dd28ba.png)

**Comment by sives** [comment]
@Praxie There are 6 remaining problems.   First, the blank space needs to be removed in the top panel containing the question mark icon, it serves no purpose.  Second, there needs to be a guidance text string right at the top of the large text box, stating "Please enter top-level guidance text here".  Third, the user needs to be able to position the cursor at the top of the large text box and start typing, and not be forced to position it 1 cm down.   Fourth, there is a blank white panel between the title area and the large text box in the New guidance card, which doesn't  seem to serve any purpose and needs to be removed.  Fifth, there needs to be a guidance text string right at the top of the large text box in the New guidance card, stating "Please enter top-level guidance text here".  Sixth, the user needs to be able to position the cursor at the top of the large text box in the New guidance card and start typing, and not be forced to position it 1 cm down.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1907

**Comment by Serhiy91** [comment]
@sives Placeholder of the large text box is hard to implement because of old blaze component (second and fifth points). Only users of admin organization can see the large text box. So, I think we do not need to waste time for it. Are you agreed?

**Comment by sives** [comment]
@Serhiy91 Yes, I agree.   However I would like us to fix the problem where the cursor is positioned incorrectly in the text box (1 cm down from the top).  The cursor needs to be positioned at the top of the text box, as in all Plio text boxes.

**Comment by Serhiy91** [comment]
@Serhiy91 All the other points which you mentioned above were fixed and these points are waiting for new deployment.

**Comment by Dartv** [comment]
@sives deployed

**Comment by Praxie** [comment]
@Serhiy91 please remove the top padding from the container with the editor, redeploy the staging app and we'll consider this issue resolved.
![image](https://user-images.githubusercontent.com/2095940/53116855-4bfd6980-3552-11e9-8920-31458d69b28d.png)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1929

**Comment by sives** [comment]
@Serhiy91 Looks good

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/01/19 - 02/01/19
Work session total: 1:33:54

Grand total: 1:33:54
