### ISSUE TITLE
Notification does not working

### ISSUE THREAD

**Issue by vitalii7777** [Pliohub/Plio#1839]
Add user in Notify changes - change key partners, key activity, key resources, value propositions, customer relationship, channels, customer segments, cost structure, revenue streams.

Expected result:  added user should receive notification about changes.
Actual result: no any emails.

**Comment by Dartv** [comment]
We don't have a background app that is responsible for notifications running for staging app. Can't test notifications sadly.

**Comment by vitalii7777** [comment]
We gonna leave it?

**Comment by Dartv** [comment]
@sives notifications should work now

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/53190520-76166080-3612-11e9-85e9-da086325d243.png)
