### ISSUE TITLE
Empty Unique number (Standard)

### ISSUE THREAD

**Issue by vitalii7777** [Pliohub/Plio#1840]
Go to Customer segments
Create new or choose existing Standards
Input in Standart section correct Unique number
Close Standart section and close window of Customer segment.
Open same Standart section again.

Expected result: Unique number will be present.
Actual result: empty Unique number

This issue is present in any resource Customer relationships, Customer segments, etc.

![standards](https://user-images.githubusercontent.com/47181845/52059409-76bb5a00-2572-11e9-809b-886be458e87b.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1860

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/04/19 - 02/04/19
Work session total: 1:08:56

Grand total: 1:08:56
