### ISSUE TITLE
UI bug with diagram (Key partner)

### ISSUE THREAD

**Issue by vitalii7777** [Pliohub/Plio#1841]
Go to Key partner
Set up "Critically" and "Level of spend" to the maximum value
Click close and check diagram.
Look at the picture:
![out of range](https://user-images.githubusercontent.com/47181845/52062317-fc420880-2578-11e9-8a37-112cab910b39.png)

**Comment by Dartv** [comment]
I don't think this is a big deal. @sives is it?

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1864

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/52500571-01d9c700-2be7-11e9-8e4a-6a8c8d2d31b4.png)
