### ISSUE TITLE
Error with invalid value percentage field

### ISSUE THREAD

**Issue by vitalii7777** [Pliohub/Plio#1842]
No full input validation for correct value in the percentage field.
To reproduce this bug follow next steps:
1. Go to Revenue Streams
2. Create new resource
3. Fields "% of revenue" and "% of profit" must be empty
4. Input many digits like on the picture:
![manual input could be more 100](https://user-images.githubusercontent.com/47181845/52064248-ecc4be80-257c-11e9-99ce-969dc0aadc87.png)

Error - "$input" got invalid value

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1859

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/52500758-6ac13f00-2be7-11e9-9107-8db6537ca54a.png)

**Comment by sives** [comment]
@Praxie Change the text string at the top to "Percentages cannot add up to more than 100%. Please reduce one or more values"  Otherwise, it is working well.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1903

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/53117559-d85c5c00-3553-11e9-9851-fbf1d907a398.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/04/19 - 02/04/19
Work session total: 0:22:17

Grand total: 0:22:17
