### ISSUE TITLE
Incorrect canvas subcard labels

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1844]
The following Canvas item subcards are labelled incorrectly:

"Actively Manage" should be "Actively manage"

"Notify Changes" should be "Notify changes"

The standard design rule in Plio for labelling sub cards is to capitalise the first letter of the first word, but not any other letters.

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/52500860-96442980-2be7-11e9-88a7-c3c59ab2c525.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/01/19 - 02/01/19
Work session total: 0:03:57

Grand total: 0:03:57
