### ISSUE TITLE
Canvas report print guidance

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1845]
@Serhiy91 @Praxie Let's follow Mike's suggestion and provide a line of guidance text below the header bar and above the selection options, stating "Make sure page orientation is set to landscape in your print options before printing"

_Originally posted by @sives in https://github.com/Pliohub/Plio/issues/1780#issuecomment-459368349_

**Comment by Dartv** [comment]
![](https://i.gyazo.com/554b86df10b67091c7241100d80edc68.png)

**Comment by Praxie** [comment]
@Dartv please add a dot in the end of the help text.

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/52821577-e3c50880-30b7-11e9-95f6-6b8acdd95699.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/04/19 - 02/08/19
Work session total: 0:12:50

Grand total: 0:12:50
