### ISSUE TITLE
Milestone default date

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1846]
@Praxie When creating a new milestone, there should be a default date rather than just a blank field (default should be 1 week after current date).  Also, the date field is incorrectly labelled as "Completion - target date" (which is the label used in the General Action field).  It should be labelled as "Date".

_Originally posted by @sives in https://github.com/Pliohub/Plio/issues/1678#issuecomment-458486366_

**Comment by Dartv** [comment]
@sives what if goal's end date is less than one week later? User will still need to manually select date.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1849

**Comment by sives** [comment]
@Dartv  You make a good point.  Let's not set a default date in this case.  (We still need to change the date field label to "Date")

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1849

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/01/19 - 02/01/19
Work session total: 0:37:39

Grand total: 0:37:39
