### ISSUE TITLE
Help icon margin-right should be bigger

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1853]
The margin between the help icon and text should be equal to the left margin. 
![screen shot 2019-02-01 at 12 23 43 pm](https://user-images.githubusercontent.com/2095940/52117381-3e705600-261c-11e9-90ac-7b0b629802ae.png)

(Open the Add cost line card to see it)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1854

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/52500915-c12e7d80-2be7-11e9-8a2f-1f74da78b6ce.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/04/19 - 02/04/19
Work session total: 0:21:19

Grand total: 0:21:19
