### ISSUE TITLE
Add delete button to "Target date for desired outcome"

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1862]
@Praxie  It works fine, except that I can't remove a data value for "Target date for desired outcome" once I've set one.  There needs to be a Delete button to the right hand side of the "Target date for desired outcome" field just as there is for the "Improvement plan review dates" fields (see below).

![screenshot 2019-01-31 at 18 03 28](https://user-images.githubusercontent.com/2330529/52074831-abcfa880-2582-11e9-88c3-92b355b2d20f.png)

_Originally posted by @sives in https://github.com/Pliohub/Plio/issues/1679#issuecomment-459445097_

**Comment by Dartv** [comment]
![](https://i.gyazo.com/13d3c90592417f3695bc21db588d922e.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1863

**Comment by sives** [comment]
@Praxie Working well

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/04/19 - 02/04/19
Work session total: 0:17:28

Grand total: 0:17:28
