### ISSUE TITLE
Redesign "Match to" select input

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1865]
@Praxie I figured out what is going wrong - it's really a usability issue.  The user doesn't realise that they can only match Value propositions to unmatched Customer segments and vice versa.  They don't see the full list of Customer segments they are expecting to see when they click on the Matched to button in the top section of the card.   

We need to change the display of the selection list in the Value propositions card, so that the user understands what they are about to do and what the constraints are.  At the top of the selection list of customer segments we should display a line of guidance text "Unmatched customer segments:".  At the bottom of the selection list we should display a second line of guidance text "Each value proposition can only be matched to a single customer segment".  

We should do the same in the Customer segments card.  At the top of the selection list of value propositions we should display a line of guidance text "Unmatched value propositions:".  At the bottom of the selection list we should display a second line of guidance text "Each customer segment can only be matched to a single value proposition".  

Image showing the intended UI layout:

![screenshot 2019-01-31 at 15 15 48](https://user-images.githubusercontent.com/2330529/52063803-32788b80-256b-11e9-9fd0-bc32653506cb.png)

_Originally posted by @sives in https://github.com/Pliohub/Plio/issues/1767#issuecomment-459376910_

**Comment by Dartv** [comment]
@sives ![](https://i.gyazo.com/8b65741de96cfd462c6818894482ae51.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1866

**Comment by sives** [comment]
@Praxie   It looks confusing.  I've modified the layout - see below.  We need to add a separate control to do the unmatching (instead of the none option).

![screenshot 2019-02-13 at 22 09 12](https://user-images.githubusercontent.com/2330529/52747610-29140800-2fdc-11e9-83d5-e397bd90ec66.png)

**Comment by Praxie** [comment]
![screen shot 2019-02-14 at 4 36 31 pm](https://user-images.githubusercontent.com/2095940/52793572-b3a94580-3076-11e9-8489-dc54f33d2bdf.png)
We can try to put the delete icon into the field.

**Comment by Dartv** [comment]
![](https://i.gyazo.com/43ca181289948335d87ec113c761bee1.gif)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1901

**Comment by sives** [comment]
@Dartv Looks good

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/05/19 - 02/15/19
Work session total: 5:34:43

Grand total: 5:34:43
