### ISSUE TITLE
Calendar overlap

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1867]
![](https://i.gyazo.com/ecee24acb36f98f0f35c96c1241ae0f9.png)

**Comment by Praxie** [comment]
@Dartv z-index: initial; doesn't break anything.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1884

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/53117368-6b48c680-3553-11e9-9ae0-37cc695246da.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/11/19 - 02/11/19
Work session total: 0:25:37

Grand total: 0:25:37
