### ISSUE TITLE
Canvas item size is too big in the Cost structure section

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1878]
https://gyazo.com/ff6ed64ae2d62928e409e18a8007b8b2

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1882

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/52821692-3f8f9180-30b8-11e9-9dba-b83db4356651.png)
