### ISSUE TITLE
Service unavailable message

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#188]
When I switched from the Plio Ltd to the Testlio organization, I got a perpetual spinner.   When I closed the browser tab and tried to log in to Plio again, I got the following message.

![screen shot 2016-10-11 at 14 55 18](https://cloud.githubusercontent.com/assets/2330529/19273036/e69e84de-8fc2-11e6-918e-72d3d5f04f87.png)

**Comment by Praxie** [comment]
@sives it could happen while the system was deploying.
