### ISSUE TITLE
Canvas reactive updates

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1886]
Title and color should be reactive

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1888

**Comment by Praxie** [comment]
@sives I've tested this. Looks fine.

**Comment by sives** [comment]
@Praxie Its fine

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/12/19 - 02/12/19
Work session total: 3:42:48

Grand total: 3:42:48
