### ISSUE TITLE
Canvas reactive footer items

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1887]

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1893

**Comment by Praxie** [comment]
@sives I've tested this. Looks fine.

**Comment by sives** [comment]
@Praxie Mostly it works fine, but I can't delete Key goals items from the footer area, see #1923

**Comment by Praxie** [comment]
@sives so I'm going to close this issue because we have a separate one for Key goals deletion bug (#1923).

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/13/19 - 02/13/19
Work session total: 1:06:17

Grand total: 1:06:17
