### ISSUE TITLE
Report formatting - spurious line breaks

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1894]
In the Canvas report, in the Customer insights and Value components sections, there are unnecessary line breaks being introduced.  The NE and WA abbreviations (e.g. NE1, WA1) and the FE and BE abbreviations should follow on in brackets immediately after the text string, as in the original specification, and not be displayed on a new line.  Displaying them on the new line is not in agreement with the specification, and wastes a lot of space.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1899

**Comment by sives** [comment]
@Serhiy91 Looks good
