### ISSUE TITLE
Item numbers on Home screen not updating

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1897]
@Praxie When I add a new item to a screen e.g. Nonconformities it doesn't update the number shown in the relevant icon panel on the Home screen.  I would expect the item number to update by one.

**Comment by sives** [comment]
@Praxie When I refresh the screen by clicking on the page refresh button in the browser, the number updates correctly.

**Comment by Dartv** [comment]
@sives the numbers are updated each minute.
