### ISSUE TITLE
Standards types list has not been updated

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1912]
This requirement (Section 8, para 2) does not seem to have been implemented yet:

"In Org Settings, change the list of Standard types, removing Business Design (BD) and Compliance Management Objective (CMO) from the list of default types, and adding General Standard (STD) and Guideline (GLN).  The default selection option should be General Standard.”

**Comment by Dartv** [comment]
This is problematic because the user can just rename General Standard. We'll have to disable editing of this standard type. Then, there is Standard operating procedure that is also disabled.
Also, Business Design was never a default standard type.

**Comment by sives** [comment]
@Dartv OK, let's leave it as currently implemented

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/20/19 - 02/20/19
Work session total: 0:13:17

Grand total: 0:13:17
