### ISSUE TITLE
Reassigning document ownership when deleting a user

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1913]
There was a requirement in the Step 5 spec that stipulates that when a user is deleted by another user, the system checks to see if that user owns any documents, and if any such documents are found, the user who is doing the deleting is prompted to assign ownership of these document(s) to another user.  
In the special case that the user deletes their own profile, then any owned documents are automatically transferred to the Org owner.

This requirement has only been partially implemented.  At the moment, the system is prompting to "Select user to take on [username] owner responsibilities" even if that user doesn't own any documents.  It needs to first check if that user does own any documents and only if the user is the designated owner for certain documents should it be prompting to reassign ownership.

There needs to be a guidance text at the top of this modal, just above the selection list:
"[username] is the owner of 6 documents. Please select a user to take over these document owner responsibilities"  After a user has been selected, and after the user clicks on the Delete button again, a confirmation message needs to be displayed as follows:  "[username] has been deleted and ownership of 6 documents has been transferred to [new user]"

![screenshot 2019-02-19 at 14 48 51](https://user-images.githubusercontent.com/2330529/53024462-0ad45f00-3457-11e9-8ad6-9a6102a745bf.png)

**Comment by Dartv** [comment]
We simply can't do that. It's a very heavy computation and requires scanning through all collections and documents. Plus, with any added entity and changes to existing entities, we will have to go back and tweak this every time.

**Comment by sives** [comment]
@Dartv @Praxie Then we need to build a specific database structure that makes it easy and quick to obtain this information, so we don't have to scan through all collections and documents. It should be fairly straightforward to build a database view of document ownerships by user.

**Comment by Praxie** [comment]
@sives now it's too late to incorporate something like this in the current database design. It's possible to implement this if we'll rebuild the whole application from scratch. 
Right now it's possible to do this, but we'll need to list all document types that will need to be checked manually in the code, it will be very messy. It would be easier and cleaner to leave it as it is.

**Comment by sives** [comment]
@Praxie Then we need to provide a better confirmation response to the user after they have pressed the Delete button.  Something like this:  User "John Smith" has been deleted.  Documents owned by John Smith have been reassigned to "New user"
