### ISSUE TITLE
Opening a canvas card sends it into a strange state

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1914]
When I'm in the Plio Ltd organisation, and I go to the Canvas view, then click on the card labelled "Entrepreneur" in the Customer Segment section, the card opens but then immediately goes into a continuous "Saving" state.  The only way to exit this state is to reload the browser page.  This also happens with the New Channel card in the Channels section, but not with any other canvas items.

![saving loop bug](https://user-images.githubusercontent.com/2330529/53027908-b97b9e00-345d-11e9-9c7e-4b08e5c2e7d9.png)

**Comment by Dartv** [comment]
My guess is you're trying to open the old document that was created before we added or changed the schema of this type of document, so it doesn't have required fields. You should just delete this document and create a new one. Then the problem will disappear.
