### ISSUE TITLE
Shortcut to Operations view - UI issue

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1915]
The "Go to Operations view" button that is displayed at the bottom of canvas sections when there are multiple items is confusing - it looks like the system is instructing the user to go to the Operations view, rather than presenting a shortcut option.

We need to reword the text label to "Shortcut to Operations view" and position this button at the bottom of the item list rather than at the top.

![screenshot 2019-02-19 at 15 54 37](https://user-images.githubusercontent.com/2330529/53028605-19bf0f80-345f-11e9-9cc4-cb5ab3389f48.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1917

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/53114070-aa731980-354b-11e9-816b-153006acc90c.png)

**Comment by sives** [comment]
@Praxie Looks good

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/20/19 - 02/20/19
Work session total: 0:22:53

Grand total: 0:22:53
