### ISSUE TITLE
Adding a new canvas card takes 8 sec to display in the UI

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1916]
@Praxie The lag time between adding a new canvas card and seeing it show up on the canvas is far too long. I counted it at 8 seconds.  I'm sure it's got a lot slower since the last time I tested it.

**Comment by Dartv** [comment]
What do you mean? Shows up instantly for me.

**Comment by sives** [comment]
Very strange.  When I tested 5 minutes ago I carried out 3 separate tests and it took 5-10 sec for cards to show up in the UI. When I go back into the system and test again, it shows up instantly.  I will try and reproduce the problem.  Maybe it was a network problem.

**Comment by sives** [comment]
@Dartv I'm seeing this problem again in my new testing session, in both Chrome and Safari browsers.  It's not a network problem, because I can load other external website pages quickly.  Unfortunately the problem is unpredictable in onset, there is no specific user action that provokes it.

**Comment by sives** [comment]
I'm able to provoke this behaviour by adding a few canvas cards in one organisation, switching to another organisation using the LHS dropdown and adding some canvas cards in that 2nd organisation, then switching back to add or delete some more cards in the original organisation.   When the system goes into its 8 second lag mode, new card updates show up instantly when viewing the canvas in a different browser window, indicating that saving to the database is happening quickly but retrieving the data back to the active browser window is happening slowly.

**Comment by sives** [comment]
@Dartv I'm now able to reproduce this problem about 90% of the time by carrying out the steps described above, adding and deleting a few canvas cards in one organisation, then switching to another organisation and adding and deleting a few cards, and then back again and so on.   After 5 or 6 cycles of doing this, I can usually get the system to go into slow mode.

**Comment by Dartv** [comment]
I get why this is happening. For some reason, client sometimes can't connect to websockets throwing this warning: `WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.`. Not sure why this is happening though. Maybe if we increase max reconnect retries, this warning will go away.

**Comment by sives** [comment]
I'm not sure if this is the problem, because the write updates are reaching the database immediately.  (In slow mode, new card updates show up instantly when viewing the canvas in a different browser window, indicating that saving to the database is happening quickly but retrieving the data back to the active browser window is happening slowly)

**Comment by Dartv** [comment]
@sives try testing this now

**Comment by sives** [comment]
@Dartv Your fix seems to have solved the problem - I can no longer provoke this behaviour

**Comment by sives** [comment]
@Dartv Unfortunately the problem has recurred as I continued testing, so it remains an open issue.

**Comment by sives** [comment]
@Dartv Reloading the page using the browser's refresh button always restores the system to a fast-working state

**Comment by sives** [comment]
@Dartv The problem seems to be much harder to provoke in this latest version.  Previously I was able to trigger by completing 4 or 5 cycles of adding and deleting canvas items while switching between different organisations.  Now I've only seen it happen once, and I can't easily trigger it even with 10 or more cycles or adding and deleting.

**Comment by sives** [comment]
@Dartv With the latest version, I can still trigger the problem (after many canvas add/delete/switch operations) but when I add the next canvas item the UI responds quickly again. With the previous version, once I triggered the problem, then every subsequent canvas item addition would show the same problem.  So this is definitely an improvement, although still not completely fixed.

**Comment by Dartv** [comment]
@sives should be ok now

**Comment by sives** [comment]
@Dartv This problem has come back more seriously in 0.3.61, I'm seeing consistent 5 - 10 sec lag times and sometimes as long as 15 sec when adding new cards to the Southwind Capital Management canvas, using Safari.  It happens every time I add a new card.

**Comment by sives** [comment]
@Dartv This problem seems to be related to a more general malfunctioning of the real time updates of the system.  Whilst I was observing the canvas item lag time, I went to the Work inbox and tried to complete a couple of work items.  The system took 20 seconds to complete processing of the request, compared to 2 sec in the current live system at app.pliohub.com.  Something within this new system seems to be interfering with the previously well-running Meteor real time updates.

![screenshot 2019-02-21 at 17 23 41](https://user-images.githubusercontent.com/2330529/53189099-a05e2300-35fe-11e9-8546-536d498312e3.png)

**Comment by sives** [comment]
Five minutes later I returned to the canvas, and suddenly I was able to add items with low lag time again.  However the Work inbox 20 second delay in processing was still there when I went back to the Work inbox.

**Comment by sives** [comment]
@Dartv Not sure if this helps or not with your troubleshooting. With two different browsers running on my MacBook (Safari and Chrome) I added canvas items into the Southwind canvas.  Zero lag time observed on Chrome, 10 sec lag seen with Safari, per item.  The Safari lag was consistent - it happened every time I added a canvas item, for multiple items over a 5 minute testing period. Then when I refresh the Safari browser window everything is fine and it works without lag time (for a while, until it reverts back to the lag behaviour).

**Comment by vitalii7777** [comment]
Localized and restored this bug.
Steps to reproduce:
Logout > refresh login page > login > try to create new card > we will wait long time for display new created card.

If you refresh the page again this bug will disappear. 
To reproduce it again you have to pass steps to reproduce again: 
Logout > refresh login page > login > try to create new card


Look on the video:
https://youtu.be/rUoCwM3LPsM

**Comment by Dartv** [comment]
@vitalii7777 the bug you described is fixed here https://github.com/Pliohub/Plio/pull/1949
But it could've been a whole different bug than what Steve experienced
The only thing we still can do is host redis db and make it handle subscriptions.

**Comment by sives** [comment]
@Dartv Let me know when fix has been deployed and I will retest

**Comment by vitalii7777** [comment]
When I created a lot of cards in canvas I pay attention sometimes without any reason I get long processing time for operations. But next time this will disappear. 
For example it happens when I want to delete card:
![12 54 03](https://user-images.githubusercontent.com/47181845/53485852-f95f0880-3a8f-11e9-9229-b5d81430f9ae.png)

maybe this info can help

**Comment by Dartv** [comment]
Probably because of cheap server

**Comment by Dartv** [comment]
@sives I deployed a new version of graphql server with subscriptions backed by redis hosted on amazon elasti cache. This is production ready environment and should work without any troubles (I hope)

**Comment by sives** [comment]
@Dartv Does this mean that MongoDB/ObjectRocket and Galaxy are no longer required for the next version of the system, or is this new Redis/ElastiCache backend required in addition to the existing back ends?

**Comment by Dartv** [comment]
It is required in addition to existing back ends. Redis will only handle graphql subscriptions. It is extremely fast in comparison to default implementation and will not crash the server by running out of memory like our previous implementation did.

**Comment by sives** [comment]
What is the cost impact, in terms of expected average monthly running cost?

**Comment by Dartv** [comment]
Not much. It is the same price we use for other servers (micro instance)

**Comment by Dartv** [comment]
No, it is completely separate from MongoDB

**Comment by Dartv** [comment]
@sives I found the exact reproduction of this bug:
Canvas -> go to operations view -> change organization -> go to canvas -> change organization

**Comment by sives** [comment]
@Dartv Great to hear you've identified the root cause, I will make sure I test it with this in mind

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1974

**Comment by Dartv** [comment]
@sives I was able to fix this bug finally. Now it should work flawlessly

**Comment by sives** [comment]
@Dartv that is excellent news!

**Comment by sives** [comment]
@Dartv Tested and works fine now!

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/20/19 - 03/04/19
Work session total: 6:37:18

Grand total: 6:37:18
