### ISSUE TITLE
Header panel in canvas screen disappears 

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1918]
On Safari, after adding and deleting several items from the canvas screen, the header panel disappeared.  I could only bring it back by reloading the page using the browser page refresh button.  Unfortunately I haven't been able to determine a clear sequence of events that triggers this behaviour.

![screenshot 2019-02-20 at 09 37 52](https://user-images.githubusercontent.com/2330529/53083451-dca65c00-34f6-11e9-85a2-818a4f5a0490.png)

**Comment by sives** [comment]
I have been able to reproduce this behaviour in Safari by taking the following steps:

1. Close browser window
2. Open new browser window and log in to system into the Plio organisation
3. Delete a canvas item from one section of the canvas then delete another canvas item from another section of the canvas.  Eventually the header bar will disappear.

**Comment by Dartv** [comment]
Are you on a mobile perhaps?

**Comment by sives** [comment]
No I'm using a MacBook Air

**Comment by Dartv** [comment]
I couldn't reproduce this, but there was some problem with scrolling on desktops. I already fixed it, but it is not deployed yet. Maybe this is related

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1919

**Comment by Dartv** [comment]
@sives try testing it now

**Comment by sives** [comment]
@Dartv Good news, I no longer see this problem on the latest deployed version of the system
