### ISSUE TITLE
Org settings card has no footer panel

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#192]
In the spec, every card should have a card header and a card footer (even if the footer doesn't contain any buttons)

**Comment by Praxie** [comment]
Implemented in the current release

**Comment by sives** [comment]
Looks good

**Comment by sives** [comment]
Either the card footer should be a blank white panel, or it should be an expandable dropdown showing an audit log of changes. The card footer in the Org settings card is neither, it is expandable but doesn't show any changes. If we are not going to show any changes, then we should just display a blank footer panel (minus the user name, date, and expand button).

**Comment by sives** [comment]
Now you just need to do something to the database to allow the audit history changes to show up in Plio Ltd's Org settings card

**Comment by Praxie** [comment]
@meyginix  The audit history is empty for existent organizations. Could we add  at least one entry about organization creation to organizations with empty audit log?

**Comment by meyginix** [comment]
https://github.com/Pliohub/Plio/pull/299

**Comment by Praxie** [comment]
**v0.2.52**
