### ISSUE TITLE
Cannot delete a Key Goal from the canvas 

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1923]
When I go to the Southwind Capital Management organisation, in the Key activities section of the canvas there is a Key Goal titled "fe"(KG4).  When I try and delete it, I get a UI response stating that the key goal has been deleted successfully, but it does not get deleted.

![screenshot 2019-02-20 at 14 10 08](https://user-images.githubusercontent.com/2330529/53097411-4df70680-3519-11e9-9618-720d5c7d09c5.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1925

**Comment by Praxie** [comment]
@sives I was able to delete another Key goal and noticed that "fe"(KG4) is already in the Completed & Deleted  goals section. Please check again.
"fe"(KG4)
![screen shot 2019-02-20 at 9 48 41 pm](https://user-images.githubusercontent.com/2095940/53119930-4ce5c980-3559-11e9-930a-8777aecb3dba.png)

**Comment by Dartv** [comment]
This was a bug indeed. Goal was deleted, but still presented in canvas unlike other documents. Redeploy is needed

**Comment by sives** [comment]
@Dartv I still can't delete Key goals on 0.3.61.  Using Safari, I went to the canvas for Southwind Capital Management, added a new Key goal in the Value Proposition section and a new Key goal in the Key Resources section.  When I tried to delete them, I get a confirmation message stating that the Key goal has been deleted successfully, but the Key goal remains displayed in the Section footer area.

**Comment by Praxie** [comment]
Tested, works fine.

**Comment by sives** [comment]
@Dartv Tested and works fine

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/20/19 - 02/20/19
Work session total: 0:34:48

Grand total: 0:34:48
