### ISSUE TITLE
Unlinking vs deleting objects from the canvas section footer area

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1924]
Whenever new data objects are added to canvas sections (e.g. Standards, Key goals etc) there is a corresponding requirement for the user to be able to unlink these objects from the canvas without deleting them from the database. The user may not wish to delete the data object from the database, just to unlink it from the canvas.   

This requirement is correctly implemented when a user tries to delete an object from within the relevant sub card for that data object in the canvas card (see below) but it is not implemented when a user tries to delete an object directly from the canvas section footer area.  In this case, the data object is deleted completely from the database with no opportunity to unlink. Users need to be given a choice of deleting or unlinking the data object in both deletion scenarios.

(A user can cause a lot of damage to the system by accidentally deleting key data documents)

Also the user dialog text needs to be changed to 'Do you wish to unlink the Standard "8.3 Management review" from the canvas section, or delete it completely from the system?'

![screenshot 2019-02-20 at 14 14 56](https://user-images.githubusercontent.com/2330529/53098143-f22d7d00-351a-11e9-9eab-16e0be726a02.png)

**Comment by Praxie** [comment]
@sives it won't be a consistent behaviour and we can't do this because we re-use the generic document card. We display this alert with actions only for subcard items.

As a solution for this problem, we could do something like this, but it'll be considered as an enhancement:
![image](https://user-images.githubusercontent.com/2095940/53119457-3be88880-3558-11e9-8975-ba2aedbdebdc.png)

**Comment by sives** [comment]
@Praxie We do absolutely need a solution for this problem.  Your proposed solution is a good one. (note: there needs to be a white circle around the X symbol, against the grey background).  I'm fine with this being an enhancement.

**Comment by Dartv** [comment]
How do you expect this to work? It's not that easy to implement. Remember, one item can be linked to multiple canvas items in this section. We will need to create new mutation for every canvas section just for this one feature. This will take a lot of time and increase maintenance cost.

**Comment by sives** [comment]
Think about this from the user perspective.  As an existing Plio user I've added several Key goals and Standards to the system previously.  Now I start using the Canvas.  I add a Key goal to one section of the canvas and a Standard to another section.  Then I change my mind and want to move this Standard  to a different section. The only way I can do this is to delete the Standard, go back to the Standards screen and add it back all over again, then go to the Canvas screen and add it to the new canvas section.  All of which is incredibly time-consuming.  Users will rightly see this as a complete design fail.

**Comment by Dartv** [comment]
As I said, we can do this, but it will take some time. Lesser than I initially thought because we redesigned how relations work for canvas items (this will help a lot)

**Comment by Dartv** [comment]
![](https://i.gyazo.com/5755e2f73d47d171e7553acedf3b5388.png)
![](https://i.gyazo.com/45ad938ee34e3b2a82320a634b7ab6dc.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1948

**Comment by sives** [comment]
@Dartv Tested and works fine (subject to small cosmetic UI issue raised in #1982)

**Comment by sives** [comment]
@Dartv Delete buttons now look great

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/25/19 - 02/26/19
Work session total: 6:01:01

Grand total: 6:01:01
