### ISSUE TITLE
The help icon is replaced with two dots in the Cost line card

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1927]
![image](https://user-images.githubusercontent.com/2095940/53117693-2d986d80-3554-11e9-996b-a6e1215c9674.png)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1928

**Comment by sives** [comment]
@Serhiy91  This is also not formatted correctly in the master administrator help editor mode

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/53190909-3ef47f00-3613-11e9-9780-46a3fd79cc3e.png)
