### ISSUE TITLE
Visiting Plio app from external site

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#193]
When you visit the Plio app from an external URL and then try to go back to that external web page, using the browser back button, you get stuck in a Plio loop

**Comment by Praxie** [comment]
@sives could you share a link to reproduce this bug?

**Comment by sives** [comment]
Hmm.  Seems to work fine when I do it (James reported the issue).  Will investigate further.   It may be that he was referring to what happens when you go into a Plio document e.g.  a standards document, click edit and then click the browser button.  This is when you get stuck.

**Comment by Praxie** [comment]
@sives yes you're right. 
https://app.pliohub.com/100/standards/ will redirect the user to the first document in the list (https://app.pliohub.com/100/standards/Tw4GxvZk7zWTJerGT)
Then if you'll hit the back arrow, you'll be redirected to https://app.pliohub.com/100/standards/ that will redirect you back to the first document.

**Comment by Praxie** [comment]
**v0.2.41** feature

**Comment by sives** [comment]
Spoke to James to get better understanding of his issue.  In a browser tab on Chrome, he goes from an external web site to the Plio login screen then logs in to the Plio home screen, then tries to go back to the login screen and can't.

**Comment by Praxie** [comment]
@sives does it makes sense to show the login screen for the logged in user? I think no.
There were issues with going back from the document page to the home screen by clicking on the arrow button, but it's fixed now. (It'll be in the future release)

**Comment by sives** [comment]
All working nicely now.
