### ISSUE TITLE
Fix the padding issue in the Edit canvas item card

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1932]
![image](https://user-images.githubusercontent.com/2095940/53190791-018ff180-3613-11e9-81d0-0aa5fdc32107.png)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1933

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/53587898-3ca29f80-3b94-11e9-9e04-087ca9c00f3c.png)
![image](https://user-images.githubusercontent.com/2095940/53587909-42988080-3b94-11e9-8e42-ddeb10614592.png)
![image](https://user-images.githubusercontent.com/2095940/53587915-475d3480-3b94-11e9-9a2e-616b834370cb.png)
