### ISSUE TITLE
Updated help text

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1938]
Most of the updates listed below are in small details. We didn’t have a consistent treatment of capitalisation of words with the old help text, so I’ve set a rule where higher-level data entities in Plio (Standards, Risks, Nonconformities, Potential Gains - those that have their own Plio cards in the UI) are capitalised.  Lower level data entities (e.g. corrective actions) are not capitalised.

STANDARDS

New card header help:
A Standard is a document that explains the agreed way or best way to carry out a key activity (e.g a process, task or policy) in your organization. To add a Standard into Plio, just fill in the card details, and link to a source file.  This can be either a Word document, a URL link to a web document or a video.

New unique number help:
Uniquely identify your Standard with a number between 1 and 10000.

RISKS

New card header help:
Risk is the effect of uncertainty on an organization's objectives. To add a Risk record in Plio, give it a name and fill in the top section below. Next, carry out an initial risk analysis by scoring the Risk, evaluating it and creating a treatment plan. Then you can go ahead and create corrective or preventative actions to reduce the potential impact or the probability of occurence of this Risk.

New Standard field help:
Optionally, you can link this Risk to one or more of your Standards.

New Risk evaluation subcard, treatment decision field help:
Indicate how you plan to deal with this Risk; Tolerate - you are just going to live with the risk; Treat - you are going to act to reduce the risk; Transfer - you are going to pass the risk on to a 3rd party; Terminate - you are going to stop the business activity which has created this Risk.

NONCONFORMITIES

New card header help:
A Nonconformity (sometimes called an exception) is a deviation from a Standard.  It can also be a deviation from an unstated expectation of how things should be done, or a breach of a legal regulation. To add a Nonconformity into Plio, give it a name and fill in the top section below. Once you've carried out an analysis of the reasons for the Nonconformity, go ahead and enter corrective or preventative actions to fix the problem or prevent it reoccurring in the future.

New financial impact field help:
Estimate the approximate cost of each occurrence of this Nonconformity.

POTENTIAL GAINS

New card header help:
A Potential Gain is essentially the opposite of a Nonconformity. In Plio it is defined as an opportunity for an improvement in a task or process (contrast this with a Nonconformity which is a deviation from a documented Standard or from a specification  - in other words, an identified problem in a process, task or policy).

New financial impact field help:
Estimate the approximate financial benefit that will be achieved through implementing this Potential Gain.

ORGANIZATION SETTINGS

New card header help:
Organization settings is where you can customize the behaviour of the Plio system. For example, you can customize lists (e.g. Departments, Standards types, Risk types) and create a section structure for your Standards documents. You can also configure whether you want to use simple (3-step) or full (6-step) workflows for dealing with different levels of Nonconformities and Risks.

New home screen subcard help:
You can change the default screen view that first appears when you log in to Plio, between the Operations view and the Canvas view.

In the Operations view screen, Plio lets you set different default values for numbers of items to be displayed. Whenever these default values are exceeded, Plio will display a "More” button next to each item list. Plio also lets you customize the labels for each of the main icons on your home screen.  In the "Operations view - titles” section, just select an icon label you wish to change, then click on the selection button and select an alternative name or create an entirely new name.

New Standards types subcard help:
Create a list of Standards types for your organization.

New Standards sections subcard help:
Create a customised section structure to make it easier for your users to browse and navigate through your collection of Standards documents.

New Workflow steps subcard help:
Indicate whether you want Plio to use simple (3-step) or full (6-step) workflows for your Nonconformity and Risk-handling processes. To save time and effort, you can set simpler workflows for your less critical Nonconformities and Risks. Plio always uses a 3-step workflow process for managing Potential Gains. Workflows can be further simplified by ticking the “Simplified completion of own actions” box. When this box is ticked, if an owner of a Nonconformity (or Potential Gain) has created an action for themselves and then clicked the complete button for that action, it won’t be returned to that same person to verify completion. If you do need specific recording of each and every verification step in Plio, then untick this box.

New Workflow reminders subcard help:
Set appropriate reminder times for actions that become due within your Nonconformity and Risk-handling processes. If you wish, you can set shorter reminder times for less critical Nonconformities and Risks.

New Nonconformity guidelines subcard help:
Help users to indicate the magnitude of this Nonconformity, by giving them some clear guidelines relating to the estimated cost impact or impact on customers.

New Gain guidelines subcard help:
Help users to indicate the magnitude of this Potential Gain, by giving them some clear guidelines relating to the estimated benefits to be gained.

New Risk types subcard help:
Create a list of Risk types for your organization.

New Risk guidelines subcard help:
Help users to categorize the Risk magnitude more accurately by giving them some clear guidelines on what these terms mean in the context of your organization (e.g. quantify the ranges of potential cost impact or impact on customers)

New Risk scoring guidelines subcard help:
Help users to score this Risk more accurately by giving them a brief summary on what the various scoring terms (e.g. minor impact, moderate impact, significant impact) mean in the context of your organization (e.g. quantify the ranges of potential cost impact or impact on customers).

**Comment by Serhiy91** [comment]
@sives There is one more help text in "Score type" field of "Risk scoring" subcard of risk:
"Indicate whether you scoring the inherent risk (which is the level of risk that existed before you treated the risk) or the residual risk (the reduced level of risk that you are expecting after you treat the risk)."
Should I change it to:
"Indicate whether you scoring the inherent Risk (which is the level of Risk that existed before you treated the Risk) or the residual Risk (the reduced level of Risk that you are expecting after you treat the Risk)." ?

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1946

**Comment by Serhiy91** [comment]
via Hubstaff
User: Serhiy Zinchuk

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/26/19 - 02/26/19
Work session total: 1:29:52

Grand total: 1:29:52
