### ISSUE TITLE
Non-conformity error message: owner is required

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#194]
When you create a new Non-conformity, save the initial top section, then go to Lessons learned and add one, when you click on the Save button in the Lessons learned subcard you get the error message: "Owner is required".  But there is no visible owner field to set in any of the fields above it. (reported by Ian Scaife at CAM)

**Comment by Praxie** [comment]
**v0.2.41** feature

**Comment by sives** [comment]
The error message problem is fixed.  However, when I start entering data in the Lessons learned subcard, it is defaulting to James Ives in the Created by field, and not to the current logged-in user.

**Comment by Praxie** [comment]
@sives it's fixed in the current release
