### ISSUE TITLE
Change error message

### ISSUE THREAD

**Issue by vitalii7777** [Pliohub/Plio#1940]
Go to canvas dashboard > try to create any card > input space into the title field > save
![3 57 42](https://user-images.githubusercontent.com/47181845/53342289-4b7c1e80-3916-11e9-89ea-35b4e652544f.png)

Maybe make sense to change error message.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1947

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/53587969-6f4c9800-3b94-11e9-9502-ba554d5e43e9.png)
