### ISSUE TITLE
Title (short text line 40 characters maximum) 

### ISSUE THREAD

**Issue by vitalii7777** [Pliohub/Plio#1942]
Go to canvas > create any new card
We can input more than 40 chars into the title field.
But according to requirements, 40 chars is maximum for title field.
![5 49 48](https://user-images.githubusercontent.com/47181845/53349496-e2040c00-3925-11e9-833b-9ce871f85e88.png)

**Comment by Dartv** [comment]
Requirements were changed to allow for up to 80 max characters
