### ISSUE TITLE
Wrong total count of card elements

### ISSUE THREAD

**Issue by vitalii7777** [Pliohub/Plio#1943]
Go to Canvas main dashboard > create or edit any card.

Total elements of the card are wrong. Every time did not include the element "Notify changes".
For example on the video which I attached to this issue: total elements are 5, but in fact must be 7 - watch it:

https://youtu.be/JmkEpgC6aKA

**Comment by Dartv** [comment]
This number is the number of entities in subcards. Notify changes doesn't have any entities, so it should not be counted
