### ISSUE TITLE
UI bug (organizations settings)

### ISSUE THREAD

**Issue by vitalii7777** [Pliohub/Plio#1950]
Go to Organizations settings > Review frequency > Reviewer > UI bug:
![6 56 54](https://user-images.githubusercontent.com/47181845/53431049-6fb02c00-39f8-11e9-9340-489312b16fe8.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1954

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/53588033-9c994600-3b94-11e9-8056-fd58095257c3.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/27/19 - 02/27/19
Work session total: 0:47:50

Grand total: 0:47:50
