### ISSUE TITLE
Notifications (few issues or features)

### ISSUE THREAD

**Issue by vitalii7777** [Pliohub/Plio#1951]
In this task, I write a few questions about notifications. I think we have to discuss it and decide what is the features and what is the bugs. 

* **1**
If I created a new card and selected my email for notification then made some changes - I do not receive any notification to email. But if I select another user he will receive notification. This is the correct logic or not? 

* **2**
Notification link without staging  - look on the picture all info there:
![7 15 51](https://user-images.githubusercontent.com/47181845/53432633-8e63f200-39fb-11e9-9be6-6833d9f4d54c.png)

**Comment by Dartv** [comment]
1. Ofc. Why would you want to receive notifications for changes you made yourself?
2. Should be fixed after new deployment
