### ISSUE TITLE
Lessons learned input field error message

### ISSUE THREAD

**Issue by vitalii7777** [Pliohub/Plio#1952]
Lessons learned input field - can receipt very lot of chars. But when we want to copy-paste very long text (more 60000 chars) we can catch this error:
![7 36 03](https://user-images.githubusercontent.com/47181845/53433948-34186080-39fe-11e9-9a8c-30d68e58ec8e.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1955

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/53588124-e7b35900-3b94-11e9-8454-38d21a11a135.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/27/19 - 02/27/19
Work session total: 0:51:12

Grand total: 0:51:12
