### ISSUE TITLE
UI bug with diagram on Mobile

### ISSUE THREAD

**Issue by vitalii7777** [Pliohub/Plio#1953]
The issue is dependent on screen resolution:

Go to Key partner
**Create a lot of cards** and set up "Critically" and "Level of spend" with different values
Click close and check diagram.
Look at the picture:
![10 41 38](https://user-images.githubusercontent.com/47181845/53477210-df67fa80-3a7c-11e9-9807-403031a2f249.png)
![bs_realdroid_mobile_samsung galaxy s9 plus-8 0-1440x2960](https://user-images.githubusercontent.com/47181845/53477422-54d3cb00-3a7d-11e9-9fc4-78d4253b70af.jpg)

The same with Customer segments. When we set up a lot of cards with % of market size:
![11 07 24](https://user-images.githubusercontent.com/47181845/53478611-eb08f080-3a7f-11e9-8a4a-b265054c3b38.png)
Revenue streams graphs:
![screenshot_20190227-114006](https://user-images.githubusercontent.com/47181845/53480959-e72b9d00-3a84-11e9-97cd-3c13cc107e4d.png)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1956

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1956

**Comment by Serhiy91** [comment]
https://drive.google.com/file/d/1WwCktJoRvay_Gn9uSY4aoROUMRRCxD_Y/view

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1958
