### ISSUE TITLE
Guidance panel stretches modal

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1961]
![](https://i.gyazo.com/7492fe4ab76ac79f03bdeab9dca29930.gif)

**Comment by Praxie** [comment]
@Dartv I can't reproduce this
![image](https://user-images.githubusercontent.com/2095940/53588892-a7ed7100-3b96-11e9-8a2e-f48c330f6ba2.png)

**Comment by Serhiy91** [comment]
I also can't reproduce this
