### ISSUE TITLE
Canvas section footer issues

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1962]
Please add a right padding so that text would not overlap the icon:
![image](https://user-images.githubusercontent.com/2095940/53587605-817a0680-3b93-11e9-84e4-17b7aa51417e.png)

Make corners round, add margin-top: 1px to the remove icon:
![image](https://user-images.githubusercontent.com/2095940/53587648-95be0380-3b93-11e9-97af-9a4e37e63800.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1965

**Comment by sives** [comment]
@Dartv Delete button still has small cosmetic issue,see #1982

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 03/01/19 - 03/01/19
Work session total: 1:31:03

Grand total: 1:31:03
