### ISSUE TITLE
It's not possible to set user superpowers

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1963]
1. Invite mike@apiko.com.
2. Try to edit his superpowers.
https://gyazo.com/20669b7ed3fc042bad2c85e28ed760ce

**Comment by Dartv** [comment]
It shouldn't be possible since the user hasn't even created an account

**Comment by Praxie** [comment]
@Dartv the account is already created. So this happens when the existing Plio user has been invited.

**Comment by Praxie** [comment]
It works well now, it looks like it was some server issue, I can't reproduce it know. I'll reopen the issue if it'll appear again.
