### ISSUE TITLE
Change colors on the Home screen according to the prototype

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1964]
In the prototype we have white background and grey tiles.

![screen shot 2019-03-01 at 12 37 36 pm](https://user-images.githubusercontent.com/2095940/53632935-d31ba300-3c1e-11e9-966a-8f56b6e1d1bd.png)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1968

**Comment by sives** [comment]
@Serhiy91 Tested and looks fine now
