### ISSUE TITLE
Updated notification email text

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1966]
Before we go live with the new system, we need to update the text at the bottom of notification emails, see below.
Many thanks,
Steve

Current text:
At Plio we believe that continuous improvement is vital to the future of your organization. You need a better software tool than a spreadsheet to keep on top of quality problems, compliance issues and the multitude of other potential process improvements that could save you time and money.

Spreadsheets are time-consuming to maintain and don’t give you the proper structure or audit trail that you need in a management system. One day, it’s likely that you will need to demonstrate the integrity of your management system either to a new boss or to a regulatory body, and the Plio app helps you do this.

Software systems for operation management, quality management and compliance management and have been around for several years, and are routinely used by larger organizations. However the price tag for these systems – and the time needed to implement them – have put them out of range for most small firms.

At Plio, we believe that any business should be able to afford this kind of management system, and it ought to be easy enough to understand for everyone.

_______________________________________________________________________________________________________________________-

New text
At Plio we believe that the adoption of structured management systems makes a big difference to the performance of your organization. The ad hoc use of spreadsheets is not  sufficient to keep you on top of quality problems, compliance issues and the multitude of other process improvements that could save you time and money.

Spreadsheets are time-consuming to maintain and don’t give you the rigorous structure or audit trail that you need in a management system. One day, it’s likely that you will need to demonstrate the integrity of your management system either to a new boss or to a regulatory body, and the Plio app helps you do this.

Software systems for operations management, quality management and compliance management have been around for several years and are routinely used by larger organizations. However the price tag for these systems – and the time needed to implement them – have put them out of range for many smaller firms.

At Plio, we believe that any business should be able to afford this kind of management system, and it ought to be easy enough to understand for everyone to use.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1969
