### ISSUE TITLE
Rewrite dashboard layout in React

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1967]

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1972

**Comment by sives** [comment]
@Dartv Looks good

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 03/01/19 - 03/04/19
Work session total: 4:31:30

Grand total: 4:31:30
