### ISSUE TITLE
List of Help sections needs updating

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1971]
When creating new items for the Help Center, I am currently able to select which section that help document is allocated to, from a list of 8 sections (How to get help; Getting started; Creating your Standards manual; Managing risks; Managing non-conformities; Managing workflows; User management' FAQs).

This list needs to be updated, in line with the new functionality, to 12 sections, in the following order:

How to get help
Getting started
Creating your standards manual
Creating your business model canvas
Managing nonconformities & gains
Managing risks
Managing training
Managing key goals
Managing workflows
User management
Customizing Plio
FAQs

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1973

**Comment by sives** [comment]
@Serhiy91 Tested and looks fine.

**Comment by Serhiy91** [comment]
via Hubstaff
User: Serhiy Zinchuk

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 03/01/19 - 03/01/19
Work session total: 1:29:28

Grand total: 1:29:28

**Comment by sives** [comment]
My apologies, this needs to be changed to the following updated list:
(please include the numbers in front of the list titles):

1. How to get help
2. Getting started
3. Managing standards
4. Managing risks
5. Managing nonconformities and gains
6. Managing workflows
7. Managing key goals
8. User management
9. Customizing Plio
FAQs

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2008

**Comment by sives** [comment]
@Praxie Not deployed in the live system yet

**Comment by sives** [comment]
@Praxie I've just updated and renumbered this list, had missed out one important section by mistake

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2012

**Comment by sives** [comment]
Looks good.  We'll remove the old sections once I've recategorised all the existing help documents

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/05/19 - 04/15/19
Work session total: 1:35:54

Grand total: 3:05:22

**Comment by sives** [comment]
With the new release I'd like to update item 9 in the help topics list.
Please change it from "Configuring to fit your business" to "Configuring to fit your organization"

(reason for doing this - we have created specific configurations for non-profit organizations in healthcare and education which do not regard themselves as businesses"

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2093

**Comment by michaelrokosh** [comment]
![image](https://user-images.githubusercontent.com/2095940/62427530-11048200-b6fd-11e9-8d1b-f613bbeccd5d.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 07/26/19 - 07/26/19
Work session total: 0:38:37

Grand total: 3:43:59
