### ISSUE TITLE
Review dates in email notifications are incorrect

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1975]
Notifications of reviews are being sent out with the incorrect year date.  See example of a review reminder which I received today (Tue 5th Mar 2019) which stated that standards documents are scheduled for review on March 02 2018 and should have stated March 02 2019.

![plio standards review notification bug](https://user-images.githubusercontent.com/2330529/53796453-17af8300-3f2c-11e9-8345-822d89317049.png)

**Comment by Praxie** [comment]
@sives wouldn't it be better to remove the year at all?
The review process is recurring so it makes sense probably to have only date with no year specified.

**Comment by Praxie** [comment]
Or we can replace year with the current year.

**Comment by unplugged** [comment]
@praxie I agree, it’s better to remove the year from the notification text, because the review process is recurring

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1977

**Comment by sives** [comment]
@Dartv I have no way to test this, so I'll assume that this issue is now resolved (can always be fixed after go-live)

**Comment by sives** [comment]
@Dartv I'm receiving occasional duplicate email notifications of Standards reviews, see screen clippings.  In one copy the date is inaccurate (one year error) in the other copy the year is not displayed (correct behaviour).  I'm not sure whether this duplication is a bug or just because you are testing the fix to the year problem.

![Screenshot 2019-03-15 at 09 37 42](https://user-images.githubusercontent.com/2330529/54422473-821faa80-4706-11e9-8fb5-6994b46d8da6.png)

![Screenshot 2019-03-15 at 09 38 00](https://user-images.githubusercontent.com/2330529/54422484-86e45e80-4706-11e9-82f5-470eda5da8a8.png)

![Screenshot 2019-03-15 at 09 38 12](https://user-images.githubusercontent.com/2330529/54422497-8ba91280-4706-11e9-95cd-b535321081bf.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 03/05/19 - 03/05/19
Work session total: 0:12:23

Grand total: 0:12:23
