### ISSUE TITLE
Completion of items in Work inbox - UI updating is slow

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1979]
@Dartv When I complete an outstanding work item in the Work inbox screen, it takes about 8 sec delay to update the left hand side list view and remove the item from the list of outstanding work items.  This is a consistent delay across different work items.  When I do the same operation on the app.pliohub.com live system it only takes about 3 sec delay to update the left hand side list view.

**Comment by Dartv** [comment]
This is because we don't have mongo oplog set up for staging app. It will work fine on the live app.

**Comment by sives** [comment]
OK I understand
