### ISSUE TITLE
Help icon in Canvas chart modals doesn't display any help

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1980]
When a user clicks on this help icon, there is no help displayed - just a blank space with a Close button.  I would expect the same help text to be displayed when clicking on this icon as is displayed when a user clicks on help in the main Canvas item card in the same canvas section.  Alternatively, we should delete help icons from header bars in Canvas chart modals (this is the preferred option - they don't serve a very useful purpose here).

![screenshot 2019-03-06 at 15 09 14](https://user-images.githubusercontent.com/2330529/53891727-e2d22780-4022-11e9-858c-a6eeb8076f0a.png)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1987

**Comment by sives** [comment]
@Serhiy91 Tested and help icon no longer displayed, so issue is resolved.
