### ISSUE TITLE
White space in canvas chart modals

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1981]
There is not quite enough white space surrounding the canvas charts to display the surrounding legend text properly. Compared to Jack's prototype the legend text is much too close to the adjacent elements and to the edge of the modal.  We should shrink the canvas charts by 10-15% to create more surrounding white space.

**Comment by Dartv** [comment]
Prototype chart modal is not responsive, but ours is. It all makes sense when you open the modal on mobile ![](https://i.gyazo.com/ce4c90bba94fbbcfe131a04dd274b932.png)
We can, however, increase padding between legend items

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1991

**Comment by sives** [comment]
@Dartv Looks fine now, so issue is resolved.

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 03/08/19 - 03/15/19
Work session total: 1:44:49

Grand total: 1:44:49
