### ISSUE TITLE
Positioning of delete buttons in canvas section footer

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1982]
The buttons need to be moved approx 2mm to the right hand side, both in the canvas section footers and in the pop-up modals that get displayed when you click on a canvas footer button.  The general rule in Plio is that the white space to the left and right hand side of these icons should be equal in dimensions to the white space to the top and bottom of the icon.

**Comment by Dartv** [comment]
Sorry, but your description is too vague. It can be interpreted in many ways.

**Comment by sives** [comment]
@Dartv Yes, you are right - it's surprisingly hard to explain this cosmetic UI issue in clear words.  Here's a diagram which may be helpful.


![screenshot 2019-03-07 at 13 50 45](https://user-images.githubusercontent.com/2330529/53961358-4bcba500-40e0-11e9-9922-d44a49f43580.png)

**Comment by Dartv** [comment]
@sives It's not random, I just used prototype's styles for these buttons

**Comment by sives** [comment]
@Dartv OK now I see why you did it this way.  I just checked the UI prototype and found that it is not always consistent in its styling of delete buttons.  Here is an example of the correct design and positioning of delete buttons, taken from the top section of the Nonconformity card.

![screenshot 2019-03-07 at 14 02 42](https://user-images.githubusercontent.com/2330529/53962077-1758e880-40e2-11e9-85e8-c72f91c56400.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1989

**Comment by Dartv** [comment]
![](https://i.gyazo.com/a08784bfa8fa73f25585a2eabd4b95b2.png)
![](https://i.gyazo.com/38a380e55b008a0d3b83cf18631fbdd3.png)

**Comment by sives** [comment]
@Dartv Looks good

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 03/07/19 - 03/07/19
Work session total: 1:04:50

Grand total: 1:04:50
