### ISSUE TITLE
Adding a key goal to the Canvas screen doesn't add it to the Operations screen

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1983]
@Dartv When I'm in the Operations screen and I add a key goal, I immediately see the Key goal appear on that screen.  However, when I'm in the Canvas screen and I add a key goal and then switch to the Operations screen I don't see that key goal added to the Operations screen.  As a user, I have to reload the page using the browser reload button to be able to see the new key goal.  

The current behaviour gives users the impression that there  is a bug in Plio and that the action of adding a key goal has failed for some unknown reason. (I understand that in reality it has been added to the database, but just not updated on screen yet). 

The expected behaviour is that when I add a key goal, I should see it update immediately on the Operations screen no matter whether I add it from the Canvas screen or from the Operations screen.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1988

**Comment by sives** [comment]
@Dartv Key goals are not listed in the correct order.  The display ordering rule is shown below.   Key goals are being displayed by level of criticality (correct) but are not being displayed alphabetically if they have the same level of criticality (note: let's only fix this if it is easy - it is not a critical bug).

Key goals should be ordered i) by level of criticality, with critical goals at top, then major goals then minor goals ii) alphabetically, so that if there are multiple key goals with the same level of criticality they are ordered a to z by key goal title.

**Comment by Dartv** [comment]
@sives Key goals are sorted by criticality first and then by end date. This has been a requirement before.

**Comment by sives** [comment]
@Dartv OK, I mis-remembered the specification. I will mark this issue as resolved.

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 03/07/19 - 03/07/19
Work session total: 1:13:18

Grand total: 1:13:18
