### ISSUE TITLE
When printing a canvas, unwanted data elements appear on the first page

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1984]
When printing a canvas, 3 unwanted data items are being displayed on page 1:
- the word "Plio" at the top of the page, in the centre
- the current date, at the LHS of the top of the page
- the current URL, at the LHS of the bottom of the page

These items are not present in the Print Canvas layout Jun 2018 requirements specification document and should be removed.  

The page numbers at the RHS of the bottom of page 1 and at the bottom of all the other pages should NOT be removed because they are included in the specification document - but the font needs to be changed to match the primary font used in the rest of the page.

![canvas printing errors](https://user-images.githubusercontent.com/2330529/53893060-5aa15180-4025-11e9-8399-83a86a32c9a4.png)

**Comment by Praxie** [comment]
@Dartv https://stackoverflow.com/questions/2573603/removing-page-title-and-date-when-printing-web-page-with-css

**Comment by Dartv** [comment]
@Praxie this solution also removes page number

**Comment by Dartv** [comment]
We have to either remove page number along with everything else, or keep URL

**Comment by sives** [comment]
@Dartv OK, now I understand the technical constraints.  

I've modified the design of the report layout slightly and uploaded this to Basecamp files (see "Plio canvas print layout Jun 2018 v03").   

Summary of key points:
- Keep the page number, URL, title and date elements, but if possible make sure they use the same text font used in our report pages
- Change the title from "Plio" to "Plio canvas report"
- Delete the words "Business model canvas" from the 2nd line on the first page of the report
- Reposition the "cc Canvas by Strategyzer" copyright message to the RHS of the first page of the report


![screenshot 2019-03-07 at 16 19 50](https://user-images.githubusercontent.com/2330529/53971485-e6ce7a00-40f4-11e9-9a38-51b12d1e6320.png)

**Comment by Dartv** [comment]
![](https://i.gyazo.com/bf922c32fc852e2f8e8777e6d978b03a.png)

**Comment by Dartv** [comment]
Unfortunately, changing title font is not possible. User can always disable these elements by turning off this option in print dialog:
![](https://i.gyazo.com/95df3f1b7109e9c31cd018ed9bf21db4.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1990

**Comment by sives** [comment]
@Dartv Unwanted data elements are now removed, so this issue is now resolved

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 03/07/19 - 03/07/19
Work session total: 1:00:29

Grand total: 1:00:29
