### ISSUE TITLE
Top canvas sections not rendering properly when printing

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1986]
The top 7 sections of the canvas are aligned correctly with the bottom 2 sections in the Print view when viewed in the browser.  However, when the user is actually printing from this print view (either to a printer or to a PDF file) the top 7 sections are skewed to the right hand side by about 1 cm.  As well as looking untidy, this also obscures the right hand edge of the text labels in the Customer segments section, and needs to be fixed. The bottom 2 sections do not suffer from this problem and are printing correctly.

![canvas printing errors](https://user-images.githubusercontent.com/2330529/53893616-70634680-4026-11e9-9acc-f84f0066892b.png)

**Comment by Praxie** [comment]
Can be reproduced by resizing the browser window.
![image](https://user-images.githubusercontent.com/2095940/53895110-fa68da80-4039-11e9-9736-f4f972203f42.png)

**Comment by sives** [comment]
@Praxie I checked Jack's UI prototype (at http://ui2.isometrica.io/ui1-3/canvas.html) and it doesn't do this, so it seems to be a bug in the implementation

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1992

**Comment by sives** [comment]
@Dartv This issue is not resolved, in some respects it behaves worse than before.  Before, the page breaks were correct, the main problem was in rendering the canvas section outlines correctly as the browser window is resized.   Canvas section outlines are still not rendering the correct way (as in Jack's prototype) and there is a new problem with incorrect page breaks.  

I have attached PDF files to show extent of the problem (Plio canvas report 1 is a PDF created from the previous Plio release, Plio canvas report 2 is a PDF created with the current Plio release).

Jack tells me that he had significant issues in getting canvas section resizing to work correctly in his prototype, which he was eventually able to overcome.  I suggest we go back to the previous Plio implementation on staging, where page breaks were working correctly as in Plio canvas report 1, and ask Jack to look at the markup and fix it so that canvas section resizing works in the same way as his prototype.

[Plio canvas report 1.pdf](https://github.com/Pliohub/Plio/files/2960847/Plio.canvas.report.1.pdf)

[Plio canvas report 2.pdf](https://github.com/Pliohub/Plio/files/2960848/Plio.canvas.report.2.pdf)

**Comment by Dartv** [comment]
The item's title was cut before to save space. 
Btw, when printing in prototype, the page also breaks:
![](https://i.gyazo.com/2f62f55a7336c08e99b5e85dd2529681.png)

**Comment by sives** [comment]
@Dartv Yes, it's good to remove the title to save space, this has previously been agreed in #1984.

**Comment by Dartv** [comment]
@sives I was talking about this:
![](https://i.gyazo.com/4d2078a9ba116d7ca6dd2168a8a89216.png)

**Comment by sives** [comment]
@Dartv Agreed, the prototype does not print correctly either.  However, the previous working software implementation on Staging did print correctly with respect to pagination when the canvas was loaded with a typical number of items.  

I've previously spent time feeding back on this issue with Sergei to ensure we had a canvas that could print out correctly on a single page when loaded with a typical number of items.  It's important to the user that we meet this requirement.

**Comment by Dartv** [comment]
Btw, it prints nicely for me in the Southwind organization
![](https://i.gyazo.com/2d8c69a60dcce51109a460ff1eec56e5.png)

**Comment by sives** [comment]
@Dartv Yes, I can get it to print on one page in Chrome but not in Safari

**Comment by sives** [comment]
@Serhiy91  Strange that your canvas displays date, title and page number info when printing.  When I print, it doesn't display these items.

**Comment by Dartv** [comment]
Oh, safari...

**Comment by sives** [comment]
@Dartv See also related issue #1994, canvas sections do not display properly on a laptop-sized screen  when using either Chrome or Safari

**Comment by sives** [comment]
@Serhiy91 Going back to your point about cutting the title to save space, I think that cutting the title will not solve this particular problem.  In Southwind there are only 3 items in the Key partners section, so there is plenty of space for one item to have a longer title.

**Comment by Dartv** [comment]
@sives I fixed the problem with the first page break. However, the second page also breaks if "Print headers and footers" option is enabled in print dialog. Should we make it not break even if this option is enabled?

**Comment by sives** [comment]
@Serhiy91 Yes, similar to the previous version, it should not break in either scenario, with the option enabled or disabled.  The PDF below is from the previous version and it shows no page break even with the option enabled.

[Plio canvas report 1.pdf](https://github.com/Pliohub/Plio/files/2961389/Plio.canvas.report.1.pdf)

**Comment by sives** [comment]
@Serhiy91 It might be good to solve related issue #1994 first, which is a more fundamental problem, and then fix the printing problem.  Otherwise any fixes we make to solve the printing problem may have to be reworked after solving the laptop screen display problem.

**Comment by sives** [comment]
@Serhiy91 I think there may also be a minor problem with the allowable column width in the Key partners section being too wide compared to the other sections, resulting in this specific canvas section taking up a little bit too much of the total available page width.  The "Prof John Callaghan - London Business School" item should be wrapping onto a new line a bit earlier than it currently does.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1995

**Comment by sives** [comment]
@Dartv Tested on both Chrome and Safari and it's working well.

**Comment by sives** [comment]
@Dartv Tested on both Chrome and Safari and it's working well.

**Comment by sives** [comment]
@Dartv Tested just now on Chrome and Safari and Safari is no longer printing the canvas on 1 page (still fine with Chrome).

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/54426313-26fab180-4720-11e9-8fdc-d2b9e9cc8581.png)
@Dartv please move the linked items left and align them with original items.
Please also increase the max-width of items to 400px.

**Comment by Praxie** [comment]
The alignment should be updated on the Print screen and the Canvas screen in the app.

**Comment by Dartv** [comment]
Setting max-width to more than it is now will bring https://github.com/Pliohub/Plio/issues/1994 back

**Comment by sives** [comment]
@Dartv  It may be possible to increase max width if at the same time we simultaneously decrease the width of the white border between the canvas items and the right hand edge of each canvas box

**Comment by sives** [comment]
@Dartv Let's make sure we are both running up to date versions of Safari on our computers. This will save time for both of us, to avoid unnecessary iterations

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1999

**Comment by sives** [comment]
@Dartv Latest version almost working on Safari. Southwind Canvas is now printing on a single page (which is good) but the right hand edge of the canvas outline is missing.  This should be able to fixed by removing a few pixels from the left hand white border within each canvas section (i.e.the white border separating the left hand vertical edge of the canvas section from the left hand vertical list of item icons).

**Comment by Dartv** [comment]
I'm running the latest macOS mojave version 10.14 and I can't reproduce this.
[Plio canvas report.pdf](https://github.com/Pliohub/Plio/files/2971790/Plio.canvas.report.pdf)

**Comment by Dartv** [comment]
We can also add a message, like "Please, use chrome for the best printing experience"

**Comment by sives** [comment]
@Dartv Sorry, that's a non-starter as a solution.  Business users typically choose their favourite browser and stick with it.  Many Mac business users use Safari as their default browser (as I do) because it has better integration with the rest of the OS.

**Comment by sives** [comment]
@Dartv With my Safari browser everything prints OK if I set the print scale option to 99% instead of 100%.  

So I think this bug is an edge case (excuse the pun) where the slight differences in calculating vector transformations for different sized screens on different computers lead to slightly divergent results.  This could explain why you can't see the effect on your Mac, which has a different screen size to mine, and why I don't see it when I change the print scaling by a tiny amount, just by 1%.

I believe that a viable solution is to make the overall canvas very slightly smaller by decreasing the width of each canvas section size by a tiny amount, just a few pixels, so that the overall width of the canvas is 98 or 99% of the current width.  Then Safari and Chrome users will both be happy.

**Comment by Dartv** [comment]
@sives one thing we can try is to add `word-break: break-all` property to canvas items, it will most likely fix this, but at the cost of breaking words to fit the container. You can see it in action here: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
Click on the second demo item and resize your browser window.
If this is ok with you, I'll add this.

**Comment by Dartv** [comment]
![](https://i.gyazo.com/0299659f99adf71c2ab31ca9bd6537d1.gif)

**Comment by Dartv** [comment]
We can even add hyphens: ![](https://i.gyazo.com/3aa9f08dd42cdbd72cdd40ec5711831a.png)
I don't see a better solution

**Comment by sives** [comment]
@Dartv OK let's try this, we can always reverse the change if it doesn't work.  If we do this, it's good to add hyphens.  If it doesn't work, we can try my suggested solution :-)

**Comment by Dartv** [comment]
@sives Mike and I tested this. On 24" and 15". In both cases printed document looks fine. Mike will later test this with 13" screen and reply.

**Comment by Praxie** [comment]
I can reproduce this issue on my 13" macbook:
![image](https://user-images.githubusercontent.com/2095940/54455846-6ac3da00-4765-11e9-88d1-1cd2b98ca164.png)

On preview it looks as there's no RHS border at all:
![image](https://user-images.githubusercontent.com/2095940/54455913-8b8c2f80-4765-11e9-81b5-760bdd36c11b.png)

**Comment by sives** [comment]
@Praxie This issue is still outstanding.  It did seem to be fixed when I last tested a couple of weeks ago, but in the current release 0.3.6 the RHS border is not printing in Safari (if you set print scale option to 99% it does print).

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2010

**Comment by sives** [comment]
@Dartv The first page is now printing perfectly, but the page breaks between pages 5/6 and also between 6/7, are not longer page-breaking correctly (see attached PDF).  In each case, the page title is getting split up between two pages.  

[Plio Canvas test print 1.pdf](https://github.com/Pliohub/Plio/files/3090212/Plio.Canvas.test.print.1.pdf)

**Comment by Praxie** [comment]
@sives we've found the solution. Dmitry will update the staging application soon.

**Comment by sives** [comment]
@Praxie @Dartv Now working well

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 03/11/19 - 04/15/19
Work session total: 15:26:18

Grand total: 15:26:18
