### ISSUE TITLE
Canvas sections not rendering correctly on laptop screen

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1994]
@Serhiy91 The canvas does not display correctly on a laptop-sized screen when using Chrome or Safari,. It only displays correctly on a large desktop monitor.  Many business users will be working on laptop screens, and it is important to display correctly on this screen size.   (The UI prototype does display correctly on laptop screens)

As with issue #1986 the root cause of the problem seems to be that our implementation does not exactly follow the behaviour of the UI prototype when resizing the browser window. In the prototype, the canvas sections keep their correct relative proportions and positioning as the browser window shrinks and at no point does any canvas section become obscured on the right hand side. 

![Screenshot 2019-03-13 at 11 35 46](https://user-images.githubusercontent.com/2330529/54276317-fe8a8000-4584-11e9-94a7-0a503c43e7ca.png)

**Comment by sives** [comment]
Suggestion: to save time, it might be a good idea to go back to Jack and get him to adjust the markup. He previously told me that he had significant problems in getting the markup to work correctly but he was eventually able to overcome them. In my most recent call with Jack he said that he expected us
to have problems with this screen. He offered to take a look at our canvas markup and fix it based on what he learned in his own troubleshooting work. If he can examine our markup and ensure that it works in exactly the same way as his prototype when resizing, then we will make it much easier to fix any future printing problems.

**Comment by Dartv** [comment]
Wait... This can be only reproduced in Southwind organization. I'm so confused

**Comment by sives** [comment]
@Dartv We use Southwind to test this feature because it contains a representative amount of demo data, with text strings that are similar in length to real text strings that users would enter.

**Comment by sives** [comment]
@Dartv I think the problem is being caused by the length of the operational items at the bottom of the canvas sections (see below).  When the titles of these items (e.g. Key goals) are too long, it prevents the correct shrinkage of the canvas section when you resize the browser window.  The Southwind organisation contains operational items with longer text strings, the Shift Bioscience organisation doesn't.  The fix could be very simple - just constrain the max length of the item title to be no longer than 

![Screenshot 2019-03-13 at 12 43 19](https://user-images.githubusercontent.com/2330529/54279901-187c9080-458e-11e9-85ee-e2ff8a1f0bb3.png)

**Comment by Dartv** [comment]
@sives Yeah, you're almost correct. The problem is with canvas items width though.

**Comment by sives** [comment]
@Dartv Yes, I think you are correct. The width of the canvas text titles relative to the available display width in the canvas section seems to be the problem.  I would tackle it in two directions. First reduce the width of the white borders to the left and right of the canvas items by 50% (borders are taking too much of the limited available space).  If this doesn't fix the problem, then reduce the column width taken by the lists of canvas items in some or all of the top 7 sections.  (I wouldn't change the bottom 2 sections because I don't think they are causing any problem, and they have a different display model because of their reduced vertical height)

**Comment by sives** [comment]
@Serhiy91 I disagree.  On Southwind, I just deleted all the long text title items from the footer area of each canvas section and it fixed the problem. This fix worked for both Chrome and Safari.

**Comment by sives** [comment]
@Serhiy91 Previously I've indicated that the Southwind organisation demo data should not be changed in testing, because it took so long to creete a high quality demo environment.  However, feel free to add or delete one or two or your own test data footer items to verify the hypothesis I described above.

**Comment by sives** [comment]
@Serhiy91 I think there may also be a minor problem with the allowable column width in the Key partners section being too wide compared to the other sections, resulting in this specific canvas section taking up a little bit too much of the total available page width. The "Prof John Callaghan - London Business School" item should be wrapping onto a new line a bit earlier than it currently does.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1995

**Comment by sives** [comment]
@Serhiy91  Works much better now on Safari and on Chrome.  With Chrome, there is a small rendering artifact when drawing canvas section outlines.  For some canvas sections, e.g. Customer relationships and Channels these outlines have an uneven width (see screenshot clipping).

![Canvas box outline artifact - Chrome](https://user-images.githubusercontent.com/2330529/54355963-5c38ce00-4652-11e9-833b-02c92b795ec4.png)

**Comment by Dartv** [comment]
@sives I can't reproduce this. This is probably your chrome or macOS version specific

**Comment by sives** [comment]
@Dartv Chrome on my MacBook Air is completely up to date (version 73.0.3683.75).  

Everything looks fine on Chrome on my MacBook Pro with an older version of Chrome and an newer version of MacOS.  So it seems to be a problem that appears with a newer version of Chrome in combination with an older version of MacOS.

Could you just double-check that your version of Chrome is also completely up to date?   If it is, and you still don't see this problem, then I'll close this issue because it's not important enough to invest in more troubleshooting.

(My MacBook Pro is running Chrome Version 71.0.3578.98 and High Sierra 10.13.4. My MacBook Air is running Chrome Version 73.0.3683.75 and Mojave 10.13.3)

**Comment by Praxie** [comment]
My Chrome is also up-to-date and I can't reproduce this.
