### ISSUE TITLE
Handle removing/unlinking children docs in case of permanent removal of parent doc

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#200]
After NC/CA/PA is deleted softly (isDeleted: true), we need to remove work items that are linked to this document permanently.
Also if some document is deleted permanently, we need to unlink related documents or remove them if it's not possible to unlink them.

![screen shot 2016-10-19 at 12 42 48 pm](https://cloud.githubusercontent.com/assets/2095940/19514750/684f1d6e-95fd-11e6-9a0d-7cea55ec378b.png)

**Comment by sives** [comment]
All fixed and working
