### ISSUE TITLE
"Invite users" button has disappeared

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2000]
The invite users button has disappeared from the right hand side of the header bar in both the Operations and the Canvas screens.  It needs to be restored, as per the UI prototype.

**Comment by Dartv** [comment]
@sives it hasn't disappeared. You're probably just logged in as a user that doesn't have a role to invite users.

**Comment by sives** [comment]
@Dartv Apologies, my brain's running slow this afternoon
