### ISSUE TITLE
Add the "Sign-up path" field to the  Organization card 

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#2002]
![image](https://user-images.githubusercontent.com/2095940/55255673-dc228300-5263-11e9-9fd0-a00af24e6f0c.png)

Organization card is a card that appear when you go the the Plio organization and select Plio organizations from the LHS dropdown in the header -> select the organization.
This field should not be editable. It should not be present in the editable card, only the read-only one.

**Comment by Praxie** [comment]
<img width="1053" alt="Screen Shot 2019-04-13 at 12 46 20 PM" src="https://user-images.githubusercontent.com/2095940/56077888-37b74980-5dea-11e9-8b1e-811b71d0ecfc.png">

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2009

**Comment by sives** [comment]
Working well

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/15/19 - 04/15/19
Work session total: 0:57:51

Grand total: 0:57:51
