### ISSUE TITLE
Several windows are opened after tapping on '+Add' button for several times

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#201]
26941
https://testlio.com/c/plio/issues/26941
**Environment:**
Device and OS: Nexus 5X Android 7.0
Testable App version: app.pliohub.com
Network: Wi-Fi
Location: Ukraine
Reproducibility rate: 3/3

**Steps to reproduce:** 
1. Open the 'Risk register'.
2. Tap several times on '+Add' button.

**Expected result:**
Only one window should be opened.

**Actual result:** 
Several windows are opened after tapping on '+Add' button for several times.

**Comment by Praxie** [comment]
This issue needs to be fixed for all buttons that trigger modal window. The solutions should be unified and reusable.
Use _.debounce?
(basic principles: http://stackoverflow.com/questions/8055923/javascript-jquery-add-debounce-throttle-to-a-button)

**Comment by Praxie** [comment]
We need to have the minimal possible latency. Otherwise it may look like a lag.

**Comment by Praxie** [comment]
It seems to be fixed in the current release.

**Comment by RevelsGit** [comment]
No it is not. I am able to open multiple modals still.

**Comment by Praxie** [comment]
Resolved in the current release.
