### ISSUE TITLE
Avatar missing in user directory on Staging

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2014]
@dartv The avatar image for Bryan Abercrombie in the User directory is not loading properly in the Staging system (but working fine on app.pliohub.com).

![Screenshot 2019-04-17 at 16 04 46](https://user-images.githubusercontent.com/2330529/56299023-22645700-612b-11e9-939e-f1a2a7c29187.png)

**Comment by Praxie** [comment]
This is probably the network issue. I can't reproduce this. @sives
