### ISSUE TITLE
Adding actions to key goals - not updating in UI

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2015]
When adding new actions to Key goals, the new saved action doesn’t update in the user interface until the page is reloaded in the browser

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2018

**Comment by sives** [comment]
@Dartv The new saved action is now updating correctly in the user interface but there is now a new bug relating to adding of new actions.  When I add a new action, the title from the previously-created action is displayed in the title field

**Comment by Praxie** [comment]
https://i.gyazo.com/dd8666356c431c52490f7ef8b10d83c6.gif

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2020

**Comment by sives** [comment]
@Dartv Adding actions is now working fine, but I've just discovered that deleting Key goals does not update the UI until the browser window is refreshed.

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/18/19 - 04/18/19
Work session total: 0:14:16

Grand total: 0:14:16
