### ISSUE TITLE
Key goals title label needs changing

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2016]
Underneath the Key Goals timeline section of the Plio Operations home page, there is a section titled "Completed & deleted goal(s)" which appears if any Key Goals are completed or deleted.

To avoid user confusion the title should be changed to "Completed or deleted goal(s)".

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2019

**Comment by sives** [comment]
@Dartv When I delete a key goal, I no longer see the section "Completed or deleted goal(s) on the home screen.  Also, when I delete a key goal, I need to refresh the browser window to update the list of key goals.  The list should update without me having to do this.

**Comment by Dartv** [comment]
@sives I can't reproduce this. What are the exact steps?

**Comment by sives** [comment]
@Dartv It works now when I test it again, very strange.  Let's not worry about this, it all seems to be fine

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/18/19 - 04/18/19
Work session total: 1:00:00

Grand total: 1:00:00
