### ISSUE TITLE
Unnecessary duplication in daily recap

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2021]
Since the new release has gone live, the daily recap emails no longer list the name of the user in the left hand side column who is responsible for each specific change.  This is happening across multiple organisations.

![Screenshot 2019-04-21 at 10 59 10](https://user-images.githubusercontent.com/2330529/56468492-335fe180-6425-11e9-8432-176d1cd81d2e.png)

**Comment by Dartv** [comment]
Makes sense that status changes don't show any user. They are made by background app hence no user is displayed.

**Comment by sives** [comment]
@Dartv Of course, you are correct

**Comment by sives** [comment]
@Dartv I've looked at some more examples.  The original example I posted above does fit into your classification and represents a correct behaviour.  However, I've found other examples where no user name is displayed that do not fit this classification.  The user makes a change in the system and Plio shows 2 or more change summary lines for the same event, at least one of which is unlabelled (see below for examples).

![Screenshot 2019-04-23 at 08 50 54](https://user-images.githubusercontent.com/2330529/56564105-45688e00-65a5-11e9-83c4-bf0f9f42c500.png)

![Screenshot 2019-04-23 at 08 51 27](https://user-images.githubusercontent.com/2330529/56564161-5fa26c00-65a5-11e9-976a-70fcd1ac5545.png)

**Comment by Praxie** [comment]
@sives the ones that are unlabeled define changes that are made automatically by the system in response to user updates.

**Comment by sives** [comment]
@Praxie I understand the reason why it's happening, but going back to first principles it's not the way that we should present information to the user.  

In the GA22 example above, the user Steve Ives completes an action.  This is a single, user-initiated event.  The system creates a line entry for the completion of the action by Steve Ives, and also an additional  line entry (the entry displayed above the Steve Ives completion event) for the resulting change in status detected by the background application for this exact same event.  The wording in the daily recap makes it look like two different events have occurred, when in reality there was only one  event.  The duplication of line entries is a consequence of the design of the system.  It doesn't result from a coding bug, but from a design problem.

**Comment by Praxie** [comment]
@sives what would you suggest to do? It's a very complicated issue.
I'd suggest to remove system messages from Daily Recap and/or group messages that was done by a single user over 1 minute into one line.
