### ISSUE TITLE
Daily recap - canvas updates

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2022]
3 changes needed in the way we handle canvas updates in the Daily recap email: 

1. Remove unwanted Notes line items
There are unwanted line items being added relating to changes in Notes on canvas cards, where a blank item "" is displayed (see screenshot below, Salaries section, Bryan Abercrombie "Notes set to "").  I believe this is happening when the user places the cursor into the Notes field on the canvas item card but doesn't enter any notes.  Plio mistakenly interprets this event as a change to the Notes field.  

2. Subtitle layout
See screenshot below, 2nd section down:
"2 Channels were updated:" needs to be changed to:
"2 Channels were updated in the business model canvas:" 
(To make it clearer that these are not changes related to canvas items and not to operational items)

3. Document created
Whenever there is a new canvas item card added to the business model canvas, the Daily recap email records this a "Document created" (see below, Own direct and Fund supermarket sections).  It would be better to record it as "New canvas item created".

![Screenshot 2019-04-23 at 12 07 07](https://user-images.githubusercontent.com/2330529/56645462-9f388900-6675-11e9-8895-cd5648d82f44.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2026
