### ISSUE TITLE
Avatar not being displayed in discussions

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2023]
The avatar image is not being displayed, instead you just see two horizontal lines.

![Screenshot 2019-04-24 at 11 32 31](https://user-images.githubusercontent.com/2330529/56653096-d5c9d000-6684-11e9-9397-d5aa3690c609.png)

**Comment by Dartv** [comment]
Works fine for me ![](https://i.gyazo.com/7b9ceabfe9e52f7cb8a6a04d6889b47a.png)

**Comment by sives** [comment]
Seems to be a sporadic problem so no need to investigate further.
