### ISSUE TITLE
Ability to see all Plio organizations should be a private feature

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2024]
In the new live 0.4.1 release, any user in any organization can click on the left hand side dropdown menu and see the list of all Plio organizations.  This features was always strictly private (to members of the Plio organisation only) in previous releases.  It must not be available to users in any other organization.

**Comment by Dartv** [comment]
@sives I just checked and this is not true. Only the users in Plio organization can see this option.

**Comment by sives** [comment]
@Dartv The behaviour seems to have changed since the 0.3 release - previously you could only access this list if 2 conditions were satisfied: you were a user in the Plio organisation and you were actually working in the Plio organisations.  I switched my screen display into another Plio organisation and was still able to access the list of all Plio organisations - this is what fooled me.  If it is still secure, then no need to change the behaviour.
