### ISSUE TITLE
Invitation email text needs updating

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2028]
In the Step 5 requirements, there was a requirement to update the email invitation text:
"Before we go live with the Step 5 system, we need to change the text wording for the Invite user messages and for the footer text of the other system-generated emails (because current wording is specific to the original role of Plio as just a quality & compliance management system)."

This has not been done correctly (see screenshot) - I am still receiving emails with the old invitation text that has the word "compliance" in the first line.

For invites sent from the Plio Operations screen the text should read as follows:
"((Steve Ives)) invited you to join the Plio Ltd management system. 
Accept the invitation 
Hi there.  We'll be using Plio to share standards documents, to record nonconformities and risks and to track actions. Please accept this invitation to join Plio as a user. See you there soon."

For invites sent from the Plio Canvas screen the text should read as follows:
"((Steve Ives)) invited you to join the Plio Ltd management system. 
Accept the invitation 
“Hi there. We’ll be using Plio to create and share a business model canvas.  Please accept this invitation to join Plio as a user. See you there soon.”

![Screenshot 2019-05-13 at 11 52 49](https://user-images.githubusercontent.com/2330529/57616722-c5678f80-7576-11e9-8bb7-a56b2f845fc9.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2030

**Comment by sives** [comment]
@Dartv The only problem I can see is in the invitation expiry date wording.  My understanding is that users have 24 hours to respond to the invitation before it expires. Currently the wording states that the invitation is expiring on the same day that it is received, which is not correct (see screenshot below - the expiration date should be 18th May 2019).

![Screenshot 2019-05-17 at 11 32 44](https://user-images.githubusercontent.com/2330529/57922597-ff4ad580-7897-11e9-8740-2c690023f1fa.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2032

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/15/19 - 05/17/19
Work session total: 1:34:47

Grand total: 1:34:47
