### ISSUE TITLE
Members calculation error in Plio organizations screen

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2029]
Plio is incorrectly calculating the number of currently active members of Plio Organization.  It seems to be included users that have previously been deleted by the org owner, leading to reporting a user number that is higher than it should be.

**Comment by Dartv** [comment]
Doesn't seem to be true. I just checked.

**Comment by sives** [comment]
@Dartv I've just sent you through more details by email.  Are "users" as displayed in the user directory screen the same entity as "members" as displayed in the Plio organisations screen, or a different entity?

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2031

**Comment by Dartv** [comment]
This should be resolved automatically in 1 day

**Comment by sives** [comment]
@Dartv It's still reporting the old incorrect values when I looked this morning

**Comment by Dartv** [comment]
@sives should be resolved now

**Comment by sives** [comment]
@Dartv Yes, it is now showing the correct value
