### ISSUE TITLE
[Testlio][Mobile][Discuss] Browser freezes on upload attachment 

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#203]
**Environment:**
Device and OS:iPhone6S iOS 10.0.2
Testable App version:https://app.pliohub.com v0.2.36
Network:WiFi
Location:Bangladesh
Reproducibility rate: 3/3

**Steps to reproduce:** 
1. Login to the web.
2. Compliance standards> Add
3. Enter a title and all other fields.
4. Open that compliance 
5. Discuss> Attachment
6. Take or choose picture
7. Use any picture> Observe, full browser hanged (i.e: no button works even user can't go back)
8. Tap on device home button> Reopen browser> See blank page shows 

**Expected result:**
Webpage should not hang. Everything should function properly.

**Actual result:** 
Browser freezes, nothing works there. Need to close webpage and rerun homepage URL where user will be logged out.<p><a href="https://testlio.s3.amazonaws.com/issue/145563/a/2528c24e-12a2-7a3d-5ba1-59ec02d29a2d/9665b7af640b0af931a87f309a2c6219.mp4">26763_Browser Hanged.mp4</a><br><a href="https://testlio.s3.amazonaws.com/issue/145563/a/ee2efd8e-c5cd-9fe2-939d-d0239e169144/019274945a3efbbe64b85b009c46560b.txt">26763_Browser hanged.txt</a><br></p>

**Comment by sives** [comment]
If it's not an easy fix, don't spend too much time on this, mark it forward to Step 3a

**Comment by Praxie** [comment]
@RomanValihura take a look at this. But don't spend much time.

**Comment by RomanValihura** [comment]
How I can test it? On other devises it works.

**Comment by RomanValihura** [comment]
Cannot reproduce on iPhone Simulator

**Comment by markokruustuk** [comment]
Closed from GitHub
