### ISSUE TITLE
Background application/GraphQL error email notifications

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2033]
@Dartv We need to modify these email error notifications to inform me which server has crashed for the Background application and GraphQL application (i.e. the Live server or the Staging server).  

Currently I get an identical email error notification for both of these situations, so I can't tell if the staging background applications have crashed, or the live background application applications have crashed.

Clearly, it’s a much bigger deal if the live server has crashed, so I need to know this.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2053

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 06/14/19 - 07/18/19
Work session total: 4:23:20

Grand total: 4:23:20
