### ISSUE TITLE
Modified Plio sign-up process

### ISSUE THREAD

**Issue by michaelrokosh** [Pliohub/Plio#2034]
For each industry sector there will be a customised sign-up screen with a dedicated URL, for example:
 app.pliohub.com/sign-up?type=quality-healthcare  

When the new customer visits the sign-up page, they see a page that is labelled with the management system type and the industry sector, for example:
"Quality management for healthcare"

Examples of the new sign-up page layout are provided in Files in Basecamp. 
See https://basecamp.com/1896845/projects/11083679/uploads/45812881?enlarge=374863376#attachment_374863376

The  following 3 changes will be made to the existing sign-up page:
- an extra line of text below the "Plio" text label at the top of the screen
- Plio logo has been moved from the bottom of the screen 
- The large Plio label at the top of the screen has been updated to include the Plio logo

An initial list of 11 industry sectors which will each need their own version of the sign-up page is included at the bottom of this document.  It must be possible to add new sectors in the future (up to a maximum of 50) if we discover that they are going to be attractive target markets for Plio.

When the new customer completes their sign-up details they are taken to the Plio Operations screen. Their Plio account will then be already be pre-loaded with customised organisation settings for the following settings options:
- Standards types
- Standards sections
- Risk types.  
All other settings are the same as the current system defaults.

The addition of these customised settings  should add no more than 5 seconds of extra system processing time delay before the user is taken to the Plio Operations screen.

**Comment by michaelrokosh** [comment]
Sign-up screen top-of-page text strings:

"Quality management for construction"
"Quality management for education"
"Quality management for healthcare"
"Quality management for laboratories"
"Quality management for manufacturing"
"Quality management for software engineering"
"Compliance management for banking"
"Compliance management for education"
"Compliance management for financial services"
"Compliance management for healthcare"
"Quality & compliance management for law firms"

Sign-up page URLs:

app.pliohub.com/sign-up?type=operations&template=quality-construction
app.pliohub.com/sign-up?type=operations&template=quality-education
app.pliohub.com/sign-up?type=operations&template=quality-healthcare
app.pliohub.com/sign-up?type=operations&template=quality-laboratories
app.pliohub.com/sign-up?type=operations&template=quality-manufacturing
app.pliohub.com/sign-up?type=operations&template=quality-software
app.pliohub.com/sign-up?type=operations&template=compliance-banking
app.pliohub.com/sign-up?type=operations&template=compliance-education
app.pliohub.com/sign-up?type=operations&template=compliance-finance
app.pliohub.com/sign-up?type=operations&template=compliance-healthcare
app.pliohub.com/sign-up?type=operations&template=compliance-law

together with the existing sign-up page URLs, which point to the existing organization settings lists:

app.pliohub.com/sign-up?type=operations
app.pliohub.com/sign-up?type=canvas

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2049

**Comment by Dartv** [comment]
@sives please, note that you should not delete or create another "General purpose" organization since its id is hardcoded. You can create and delete any other template organization though.

**Comment by vitalii7777** [comment]
Sign-up page URLs works and display organization name under Plio logo

**Comment by sives** [comment]
The requirements specify that the following text strings are to be displayed under the Plio logo, not the organization name:

![Screenshot 2019-06-14 at 09 54 35](https://user-images.githubusercontent.com/2330529/59497213-e4fe1a80-8e8a-11e9-8c8b-fc5352454dce.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/issues/2037#issuecomment-502030375

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 06/11/19 - 06/11/19
Work session total: 2:56:53

Grand total: 2:56:53
