### ISSUE TITLE
Customised sign-up URL for invitations 

### ISSUE THREAD

**Issue by michaelrokosh** [Pliohub/Plio#2035]
When new users are invited to a Plio organization, the email invitation that is sent will contain the customised sign-up URL for the same vertical sector as the organization from which the invitation originates.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2052

**Comment by vitalii7777** [comment]
Customized sign-up URL is present in invitations, and we can successfully register an account.


@Dartv 
But this looks like not correct:

![Знімок екрана  о 12 24 37 пп](https://user-images.githubusercontent.com/47181845/59423910-c260f880-8ddb-11e9-8559-5a8a4bd21634.png)

**Comment by Dartv** [comment]
It's your browser's autocompletion

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 06/12/19 - 06/12/19
Work session total: 2:59:19

Grand total: 2:59:19
