### ISSUE TITLE
Add a "Template" type to the list of possible organization types in Plio organizations

### ISSUE THREAD

**Issue by michaelrokosh** [Pliohub/Plio#2036]
In the Plio Organisations screen card, the Organisations card contains a field called Organisation type (with the available types Paying subscriber, Free trial, Test account, Past customer).  We will add a new Plio Organisation type called "Template".  

I will then create a number of new organisations with the Organisation type field set to "Template".  These organisations will be used solely for the purpose of creating and maintaining the customised template organisation settings lists.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2041

**Comment by vitalii7777** [comment]
"Template" type added to the list of possible organization

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 06/04/19 - 06/04/19
Work session total: 0:21:43

Grand total: 0:21:43
