### ISSUE TITLE
Mapping template organizations to sign-up paths

### ISSUE THREAD

**Issue by michaelrokosh** [Pliohub/Plio#2037]
E.g. 
"quality-construction": <OrganizationId>
"quality-education": <OrganizationId>
As an alternative, we could agree on the naming convention. 
E.g. template=quality-education would look for an organization with type "template" and name "Quality Education", not case sensitive.

**Comment by michaelrokosh** [comment]
Sign-up screen top-of-page text strings:

"Quality management for construction"
"Quality management for education"
"Quality management for healthcare"
"Quality management for laboratories"
"Quality management for manufacturing"
"Quality management for software engineering"
"Compliance management for banking"
"Compliance management for education"
"Compliance management for financial services"
"Compliance management for healthcare"
"Quality & compliance management for law firms"

Sign-up page URLs:

app.pliohub.com/sign-up?type=operations&template=quality-construction
app.pliohub.com/sign-up?type=operations&template=quality-education
app.pliohub.com/sign-up?type=operations&template=quality-healthcare
app.pliohub.com/sign-up?type=operations&template=quality-laboratories
app.pliohub.com/sign-up?type=operations&template=quality-manufacturing
app.pliohub.com/sign-up?type=operations&template=quality-software
app.pliohub.com/sign-up?type=operations&template=compliance-banking
app.pliohub.com/sign-up?type=operations&template=compliance-education
app.pliohub.com/sign-up?type=operations&template=compliance-finance
app.pliohub.com/sign-up?type=operations&template=compliance-healthcare
app.pliohub.com/sign-up?type=operations&template=compliance-law

**Comment by michaelrokosh** [comment]
We should store these templates in constants and map them to organization ids after Steve will create template organizations.

**Comment by Dartv** [comment]
I feel like we need to make this dynamic, so that Steve can adjust these whenever he wants

**Comment by Dartv** [comment]
Like, maybe store these mappings in mongo. Then we can add a field to Plio organizations screen modal "Sign-up path" and the url will just look for that path in database and import documents?

**Comment by Dartv** [comment]
@sives what do you think? You will have more control over this. This will require more time of course.

**Comment by sives** [comment]
@Dartv Yes, ideally it would be good to have control, but please let me have an estimate of extra hours of time needed

**Comment by Dartv** [comment]
I'd say around 16 hours extra

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2047

**Comment by Dartv** [comment]
@sives Note that I named this field "Customer sign-up path" since we already have "Sign-up path" field. If you want to change that, please respond.

**Comment by sives** [comment]
@Dartv Please call the new field "Sign-up URL"

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2048

**Comment by vitalii7777** [comment]
Checked Sign-up page URLs  (changed URL manually, because no button or functionality for automate). Looks like works well, correct organization name is displayed:

![Знімок екрана  о 2 06 03 пп](https://user-images.githubusercontent.com/47181845/59428022-cd6c5680-8de4-11e9-8adc-d7cae3038f6e.png)

**Comment by sives** [comment]
@Dartv The text string below the Plio logo (shown in vitalii's comment above) is not following the format described in the Step 5b requirements document:

![Screenshot 2019-06-14 at 09 54 35](https://user-images.githubusercontent.com/2330529/59497051-95b7ea00-8e8a-11e9-8c5a-e4f50abcf891.png)

**Comment by Dartv** [comment]
@sives this way it's flexible, so you can change this whenever you want. Can't you just name these organizations that way?

**Comment by sives** [comment]
@Dartv OK, yes I understand now. You are correct. I will modify the names of the new organizations I have created to fit in exactly with the list in the requirements document.

**Comment by sives** [comment]
@Dartv We will need to increase the maximum permitted length of an organization name from 40 characters to 64 characters in order to accommodate the new top-of-page text strings.  At the moment Plio doesn't allow any organization name longer than 40 characters to be entered into the top field of the Org settings card.

**Comment by vitalii7777** [comment]
@Dartv still 40 chars is max

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 06/07/19 - 06/10/19
Work session total: 4:53:07

Grand total: 4:53:07
