### ISSUE TITLE
Importing Org settings from the Template organization

### ISSUE THREAD

**Issue by michaelrokosh** [Pliohub/Plio#2038]
We should be able to clone Standard types, Standard sections and Risk types from the existent "template" organization into a new one.

**Comment by Dartv** [comment]
@sives what about current default Standard types, Standard sections, Risk types? Do we still create them?

**Comment by Dartv** [comment]
@sives Also, we already have import standards feature. We could just allow users to import standards from template organizations if they wish

**Comment by sives** [comment]
@Dartv the current default Standard types, Standard sections and Risk types should be replaced with the latest ones in the template organization titled "General purpose".

**Comment by sives** [comment]
@Dartv yes, I considered adding this feature (to import standards from a template organisation) but it's a very large amount of work to come up with generally-useful sets of documents for 11 different vertical sectors that are applicable in both the US and the UK.  So I decided to defer this to a future release.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2043

**Comment by Dartv** [comment]
@sives what about these old fields? ![](https://i.gyazo.com/16b46632e4e2f9666d404d5d30209cb3.png)

There is quite a bit of code that checks these on client & server side. Ultimately we need to get rid of  them.

**Comment by sives** [comment]
@Dartv Yes we should retain these fields, they are still needed in all templates, at least for the moment

**Comment by vitalii7777** [comment]
Settings inherited from template `organization 1` to new one `organization 2` based on a template

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 06/06/19 - 06/07/19
Work session total: 4:32:18

Grand total: 4:32:18
