### ISSUE TITLE
Template selection in the New Organization modal

### ISSUE THREAD

**Issue by michaelrokosh** [Pliohub/Plio#2039]
The field should load all template Organization names in Plio.
(the dropdown should contain names of all organizations with the type "Template")

![image](https://user-images.githubusercontent.com/2095940/58651332-b3794100-8319-11e9-8225-98976d287ba6.png)

When creating a new Plio organization from the LHS dropdown menu, we will add a selector field called "Template" to the bottom of the "Create new Plio organization" modal, just above the default currency selector.   Clicking on the selector will then display a selection list of the available templates, labelled in an identical way to the sign-up screen top-of-page text strings shown in Section 2 above.  The user selects his desired template and the new organization is then created using the organization settings that correspond to this template.   

An image of the new "Create new Plio organization" modal can be found in Files on Basecamp.

**Comment by michaelrokosh** [comment]
@Dartv I don't think that we should save the link to the template document in the database.
We need the template organization ID only for a one-time settings import.

**Comment by michaelrokosh** [comment]
So we don't need to have the Template field in the Organization card.

**Comment by Dartv** [comment]
It's better to save it. We may need that information later

**Comment by michaelrokosh** [comment]
@Dartv ok, we can save it.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2042

**Comment by vitalii7777** [comment]
We can create new organization using existing templates

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 06/04/19 - 06/12/19
Work session total: 10:51:32

Grand total: 10:51:32
