### ISSUE TITLE
[Testlio][Mobile][Compliance standard] More info is not showing from help.

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#204]
**Environment:**
Device and OS:iPhone6S iOS 10.0.2
Testable App version:https://app.pliohub.com v0.2.36
Network:WiFi
Location:Bangladesh
Reproducibility rate: 3/3

**Steps to reproduce:** 
1. Login to web.
2. Compliance standards> Add
3. Tap on Help icon
4. More info and observe

**Expected result:**
Should open more info page/pop up.

**Actual result:** 
Nothing happens on tap More Info. <p><a href="https://testlio.s3.amazonaws.com/issue/145541/a/d10ff8f5-10de-2290-b228-131dcb489e03/183cfcb9914ba033540ef42568520387.txt">26741_Log.txt</a><br><a href="https://testlio.s3.amazonaws.com/issue/145541/a/f503ab55-a100-ccce-23b2-173739a85c93/2ad4fc8b9a6917cf75a483526cdba2d4.mp4">26741_Video.mp4</a><br></p>

**Comment by markokruustuk** [comment]
#26762 [Work Inbox] No action clicking on 'More info' at Help section during creating/editing action
Feature: Work Inbox screen
Environment:
Device and OS: MacBook Pro Sierra 10.12 | Firefox 49.0.1
Testable App version: https://app.pliohub.com/107/work-inbox/
Network: WiFi
Location: UA
Reproducibility rate: 5/5

Steps to reproduce:
1. Work Inbox
2. Add &gt; Corrective/Preventative action &gt; Click Help icon [?] &gt; More info
3*. Edit created item &gt; Click Help icon [?] &gt; More info

Expected result:
'More info' screen opened

Actual result:
No action clicking on 'More info'

Note: no logs generated during reproducing<p><a href="https://testlio.s3.amazonaws.com/issue/145541/ca/64715/caeb63dd3ac09486a042c6c33b626f6f.mp4">more_info.mp4</a><br></p>

**Comment by sives** [comment]
"More info" feature not required until Step 3a.   The "More info" button should link to a pre-defined document in the Online documentation set.

**Comment by Praxie** [comment]
Resolved in the current release.

**Comment by markokruustuk** [comment]
Closed from GitHub
