### ISSUE TITLE
[Testlio][Desktop][Non Conformities] Unable to add a lesson to non-conformity as owner is required error occurs

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#205]
**Environment:**
Device and OS: Lenovo G50 Windows 10
Browser: IE 11
Testable App version: app.pliohub.com/sign-up
Network: Wifi
Location: Pakistan
Reproducibility rate: 5/5

**Steps to reproduce:** 
1. Open the URL and sign in
2. Click on Non-Conformities
3. Click on Add
4. Enter all required fields and click on Save
5. On second popup that appear, scroll down and click on "Lessons Learned"
6. Click on "Add a new lesson"
7. Enter all the fields and click on "Save" 
6. Observe

**Expected result:**
User should be able to add a lesson

**Actual result:** 
User gets an error "Owner required," although all fields have already been entered<p><a href="https://testlio.s3.amazonaws.com/issue/145534/a/e1a3fcac-08ec-678d-660e-d7e85bfc3948/7dd3547f81183999c7ddb5aa069a8843.mp4">2016-10-11 17h39_00.mp4</a><br></p>

**Comment by markokruustuk** [comment]
Reproducible on
Device and OS: Windows 10, Firefox 47.0.1
Testable App version:https://app.pliohub.com
Network: Wifi
Location: Cz
Reproducibility rate: 3/3

<p><img src="https://testlio.s3.amazonaws.com/issue/145534/ca/64639-medium.jpg"/><br></p>

**Comment by markokruustuk** [comment]
Tagging this as question. It is not specified in the testcases if the user needs to be an owner or not.

**Comment by markokruustuk** [comment]
I am an owner in this case

**Comment by sives** [comment]
This error should not be showing up.   (BTW - to add a Lesson Learned, you don't need to be the owner of the Non-conformity)

**Comment by Praxie** [comment]
Fixed in **v0.2.47**

**Comment by markokruustuk** [comment]
Closed from GitHub
