### ISSUE TITLE
Import default settings from the "General purpose" organization for any new templates created without a template

### ISSUE THREAD

**Issue by michaelrokosh** [Pliohub/Plio#2054]

**Comment by vitalii7777** [comment]
@Dartv 

Can not create an organization without a template. Template is required:

![Знімок екрана  о 1 16 10 пп](https://user-images.githubusercontent.com/47181845/59424922-875fc480-8ddd-11e9-92ef-92bd327208f7.png)

**Comment by Dartv** [comment]
You can create organization without template when signing up

**Comment by vitalii7777** [comment]
https://github.com/Pliohub/Plio/issues/2038#issuecomment-501653246
