### ISSUE TITLE
Sign-up success page Adwords tracking

### ISSUE THREAD

**Issue by michaelrokosh** [Pliohub/Plio#2059]
Embed a Google AdWords code snippet in the new account sign-up success page (the same code snippet for all sign-up paths, I will provide details of this snippet and where to find it).
@sives is going to provide the code snippet.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2070

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 06/27/19 - 06/27/19
Work session total: 2:11:28

Grand total: 2:11:28
