### ISSUE TITLE
[Testlio][Mobile][User Settings] The 'User Settings' window is not fully available in landscape mode, because there is no way to scroll the page to view all the options.

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#206]
**Environment:**
Device and OS: Nexus 5X Android 7.0
Testable App version: app.pliohub.com
Network: Wi-Fi
Location: Ukraine
Reproducibility rate: 3/3

**Steps to reproduce:** 
1. Go to URL>Sign in.
2. Open the 'User Settings' window>Observe everything is displayed correctly.
3. Now change your device to landscape mode.

**Expected result:**
User should be able to use the 'User Settings' window in landscape mode, so all the options from there is should be available.

**Actual result:** 
The 'User Settings' window is not fully displayed in landscape mode and there is no way to scroll the page down to access to all the options.<p><img src="https://testlio.s3.amazonaws.com/issue/145747/a/a63f794a-25b9-918d-abfd-77af1d4009bc-medium.jpg"/><br><a href="https://testlio.s3.amazonaws.com/issue/145747/a/73e686e1-dd21-0b2e-17e5-0b7cd9b280d2/50337547be535748d26f14dcae705d95.mp4">#26947_Vide.mp4</a><br></p>

**Comment by Praxie** [comment]
**v0.2.51**

**Comment by markokruustuk** [comment]
Closed from GitHub
