### ISSUE TITLE
LHS dropdown menu (home screen and canvas screen)

### ISSUE THREAD

**Issue by michaelrokosh** [Pliohub/Plio#2060]
Change the text label in the LHS dropdown menu from "Canvas view" to "CEO view" and change the ordering so that the "Operations view" text label is at the top of the dropdown subsection.

**Comment by Dartv** [comment]
@sives what about ![](https://i.gyazo.com/e5e6b5fd0ed75e20d82a284fb0973b41.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2066

**Comment by unplugged** [comment]
Yes, also “CEO view” here too

**Comment by vitalii7777** [comment]
Implemented

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 06/19/19 - 06/19/19
Work session total: 0:21:12

Grand total: 0:21:12
