### ISSUE TITLE
Numbering of items in List views

### ISSUE THREAD

**Issue by michaelrokosh** [Pliohub/Plio#2061]
In the Nonconformities screen and in the Risks screen there is a left-hand-side list view panel which helps the user navigate to items displayed within these screens.  I'd like to add item numbers to the different sub-panels in each list view.  These should display the number of right-hand-side items that correspond to this sub-panel.

![image](https://user-images.githubusercontent.com/2095940/59538964-28489f80-8f04-11e9-94e1-059ee7a25edb.png)

(margin-left: 10px)

From a UI design perspective, this follows the existing design pattern we use in subcards, where we display a number signifying the total number of items contained within that subcard (e.g the number of CAs contained within the Corrective actions subcard at the bottom of the Nonconformites card).

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2067

**Comment by michaelrokosh** [comment]
Now the question is whether we should add numbers to Standards and Work inbox as well. @Dartv @sives

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 06/19/19 - 06/19/19
Work session total: 1:01:17

Grand total: 1:01:17

**Comment by sives** [comment]
@michaelrokosh We decided to implement numbering in both Standards and Work inbox.
