### ISSUE TITLE
[Testlio][Mobile][Risks register] The 'Calendar' window is overlapped by keyboard, because they are opened in the same time at tapping on 'Identified date'.

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#207]
**Environment:**
Device and OS: Nexus 5X Android 7.0
Testable App version: app.pliohub.com
Network: Wi-Fi
Location: Ukraine
Reproducibility rate: 3/3

**Steps to reproduce:** 
1. Open the 'Risks register'.
2. Tap on '+Add' button.
3. From new opened window>Tap on 'Identified date'.
4. Observe the 'Calendar' window.

**Expected result:**
Application should work properly, so everything should be displayed correctly.

**Actual result:** 
The 'Calendar' window is overlapped by keyboard, because they are opened in the same time at tapping on 'Identified date'.<p><a href="https://testlio.s3.amazonaws.com/issue/145743/a/78d3a9c7-021e-77d8-5ae2-512aabc5a1d1/2f635dcae98c6e84c4ee401fbe850c7d.mp4">#26943_Video.mp4</a><br></p>

**Comment by Praxie** [comment]
@RomanValihura find a way to prevent the keyboard from opening by clicking on the calendar field.

**Comment by Praxie** [comment]
**v0.2.50**

**Comment by markokruustuk** [comment]
Closed from GitHub
