### ISSUE TITLE
When creating a new organization, template field needs a default value

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2071]
Currently when creating a new Plio organization the recently-added template field has no default value, so the user has to actively select a template from the list.  However, not every user will be aware of what "template" actually means, so it is best to provide a safe default value.  I've added a requirement to the Step 5b requirements document for this field to display a default value of the template identical to that of the organization that the user is currently working in .

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2081

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 07/12/19 - 07/12/19
Work session total: 2:03:46

Grand total: 2:03:46
