### ISSUE TITLE
Spacing between the new item number field and the monetary value field

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2072]
In the Nonconformities screen, we've added a new field in the LHS list views to display the number of items in a section.  We need to increase the spacing between this field and the financial value field (showing £90k below), by moving the financial value field to the left slightly, to double the width of the existing spacing.

![Screenshot 2019-07-04 at 12 55 00](https://user-images.githubusercontent.com/2330529/60664932-071c0480-9e5b-11e9-8839-bbcb46ad39f6.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/commit/ac341635a67fe74b2093398c193ad9084b2e357e

**Comment by sives** [comment]
@Dartv Looks good
