### ISSUE TITLE
Item numbering in Work inbox

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2073]
If it is quick and easy to do, then it would be useful to add item totals to the dropdown list view selector in the header panel of the Work inbox e.g. 

my current work (7)
team current work (15)
my completed work (129)
team completed work (235)
my deleted actions (23)
team deleted actions (15)

![Screenshot 2019-07-04 at 12 57 58](https://user-images.githubusercontent.com/2330529/60665147-99bca380-9e5b-11e9-80b0-440d7de5d671.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2077

**Comment by sives** [comment]
@Dartv @michaelrokosh  It looks good

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 07/08/19 - 07/08/19
Work session total: 1:33:30

Grand total: 1:33:30
