### ISSUE TITLE
Customised top-of-page text string not appearing

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2074]
As specified in the 4th paragraph of section 1 in the Step 5b requirements document, there should be a customised top-of-page text string just below the Plio logo on the sign-up screen, and just above the box containing the sign-up fields e.g. "Compliance management for financial services".  This is not being displayed (see screenshot below).

![Screenshot 2019-07-04 at 13 02 44](https://user-images.githubusercontent.com/2330529/60665446-5f9fd180-9e5c-11e9-9db7-43927d1da87b.png)

**Comment by Dartv** [comment]
@sives What url did you use for this? I looked at staging and there is no url defined for "Compliance management for financial services" template, so of course it doesn't show anything.

**Comment by sives** [comment]
@Dartv OK, understood.  I just tried to enter the following URL into "Compliance management for financial services":   app.pliohub.com/sign-up/cm-financial-services.  The signup URL field doesn't seem to be able to accept certain characters e.g. hyphen character (see below).

![Screenshot 2019-07-04 at 15 38 43](https://user-images.githubusercontent.com/2330529/60674361-e4e1b100-9e71-11e9-8061-146169aa026d.png)

**Comment by michaelrokosh** [comment]
Suggested update:

![image](https://user-images.githubusercontent.com/2095940/61004079-da418300-a36d-11e9-8866-77546241683f.png)

![image](https://user-images.githubusercontent.com/2095940/61004156-ff35f600-a36d-11e9-9b27-3b1b296673cd.png)

@sives @Dartv

**Comment by michaelrokosh** [comment]
In this case we'll need only to rename the field in the "Sign-up URL" in the edit mode and add a read-only field to the card "Template ID".
"Template ID" would be a unique identifier for a template, appended to the sign-up URL.

**Comment by michaelrokosh** [comment]
@sives we should display the name of the template organization under the Plio logo on the sign up-page. No need to add a new field for the custom headline is we can use the name for this purpose. @Dartv

**Comment by sives** [comment]
@michaelrokosh Yes, this is acceptable, no need to add a new field for the custom headline. We can close this issue.
