### ISSUE TITLE
No "Section header" standard type in Org settings

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2075]
In all previous versions of Plio, there has been a pre-set Standards type called "Section header" in the default list of Standards types in Org settings.  This Standard type differs from other Standard types in that it is used solely for displaying section headers in the LHS list view in the Standards screen.  Because of this specific purpose it has no 3-letter abbreviation associated with it.

This feature appears to be missing from the new test version of Plio currently running on the Staging server.  Without this feature, it is not possible to create section headers to break up the different sections in the LHS list view in the Standards screen.

![Screenshot 2019-07-04 at 13 10 59](https://user-images.githubusercontent.com/2330529/60665728-36cc0c00-9e5d-11e9-8bbe-e22df5330964.png)

**Comment by Dartv** [comment]
@sives Standard types are imported from the template organization. If the template organization doesn't have "Section header" standard type, it will not get imported obviously.

**Comment by sives** [comment]
@Dartv I can't just add standard type = "Section header" because it is a hard-wired standard type which doesn't permit 3 letter abbreviations (see example below taken from Southwind org settings).

![Screenshot 2019-07-04 at 15 51 20](https://user-images.githubusercontent.com/2330529/60675170-a3520580-9e73-11e9-8de9-2b4d93c6ca59.png)

**Comment by sives** [comment]
@Dartv OK I understand. I had thought that the Standard type "Section header" was hard-coded, but obviously this is not (or no longer) the case

**Comment by michaelrokosh** [comment]
@sives so can we close it now?

**Comment by sives** [comment]
@michaelrokosh @Dartv See below the desired appearance for Standard type = "Section header" in the Org settings subcard (as taken from the current 0.4.4 system, organisation = Kangaroo Travel)

![Screenshot 2019-07-12 at 13 14 36](https://user-images.githubusercontent.com/2330529/61127442-33f99880-a4a7-11e9-91f5-5e9faabae950.png)

**Comment by Dartv** [comment]
This is working as intended when you create new organization with template that has "Section header" type

**Comment by sives** [comment]
@Dartv Yes, I've looked at this again and it is working as intended.

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 07/15/19 - 07/15/19
Work session total: 0:04:49

Grand total: 0:04:49
