### ISSUE TITLE
Question - should we use org ID for signup URLs?

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2076]
In the current Step 5b requirements document, signup URLs are designed in the following format:

app.pliohub.com/sign-up?type=operations&template=quality-construction

Where "quality-construction" is the Org name of the relevant template used when creating the new organisation.

It would be better to use the Org ID instead of the Org name, because this would allow me to change the template name in the future without having to change any of the signup URL strings on the Plio public web site.  

For example:
app.pliohub.com/sign-up?type=operations&template=CU233
or
app.pliohub.com/sign-up?type=operations&template=233

**Comment by Dartv** [comment]
If you define custom url in "Plio organizations" screen modal the url will not change even if you change organization name

**Comment by sives** [comment]
@Dartv What are the rules for the syntax of this sign-up URL?  Clearly I can't just type anything into this field.  For example, the field will not currently accept hyphen characters (see below).  Also, the URL must link to a valid page. 

![Screenshot 2019-07-04 at 15 51 20](https://user-images.githubusercontent.com/2330529/60710308-4ce3d600-9f0a-11e9-9670-b1ee7a5f1117.png)

**Comment by Dartv** [comment]
@sives it's recommended to only use dashes as separators. Also, you shouldn't pass in "app.pliohub.com/sign-up?template=...", just the template part. So, for the template "Cm financial services" you should pass "cm-financial-services". The cryptic url will still work in this case.

**Comment by Dartv** [comment]
@sives I changed this to show full url in RHS card, so this is easier for you to see

**Comment by sives** [comment]
@Dartv Thank you, now it's much easier to understand and use.  It was quite a lot of work to create all the 12 template organizations on app.pliohub.com, so I'm only going to create a couple of template organizations on staging.pliohub.com for testing purposes.  Hope this is OK, if not let me know.

**Comment by sives** [comment]
@Dartv When editing the signup URL in the Organization card, the field that is currently labelled "Sign-up URL" should be labelled as "Sign-up suffix".  (When the Organization card is in read mode, the field should still be labelled as "Signup URL")

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2080
