### ISSUE TITLE
Missing feature - organization names in LHS dropdown

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2078]
@Dartv There is a requirement in the Step 5b requirements document to create a clearer layout of organization names in the LHS dropdown menu, see Section 4 (copied below.) This feature has not been implemented yet.

4. Ordering on items in home screen LHS dropdown menu

The list of organizations that I have to manage in this dropdown menu is becoming very long, and the template organizations are getting mixed up with the normal organizations.  It is becoming quite hard to use this list, especially since the names of organizations are not ordered alphabetically.

To make the dropdown menu easier to use, we will create a new separate section at the bottom of the dropdown menu options list, just below the "Plio organizations" menu option and just above the software version number section.  Only members of the Plio organization will see this section.

This new section will contain the list of template organizations.  In both sections of the LHS dropdown where organizations are listed, they will be ordered alphabetically by name.

**Comment by michaelrokosh** [comment]
@sives what if we would display this as a separate dropdown?
![image](https://user-images.githubusercontent.com/2095940/61005708-5b4e4980-a371-11e9-83df-036fd1bcafde.png)

**Comment by michaelrokosh** [comment]
As a second option, we could have a nested dropdown.

**Comment by michaelrokosh** [comment]
![image](https://user-images.githubusercontent.com/2095940/61005834-9781aa00-a371-11e9-8edc-8a61981bc241.png)

**Comment by sives** [comment]
@michaelrokosh A nested dropdown of the type you have suggested, using the label "Templates organizations" and positioned at the bottom of an alphabetically-ordered list of organizations would be a good solution.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2079

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 07/12/19 - 07/12/19
Work session total: 1:31:41

Grand total: 1:31:41
