### ISSUE TITLE
[Testlio][Mobile][Risks register] Several windows are opened after tapping for several times on '+Add' button.

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#208]
**Environment:**
Device and OS: Nexus 5X Android 7.0
Testable App version: app.pliohub.com
Network: Wi-Fi
Location: Ukraine
Reproducibility rate: 3/3

**Steps to reproduce:** 
1. Open the 'Risk register'.
2. Tap several times on '+Add' button.

**Expected result:**
Only one window should be opened.

**Actual result:** 
Several windows are opened after tapping on '+Add' button for several times.<p><a href="https://testlio.s3.amazonaws.com/issue%2F145741%2Fa%2F168428da-2068-a9ba-5b16-2e21b8fa6a7f%2Fbad4600c17cba3a12d1bfbd09bd0cee8.mp4">#26941_Vide.mp4</a><br></p>

**Comment by Praxie** [comment]
Fixed in the current release

**Comment by markokruustuk** [comment]
Closed from GitHub
