### ISSUE TITLE
Remove the Sign-up URL field from normal organizations

### ISSUE THREAD

**Issue by michaelrokosh** [Pliohub/Plio#2082]
![image](https://user-images.githubusercontent.com/2095940/61156109-5ae1ba00-a4fb-11e9-9030-2b9ba932e2c0.png)

**Comment by sives** [comment]
@michaelrokosh Yes, we need to remove the Sign-up URL field from the Organization card for all organization types except for the template type.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2086

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 07/18/19 - 07/18/19
Work session total: 0:19:35

Grand total: 0:19:35
