### ISSUE TITLE
Background application - recovery notification

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2084]
When the background application fails, I receive an error notification (as happened this morning at 9am BST London time). However, when the background application is then automatically restarted, the notification of restarting is not being sent out.  The expected behaviour is that an email notification is sent out immediately after successful restarting.

**Comment by michaelrokosh** [comment]
![image](https://user-images.githubusercontent.com/2095940/61369521-f7f47800-a898-11e9-9b6b-47829a757186.png)
It looks like the last recovery notifications was sent from Apr 18

**Comment by michaelrokosh** [comment]
Freshping has been set as a fallback.
