### ISSUE TITLE
Item numbering in Work inbox bug

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2088]
@Dartv The top central dropdown menu in the Work Inbox, showing the different available list views, now contains item numbers.  However, these item numbers only display intermittently.  If you go back to the Home screen, then go into the Work inbox again, these item numbers disappear.    If you then go back to the Home screen and refresh the browser window and then return to the Work inbox, the item numbers come back again.

**Comment by michaelrokosh** [comment]
https://i.gyazo.com/c91aa92dce7fac11d55478db754b72e3.gif

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2090
