### ISSUE TITLE
Root cause analysis completion - gap in workflow

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2089]
Completion of a root cause analysis is not triggering the creation of a work item in the Work Inbox to add corrective or preventative actions.

Organisation: Southwind
As user Bryan Abercrombie, I created a new Nonconformity called 'Test'
I assigned the Root Cause Analysis to a different user, Steve Ives.
As Steve Ives, I then completed the root cause analysis.
As Bryan Abercrombie, I received notification of completion of the root cause analysis (see screenshot below)
However I did not receive notification of the next task in the workflow, to create corrective or preventative actions, and this next task does not appear in the Work Inbox.

The consequence is that users may not notice that a root cause analysis has been completed, and the workflow may fail to progress to the next stage, which is the creation of corrective or preventative actions for that nonconformity.

Expected behaviour:
Completion of a root cause analysis should trigger the creation of a new work item.  The wording of the To do panel in the Work inbox is shown below:

To do
Based on the recently-completed root cause analysis, now add corrective or preventative actions in order to manage this nonconformity.

The nonconformity card should be displayed below this To do item in the Work inbox.

(If this turns out to be a lot of work, a simple stopgap solution would be to just add this extra sentence to the existing email notification displayed below:  "Now add corrective or preventative actions in order to manage this nonconformity.")

![Screenshot 2019-07-22 at 10 01 49](https://user-images.githubusercontent.com/2330529/61624342-55f5d680-ac70-11e9-9f23-0b175830f3b2.png)

**Comment by michaelrokosh** [comment]
@Dartv I guess displaying the the work item for adding actions would be too hard. We should add the sentence "Now add corrective or preventative actions in order to manage this nonconformity." to the message in the email.

Example:
Steve Ives completed root cause analysis of nonconformity NC44 "Test 2". Now add corrective or preventative actions in order to manage this nonconformity.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/2091

**Comment by michaelrokosh** [comment]
![image](https://user-images.githubusercontent.com/2095940/62353588-a0e6d800-b513-11e9-90a1-4e6ee81f2819.png)

**Comment by michaelrokosh** [comment]
![image](https://user-images.githubusercontent.com/2095940/62420134-0f53a380-b696-11e9-9d8c-0bdcc30a6906.png)

@Dartv please add a whitespace between "." and "Now".

**Comment by michaelrokosh** [comment]
![image](https://user-images.githubusercontent.com/2095940/62427518-f3371d00-b6fc-11e9-805f-6b7502f01a7e.png)
