### ISSUE TITLE
[Testlio][Mobile][Compliance Standards] Incorrect message is displayed on search result at searching for valid data and tapping 'return' button.

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#209]
**Environment:**
Device and OS: Nexus 5X Android 7.0
Testable App version: app.pliohub.com
Network: Wi-Fi
Location: Ukraine
Reproducibility rate: 3/3

**Steps to reproduce:** 
1. Open the URL>Sign in.
2. Tap on 'Compliance Standards'.
3. Open the search>Enter valid data - e.g. 'Test'>Tap 'return' button from keyboard
4. When search result is displayed>Scroll down the page>Observe the message.

**Expected result:**
The message ' 9 matching results' should be displayed.

**Actual result:** 
The message '0 matching results' is displayed instead of '9 matching results' after searching for valid data and tapping 'return' button - pay attention that issue is reproducible only after tapping 'return' button from keyboard.<p><a href="https://testlio.s3.amazonaws.com/issue%2F145731%2Fa%2F4c2b4d2b-40a6-80ff-b019-e3c19f92e36f%2F11583cafb714f1ff3331f81db3bb41be.mp4">#26931_Video.mp4</a><br></p>

**Comment by RomanValihura** [comment]
I cannot reproduce it. Counter is updating with some delay, but the value is correct.

**Comment by sives** [comment]
It's a valid bug.  I can reproduce it on my Android 5.0 phone, after searching and tapping on the return button on the virtual keyboard.  It displays the incorrect message "0 matching results"

**Comment by RomanValihura** [comment]
Fixed #315

**Comment by Praxie** [comment]
**v0.2.54**

**Comment by markokruustuk** [comment]
Closed from GitHub
