### ISSUE TITLE
[Testlio][Mobile][Compliance Standards] The search is closed when going back from opened item from search results

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#210]
**Environment:**
Device and OS: Nexus 5X Android 7.0
Testable App version: app.pliohub.com
Network: Wi-Fi
Location: Ukraine
Reproducibility rate: 3/3

**Steps to reproduce:** 
1. Open the URL>Sign in.
2. Tap on 'Compliance standards'>Tap on search text field and enter some valid data.
3. Now open an item from search result.
4. Go back to search, by tapping 'back' button from left top corner.

**Expected result:**
Search should be displayed at going back.

**Actual result:** 
The search is closed at going back from opened item.<p><a href="https://testlio.s3.amazonaws.com/issue/145727/a/3bc31de0-bec7-f522-0523-5cd8ad2697ca/15d0580930d13005b88cc44b27bb852b.mp4">#26927_Video.mp4</a><br></p>

**Comment by RevelsGit** [comment]
Is this really an issue? Wouldn't the user be confused if he goes back and sees only a couple of items instead of all?

**Comment by sives** [comment]
I agree that the user would be confused if he goes back and sees only a few items so let's leave this as it is.  

However, we now seem to be missing the delete symbol at the right hand side of the text box.  

Also, the search icon (the magnifier symbol to the left of the search term) is mis-aligned on Android.  The bottom of the symbol needs to align with the bottom of the adjacent text.

**Comment by Praxie** [comment]
@sives 
>However, we now seem to be missing the delete symbol at the right hand side of the text box.

I see the delete symbol. It's displayed only if the field is active.

@RomanValihura Could you fix the alignment of the search icon on Android?

**Comment by Praxie** [comment]
**0.2.55**

**Comment by sives** [comment]
Search icon is still not correctly aligned on Android (it's fine on iOS).  It needs to be moved down a few pixels so that the bottom of the circle in the icon aligns with the bottom of the search text.

**Comment by sives** [comment]
Notice that the search icon is positioned higher on the Android screen (the portrait image) compared to the iOS screen (the landscape image).  

![screenshot_2016-11-08-20-50-56](https://cloud.githubusercontent.com/assets/2330529/20117125/1e87b47a-a5f7-11e6-87d7-e49999ac657f.png)

![img_0154](https://cloud.githubusercontent.com/assets/2330529/20117131/22d30606-a5f7-11e6-8950-b7552def3648.PNG)

**Comment by Praxie** [comment]
**v0.2.57**

**Comment by RomanValihura** [comment]
On Huawei P8 it looks like
![screenshot_2016-11-09-12-37-58](https://cloud.githubusercontent.com/assets/17511584/20135668/974304fa-a679-11e6-9bb9-de45179b45d0.png)

**Comment by Praxie** [comment]
@sives check if the issue is resolved please.

**Comment by sives** [comment]
OK, it's good enough now!

**Comment by markokruustuk** [comment]
Closed from GitHub
