### ISSUE TITLE
[Testlio][Desktop][Non-conformities] Page loading where slowly and irresponsible when try to upload several files to Other and then delete 1

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#211]
**Environment:**
Device and OS: MacBook Pro Sierra 10.11.5 afari 9.1.1 (11601.6.17)
Testable App version: https://app.pliohub.com/107/standards/
Network: WiFi
Location: UA
Reproducibility rate: 5/5

**Steps to reproduce:** 
1. Log in > Go to Non-conformities > Add or open existing
2. Other Files > Add > Select several files > Upload
3. Delete one uploading file
4. Verify behaviour

**Expected result:**
Site should work without delay/exceptions

**Actual result:**
Site works very slowly, sometimes it freezes for 5 or more seconds

**Note:**
Files weren't so big, each file approximately 5 Mb<p><a href="https://testlio.s3.amazonaws.com/issue%2F145720%2Fa%2F27dab2af-0fbd-016f-f48d-8cc54648ed1b%2Fa79efc8eada6c20358d6f8a16510488a.mp4">Delete Others.mp4</a><br></p>

**Comment by Praxie** [comment]
Fixed in the current release

**Comment by markokruustuk** [comment]
Closed from GitHub
