### ISSUE TITLE
[Testlio][Mobile][Compliance Standards] By tapping 'back' button from 'Add' window - the page from background of 'Add' window is changed, but the window is still displayed.

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#212]
**Environment:**
Device and OS: Nexus 5X Android 7.0
Testable App version: app.pliohub.com 
Network: Wi-Fi
Location: Ukraine 
Reproducibility rate: 3/3

**Steps to reproduce:** 
1. Open the URL>Sign in.
2. Tap on 'Compliance Standards'>'+ Add'.
3. When 'Add' window is opened>Tap device 'back' button.

**Expected result:**
The opened 'Add' window should be closed and user should be returned to previous 'Compliance Standards' page.

**Actual result:** 
At tapping 'back' button, the page from background of 'Add' window is changed, but the window is still displayed.<p><a href="https://testlio.s3.amazonaws.com/issue%2F145716%2Fa%2Fe982ca50-6742-2142-0322-395a0b55e043%2Fba541e62a4a19857b8eca3f6a95a3787.mp4">#26916_Video.mp4</a><br></p>

**Comment by Praxie** [comment]
**v0.2.47** fix

**Comment by markokruustuk** [comment]
Closed from GitHub
