### ISSUE TITLE
[Testlio][Desktop][Work Inbox] User can create two preventive/corrective actions with same name

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#213]
**Environment:**
Device and OS:Windows 8.1 Chrome 53
Testable App version: https://app.pliohub.com/107/work-inbox/QHxuPDq9GT9SQQL5J?filter=1
Network: WiFi
Location: Romania
Reproducibility rate: 5/5
Account: cellqa2014@gmail.com/Aa28101984!!

**Steps to reproduce:** 
1. Log in with mentioned user and go to Work Inbox
2. Click Add and choose Corrective action and then create one with name "m"
3. Try to create another one with same name 

**Expected result:**
User is not able to create second corrective action with same name as for first one

**Actual result:** 
User is  able to create second corrective action with same name as for first one

No issues on console logs
<p><a href="https://testlio.s3.amazonaws.com/issue/145666/a/f92d572b-c6e9-900b-0377-2ff9b4f7bd55/f25b8664262d4a23768c41eb9c9220ec.mp4">#26866.mp4</a><br></p>

**Comment by sives** [comment]
It's fine to create multiple CAs or PAs with same name, so long as they have unique numbers

**Comment by markokruustuk** [comment]
Closed from GitHub
