### ISSUE TITLE
[Testlio][Desktop][Risk Register] Long risk name is not displayed properly

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#214]
**Environment:**
Device and OS:Windows 8.1 Chrome Latest 
Testable App version: https://app.pliohub.com/107/risks/zwgeLvKjCsAsGACGo?filter=1
Network: WiFi
Location: Romania
Reproducibility rate: 5/5
Account: cellqa2014@gmail.com/Aa28101984!!

**Steps to reproduce:** 
1. Log in with mentioned user and go to Risk Register
2. Select Major riskkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk then click Edit
3. Scroll to Corrective actions and expand the only corrective action displayed
4. Check if risk name is properly displayed 

**Expected result:**
Long risk name is  displayed properly

**Actual result:** 
Long risk name is not displayed properly, it's going out of the overlay 
<p><a href="https://testlio.s3.amazonaws.com/issue/145660/a/1bda1aa3-19fc-4718-392a-93c19ea0800c/a5470149fcbabb68775dd08e79423724.mp4">#26860.mp4</a><br></p>

**Comment by Praxie** [comment]
**v0.2.45** fix

**Comment by markokruustuk** [comment]
Closed from GitHub
