### ISSUE TITLE
[Testlio][Desktop][Forgot password] Empty screen is opened after resetting a password

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#215]
**Environment:**
Device and OS: Windows 10; Microsoft Edge 38.14393.0.0
Testable App version: https://app.pliohub.com v0.2.37
Network: WiFi
Location: Ukraine
Reproducibility rate: 5/5

**Steps to reproduce:** 
1. Log in > Forgot Password
2. Input existing email> Send
3. Go to email inbox > Open received email > Click the 'Reset Password'
4. Input new password > Confirm > Set Password

**Expected result:**
Content is displayed in the screen after resetting password

**Actual result:** 
Empty screen is opened after resetting a password.
After clicking 'Login' a user is redirected to the main page of the app<p><a href="https://testlio.s3.amazonaws.com/issue/145622/a/cf1c142b-6817-1940-e959-957ad04b3675/38e6f118347403ad4cb63453315fd778.mp4">emty1.mp4</a><br></p>

**Comment by Praxie** [comment]
Fixed in **v0.2.46**

**Comment by markokruustuk** [comment]
Closed from GitHub
