### ISSUE TITLE
[Testlio][Desktop][Edit User] ' "" is not a valid phone number ' error shown after selecting type phone number in the 'Contact details'

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#216]
**Environment:**
Device and OS: Windows 10; Microsoft Edge 38.14393.0.0
Testable App version: https://app.pliohub.com v0.2.37
Network: WiFi
Location: Ukraine
Reproducibility rate: 5/5

**Steps to reproduce:** 
1. My profile > Edit
2. Contact details > Click the 'Add another phone number'
3. Select 'Home' type from the drop down > Scroll up the screen

**Expected result:**
Nothing happens until phone number be inputted. 

**Actual result:** 
' "" is not a valid phone number ' error shown after selecting type phone number in the 'Contact details'<p><img src="https://testlio.s3.amazonaws.com/issue/145619/a/2cfa6301-3a7f-7aed-6f28-96ac51a79431-medium.jpg"/><br><a href="https://testlio.s3.amazonaws.com/issue/145619/a/b85168cb-6873-2358-6f96-f7b17228c9c1/ff5dbfea45110864be2b6d5d1e376ff2.mp4">error_phone_number.mp4</a><br></p>

**Comment by RomanValihura** [comment]
Fixed in commit https://github.com/Pliohub/Plio/commit/2d061591484152d1151a4b78cbd5b81ea65befdc

**Comment by RomanValihura** [comment]
Pull request https://github.com/Pliohub/Plio/pull/261

**Comment by Praxie** [comment]
**v0.2.50**

**Comment by markokruustuk** [comment]
Closed from GitHub
