### ISSUE TITLE
[Testlio][Desktop][Organization settings] Unable to delete text from the Guidelines fields of the 'Non-conformity guidelines' section

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#217]
**Environment:**
Device and OS: Windows 10; Microsoft Edge 38.14393.0.0
Testable App version: https://app.pliohub.com v0.2.37
Network: WiFi
Location: Ukraine
Reproducibility rate: 5/5

**Steps to reproduce:** 
1. Go to 'Organization settings' >   'Non-conformity guidelines' section
2. Input some text into  Guidelines fields > Close settings
3. Open  'Organization settings'  again > 'Non-conformity guidelines' section
4. Delete text from each  Guidelines fields > Reopen settings

**Expected result:**
Deleted text is not displayed anymore

**Actual result:** 
Unable to delete text from the Guidelines fields of the 'Non-conformity guidelines' section. After reopening settings deleted text remains. <p><a href="https://testlio.s3.amazonaws.com/issue/145612/a/753a8570-b80b-935f-a236-96868289c485/7a6ffb13683b8620f88872e8a4dba9a8.mp4">deleted_not_deleted.mp4</a><br></p>

**Comment by Praxie** [comment]
Fixed in **v0.2.47**

**Comment by markokruustuk** [comment]
Closed from GitHub
