### ISSUE TITLE
[Testlio][Desktop][Work inbox] Two vertical scroll bars appear after clicking 'Expand' button in the 'Notes' section of the 'Corrective action' pop up 

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#219]
**Environment:**
Device and OS: Windows 10; Microsoft Edge 38.14393.0.0
Testable App version: https://app.pliohub.com v0.2.37
Network: WiFi
Location: Ukraine
Reproducibility rate: 5/5

**Steps to reproduce:** 
1. Work inbox > Add CA
2. Edit mode > Notes > Click the 'Expand' button

**Expected result:**
One scroll bar is present when it needed. 

**Actual result:** 
Two vertical scroll bars appear after clicking 'Expand' button in the 'Notes' section of the 'Corrective action' pop up. 
<p><img src="https://testlio.s3.amazonaws.com/issue/145601/a/df362cd0-7b2d-8a79-b333-d482aaaceb7e-medium.jpg"/><br><a href="https://testlio.s3.amazonaws.com/issue/145601/a/c7fa2c71-aff3-f93c-4443-d1dc28bbd3bf/3180d3188240200757fa93557e0122c6.mp4">vertical_scroll_bar.mp4</a><br></p>

**Comment by Praxie** [comment]
**v0.2.47** fix

**Comment by markokruustuk** [comment]
Closed from GitHub
