### ISSUE TITLE
[Testlio][Corrective action]Tooltip doesn't appear hovering over 'Expand' button in the 'Notes' 

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#220]
**Environment:**
Device and OS: Windows 10; Microsoft Edge 38.14393.0.0
Testable App version: https://app.pliohub.com v0.2.37
Network: WiFi
Location: Ukraine
Reproducibility rate: 5/5

**Steps to reproduce:** 
1. Go to 'Work inbox' > Add Corrective action
2. Edit mode > Notes > Hover the  'Expand' button 

**Expected result:**
Tooltip is shown hovering the 'Expand' button

**Actual result:** 
Tooltip doesn't appear hovering over 'Expand' button in the 'Notes'  
<p><a href="https://testlio.s3.amazonaws.com/issue/145599/a/e2e47637-9861-f3da-a9de-f7b3d5461d19/040e240dab44bc2ed00bd0f9d91178a7.mp4">expand.mp4</a><br></p>

**Comment by Praxie** [comment]
Fixed in **v0.2.46**

**Comment by markokruustuk** [comment]
Closed from GitHub
