### ISSUE TITLE
[Testlio][Desktop][User Directory] Cannot clear search field by [X] icon from first attempt

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#221]
**Environment:**
Device and OS: MacBook Pro Sierra 10.12 | Firefox 49.0.1
Testable App version: https://app.pliohub.com/107/work-inbox/
Network: WiFi
Location: UA
Reproducibility rate: 4/4

**Steps to reproduce:** 
1. User directory 
2. Search field > Type some name > Click [X] icon

**Expected result:**
Search query deleted

**Actual result:** 
Search query deleted and appears again immediately 
Need to delete twice<p><a href="https://testlio.s3.amazonaws.com/issue/145586/a/5cc06973-d5b8-0813-935c-117e0c761c83/8a85f7676c8ba3eaaa3f11f4dda59f7e.mp4">del_search.mp4</a><br></p>

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/283

**Comment by RevelsGit** [comment]
Also refactored page and list components to fit other screens code.

**Comment by Praxie** [comment]
**v0.2.50**

**Comment by Praxie** [comment]
@RevelsGit 👍

**Comment by markokruustuk** [comment]
Closed from GitHub
