### ISSUE TITLE
[Testlio][Desktop][Corrective action] Corrective actions and preventative actions are not saved

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#222]
**Environment:**
Device and OS: MacBook Pro Sierra 10.11.5 afari 9.1.1 (11601.6.17)
Testable App version: https://app.pliohub.com/107/standards/
Network: WiFi
Location: UA
Reproducibility rate: 5/5

**Steps to reproduce:** 
1. Log in > Go to Compliance standard > Add
2. Fill in some name > Save
3. Click Corrective actions or preventative actions
4. Fill in valid title > click Save
5. Verify behaviour

**Expected result:**
Corrective action and/or Preventative actions should be saved and should be shown somewhere

**Actual result:**
Corrective action and/or Preventative actions became empty after clicking Save button<p><a href="https://testlio.s3.amazonaws.com/issue%2F145585%2Fa%2F0a3e59cb-6018-6d7d-7aa3-242185ef75be%2Fe2f3991e8a6767b0eaa83f3493803049.mp4">Corrective actions.mp4</a><br></p>

**Comment by Praxie** [comment]
@sives It's not a bug. The user needs to select a NC/RK that is linked to the selected standard. ("Linked to" CA/PA field)
This behaviour appeared after we decided to make a "Linked to" field not mandatory.

**Comment by Praxie** [comment]
@sives We can remove the option of creating new actions from the Compliance Standard card.

**Comment by sives** [comment]
Can it be linked to a Standard document instead of a NC when a CA or PA is added from this screen?  Or does the database structure not allow this?   (As a user, if I added a CA or PA in this screen, I might expect it to be linked to the currently-selected Standard document)

**Comment by sives** [comment]
If this is not possible then I would agree that removing the ability to add CAs or PAs in this screen would be the logical way forward.

**Comment by Praxie** [comment]
@sives The CA or PA cannot be linked to a Standard document.

**Comment by sives** [comment]
We agreed to remove the "Add a corrective action" and "Add a preventative action" buttons

**Comment by Praxie** [comment]
@RevelsGit remove the "Add a corrective action" and "Add a preventative action" buttons from the Standard card.
After this I guess that we don't need to subscribe to all Risk/NC documents in the Standard card. (List subscription will be no longer needed)

**Comment by RevelsGit** [comment]
@Praxie We still need to subscribe to all ncs/risks because you can edit action's `linked to` field.

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/273

**Comment by Praxie** [comment]
**v0.2.51**

**Comment by markokruustuk** [comment]
Closed from GitHub

**Comment by markokruustuk** [comment]
Reopened from GitHub

**Comment by sives** [comment]
Where the "Add a corrective action" and "Add a preventative action" buttons used to be, we should display the following text  "To add an action here, first add it to the relevant non-conformity or risk".

**Comment by Praxie** [comment]
@sives - is it necessary to duplicate this message. Maybe it's enough to put it in place where the "Add new action" button is usually displayed.
![screen shot 2016-11-07 at 2 56 02 pm](https://cloud.githubusercontent.com/assets/2095940/20058571/573e2da6-a4fa-11e6-89cd-50e4b97a7704.png)

**Comment by sives** [comment]
Yes, this is a good way to do it

**Comment by Praxie** [comment]
**v0.2.54**

**Comment by sives** [comment]
Sorry Mike - can we change the text to "To add a corrective action, first add it to a non-conformity or risk record"  and for the preventative action case "To add a preventative action, first add it to a non-conformity or risk record"

**Comment by Praxie** [comment]
**v0.2.56**

**Comment by sives** [comment]
Sorry Mike, I'm not doing very well with this one, it's still not clear.  Can we change the text to:  "To add a corrective action, go to either the Non-conformities or Risks screen and add it to a Non-conformity or Risk record first"   and "To add a preventative action, go to either the Non-conformities or Risks screen and add it to a Non-conformity or Risk record first"

**Comment by Praxie** [comment]
@sives no problem.
**v0.2.57**

**Comment by sives** [comment]
All good now.

**Comment by markokruustuk** [comment]
Closed from GitHub
