### ISSUE TITLE
[Testlio][Desktop][User Directory] Cannot edit user superpowers for the first time

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#223]
**Environment:**
Device and OS: MacBook Pro Sierra 10.12 | Firefox 49.0.1
Testable App version: https://app.pliohub.com/107/work-inbox/
Network: WiFi
Location: UA
Reproducibility rate: 3/3
 
**Steps to reproduce:** 
1. My profile > Edit 
2. Superpowers > Try to edit

**Expected result:**
Can edit user superpowers

**Actual result:** 
Cannot edit user superpowers 

**NOTE:** after opening Superpowers section for the first time I was able to edit it (to uncheck/check)<p><a href="https://testlio.s3.amazonaws.com/issue/145582/a/d81c4753-528a-c322-9e32-bcc7d5a75bce/cd72272d325448e737f23a712d847b24.mp4">own_user_superpowers.mp4</a><br></p>

**Comment by markokruustuk** [comment]
the same trying to edit the user superpowers:
STR:
1. User Directory &gt; Edit 
2. Superpowers &gt; Try to edit<p><img src="https://testlio.s3.amazonaws.com/issue/145582/ca/64644-medium.jpg"/><br><a href="https://testlio.s3.amazonaws.com/issue/145582/ca/64645/dee283fc3e8cdb81083f40547c6cc111.mp4">user_superpowers.mp4</a><br></p>

**Comment by sives** [comment]
Add this line of text whenever superpowers are shown inactive in grey:
"These superpowers can only be edited by an administrator"

**Comment by Praxie** [comment]
**v0.2.50**

**Comment by markokruustuk** [comment]
Closed from GitHub
