### ISSUE TITLE
[Testlio][Desktop][Compliance standard] Can't delete video without replacement to new file when open existing standard

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#224]
**Environment:**
Device and OS: MacBook Pro Sierra 10.11.5 afari 9.1.1 (11601.6.17)
Testable App version: https://app.pliohub.com/107/standards/
Network: WiFi
Location: UA
Reproducibility rate: 5/5

**Steps to reproduce:** 
1. Log in > Go to Compliance standard > Add
2. Fill in some name > Save
3. Click on Source file > Video 
4. Fill in valid youtube link > Close
5. Open created standard > edit > Erase link in video or change Source file to attachment or URL link (don't add link or file)
6. Click Close

**Expected result:**
User should be able to delete video without replacement

**Actual result:**
Video file can't be deleted without replacement to new file<p><a href="https://testlio.s3.amazonaws.com/issue/145579/a/6e23c3c8-ddd1-0c0b-1656-e423c06ea1f5/79dfe6c80f402dee64ad86cf9db40d7d.mp4">Can't delete video.mp4</a><br></p>

**Comment by Praxie** [comment]
@meyginix we need to delete the source file if the url string is deleted completely. It should work this way for both Video and Url link fields

**Comment by Praxie** [comment]
**v0.2.50**

**Comment by markokruustuk** [comment]
Closed from GitHub
