### ISSUE TITLE
[Testlio][Desktop][Compliance standard] There is no verification in link for video during adding new standard

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#225]
**Environment:**
Device and OS: MacBook Pro Sierra 10.11.5 afari 9.1.1 (11601.6.17)
Testable App version: https://app.pliohub.com/107/standards/
Network: WiFi
Location: UA
Reproducibility rate: 5/5

**Steps to reproduce:** 
1. Log in > Go to Compliance standard > Add
2. Fill in some name > Save
3. Click on Video like Source file and fill in some non video link

**Expected result:**
Only video files should be accepted

**Actual result:** 
Any link can be inserted and then opened. See attached video<p><a href="https://testlio.s3.amazonaws.com/issue%2F145578%2Fa%2F64b5c97f-fbd4-b968-b57d-a02a0b620e39%2F10ceb45f32fb77f5dbfa2db5cb6ab83e.mp4">Video.mp4</a><br></p>

**Comment by sives** [comment]
If it is possible to easily check this is a video link, then we should check for it.  Otherwise, don't worry about this issue.  User will soon find out they have done it incorrectly, and fix it.

**Comment by Praxie** [comment]
@sives there's no elegant long-term solution for this. I'll put this issue on hold.

**Comment by sives** [comment]
I took it out of Step 2c

**Comment by markokruustuk** [comment]
Closed from GitHub
