### ISSUE TITLE
[Testlio][Desktop][Compliance standard] It's possible to create document with the same title

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#226]
**Environment:**
Device and OS: MacBook Pro Sierra 10.11.5 afari 9.1.1 (11601.6.17)
Testable App version: https://app.pliohub.com/107/standards/
Network: WiFi
Location: UA
Reproducibility rate: 5/5

**Steps to reproduce:** 
1. Log in > Go to Compliance standard > Add
2. Fill in some name > Confirm adding
3. Click Add again > Fill in name like in step 2 > Try to finalize adding

**Expected result:**
User shouldn't be able to create file with the same title

**Actual result:**
User can create file with the same name<p><a href="https://testlio.s3.amazonaws.com/issue/145576/a/763fca55-52d2-dc12-0074-052922a5f47e/001ead3b0ebcc794ae9dd885356bb379.mp4">Issue 1.mp4</a><br></p>

**Comment by sives** [comment]
It's fine to create documents with the same title, this may sometimes happen e.g. Title = Introduction might be in more than one document.   When we add unique numbers to Standards in Step 3a, this becomes even less of an issue.

**Comment by markokruustuk** [comment]
Closed from GitHub
