### ISSUE TITLE
[Testlio][Desktop][Compliance standard] XSS vulnerability through adding 'department' with script in the name

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#227]
**Environment:**
Device and OS: Apple Mac El Capitan 10.11.6 Chrome Version 53.0.2785.143 (64-bit)
Testable App version: https://app.pliohub.com v0.2.36
Network: Ethernet
Location: Ukraine
Reproducibility rate: 3/3

**Steps to reproduce:** 
1. Enter Compliance standards > add
2. Type any name > save
3. Click into department/sector field > paste <script>alert('dept');</script> > click to add new department > close
4. Again click to add new Compliance standard > any title > save > observe JS alert

**Expected result:**
All tags should be escaped 

**Actual result:** 
XSS vulnerability, script in the name of new department executes when adding new Compliance standard<p><a href="https://testlio.s3.amazonaws.com/issue/145571/a/a04bcb46-39eb-af75-0815-7478cfba68b2/22ee2bc266fe803c12f40299baa9668b.mp4">Screen Capture Tool Pro_2016-10-11 17.57.46.mp4</a><br></p>

**Comment by sives** [comment]
It doesn't execute the script any more but it still lets me add the script into the Department/sector field.  Perhaps it would be better to do flag up to the user at the time of entering this text string that it certain characters are not permitted?

**Comment by markokruustuk** [comment]
Closed from GitHub
