### ISSUE TITLE
[Testlio][Mobile][Risk register] Red label appears everywhere in the webpage after getting any alert. 

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#228]
**Environment:**
Device and OS:iPhone6S iOS 10.0.2
Testable App version:https://app.pliohub.com v0.2.36
Network:WiFi
Location:Bangladesh
Reproducibility rate: 3/3 (Not sure when alert appears, but if alert appears, issue is reproducible always)
Account: azadnsu@gmail.com/Tester1234

**Steps to reproduce:** 
1. Login to the web.
2. Risk > Add
3. Enter all required fields> Add
4. Suddenly an alert will show> Close and observe full page.

**Expected result:**
Page should remain same in color.

**Actual result:** 
Full webpage becomes red.<p><a href="https://testlio.s3.amazonaws.com/issue/145569/a/539f449f-9948-56cd-49f9-36e300371818/9694b9298892920b71125410b0921d5c.txt">26769_Log.txt</a><br><a href="https://testlio.s3.amazonaws.com/issue/145569/a/c837d0a6-12a6-88b7-fbfd-6cee2215e23a/a42164c40e43e6eaf8bacca21155bd67.mp4">26769_Video.mp4</a><br></p>

**Comment by Praxie** [comment]
@markokruustuk @sives I can't reproduce this issue. It's the first time that I see these alerts. Perhaps, @markokruustuk found a XSS vulnerability by adding a script html into some risk title.

**Comment by sives** [comment]
I"m getting a different error when I try to add a new Risk.

I fill in the Risk name and then link to a Standard, then click on Save.   I get the error message: "Reviewed at is not a valid date"  (which is a bit of a strange error message)

**Comment by Praxie** [comment]
**v0.2.54**

**Comment by markokruustuk** [comment]
Closed from GitHub
