### ISSUE TITLE
[Testlio][Desktop][Corrective action] note's expanded reach editor has sticked toolbar, so it's not available when editing a lot of lines of text

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#229]
**Environment:**
Device and OS: Apple Mac El Capitan 10.11.6 Chrome Version 53.0.2785.143 (64-bit)
Testable App version: https://app.pliohub.com v0.2.36
Network: Ethernet
Location: Ukraine
Reproducibility rate: 3/3

**Steps to reproduce:** 
1. Go to Work inbox 
2. Add > Corrective action > add any
3. Enter Notes editor > enter expanded view
4. Enter a lot of lines of text, so scroll should appear
5. Scroll to the end of typed text > observe editor toolbar is not available 

**Expected result:**
Toolbar should be always available 

**Actual result:** 
Note's expanded reach editor has sticked toolbar, so it's not available when editing a lot of lines of text<p><a href="https://testlio.s3.amazonaws.com/issue/145564/a/28c7742f-94fd-0b8d-0b41-99d7194a3ca4/ec090c4912f3c8975bc6d6d97e0d498d.mp4">Screen Capture Tool Pro_2016-10-11 17.34.00.mp4</a><br></p>

**Comment by Praxie** [comment]
Fixed in **v0.2.47**

**Comment by markokruustuk** [comment]
Closed from GitHub
