### ISSUE TITLE
[Testlio][Desktop][Profile] wide landscape photo appears shifted and cropped when uploading as user avatar

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#230]
**Environment:**
Device and OS: Apple Mac El Capitan 10.11.6 Chrome Version 53.0.2785.143 (64-bit)
Testable App version: https://app.pliohub.com v0.2.36
Network: Ethernet
Location: Ukraine
Reproducibility rate: 3/3

**Steps to reproduce:** 
1. Account menu > my profile > edit
2. Upload wide landscape photo (attached) 

**Expected result:**
Photo should be centred 

**Actual result:** 
Wide landscape photo appears shifted to the top and cropped when uploading as user avatar<p><a href="https://testlio.s3.amazonaws.com/issue/145561/a/cb048533-c83f-07ce-7e9f-96f07631c1de/90e48c4997d737d62d858ea02164c768.mp4">Screen Capture Tool Pro_2016-10-11 17.21.23.mp4</a><br><img src="https://testlio.s3.amazonaws.com/issue/145561/a/2c673ba2-83e6-cc23-01e7-e9c974751eb3-medium.jpg"/><br></p>

**Comment by Praxie** [comment]
**v0.2.46** Fix

**Comment by markokruustuk** [comment]
Closed from GitHub
