### ISSUE TITLE
[Testlio][Desktop][Work Inbox] No possibility to remove single 'Linked to' option

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#231]
**Environment:**
Device and OS: MacBook Pro Sierra 10.12 | Firefox 49.0.1
Testable App version: https://app.pliohub.com/107/work-inbox/
Network: WiFi
Location: UA
Reproducibility rate: always

**Steps to reproduce:** 
1. Work Inbox 
2. Add > Corrective action > Save without 'Linked to' option
3. Edit created item > Add 2 'Linked to' options 
4. Try to remove all 'Linked to' options

**Expected result:**
Possibility to remove single 'Linked to' option

**Actual result:** 
No possibility to remove single 'Linked to' option

**Note:** 
1. Possible to create without 'Linked to' option
2. No logs generated during reproducing<p><a href="https://testlio.s3.amazonaws.com/issue/145556/a/e3d04472-8708-f8be-6483-e8aa71f23ba8/57830878a65e3cf47a5b4c8f8614f5ca.mp4">linked_to.mp4</a><br></p>

**Comment by sives** [comment]
Answer to question: It should be possible to create a CA or PA action with linking to anything, which is how the system is currently working.  But we do need to fix the bug that you can't remove a single Linked to option.

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/272

**Comment by Praxie** [comment]
**v0.2.51**

**Comment by markokruustuk** [comment]
Closed from GitHub
