### ISSUE TITLE
[Testlio][Desktop][User Directory] user list twitches while changing user's superpowers

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#232]
**Environment:**
Device and OS: Apple Mac El Capitan 10.11.6 Chrome Version 53.0.2785.143 (64-bit)
Testable App version: https://app.pliohub.com v0.2.36
Network: Ethernet
Location: Ukraine
Reproducibility rate: 3/3

**Steps to reproduce:** 
1. Enter User Directory
2. Select any user > edit
3. Expand superpowers > start changing values one by one > observe user list twitches

**Expected result:**
User list should stay stable

**Actual result:** 
User list twitches while changing user's superpowers<p><a href="https://testlio.s3.amazonaws.com/issue/145555/a/780ec2e0-3092-8302-6ebc-6434042875a2/854e5bfeda4af5b62c989ba029ee7ae5.mp4">Screen Capture Tool Pro_2016-10-11 17.12.52.mp4</a><br></p>

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/265

**Comment by Praxie** [comment]
**v0.2.48**

**Comment by markokruustuk** [comment]
Closed from GitHub
