### ISSUE TITLE
[Testlio][Desktop][Profile] first click on Close doesn't close pop-up

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#233]
**Environment:**
Device and OS: Apple Mac El Capitan 10.11.6 Chrome Version 53.0.2785.143 (64-bit)
Testable App version: https://app.pliohub.com v0.2.36
Network: Ethernet
Location: Ukraine
Reproducibility rate: 3/3

**Steps to reproduce:** 
1. Account menu > My profile
2. Edit > observe pop-up
3. Click into first name > edit > click into last name > edit
4. Click close > observe saving, pop-up is not closed

**Expected result:**
Click on close should close pop-up

**Actual result:** 
First click on Close doesn't close pop-up<p><a href="https://testlio.s3.amazonaws.com/issue/145553/a/4a067ccb-f2cd-c370-edbe-d71aa735e0f5/b0d66746a320697c4b0077d1376c70de.mp4">Screen Capture Tool Pro_2016-10-11 17.08.48.mp4</a><br></p>

**Comment by RomanValihura** [comment]
I cannot reproduce the problem. My environment is the same.

**Comment by RevelsGit** [comment]
I can reproduce this

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/284

**Comment by Praxie** [comment]
**v0.2.50**

**Comment by markokruustuk** [comment]
Closed from GitHub
