### ISSUE TITLE
[Testlio][Desktop][Risk] Possible to set Last reviewed date in the future

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#234]
**Environment:**
Device and OS: Windows 10, Firefox 47.0.1
Testable App version:https://app.pliohub.com
Network: Wifi
Location: Cz
Reproducibility rate: 3/5

**Steps to reproduce:** 
1. Go to Risks tab
2. Create or Edit risk
3. Scroll down and expand Review section
4. Set date in the future and click Close
5. Observe restul

**Expected result:**
User should be able to set last reviewed in the future

**Actual result:** 
Possible to set Last reviewed date in the future<p><a href="https://testlio.s3.amazonaws.com/issue/145549/a/0f20e433-dc30-c539-55fd-6439d33d563e/4102fab63cff9cd1759b4387e085165f.mp4">2016-10-11 19h24_13.mp4</a><br><img src="https://testlio.s3.amazonaws.com/issue/145549/a/dd410183-3557-4c54-b68b-57f63490ccd3-medium.jpg"/><br></p>

**Comment by Praxie** [comment]
@sives Review subcard is not fully implemented yet.

**Comment by sives** [comment]
That's true, but the simple subcard that exists at the moment should implement the basics of field level validation, in particular a date that is intended to be in the past should not be able to be set in the future.  However, I'm happy to mark this forward to Step 3a.

**Comment by Praxie** [comment]
This bug if fixed in **v0.2.51**

**Comment by markokruustuk** [comment]
Closed from GitHub
