### ISSUE TITLE
[Testlio][Mobile][Compliance standard] Plus button hides on entering a long department name.

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#235]
**Environment:**
Device and OS:iPhone6S iOS 10.0.2
Testable App version:https://app.pliohub.com v0.2.36
Network:WiFi
Location:Bangladesh
Reproducibility rate: 3/3

**Steps to reproduce:** 
1. Login to web.
2. Compliance standards> Add
3. Enter title and all other fields. 
4. Save
5. Tap on Department/sector(s)
6. Type something new> Observe, Plus button visible.
7. Continue typing and observe Plus button hides when text becomes long.

**Expected result:**
Plus button should remain visible till app support typing long text.

**Actual result:** 
Plus button goes away and hides. User can't tap that. <p><img src="https://testlio.s3.amazonaws.com/issue/145546/a/35e5f3b7-58cb-c9d5-50b0-131112425b6e-medium.jpg"/><br><a href="https://testlio.s3.amazonaws.com/issue/145546/a/ce4fd8bc-6e46-fea1-2fc5-b319cdb29e75/ee93a8a0688d017074b7c187d244c034.mp4">26746_Video.mp4</a><br></p>

**Comment by sives** [comment]
Put the Plus button to the left hand side of its text label, instead of to the right hand side, in both mobile and desktop.

**Comment by Praxie** [comment]
**v0.2.51**
