### ISSUE TITLE
[Testlio][Mobile][Compliance standard] Page title overlapped with help icon.

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#238]
**Environment:**
Device and OS:iPhone6S iOS 10.0.2
Testable App version:https://app.pliohub.com v0.2.36
Network:WiFi
Location:Bangladesh
Reproducibility rate: 3/3

**Steps to reproduce:** 
1. Login to web. 
2. Compliance standards> Add
3. Observe page title.

**Expected result:**
Page title should not be overlapped.

**Actual result:** 
Page title overlapped with question icon. <p><a href="https://testlio.s3.amazonaws.com/issue/145539/a/48440677-392a-090d-95ad-162c79c36342/dbbdfd73db96e12b9dfa30610e45b1db.txt">26739_Log.txt</a><br><img src="https://testlio.s3.amazonaws.com/issue/145539/a/b0531cec-a02c-63b8-c052-efa53e7e1cb7-medium.jpg"/><br><a href="https://testlio.s3.amazonaws.com/issue/145539/a/e77c5f06-31b8-b3c4-29e9-ec51a52b2074/7fbcc03802c924f0799047fce2a7d434.mp4">26739_Video.mp4</a><br></p>

**Comment by markokruustuk** [comment]
#26934 [Non-Conformity] The '?' icon and title of opened window 'Non-conformity' are displayed on each other while saving loading is displayed.
Feature: Non-conformities screen
Environment:
Device and OS: Nexus 5X Android 7.0
Testable App version: app.pliohub.com
Network: Wi-Fi
Location: Ukraine
Reproducibility rate: 3/3

Steps to reproduce:
1. Open the URL&gt;Sign in.
2. Select 'Non-Conformity'&gt;Tap '+Add' button.
3. Enter the title and select at least one standard.
4. Tap 'Save' button and while 'Saving..' loading is displayed&gt;Observe the '?' icon and title of opened window 'Non-conformity'.

Expected result:
Everything should be displayed correctly.

Actual result:
The '?' icon and title of window 'Non-conformity' are displayed on each other while 'Saving' loading is displayed.<p><a href="https://testlio.s3.amazonaws.com/issue/145539/ca/64750/d7334f3f53decf54f2b878e0d4f26d6b.mp4">#26934_Video.mp4</a><br><img src="https://testlio.s3.amazonaws.com/issue/145539/ca/64751-medium.jpg"/><br></p>

**Comment by sives** [comment]
Change all instances of the phrase "Compliance standards" to "Standards" except for the icon panel label in the Home screen

**Comment by Praxie** [comment]
@sives What about Non-conformities card? Do we need to add an ellipsis if the work is too long?
('Non-confor...')

**Comment by sives** [comment]
It would be good to abbreviate it to just "NC" if the word is too long to fit (I'm not sure if this solution is easy to implement, if not then go with your suggestion)

**Comment by Praxie** [comment]
@sives I'm sure that we will face the similar issues in future. It's simple to implement my suggestion, by the way.

**Comment by sives** [comment]
OK, let's go with your suggestion

**Comment by Praxie** [comment]
@RomanValihura 
overflow: hidden;
text-overflow: ellipsis;

**Comment by Praxie** [comment]
**v0.2.50**

**Comment by markokruustuk** [comment]
Closed from GitHub
