### ISSUE TITLE
[Testlio][Desktop][Compliance Standard] Attachment button is non-functional in discussion in IE 11

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#240]
**Environment:**
Device and OS: Lenovo G50 Windows 10
Browser: IE 11
Testable App version: app.pliohub.com/sign-up
Network: Wifi
Location: Pakistan
Reproducibility rate: 5/5
URL: https://app.pliohub.com/107/standards/GZGHPyy5Q4tSGzBWE/discussion?filter=1

**Steps to reproduce:** 
1. Open the URL and sign in
2. Click on compliance standards
3. Click on any document and click on discuss button present on right hand side
4. Click on attachment icon
5. Observe

**Expected result:**
User should be able to add attachment

**Actual result:** 
Nothing happens. Attachment button is non-functional in IE 11<p><a href="https://testlio.s3.amazonaws.com/issue/145528/a/ca87b9a9-82b9-9082-2972-66ebb74ada05/f5291e4c402ea4c16c82a462ea764cf7.mp4">2016-10-11 17h21_24.mp4</a><br></p>

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/274

**Comment by Praxie** [comment]
**v0.2.50**

**Comment by markokruustuk** [comment]
Closed from GitHub
