### ISSUE TITLE
[Testlio][Desktop][Compliance Standard] Nothing happens when user clicks on remove on someone else's attachment

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#241]
**Environment:**
Device and OS: Lenovo G50 Windows 10
Browser: IE 11, Chrome 53
Testable App version: app.pliohub.com/sign-up
Network: Wifi
Location: Pakistan
Reproducibility rate: 5/5

**Steps to reproduce:** 
1. Open the URL and sign in
2. Click on compliance standard
3. Click on edit on any standard like Introduction (or any not created by you)
4. Scroll down and click on "x" icon beside attachment
5. Click on remove
6. Observe

**Expected result:**
Error should occur stating that "You are not allowed to delete this attachment"

**Actual result:** 
Nothing happens
<p><a href="https://testlio.s3.amazonaws.com/issue/145527/a/444c0818-f967-8b3f-d011-84c80e3c65c7/fbf9b39403faf804c12a0f089f2dd98a.mp4">2016-10-11 17h10_34.mp4</a><br></p>

**Comment by Praxie** [comment]
Fixed in **v0.2.47**

**Comment by markokruustuk** [comment]
Closed from GitHub
