### ISSUE TITLE
[Testlio][Desktop][Compliance standard] Rendering document: TypeError

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#242]
**Environment:**
Device and OS: Windows 10, Firefox 47.0.1
Testable App version:https://app.pliohub.com
Network: Wifi
Location: Cz
Reproducibility rate: 3/3

**Steps to reproduce:** 
1. Login with valid account
2. Go to Compliance standard->Add
3. Write title and click Save
4. In the Compliance standard window, choose Attachment as a source 
5. Attach .docx file
6. Observe result

**Expected result:**
File should be attached without any issues

**Actual result:** 
"Rendering document: TypeError" message is displayed
<p><img src="https://testlio.s3.amazonaws.com/issue/145526/a/eed3676f-1474-a18a-8ff0-6b04bbb41d16-medium.jpg"/><br><a href="https://testlio.s3.amazonaws.com/issue/145526/a/bb643b07-7f26-fcfd-c20d-b0605c91d9fe/0ef544965ccb2975b13e4221cbc98806.mp4">2016-10-11 14h19_48.mp4</a><br></p>

**Comment by Praxie** [comment]
@markokruustuk could you attach the .docx document to reproduce this issue?

**Comment by RevelsGit** [comment]
I have the same issue on windows 10, chrome 54.0.2840.71 (.docx attachment).

**Comment by Praxie** [comment]
@RevelsGit could you take a look at this bug? I can't reproduce it.

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/271

**Comment by Praxie** [comment]
**v0.2.51**

**Comment by markokruustuk** [comment]
Closed from GitHub
