### ISSUE TITLE
[Testlio][Desktop][General] User is logged out from website in IE when clicked on More Info from all popups

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#243]
**Environment:**
Device and OS: Lenovo G50 Windows 10
Browser: IE 11
Testable App version: app.pliohub.com/sign-up
Network: Wifi
Location: Pakistan
Reproducibility rate: 5/5

**Steps to reproduce:** 
1. Open the URL and sign in
2. Open any popup (Click on Invite users or Report a non-conformity or any other popup of website)
3. Click on "?" icon
4. Click on More Info
5. Observe

**Expected result:**
User should be redirected to more info section.

**Actual result:** 
User is logged out from website.<p><a href="https://testlio.s3.amazonaws.com/issue/145524/a/bcc229a3-5d29-2000-1664-c4061304ac4c/18a374fb3279cb97ad7568e877ae0c23.mp4">2016-10-11 17h06_31.mp4</a><br></p>

**Comment by Praxie** [comment]
@sives do we need to remove "More info" link for now?

**Comment by sives** [comment]
Yes - remove it for now, and we will put it back in when we have online documentation up and running

**Comment by Praxie** [comment]
@sives OK

**Comment by Praxie** [comment]
@RomanValihura just remove the "More info" link.

**Comment by RomanValihura** [comment]
Fixed in i153-help-messages

**Comment by Praxie** [comment]
**v0.2.51**

**Comment by markokruustuk** [comment]
Closed from GitHub
