### ISSUE TITLE
[Testlio][Desktop][Homepage] Removed user is displayed as online on Homepage

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#244]
**Environment:**
Device and OS: Chrome v53, Windows 10 x64
Testable App version: https://app.pliohub.com
Network: Ethernet
Location: Romania
Reproducibility rate: 100%

**Steps to reproduce:** 
1. Log in as superuser (user that created the Testlio organization) 
2. Invite a user (cretunnicolae@gmail.com was invited here) -> Accept invitation  -> Leave tab open
3. On a separate tab with the superuser go to User Directory -> Select user from step 2 -> Remove user

**Expected result:**
User is deleted from the project and no longer displayed in the User Directory or homepage as being online.

**Actual result:** 
User is still displayed as online, even though it is no longer part of the project.

Note: I have sent the invitation and removed the user yesterday evening. I have logged in next morning on another pc and the user was displayed as online. If you need more information, please ask. <p><img src="https://testlio.s3.amazonaws.com/issue/145508/a/806cb7d1-3af3-429e-9fc8-4202fd91d2c5-medium.jpg"/><br><img src="https://testlio.s3.amazonaws.com/issue/145508/a/74fe568d-617a-5bc5-3d1a-250b6dc13002-medium.jpg"/><br></p>

**Comment by markokruustuk** [comment]
Note: Account is no longer displayed as being online now.

**Comment by Praxie** [comment]
Fixed in **v0.2.47**

**Comment by markokruustuk** [comment]
Closed from GitHub
