### ISSUE TITLE
Plio customers card

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#245]
Steve Ives (or any user in the Plio Ltd account) need to be able to get a display of all organizations in the system, except of the Plio Ltd org, with the following information for each organization:

Account name: Smith Brothers Ltd (in subcard header)
Owner: John Smith
Email: john.smith@smithbrothers.com
Created: 20 Jun 2016,  3.15pm
Users: 3

This display of information should be accessed from an additional entry in the LHS dropdown menu - called “Plio customers” - from the home screen.
**Steve Ives (steve.ives@pliohub.com) also need to get an email whenever a new organization is created, containing this information.**

**Comment by Praxie** [comment]
Plio Ltd organization need to have a special field in the database document. 'isAdminOrg: true' 
It's shouldn't be possible to set this field in the application (don't include it in the schema). It should be set manually via mongo shell.

**Comment by Praxie** [comment]
![screen shot 2016-10-20 at 12 19 06 pm](https://cloud.githubusercontent.com/assets/2095940/19554045/71dc69f0-96bf-11e6-994a-281fbeff5c33.png)

**Comment by Praxie** [comment]
![screen shot 2016-10-20 at 12 05 31 pm](https://cloud.githubusercontent.com/assets/2095940/19554048/7b7b2604-96bf-11e6-8e73-03a6983b325a.png)

**Comment by Praxie** [comment]
implemented in the current release (card footer will be implemented as a part of another issue)

**Comment by sives** [comment]
Looks good.  To complete this feature we need an email notification to be sent to the Org owner of Plio Ltd whenever a new Plio organization is added to Plio.

**Comment by Praxie** [comment]
@RomanValihura also replace the email text with a Mailto Link.

**Comment by Praxie** [comment]
@RomanValihura
![screen shot 2016-10-25 at 11 53 31 am](https://cloud.githubusercontent.com/assets/2095940/19679233/b7c1087a-9aa9-11e6-83cf-eb7253141243.png)

**Comment by Praxie** [comment]
@RomanValihura sorry the tittle should be "New Plio organization created". We're using American English.

**Comment by RevelsGit** [comment]
I don't think that the modal is enough for this. If there were 100 or more organizations they need to be loaded with some kind of pagination. Also there should be search box which pulls data from the server or else we will experience scaling issues (just like standards or other screens).

**Comment by sives** [comment]
You are right. Let me design a Plio-style screen for this, with a LHS list view and a RHS card.  Will be done by Friday.

**Comment by sives** [comment]
I've just added the screen sketch for this screen (4.9.1 Organizations screen) in Basecamp.  It has been given the name "Organizations" instead of customers, since it needs to include free trials and test account.   

There is an Edit button on the card, to give me the ability to set the type of organization (4 types: Paying subscriber, Unpaid subscriber, Free trial, Test account)

https://basecamp.com/1896845/projects/11083679/uploads/34708508?enlarge=256104511#attachment_256104511
