### ISSUE TITLE
Add to Home screen icon

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#246]
On mobile devices, when the user does an "Add to Home screen" operation from the mobile browser, the blue Plio icon should be added to the mobile home screen.

**Comment by RomanValihura** [comment]
By mistake pushed to the wrong branch

**Comment by Praxie** [comment]
**v0.2.50**

**Comment by Praxie** [comment]
![223022246_4799535340412098033](https://cloud.githubusercontent.com/assets/2095940/19966239/97a37f10-a1d3-11e6-88b4-16065a609527.jpg)

**Comment by sives** [comment]
Looks really good!
