### ISSUE TITLE
Risk card - incorrect field label

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#252]
In the top section, 3rd grouping of the Risk card the field label is incorrectly labelled as "Update of standard(s)" and should be labelled as "Update of risk record"

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/264

**Comment by Praxie** [comment]
**v0.2.51**

**Comment by Praxie** [comment]
@RevelsGit take a look at workInbox mixin (getLinkedDocTypeText method). It'll return the proper string.

**Comment by RevelsGit** [comment]
@Praxie Where? I can't find any of these.

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/303

**Comment by Praxie** [comment]
**v0.2.52**

**Comment by markokruustuk** [comment]
Closed from GitHub
