### ISSUE TITLE
Cannot transfer a Plio organization

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#257]
The Transfer button is inactive - I can't transfer one of my Plio organizations e.g. First China Investment Fund to a new owner

**Comment by Praxie** [comment]
@sives you need to select another user first. Let me know if it helps.

**Comment by Praxie** [comment]
![427ee2678abe5b5f0745b70ae68fbe5e](https://cloud.githubusercontent.com/assets/2095940/19647836/9f837104-9a08-11e6-9cf7-5db0c7eb46c7.gif)

**Comment by sives** [comment]
The user thinks that the transfer operation is a transfer from the user who is listed in the Org owner field to the left.  So when he clicks on "Transfer" he expects to be prompted for the name of the user he is transferring to.

**Comment by Praxie** [comment]
@sives In this way we need to specify a proper UI for this field because it was missed in the initial spec.

**Comment by Praxie** [comment]
I think that we could use the same design as in the Action card (To be completed by section)

**Comment by Praxie** [comment]
Initial state:
![screen shot 2016-10-26 at 11 56 44 am](https://cloud.githubusercontent.com/assets/2095940/19719674/a97bcdc0-9b73-11e6-8399-45a9a486ca97.png)

After clicking on the "Transfer" button:
![screen shot 2016-10-26 at 11 55 48 am](https://cloud.githubusercontent.com/assets/2095940/19719676/ab70c478-9b73-11e6-8e50-a032162ae453.png)

**Comment by sives** [comment]
Yes, this looks like a good solution.  The system needs to automatically assign the full set of superpowers to the new owner, otherwise the new owner could find that they are locked out of key functions.

**Comment by Praxie** [comment]
> The system needs to automatically assign the full set of superpowers to the new owner, otherwise the new owner could find that they are locked out of key functions.

It already works this way as I see.

**Comment by sives** [comment]
Excellent - software that anticipates my requirements :-)

**Comment by Praxie** [comment]
@meyginix sorry I didn't provide the mockup for the following step:
![screen shot 2016-11-01 at 4 41 41 pm](https://cloud.githubusercontent.com/assets/2095940/19893520/1c724b28-a052-11e6-9ea3-ff64339ba870.png)

This way we'll keep the proper behaviour of the similar section in the Action card.

**Comment by Praxie** [comment]
@meyginix Could you also exclude org owner from a selection list? (If it's not difficult to do so)

**Comment by Praxie** [comment]
v0.2.50
