### ISSUE TITLE
Deleting organizations

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#258]
There doesn't seem to be any way for the Org owner to delete an organization from Plio.

**Comment by sives** [comment]
Also we need to provide a way to delete organizations that have been sitting inactive for a period of time after their 30 day free trial has expired.  This should be under the control of myself (steve.ives@pliohub.com) or James (james.ives@pliohub.com) and require a special password to complete the process.  (Suggest we provide Delete and Archive options available from a triple-dot button on the Customer list item panel)

**Comment by Praxie** [comment]
@sives What needs to be implemented in 2c? We don't have a functionality to check the trial time expiration.

**Comment by sives** [comment]
Just the ability to delete an organization from the list of customers, and also to add one field to the customer subcard:  Last active date:    Don't worry about the functionality to check the trial time expiration.

**Comment by Praxie** [comment]
We agreed to create a "Danger zone" in Org settings.
There should be a red button with gradient (our current button design) "Delete organization"
After click on that button a worning modal (sweetalerts) should appear.
@sives could you provide a warning message? 
In addition there should be a text field to enter the password in the warning modal.
After submitting this form all data that is linked to the organization needs to be removed permanently (Standards, NCs, actions etc.) After succesful removal the organization itself needs to be deleted permanently.

**Comment by sives** [comment]
Here is the warning message.
"Deleting a Plio organization will delete all records linked to that organization.  Deleting is an irreversible action and you will not be able to recover this data afterwards.  Do you still want to go ahead and delete?"   User is presented with 2 options after viewing this warning.  He can click either on a Cancel button or on a Delete button (delete button is in red).

**Comment by meyginix** [comment]
https://github.com/Pliohub/Plio/pull/291

**Comment by Praxie** [comment]
**v0.2.52**

**Comment by markokruustuk** [comment]
Closed from GitHub
