### ISSUE TITLE
Cannot use .png file as avatar

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#276]
When selecting a file to upload, Plio only lets you select .jpg files.  Any reason why we cannot support .png files as well (it's a very common web image format)

**Comment by RomanValihura** [comment]
I set png image as avatar without any problem.
Tested on Google Chrome, Opera and Safari.

**Comment by Praxie** [comment]
I reproduced it in Safari

**Comment by Praxie** [comment]
I reproduced it in Safari

**Comment by Praxie** [comment]
I reproduced it in Safari

**Comment by Praxie** [comment]
I reproduced it in Safari

**Comment by Praxie** [comment]
I reproduced it in Safari

**Comment by Praxie** [comment]
I reproduced it in Safari

**Comment by Praxie** [comment]
I reproduced it in Safari

**Comment by Praxie** [comment]
I reproduced it in Safari

**Comment by Praxie** [comment]
I reproduced it in Safari

**Comment by Praxie** [comment]
I reproduced it in Safari

**Comment by Praxie** [comment]
I reproduced it in Safari

**Comment by Praxie** [comment]
Github lagged 😟

**Comment by sives** [comment]
Mike and I have both reproduced the issue in Safari on Mac OS.  It works fine in Chrome.

**Comment by Praxie** [comment]
**current release**
