### ISSUE TITLE
General card behaviour - default display on screen entry

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#28]
When you go into a screen (e.g. Standards screen) for the first time, it should display the first item in the left hand side List view (which it does now) but it should not highlight any item in blue until the user clicks on a highlighted item. (This might seem like a trivial issue, but it affects the behaviour of the Add button - you should get additional Add options only when you highlight a card item, e.g. Add Non-conformity, but not when you've just gone into the Standards screen and haven't actively selected and highlighted an item in the LHS list view)

Related issue: when you click the Add button in the Standards screen, it should **not** respond by displaying a chooser offering the single option "Add a Standard".  It should just take you directly into the Standards card in Edit mode for you to fill out.   Only if you have actively highlighted an individual item in the LHS List view should you get the chooser which gives you the options of Add a Standard or Add a Non-conformity

**Comment by Praxie** [comment]
Let's remove this picker for the Milestone 2b.
The Add button should open the Add Standard modal window right away. 
![screen shot 2016-05-18 at 7 23 01 pm](https://cloud.githubusercontent.com/assets/2095940/15366650/f7eced1e-1d2d-11e6-950d-3d9299a41d08.png)

**Comment by sives** [comment]
Also, we put an additional Add button in the RHS card header, if we need to add a Non-conformity to the Standard

**Comment by Praxie** [comment]
> Also, we put an additional Add button in the RHS card header, if we need to add a Non-conformity to the Standard

Though this is Milestone 3A

**Comment by Praxie** [comment]
https://trello.com/c/5yVpZa7N/143-i28-general-card-behaviour-default-display-on-screen-entry

**Comment by Praxie** [comment]
https://github.com/JSSolutions/Plio/pull/109

**Comment by sives** [comment]
Verified and working as agreed.

**Comment by sives** [comment]
We agreed to revisit this in Milestone 3a

**Comment by Praxie** [comment]
>  the default item displayed should be the first item in the first collapsible section
Done

**Comment by sives** [comment]
Let's keep it simple and have additional Add options always available
