### ISSUE TITLE
Field alignment in card edit mode on mobile

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#296]
On my Android device (Samsung Galaxy Note 3 running Android 5.0), when I am in the read mode of a card all the data fields are correctly left-aligned with their corresponding field labels.

When I go into edit mode of any card, the data field is mis-aligned just a few pixels to the right of the field label.   All data fields need to be moved a few pixels to the left hand side to give perfect alignment with the field labels.

**Comment by Praxie** [comment]
![screen shot 2016-11-03 at 12 15 41 pm](https://cloud.githubusercontent.com/assets/2095940/19962290/acaa7134-a1bf-11e6-827a-b180bba83118.png)

**Comment by Praxie** [comment]
@sives , I wouldn't call it a bug. Mockups are made in the same way.
![screen shot 2016-11-03 at 12 19 28 pm](https://cloud.githubusercontent.com/assets/2095940/19962378/f93fc60c-a1bf-11e6-95bf-529d1ebacf4b.png)

**Comment by RomanValihura** [comment]
fixed in PR https://github.com/Pliohub/Plio/pull/304

**Comment by Praxie** [comment]
**v0.2.52**

**Comment by sives** [comment]
@Praxie you are right it's not a bug, it's a glitch that was present in the UI prototype too

**Comment by markokruustuk** [comment]
Closed from GitHub
