### ISSUE TITLE
Live support chat

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#308]
We will implement a live chat facility similar to Intercom.io, accessed from the bottom right hand side of the Home screen.  We will use Resend.io plugin for this (an Intercom lookalike which I've tested and seems to work pretty well, which is currently offered free of charge).

**Comment by RomanValihura** [comment]
Added snipet in PR https://github.com/Pliohub/Plio/pull/313

**Comment by RomanValihura** [comment]
Need activate application after deployment.

**Comment by RomanValihura** [comment]
Application was actived and works now.

**Comment by Praxie** [comment]
**current version**
