### ISSUE TITLE
Reopening the web app on Android doesn't take you to your current workspace

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#310]
When I'm testing on Android, Plio keeps taking me back to an old workspace (Caradon Management plc - rather than the current workspace, Plio Ltd) every time I reopen the Plio web app from an icon on my Android home screen.

**Comment by Praxie** [comment]
@sives I believe that you saved the Plio icon while being in the Caradon Management plc organization. 
So this icon will always take you to this organization because it works the same way as browser bookmarks.

**Comment by Praxie** [comment]
It's not possible to set a custom url.
> it's not possible to do this because of security constraints

Source: http://stackoverflow.com/questions/15883736/how-to-have-a-custom-url-for-an-icon-on-the-ios-home-screen

**Comment by sives** [comment]
OK, I understand what I did wrong when adding the the icon to my homescreen

**Comment by markokruustuk** [comment]
Closed from GitHub
