### ISSUE TITLE
Org settings subcard titles wrapping on mobile

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#311]
On my Android 5.0 device, when you go into Organization settings, some of the title labels in the subcard header bar (e.g. Department/sector) are displaying as expected.  Others (e.g. Standards types) are wrapping onto the next line, when they shouldn't be wrapping.

![screenshot_2016-11-04-12-40-00](https://cloud.githubusercontent.com/assets/2330529/20009735/878c41b4-a29d-11e6-94f2-0e3573c234c0.png)

**Comment by Praxie** [comment]
**v0.2.54**
