### ISSUE TITLE
Remove need to click "OK" on confirmation dialogs

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#312]
When Plio asks if you want to delete a corrective action, and you click yes, it shows you a dialog box confirming it has removed the item, along with an OK button.  The user has to click on the OK button before proceeding.

I'd like the confirmation dialog to show for a couple of seconds, then remove itself automatically, without the user having to click on the OK button.   

(Of course, if the dialog that displays contains other actions, then the user should have to click on one of them to proceed.  But not if it is just "OK")

**Comment by RomanValihura** [comment]
https://github.com/Pliohub/Plio/pull/335

**Comment by Praxie** [comment]
**v0.2.61**

**Comment by sives** [comment]
When I try and delete a corrective action from a non-conformity in 0.2.64, I'm still seeing the old behaviour (i.e. user needs to click on the OK button).  So it is not resolved yet.

**Comment by Praxie** [comment]
**staging application**

**Comment by sives** [comment]
This has re-appeared.  When I try and delete a corrective action from a non-conformity in the Non-conformities screen in v0.2.64, I'm still seeing the old behaviour (i.e. user needs to click on the OK button). So it is not fully resolved yet.

**Comment by Praxie** [comment]
**Plio version 0.2.73**
