### ISSUE TITLE
Card header labels - title text is obscured

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#318]
Go from the Home screen into Organization settings and you will see that the bottom of the title text in the card header is obscured.  The "g" character in "organization" and the "g" character in "settings" have both lost their bottom section.

This is happening in card header labels throughout the system - it's just a bit more obvious with some text letters than with others.  "g"s are particularly noticeable but "y"s are also affected.  The text is getting obscured somehow.

This problem happens on all types of browser.

![screen shot 2016-11-08 at 11 53 58](https://cloud.githubusercontent.com/assets/2330529/20098118/143f26e4-a5aa-11e6-8c68-ac372fd5ff31.png)

**Comment by Praxie** [comment]
**v0.2.56**

**Comment by sives** [comment]
Problem is still there - no difference in v0.2.56

**Comment by Praxie** [comment]
**v0.2.57**

**Comment by sives** [comment]
This issue still not resolved in the Organization setting card (it is resolved everywhere else)

**Comment by Praxie** [comment]
@sives It's fixed now (**v0.2.58** is deploying)
