### ISSUE TITLE
Home screen titles  (top priority)

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#321]
The title of the home screen icons (e.g. Compliance standards) becomes configurable in a new subcard in Org settings called "Home screen titles", which is displayed just above the Department/sector(s) subcard.  There is a Quick help slide down panel in the subcard body which explains what this feature does.
 
The selection options for these labels are:

Standards:
- Standards (default)
- Compliance standards
- Compliance manual
- Quality standards
- Quality manual
Risk register:
- Risk register (default)
- Risk records
- Risks
Non-conformities:
- Non-conformities (default)
- Exceptions
Work inbox:
- Work inbox (default, with a small "i")
- Work items 
- Work

However the Org owner has the option to enter their own label of choice, if they wish.

**Comment by Praxie** [comment]
![screen shot 2016-11-14 at 12 13 07 pm](https://cloud.githubusercontent.com/assets/2095940/20260976/915cb5ce-aa64-11e6-80cf-47a87829f546.png)

**Comment by Praxie** [comment]
![screen shot 2016-11-14 at 12 18 36 pm](https://cloud.githubusercontent.com/assets/2095940/20261008/a1ad5bf4-aa64-11e6-9665-b339c8ae8b9e.png)

**Comment by Praxie** [comment]
@sives I need your approval on this design.

**Comment by sives** [comment]
The "Compliance standards" label in Home screen titles should now be "Standards"

**Comment by Praxie** [comment]
![screen shot 2016-11-14 at 1 54 01 pm](https://cloud.githubusercontent.com/assets/2095940/20263974/e05169ec-aa71-11e6-8b80-9f1073a4de7c.png)

**Comment by Praxie** [comment]
@sives could you specify a help message for this subcard?

**Comment by sives** [comment]
Here it is:
"Plio lets you customize the labels for each of the main icons on your home screen.  Just select an icon label you wish to change, click on the selection button and select an alternative name from the options provided, or create an entirely new name"

**Comment by RomanValihura** [comment]
#379

**Comment by Praxie** [comment]
**Plio version 0.2.68 (staging)**

**Comment by sives** [comment]
Feature looks good.  Just one change needed:  change label in Org settings from "Home screen titles" to "Workspace titles"

**Comment by RomanValihura** [comment]
Changed "Home screen titles" to "Workspace titles" in PR  #384

**Comment by Praxie** [comment]
**Plio version 0.2.69 (staging)**
