### ISSUE TITLE
Online help

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#322]
Online help will be provided to all users using a screen that is very similar to the Compliance standards screen, but labelled as "Help center".  For general users it will be accessed from a rectangular button to the left hand side of the "Invite users" button on the Home screen.   Because there is only the single list view available to users (Help - by section) there is no dropdown list in this screen

Unlike the Compliance standards screen, it is set up as read-only for general users. When a user clicks on the Help center button, they enter the Help center screen, which contains a hierarchical set of source documents, just like the Compliance standards screen.  When they click on the back chevron on the LHS of the header bar, they are taken back to the home screen.

Online help is created and edited using the "New" and "Edit" buttons displayed when a Help author accesses their version of the Help center screen.  Online help can be created and edited by any Plio Ltd user with superpower = create/edit Standards documents.  

Read mode fields (General users):
Section
Source file
(Discussions function is not required)
(Audit history not required)

Edit mode fields (General users):
Card is not editable by General users.

Read mode field (Help authors):
Remove the following fields from the card:
- Description
- Department/sector
- Type
- Just a single source field, not 2
- Include the Notify changes subcard.
- Don't include any of the other subcards.
- Discussions function is not required
- Audit history not required

Edit mode fields (Help authors):
- Same as the Read mode fields above

Help documents can be displayed under one of the following 8 help sections (the equivalent of Standards sections in the Standards screen - but these sections are not configurable):
1. How to get help
2. Getting started
3. Creating your Standards manual 
4. Managing risks
5. Managing non-conformities 
6. Managing workflows 
7. User management
8. FAQs

**Comment by Praxie** [comment]
![screen shot 2016-11-14 at 12 26 38 pm](https://cloud.githubusercontent.com/assets/2095940/20261237/a0c8e4aa-aa65-11e6-8d96-93b19e7977b9.png)

**Comment by Praxie** [comment]
Read mode card: General users design
![screen shot 2016-11-14 at 12 39 25 pm](https://cloud.githubusercontent.com/assets/2095940/20261665/7ed26d24-aa67-11e6-8e4a-2a4357dbbc77.png)
![screen shot 2016-11-14 at 12 39 42 pm](https://cloud.githubusercontent.com/assets/2095940/20261667/812b0838-aa67-11e6-980b-61b59d8d4022.png)
![screen shot 2016-11-14 at 12 39 54 pm](https://cloud.githubusercontent.com/assets/2095940/20261669/83ea80ee-aa67-11e6-8f68-09dfe78ac59c.png)

**Comment by Praxie** [comment]
@meyginix add the following components to the Online Help card (right after a Section field and before the Source file component):

- Owner
- Issue number
- Status

Owner and Status fields should be included in the "Add new Help document" modal window

Also, return the old configuration of the Source file component. It should be possible to remove a source file by clicking on the cross button in the RHS of the file label. Remove the "Change" button from the view but keep this option in the "Source file" component because it may be useful in future.

**Comment by Praxie** [comment]
**Plio version 0.2.68 (staging)**

**Comment by sives** [comment]
When I try to load certain Word documents I get the following error displayed, and the .docx document fails to render as HTML.  Examples of these Word documents are attached.  These two short documents also fail to render in the current (live) version of Plio, and generate similar error messages.

![screen shot 2016-12-14 at 20 32 24](https://cloud.githubusercontent.com/assets/2330529/21201294/61bd9bd0-c242-11e6-8b4d-6c532566627d.png)

[HD1 How can I reset my password?.docx](https://github.com/Pliohub/Plio/files/652871/HD1.How.can.I.reset.my.password.docx)

[HD2 What are the technical requirements for running Plio?.docx](https://github.com/Pliohub/Plio/files/652872/HD2.What.are.the.technical.requirements.for.running.Plio.docx)
