### ISSUE TITLE
Standards numbering

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#323]
The Standards card and the Standards screen list views will be modified to display unique Standards numbers which can be optionally entered by the Standards creator for each compliance standard.  These unique numbers are linked by Plio to the 3 letter standards type.  These follow a 3 letter-plus-unique-number pattern, e.g. SOP15.  Unlike other records in the system, numbering of standards is a manual process, to allow users to re-use any previous system of standards numbering which they may have been following before Plio.

For an example of how numbering is implemented for a set of compliance standards, see the FCA handbook at https://www.handbook.fca.org.uk/handbook.

In the Standards card, we will add a new field called "Unique number" in the top section, below the Type field.   There will be a help icon to the left of the field label, (and we will add help icons to the left of the Standards section and Issue number field labels also).

In the left hand side list views, we will replace the Type attribute (e.g. "Policy") with the three letter abbreviation/unique number combination (e.g. "POL15").  If there is no number specified we will just display the three letter abbreviation (e.g. "POL").  If the Type has been set to "Other" then no type will be displayed in the LHS list view item panel (currently "Other" is displayed).   Similarly in the Read mode of the card, we will replace the "Type" field contents with the three letter abbreviation/unique number combination, instead of the full word.  However, if Type has been set to "Other" we will still continue to display this data label in the Type field of the Read mode of the card.

**Comment by Praxie** [comment]
@sives could specify a help message for the "Unique number" field?

**Comment by RomanValihura** [comment]
#383

**Comment by sives** [comment]
Sure.  Here it is.   "Please enter a unique number between 1 and 10000 for this standards document"
(We also need to carry out a check on the number that is entered to make sure it conforms to this required number range)

**Comment by Praxie** [comment]
@sives I have few questions/remarks:
1. What if there will be a type with no 3 letter abbreviation? What do we need to display in the LHS list item?
![screen shot 2016-12-13 at 6 06 31 pm](https://cloud.githubusercontent.com/assets/2095940/21147809/e8320370-c15e-11e6-94e0-f70f107f4f26.png)
2. It's been specified that the type abbreviation may contain 1-3 letters. So it's not exactly a "3 letter-plus-unique-number"
3. We decided to remove the "Other" type from the list of default types to solve the last issue. I think that we need to treat all custom types in the system equally.

**Comment by sives** [comment]
Comments:
1.  If there is a type with no 3 letter abbreviation then nothing (null, blank) will be displayed within this field in the LHS list view.
2. The the type is 1-3 letters.   The number is between 1 and 10000.   The unique ID is the combination of the two e.g. SOP23
3. Treating all custom types equally sounds good to me.

**Comment by sives** [comment]
Let me know when this is ready for testing

**Comment by Praxie** [comment]
**Plio version 0.2.69 (staging)**

**Comment by sives** [comment]
The "Type" selection list should include the abbreviation, as follows:
Checklist (CHK)
Other (DOC)
Policy (POL)
etc etc

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/399

**Comment by Praxie** [comment]
@RevelsGit there shouldn't be (undefined) if the type has no abbreviation. Don't show a second part in brackets at all.
![screen shot 2016-12-26 at 2 40 01 pm](https://cloud.githubusercontent.com/assets/2095940/21482178/34a4e8c0-cb79-11e6-8467-c976d280cc9c.png)

Also, we need to display an abbreviation in the Read mode:
![screen shot 2016-12-26 at 2 43 34 pm](https://cloud.githubusercontent.com/assets/2095940/21482231/c4f955aa-cb79-11e6-867f-e2354d22d941.png)

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/401

**Comment by Praxie** [comment]
**Plio version 0.2.73**

![screen shot 2016-12-26 at 4 43 05 pm](https://cloud.githubusercontent.com/assets/2095940/21483746/4d0e8fda-cb90-11e6-8a2b-73d782f179d9.png)

@sives Do we need to include the abbreviation here?

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/402

**Comment by sives** [comment]
Yes, we do

**Comment by sives** [comment]
Yes, we do
