### ISSUE TITLE
Standards screen performance

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#324]
The performance of the Standards screen needs to be optimised so that it will handle collections of 250 documents with only 1-2 seconds latency to open the screen and show the first document.

**Comment by Praxie** [comment]
@RevelsGit add a script to generate 250 Standard documents. Copy the data from the existent standard document like https://staging.pliohub.com/100/standards/Tw4GxvZk7zWTJerGT?filter=1
Add a unique number to the title of each test standard document. 
E.g. 
ISO framework - introduction 1
ISO framework - introduction 2
ISO framework - introduction 3
...
ISO framework - introduction 250

**Comment by Praxie** [comment]
Add these 250 documents to the organization with serial number 106 (Shift Bioscience in production)
It may be a different one on localhost.

**Comment by RevelsGit** [comment]
It's impossible to load 250 documents + layout subscription(all users + organization) in 2 seconds without pagination or SSR, code splitting and other optimizations. It only takes 3~ seconds to load the scripts

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/386

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/388

**Comment by Praxie** [comment]
**Plio version 0.2.69**
