### ISSUE TITLE
Organizations screen

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#325]
Accessed from the LHS dropdown in the home screen, takes user to a screen showing all Plio organizations (see screen sketch 4.9.1).  This replaces the Customers list that was added at the end of Step 2c.  It can only be viewed by Plio Ltd users.  In the LHS dropdown it is labelled as "All organizations".

There are 3 possible types of customer:
- Paying subscriber
- Free trial
- Test account

**Comment by Praxie** [comment]
![large](https://cloud.githubusercontent.com/assets/2095940/20834527/94d59d18-b89e-11e6-9c54-cd673808d37b.jpg)

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/395

**Comment by sives** [comment]
A couple of features that were in the old Plio customers card are no longer in the new Customers screen:
- A nice big red "Delete organization" button (instead of just a grey delete button)
- The number of users in the organization

Can we add these please?   Also, how difficult would it be to add a "Last accessed" date field?

**Comment by Praxie** [comment]
@sives I think that the third feature will take about 4 hours. But we'll need to find an elegant way to update the Last accessed time that won't create a lot of requests to the server.

**Comment by sives** [comment]
OK great.  If it makes it easier to implement the feature, a "Last updated" date would be nearly as good.

**Comment by Praxie** [comment]
**Plio version 0.2.79**

**Comment by sives** [comment]
I'm seeing "Invalid date" in the Last accessed field.  Perhaps this is something that can only be tested in the Live application?

**Comment by Praxie** [comment]
From Skype discussion:

That’s because nobody visited the organization after this feature was added. It’s not a bug. We can’t get a last accessed date in this case.
The faster way to fix this is to visit these organisations. It won’t be an issue for new organisations.

**Comment by sives** [comment]
Let's replace the error text string "Invalid date" with "No date available"

**Comment by Praxie** [comment]
@sives OK. 
**Plio version 0.2.82**
