### ISSUE TITLE
Updated work inbox screen

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#327]
~~The Work inbox icon panel should not display the total number of items, but the items that I have waiting there to be done, in the format "3 items to do, 1 new"~~

Deletion of work items:  it should only be possible to delete work items by either ~~a) carrying out the work request in the Quick action panel or~~ b) deleting the card which the work item refers to.  There should be no separate delete function in the Quick action panel.   At the same time, we should change the Delete list views contained in the Work inbox list view selector from "Work - my deleted" and "Work - team deleted" to "My deleted actions" and "Team deleted actions".

**Comment by Praxie** [comment]
@RevelsGit, so "My deleted actions" and "Team deleted actions" screens should display deleted CA/PA but not work items.

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/372

**Comment by Praxie** [comment]
**staging application**

**Comment by sives** [comment]
In the Plio Ltd organization, what has happened to Corrective action CA4 (linked to Non-conformity NC10)?  It is attached to the NC10 card, has the status "Open-action overdue" but does not show up in the Work inbox.

In the "My deleted actions" and "Team deleted actions" list views, we need to display the actual deleted card items, like we used to be able to in the previous version.  If you delete an action in this new staging version, you just see  a message "There are no current work items" where the deleted card should be displayed.    Also, there needs to be the ability to Undelete the item (by clicking on the Undelete button which should appear on the top right hand side of the card header).

**Comment by Praxie** [comment]
**Plio version 0.2.70**

**Comment by Praxie** [comment]
@sives CA4 is now visible in the work inbox.

**Comment by sives** [comment]
The List view titles in the central drop down don't quite make sense in the new format.
The "By...." word structure is only appropriate where there are mainly accordion-style list views (as in Standards, Risks, NCs)

So I would suggest the following:
Work - my current
Work - team current
Work - my completed
Work - team completed
Actions - my deleted
Actions - team deleted

**Comment by Praxie** [comment]
**Plio version 0.2.73**
