### ISSUE TITLE
Add the Discussions feature to NCs and Risks

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#329]
Add the Discussions feature to NCs and Risks. Make sure users are notified when there's a relevant new message.

**Comment by Praxie** [comment]
**current release**

**Comment by sives** [comment]
The "Add a comment" box at the bottom of the discussion window overlaps with the blue Resend chat icon.   If we make the Add a comment box a bit less wide on the right hand side, we can avoid the overlap.

**Comment by Praxie** [comment]
![screen shot 2016-12-01 at 12 21 26 pm](https://cloud.githubusercontent.com/assets/2095940/20790706/3f80036c-b7c2-11e6-9974-dc6f258a35ff.png)

**Comment by Praxie** [comment]
**staging application**
