### ISSUE TITLE
Standard typeahead controls not properly implemented

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#333]
In the Standards card, go to Add new, then go to Standards section, click into this field and start typing.  The + button for the Add new entity option should be on the left hand side of the new entity text string, not the right hand side.   (Important - we should also widen the Add new entity dialog to accommodate the + button so that it overlays and hides some or all of the Type field label. Otherwise it looks like the new entity relates to the Type field and not to the Standards field).

There is a related problem with the implementation of this control in the Department/sector field in the Standards card.  In this case the + button for the Add new entity option should be on the left hand side of the new entity text string, not sitting above it.

The identical problem is also found in the Nonconformities card (in the Department/sector field) and the Risk card (also in the Department/sector field).

**Comment by Praxie** [comment]
We decided to show "No matches..." text if there are no matched items in the dropdown. This text shouldn't be clickable/highlighted on hover etc. Just a plain text.
![screen shot 2016-11-14 at 5 43 20 pm](https://cloud.githubusercontent.com/assets/2095940/20272927/2785e6a0-aa98-11e6-95f2-adfd7e3117b6.png)

**Comment by Praxie** [comment]
The Plus button needs to be moved to the left.

**Comment by RomanValihura** [comment]
Fixed in issue https://github.com/Pliohub/Plio/issues/337

Moved to the left all buttons in select fields

**Comment by RomanValihura** [comment]
Department/sector also fixed

**Comment by RomanValihura** [comment]
Added text "There are no available items...", that it using for other dropdowns

**Comment by Praxie** [comment]
**v0.2.61**

**Comment by markokruustuk** [comment]
Closed from GitHub
