### ISSUE TITLE
Move standard section plus button to left

### ISSUE THREAD

**Issue by RomanValihura** [Pliohub/Plio#337]
![image](https://cloud.githubusercontent.com/assets/17511584/20295925/afabf790-ab10-11e6-80e3-2d8e16997089.png)

Move plus button on the screenshot on start line of field "standard section"

**Comment by RomanValihura** [comment]
https://github.com/Pliohub/Plio/pull/338

**Comment by Praxie** [comment]
**v0.2.61**
