### ISSUE TITLE
Need to remind users that actions havent been created yet

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#344]
When a new Risk or Non-conformity is first created, there is a need for someone to create a Corrective or Preventative action linked to this Risk or Non-conformity, so that the workflow may proceed.  At the moment, no work items are created at this stage, and there is no way to remind users that this needs to be done.  The consequence is that new Risks and Non-conformities may just sit there and no action is ever taken.  

Or I have I misunderstood how the system is working?

**Comment by sives** [comment]
We agreed to add this feature for 3 step workflow and for 6 step workflows (after root cause analysis).  We should use the standard step time as the trigger for creating the work item

**Comment by Praxie** [comment]
Email reminder with a link to the NC/Risk.

**Comment by Praxie** [comment]
@sives who should receive these notification?

**Comment by sives** [comment]
@Praxie it should be the "Identified by" person in both cases (NCs and Risks)

**Comment by Praxie** [comment]
**Plio version 0.2.63**

**Comment by sives** [comment]
I created a new Risk today to test this, but I didn't receive any reminder to create actions.  What is the time delay supposed to be before sending the first reminder?

**Comment by Praxie** [comment]
@sives Did you create a minor risk?

**Comment by Praxie** [comment]
The time delay depends on the risk magnitude:
![screen shot 2016-12-01 at 12 51 12 pm](https://cloud.githubusercontent.com/assets/2095940/20791286/e2490178-b7c4-11e6-9b91-01572331ce73.png)

**Comment by sives** [comment]
Of course.  Sorry, sometimes I forget how the system was designed to work.  Thanks

**Comment by sives** [comment]
I created a test risk in the Plio organization on Mon 5th Dec at 4pm London time "Test - risk of flooding"

**Comment by sives** [comment]
As of Thursday 8 Dec I didn't receive any reminder from Plio to add any actions

**Comment by Praxie** [comment]
I'm going to deploy the latest version of the background application to solve this problem. The current version is outdated. I overlooked this.

**Comment by Praxie** [comment]
Deployed. I've created a new NC to test this.

**Comment by sives** [comment]
I'm getting notifications now to add actions to NCs

**Comment by Praxie** [comment]
![screen shot 2016-12-15 at 12 09 37 pm](https://cloud.githubusercontent.com/assets/2095940/21219926/6bfd5fd6-c2bf-11e6-86d5-7ca9547e9d0b.png)

**Comment by Praxie** [comment]
Add a Plio logo to the LHS of the email notification.

**Comment by Praxie** [comment]
@meyginix

**Comment by sives** [comment]
I suggest the following layout for this type of notification, using a worked example:

Title of email:
Non-conformity NC20 "Mis-selling on a phone call" - action(s) needed

Email layout:
Plio logo (same one as in Plio daily recap emails)
Non-conformity NC20 "Mis-selling on a phone call" - action(s) needed (this just re-states the notification title)

You created non-conformity NC20 on [date].  Action(s) now need to be created for this non-conformity (7 days overdue).   

Go to this non-conformity (clickable link)


@Praxie I've posted some general guidelines on Github in issue 387 on how notification emails should be laid out, which we should follow for this new type of notification.

**Comment by Praxie** [comment]
It's going to be fixed in the Live app.

**Comment by sives** [comment]
Currently testing this
