### ISSUE TITLE
Labels for initial workflow stage need clarification

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#345]
The statuses that I have highlighted in bold in the Screen spec v1.2 (see below) need to be updated from their current text strings to the text strings shown in bold.

![screen shot 2016-11-17 at 17 04 25](https://cloud.githubusercontent.com/assets/2330529/20399357/93e34caa-ace8-11e6-9bca-c55b83e563b9.png)

**Comment by Praxie** [comment]
@sives I think that it may be a bit confusing to the user to see the same ("Open - just reported, awaiting creation of an action") status after the action was added.

**Comment by sives** [comment]
How about this version with an additional stage:
![screen shot 2016-11-22 at 15 16 22](https://cloud.githubusercontent.com/assets/2330529/20529063/b968f7c2-b0c6-11e6-9555-d9a233aa0f8a.png)

**Comment by sives** [comment]
How about this:

![screen shot 2016-11-22 at 15 27 27](https://cloud.githubusercontent.com/assets/2330529/20529498/4128141c-b0c8-11e6-9fd0-29475d1df0fc.png)

**Comment by sives** [comment]
Hopefully this fixes the problem:

![screen shot 2016-11-22 at 15 30 29](https://cloud.githubusercontent.com/assets/2330529/20529638/ccbcb154-b0c8-11e6-84df-a322bf8562db.png)

**Comment by Praxie** [comment]
@sives adding a new workflow step is very complicated because we need to maintain current documents and their statuses. What about renaming "Open - just reported, action(s) need to be added" to "Open - just reported, action(s) to be added". It's a step to add actions, but we don't now if there should be 1, 2 or more of them. So we can't say that the user needs to add more actions or that they are in place.

**Comment by sives** [comment]
OK, good idea!

**Comment by Praxie** [comment]
**Plio version 0.2.62**

@sives could you update this document please?
https://basecamp.com/1896845/projects/11083679/documents/10518839

**Comment by Praxie** [comment]
There is a small issue: 
6-step NC/Risk will still have a status "Open - analysis completed, action(s) in place (amber)"
But a 3-step document won't.

The list of statuses will look like this:
**Possible statuses of a Non-conformity: (3 step workflow)**
Open - just reported, action(s) to be added (amber)
Open - action(s) due today (amber)
Open - action(s) overdue (red)
Open - action(s) completed (but not all actions), (amber)
Closed - action(s) completed (if multiple actions, all actions completed) (green)
Deleted (no colour)

**Possible statuses of a Non-conformity: (6 step workflow)**
Open - just reported, awaiting analysis (amber)
Open - analysis due today (amber)
Open - analysis overdue (red)
Open - analysis completed, action(s) need to be added (amber)
Open - analysis completed, action(s) in place (amber)
Open - action(s) due today (amber)
Open - action(s) overdue (red)
Open - action(s) completed, awaiting verification (amber)
Open - verification due today (amber)
Open - verification past due (red)
Open - action(s) verified as effective, awaiting update of standard(s)  (amber)
Open - action(s) verified as effective, update of standard(s) due today (amber) 
Open - action(s) verified as effective, update of standard(s) past due (red)
Open - action(s) failed verification (red)
Closed - action(s) verified, standard(s) reviewed (green)
Deleted (no colour)

**Comment by Praxie** [comment]
We may need to rethink this solution if it's a big issue.

**Comment by sives** [comment]
I'm happy with your solution.
