### ISSUE TITLE
Change workflow default for critical NCs/Risks

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#346]
Change the workflow default for critical NCs/Risks from 6 days to 3 days, so that all defaults are initially set at the same level.

**Comment by Praxie** [comment]
@sives there's already a "3 days" value there.
![screen shot 2016-11-22 at 4 41 19 pm](https://cloud.githubusercontent.com/assets/2095940/20527859/a324da92-b0d2-11e6-8dfe-051a64e71475.png)

Did you mean the workflow type?

**Comment by sives** [comment]
Yes, sorry I made a mistake in my comment above.   I mean't to say to set the default Type field to be 3-step for each of Minor, Major and Critical NCs/Risks

**Comment by Praxie** [comment]
**Plio version 0.2.63**
