### ISSUE TITLE
Work inbox LHS list view not laid out correctly 

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#349]
The title line on the LHS list view item panel is not left-justified properly in each item panel.

The unique ID numbers in the LHS item panels are not highlighted with a rectangular colour code.  They should be highlighted to match the traffic light colours of the unique ID numbers at the right hand side of the title field in the card on the RHS.

This needs to be fixed quickly because we are about to create our demo video.

**Comment by Praxie** [comment]
**current release**

**Comment by markokruustuk** [comment]
Closed from GitHub
