### ISSUE TITLE
Risk scoring - colour and categorisation error

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#356]
We need to check the mapping of risk scores (numbers between 1 and 99) to risk categories (v high, high, med, low).  I have spotted one error in the mapping.  A risk score of 75 on the matrix is being mapped to the 'high' category but it should be mapped to 'very high' since it is a red square on the matrix and not an amber square.  

There may be other errors in the mapping.  We need to check each score square on the matrix maps to the right score and the right colour.   
red squares = very high
amber squares = high
yellow squares = medium
green squares = low

**Comment by Praxie** [comment]
**Plio version 0.2.63**

**Comment by markokruustuk** [comment]
Closed from GitHub
