### ISSUE TITLE
Org settings need to be ordered alphabetically

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#365]
Any section in the Org Settings card that is built out of the List type of subcard (i.e. a list of textual entities) needs to reorder this list alphabetically after adding a new item to it.    The alphabetical ordering should also properly order any numbered items (e.g. "1. Introduction") with numbered items listed before non-numbered items.

At the moment the lists look very untidy because there is no order to them (apart from the order of adding items?)

**Comment by sives** [comment]
This is top priority to fix.  It is a bit embarrassing to show these un-ordered lists to our customers!

**Comment by RomanValihura** [comment]
#389

**Comment by Praxie** [comment]
**Plio version 0.2.70**
