### ISSUE TITLE
New corrective action not showing up in subcard header

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#373]
I added a new corrective action in the Southwind organization, but it didn't show up as a numbered item in the subcard header (although it did show up as a correction action record when I opened the subcard).
![screen shot 2016-12-05 at 09 38 05](https://cloud.githubusercontent.com/assets/2330529/20888936/fc70856e-bace-11e6-9aa2-cbf80f258157.png)

![screen shot 2016-12-05 at 09 38 24](https://cloud.githubusercontent.com/assets/2330529/20888940/03ad599c-bacf-11e6-95ef-39fd7d52dd4a.png)

**Comment by Praxie** [comment]
@sives didn't we agree to show only the number of red labeled PAs/CAs in the header? I remember that we did.

**Comment by sives** [comment]
I think we agreed not to show the traffic light unless it was red or orange, but we should always show the count (i.e. just the number) of all CA/PA items.  It is misleading to the user to show no count at all, even when there are items in the subcard.  Sorry, I should have made myself clearer.

**Comment by Praxie** [comment]
@sives here's the screenshot of SC5 mockup (http://ui2.isometrica.io/ui1-3/standards.html):
![screen shot 2016-12-06 at 4 15 43 pm](https://cloud.githubusercontent.com/assets/2095940/20930879/66e9cdd2-bbcf-11e6-8546-d6c6cc33c42d.png)

And I remember that we discussed that green labeled actions are not important and shouldn't be counted. I also provided a clear prototype, but I can't find it now. But it looked just like the current version:
![screen shot 2016-12-06 at 4 21 54 pm](https://cloud.githubusercontent.com/assets/2095940/20931101/4c5993ac-bbd0-11e6-9c7a-ac4973048612.png)
As you see, there are 2 numbers. Each of them stands for the number of actions with a particular label.

Your suggestion is to keep the total number of actions and red/orange indicators, if there are appropriate actions in the subcard:
![screen shot 2016-12-06 at 4 27 31 pm](https://cloud.githubusercontent.com/assets/2095940/20931366/2114acbc-bbd1-11e6-92b2-24ac67f56bc3.png)

Let me know which version of the design is the right one. I just want to make sure that everything's clear.

**Comment by sives** [comment]
The bottom version is the right one.  Traffic light circles only show up if they are amber or red.  There is a single number which represents the total number of actions.

Example: If there are just 2 red corrective actions, there is just a single red traffic light circle displayed together with the number 2 to the right hand side

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/377

**Comment by Praxie** [comment]
**staging app - current v.**

**Comment by markokruustuk** [comment]
Closed from GitHub
