### ISSUE TITLE
Incorrect default date on new NCs and Risks

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#374]
When you add a new NC record or Risk record, the identified date should default to today's date.  This is not happening.  Today (Dec 5th) when I added a new risk record, the identified date was set to Nov 30th, which is not correct.

**Comment by RevelsGit** [comment]
Cannot reproduce. The date is correct in my case: https://i.gyazo.com/b61c980cebfac2761ed6cb81e507eb1a.gif

**Comment by Praxie** [comment]
@sives I can't reproduce it as well in app.pliohub.com Plio Ltd.

**Comment by sives** [comment]
Here's a screenshot showing the incorrect date, together with my computer's date
![screen shot 2016-12-08 at 09 00 38](https://cloud.githubusercontent.com/assets/2330529/21003734/e30ea60c-bd24-11e6-9393-4ef2c8682ee7.png)

**Comment by sives** [comment]
This problem was solved by closing and reopening the browser (Chrome).   I will keep an eye on this problem and if it keeps recurring we may have to do some more diagnosis.

**Comment by markokruustuk** [comment]
Closed from GitHub
