### ISSUE TITLE
Incorrect notification links

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#375]
I received 2 notifications in the Plio Ltd organization to complete 2 different Preventative actions, both of which contained links which took me to the Work inbox but which didn't show the correct PA.  The first one was a notification relating to PA4.   The second one was a notification relating to PA3.   In both cases the links took me to the Work inbox screen displaying the PA2 preventative action.  I was expecting to be taken the Work inbox screen displaying either the PA4 or the PA3 action.

When I browse through all the NCs and Risks in Plio Ltd, I can't find any PA3 or PA4 preventative actions.   My conclusion was that Mike has probably created these actions as tests and then deleted them later.  

Real users will also create actions and then delete them.  So we need to find a way to avoid confusing users with notification links that can no longer link to the correct item.

If an linked item in an email notification no longer exists, the user should be taken to a Plio screen with an appropriate message displayed e.g  "This item no longer exists in Plio".  

We should also enhance the notification message to display the identify of the person that created the action, to make it more informative.  In other words, change from "You have been asked to complete preventative action....." to "You have been asked by [username] to complete preventative action...."

The first incorrect link was this one:
![screen shot 2016-12-06 at 08 45 29](https://cloud.githubusercontent.com/assets/2330529/20927881/6cf8278e-bb91-11e6-87f7-8ce32a8c40eb.png)
![screen shot 2016-12-06 at 08 45 52](https://cloud.githubusercontent.com/assets/2330529/20927883/7008782a-bb91-11e6-9832-636c9328fc45.png)

The second incorrect link was this one:
![screen shot 2016-12-06 at 08 48 55](https://cloud.githubusercontent.com/assets/2330529/20927890/76fde764-bb91-11e6-8cc2-b2c09c92acd2.png)

![screen shot 2016-12-06 at 08 49 09](https://cloud.githubusercontent.com/assets/2330529/20927893/79dc7284-bb91-11e6-9f5c-1c081675be4e.png)

**Comment by Praxie** [comment]
**Plio version 0.2.68 (staging)**

**Comment by sives** [comment]
These links are not working consistently.  I tested on 3 links in 3 separate notification emails in Plio Ltd on the staging app.

Root cause analysis   RK4   09/02/16 - works as intended, links to the correct list view and item
Corrective action CA8 "Test"  11/12/16 - doesn't link to the correct item
Action for non-conformity NC4 "Delete abbreviations from Standards" must be created. 14/12/16 - links to the following URL which does not load: http://localhost:3000/100/non-conformities/GuJjinqG8a4qnBxzD

**Comment by Praxie** [comment]
@meyginix I'm still getting the link with id query parameter in the email (https://app.pliohub.com/130/work-inbox?id=uypn5ZW9pLjoXGg62)
It doesn't work with the Work inbox screen. I'm being redirected to the first item in the list view.

**Comment by Praxie** [comment]
@sives it can be tested in the Live application only because all links in Plio notifications point to the Live app.

**Comment by sives** [comment]
Working fine when I tested it.
