### ISSUE TITLE
Notification links don't highlight relevant item

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#376]
Here's an example below of a corrective action I have been asked to complete.  When I click in the link in the email, I am taken to the Work inbox, and the corrective action is displayed at the bottom of the list, but the wrong item is highlighted in the list ("Update audit plan with KPMG" instead of "Give training to Singapore sales team").

![screen shot 2016-12-06 at 09 26 50](https://cloud.githubusercontent.com/assets/2330529/20929053/7c84a218-bb96-11e6-84f8-d800a97d6f0d.png)

![screen shot 2016-12-06 at 09 28 26](https://cloud.githubusercontent.com/assets/2330529/20929058/7f1b706a-bb96-11e6-8da5-44af0c2a542b.png)

**Comment by Praxie** [comment]
**Plio version 0.2.68 (staging)**

**Comment by sives** [comment]
See comment in issue number 375 (I think this is a duplicated issue)

**Comment by markokruustuk** [comment]
Closed from GitHub
