### ISSUE TITLE
Email invitation not getting through

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#382]
In a customer demo, I invited a user at 11.40 London time (Andrew Wilson - awilson@ridgeons.net) to the Plio Ltd organisation but the invite didn't get through to his mail inbox.   

Possible causes:
1.  Bug in Plio's email sending software
2. Problem with email sending service, low reputation score sending email into spam folder

Can we investigate and fix asap?

**Comment by Praxie** [comment]
https://www.mail-tester.com/web-mfbvv

**Comment by Praxie** [comment]
To Do:
- [ ] HTML: images with 1600-2000 bytes of words. You should write more text in your email. @sives could you provide here a general Plio description that can be included in all emails?
- [ ] HTML-only message, but there is no HTML tag. Your message should contain an <html> tag.
- [ ] 	Message only has text/html MIME parts. You should also include a text version of your message (text/plain)
- [ ] Move the mail server to another IP address that is not blacklisted.

These are major issues. Hopefully we can ignore issues with the score that is equal to or less then 0.001.

**Comment by Praxie** [comment]
@sives I got a response from the Mailgun support yesterday:

> Hello Michael,
> 
> Thank you for contacting Mailgun support.
> 
> To speak in full transparency, we are aware that SpamCannibal's listing contains a few of Mailgun's IPs. We do not have any way to remove these IPs from the SpamCannibal listing service. 
> 
> Based on what we know about this list, once an IP is listed, it will not be removed. We have already reached out to the team at SpamCannibal; however, they simply copied and pasted their FAQ from their website into their response to us.  The list, over the years, has proven to be riddled with false positives. There are many conversations being had throughout the internet community related to the recklessness of this list.  The major ESPs will also have IP's listed on SpamCannibal, and for said reason, will not rely on the SpamCannibal blacklist in their spam checks.  Further, the only way to be delisted from Spam Cannibal is to pay a fee.  However, the problem with this is that there is nothing stopping them from placing the IP - or an entire IP subnet - back on their list for "spammy activity", and thus, extorting more fees.
> 
> Interestingly, when we look for deliverability issues related to SpamCannibal listings, there are not many. We have seen a very few instances in the past, but it seems that many hosts do not actually use this blacklist.  The only example that comes to mind is the obscure Linux firewall LinuxMagic.  If you have any bounces or failed messages in your Logs that say the failure is due to SpamCannibal, we'd be glad to take a look. 
> 
> Let us know if you have any questions.
> 
> Thank you,
> Matt@MG

**Comment by sives** [comment]
OK Mike - let’s focus on the other things in the list that we can control

**Comment by sives** [comment]
@Praxie I've created a new Github issue no 387 for general layout and wording of notification emails, which has a short segment of extra text at the bottom of every email.  This also provides a function where users can request to turn off the notifications.

**Comment by sives** [comment]
Question - is the 3000 word requirement all or nothing, or do we get an increase in score by adding a few hundred words?
