### ISSUE TITLE
Data export

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#385]
The latest version of Data export specification:
https://basecamp.com/1896845/projects/11083679/documents/11473429
(Data export section)

**Comment by Praxie** [comment]
4.5.3 risk register - data export card v1.21:
![4 5 3 risk register - data export card v1 21](https://cloud.githubusercontent.com/assets/2095940/21221548/705abd24-c2c6-11e6-8bf4-12f2c81b498c.jpeg)

**Comment by Praxie** [comment]
4.3.3 nonconformities - data export card v1.21:
![4 3 3 nonconformities - data export card v1 21](https://cloud.githubusercontent.com/assets/2095940/21221577/91bb0096-c2c6-11e6-9350-f15bb02eba18.jpeg)

**Comment by Praxie** [comment]
@RomanValihura We need to export only the documents that are listed in the listview. That's being said, there shouldn't be deleted documents in the CSV file if the list view is not filtered by deleted documents. Ideally, it should work with search as well (export documents filtered by a search phrase in the current list view).

**Comment by Praxie** [comment]
@RomanValihura @sives in future we may have an infinite scrolling. Some items in the list view will be loaded on demand (by scrolling to the bottom of the section) but still they need to be included in the exported CSV file as I understand. For this reason we need to fetch these documents on the server side.

**Comment by Praxie** [comment]
@RomanValihura @sives I removed Data export sketches because they were out of date.

**Comment by RomanValihura** [comment]
@sives markup of data export modal
![image](https://cloud.githubusercontent.com/assets/17511584/21543816/6254a19c-cdd2-11e6-8c57-c6a911489d98.png)
![image](https://cloud.githubusercontent.com/assets/17511584/21543829/800ce078-cdd2-11e6-8121-a09f8f575a87.png)

**Comment by RomanValihura** [comment]
#413

**Comment by Praxie** [comment]
There are few issues that need to be fixed.

**Comment by Praxie** [comment]
@RomanValihura check out my messages

**Comment by RomanValihura** [comment]
#424

**Comment by Praxie** [comment]
**Plio version 0.2.77**

**Comment by RomanValihura** [comment]
@sives @Praxie  Fixed in PR #430
