### ISSUE TITLE
Clicking on the Delete button in the Action's subcard section should remove the document, not unlink it

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#391]

**Comment by Praxie** [comment]
![screen shot 2016-12-19 at 7 32 52 pm](https://cloud.githubusercontent.com/assets/2095940/21323478/51e1e54e-c626-11e6-8cf7-4c0cf1cbf25b.png)

**Comment by RevelsGit** [comment]
I don't understand the problem. It removes the action just fine. After remove it will be listed in 'My deleted/Team deleted actions'.

**Comment by sives** [comment]
Yes, it works fine when I test it now.
