### ISSUE TITLE
Status of NCs and Risks not updating after adding actions

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#393]
On the top line of the top section of the Risk and NC cards, there is a status message e.g. RK18 - Open - just reported, action(s) to be added.  

After I go and add actions (e.g. I've added Preventative action PA1 in the screenshot below), this status message is not being updated, see below.  It needs to be updated, both the traffic light colour and the status message, to reflect the current status.

![screen shot 2016-12-19 at 19 35 14](https://cloud.githubusercontent.com/assets/2330529/21326441/8e059b1e-c622-11e6-928a-f46be0f2837d.png)

**Comment by Praxie** [comment]
@sives 
We discussed this already: https://github.com/Pliohub/Plio/issues/345
![screen shot 2016-12-20 at 2 06 44 pm](https://cloud.githubusercontent.com/assets/2095940/21349979/91c638da-c6bd-11e6-9990-9e3667e8cb27.png)

The workflow should treat both NC and risk documents in the same way.

**Comment by sives** [comment]
For both NCs and Risks, we agreed to add another workflow status step to the list of statuses for a 3-step workflow, with status of  "Open - action(s) in place" (amber).  I've updated the Screen spec v1.2 on Basecamp.

**Comment by Praxie** [comment]
@sives it can be deployed only in the day of 3a release because it will broke the Live application. But it won't be a problem if the staging application will replace the Live app.

**Comment by sives** [comment]
Waiting to test when we go live

**Comment by sives** [comment]
Tested and working fine.
