### ISSUE TITLE
Unable to complete actions in Southwind Work Inbox

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#394]
Mike has reproduced this problem

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/396 Hopefully it will fix it

**Comment by Praxie** [comment]
**Plio version 0.2.72 (staging)**

**Comment by sives** [comment]
It works on the staging, but not on the live system

**Comment by Praxie** [comment]
We need to fix this bug in a live system (app.pliohub.com) as well

**Comment by Praxie** [comment]
@sives fixed
