### ISSUE TITLE
Misspelling of card title in standards card (edit mode)

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#405]
When you open a standards card in edit mode the header title "compliance standard" is misspelt as "Compiance standard".   I would prefer that we just label it as "Standard" now to fit in with the workspace icon labelling.   We should also label the header title to "Standard" in read mode.

**Comment by Praxie** [comment]
**Plio version 0.2.75**

**Comment by markokruustuk** [comment]
Closed from GitHub
