### ISSUE TITLE
Title of linked discussion item is too long

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#406]
When you click on a link to an unread discussion item from the Plio workspace, you get taken to the relevant screen with a header title that is much too long to display on a mobile device.  The full discussion message text is being shown in the header.    We just need to display the single word "Discussion" in the header bar title.

**Comment by Praxie** [comment]
@sives Sorry I didn't understand what you meant.
![screen shot 2016-12-28 at 2 49 37 pm](https://cloud.githubusercontent.com/assets/2095940/21522348/6e6c8dde-cd0d-11e6-9678-076f2d5d5c8b.png)
![screen shot 2016-12-28 at 2 53 11 pm](https://cloud.githubusercontent.com/assets/2095940/21522350/71a40b94-cd0d-11e6-8ff9-0f7775525478.png)

Do you propose to change the title in the header from "<Standard's name> - discussion" to "Discussion"? In this way there will be two "Discussion" titles one under another.

**Comment by sives** [comment]
We definitely don't want to see two Discussion titles underneath each other

**Comment by sives** [comment]
Let's make the top header show the title of the item without any extra text e.g. "5. Leadership" and not add the word discussion onto it (which just makes it even longer, and less able to display on mobile).  The lower header should show the single word "Discussion".   This solution should also work nicely in the Nonconformities and Risks screens.

**Comment by Praxie** [comment]
**Plio version 0.2.76**
