### ISSUE TITLE
Help centre button icon needs to be a bit bigger

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#407]
The Help centre button icon (question mark) needs to be a bit bigger - currently it looks slightly smaller than the icons in the adjacent two buttons

**Comment by Praxie** [comment]
![screen shot 2016-12-27 at 6 15 25 pm](https://cloud.githubusercontent.com/assets/2095940/21503489/7be929b6-cc60-11e6-982c-822897769e53.png)
![screen shot 2016-12-27 at 6 15 30 pm](https://cloud.githubusercontent.com/assets/2095940/21503488/7be71b80-cc60-11e6-93f4-49b3a4b4358c.png)
![screen shot 2016-12-27 at 6 15 34 pm](https://cloud.githubusercontent.com/assets/2095940/21503490/7bea0fa2-cc60-11e6-89f9-06627e9e1fd4.png)

**Comment by Praxie** [comment]
@sives All buttons have the same height: 43 pixels.

**Comment by Praxie** [comment]
Tested in Safari and Chrome.

**Comment by sives** [comment]
I'm assuming that the "+" and the "?" characters are implemented with fonts, rather than image bitmaps.  Just increase the font size of the "?" character slightly

**Comment by sives** [comment]
(Often in sets of fonts, some characters are implemented a slightly different size, and you need to make a manual correction in some circumstances)

**Comment by Praxie** [comment]
@sives All icons have the same size as well.
![screen shot 2016-12-27 at 6 20 12 pm](https://cloud.githubusercontent.com/assets/2095940/21503572/28d0a5a0-cc61-11e6-917e-2894645ec664.png)
![screen shot 2016-12-27 at 6 20 17 pm](https://cloud.githubusercontent.com/assets/2095940/21503573/28d156a8-cc61-11e6-9b5d-ab9bc104d9ff.png)
![screen shot 2016-12-27 at 6 20 21 pm](https://cloud.githubusercontent.com/assets/2095940/21503574/28d1ef14-cc61-11e6-86f3-af6332731b29.png)

**Comment by Praxie** [comment]
@sives It's a fontawesome issue.

So I can make the question mark icon 1px higher:

![screen shot 2016-12-27 at 6 22 42 pm](https://cloud.githubusercontent.com/assets/2095940/21503640/a90b193a-cc61-11e6-8b28-1c117ad421e6.png)

**Comment by sives** [comment]
OK great.  Let's finalise the actual size increase via screen sharing in our next review meeting on Friday.
