### ISSUE TITLE
Enhanced discussions

### ISSUE THREAD

**Issue by RevelsGit** [Pliohub/Plio#414]
We need to make sure users are notified when there's a relevant new message.   

Users to be notified by default:
Standards discussions - standards "owner" user
Risks discussions - "identified by" user
Nonconformities - "identified by" user

These users can switch off these notifications by clicking on the new "disable this type of notification" feature described in section 3 below.

In addition, we need to implement a way to alert a specific user with an @ command e.g. @steve.   When the user types in an @ command with a name, it will usually be the first name of the person they intend to alert.  Plio needs to match the text of what they type with the names of all Plio users, using a typeahead style field similar to the one we implement in certain Plio card fields, and matching to either the first name, the second name or the email name.

**Comment by sives** [comment]
This could be implemented fairly simply, in a 2 stage logical process.  First we need some new typeahead code that is invoked when a user types an "@" command into the message box.  This code will match the text string typed by the user to a list of user names.   Second, when the user clicks on return to send the message, we need some code that creates a notification via the Plio notification system to the previously-selected user.

**Comment by Praxie** [comment]
@sives the way to disable these notification is not implemented yet. We decided to do this in the next milestone. Right after we go live with the current release.

**Comment by Praxie** [comment]
**Plio version 0.2.80**
