### ISSUE TITLE
Review of standards (and risks)

### ISSUE THREAD

**Issue by RevelsGit** [Pliohub/Plio#416]
The document review function (contained just in the Risk register screen at the moment) needs to be extended to deal with reviewing Standards documents also.   Let's just implement exactly the same simple design that we currently have in the Risk register screen.

Also, a reminder email and desktop notification function needs to be added to both Standards and Risks to remind people to carry out the review.   Reviews are due 12 months (by default) after the creation date of the relevant Organization, and this is when reminder notifications should be sent out.  Important note: review reminders are not sent for each individual document, but for each document collection, otherwise users would be flooded with reminders at review time.

A new Review frequency subcard is contained within Org settings, see SC41 Review frequency subcard in the Standard subcard spec v1.2.   The review frequency can be changed from the default value of Every 12 months to Every 6 months or Every 24 months.

**Comment by Praxie** [comment]
@sives who will receive an email notification to review documents? "Identified by" user?

**Comment by sives** [comment]
Standards:
The Standards owner should appear by default in the Notify changes sub card list, but other users can be added to this list.  The review notification should go to all users listed in the Notify changes sub card list.

Risks:
The "Identified by" user should appear by default in the Notify changes sub card list, but other users can be added to this list.  As with the Standards review process, the review notification should go to all users listed in the Notify changes sub card list.

**Comment by Praxie** [comment]
@RevelsGit review reminders are left to be implemented. 
Volodymyr completed everything else in i416-review-of-standards-and-risks.

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/456

**Comment by Praxie** [comment]
@RevelsGit 
In the read mode it's better to just lay out it as a single line of text
"Document reviewed by [Michael Rokosh] on [06 Mar 2017] with comments "[this is the comment text]""
If no comments then 
"Document reviewed by [Michael Rokosh] on [06 Mar 2017]"

We should display the last 3 reviews (or less than 3)

**Comment by Praxie** [comment]
![screen shot 2017-02-17 at 6 40 24 pm](https://cloud.githubusercontent.com/assets/2095940/23074148/a1708f9a-f540-11e6-9860-eae2a96ef83b.png)

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/463

**Comment by sives** [comment]
Some minor user interface issues with SC41 Review Frequency subcard:

1. Field label "Review annual date" should be "Annual review date"
2. Field label "Start reminding" [2 weeks] "before annual review date" should be "Start reminding" [2 weeks] "before review date"
3. There should be more white space between the Standards and Risks section in the SC41 subcard.
4. Date format in "Annual review date" field should be formatted as "20 Sep" and not "September, 20" to match more closely with our normal date formats ("20 Sep 2017"). 

Some minor issues in SC14 Reviews subcard:

1. Change "Scheduled date" to "Scheduled review date"
2. Change "Reviewed at" to "Actual review date"
3. Change error message "Review executor is required" to "Reviewer name is required" (this is the error you get when you try and save the subcard without setting a reviewer name)
4. Reviewer name should default to current user and shouldn't need to be set manually.
5. The Comments field should not be a mandatory field.  The user should be able to save the subcard without filling in this field.

**Comment by RomanValihura** [comment]
fixed #472

**Comment by Praxie** [comment]
@RomanValihura  I can't save a new review item. It's a bug.

![screen shot 2017-03-17 at 11 39 52 am](https://cloud.githubusercontent.com/assets/2095940/24037435/795d4dc8-0b06-11e7-838c-0814f9a2cb08.png)

**Comment by Praxie** [comment]
**Plio version 0.2.100**

**Comment by sives** [comment]
Tested - looks good
