### ISSUE TITLE
Work inbox list reordering

### ISSUE THREAD

**Issue by RevelsGit** [Pliohub/Plio#417]
I've now realised through my experience in using the Plio system that I made an error in the design of the first two list views in the Work inbox screen (Work - my current, and Work - team current).

These two list views should be ordered by earliest completion target date i.e. dates that are nearest to today at the top, dates that are most distant from today at the bottom.  Currently the ordering is the reverse of this.  I've updated Screen spec v1.2 to reflect this change.

**Comment by RomanValihura** [comment]
Fixed in PR #418

**Comment by Praxie** [comment]
**Plio version 0.2.77**

**Comment by sives** [comment]
Looks good
