### ISSUE TITLE
Help document can exist in a section and in FAQs

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#419]
An individual help document might be part of a help section, and also part of the FAQs section.   Currently there is no way of achieving this, except by duplicating the document and entering it twice with different section names.

Can we allow for multiple selection of Sections in the Section field of the Help document?

**Comment by RevelsGit** [comment]
@sives do you only want an ability to add multiple sections to the help document? Just like departments, standards fields work? Am I correct?

**Comment by sives** [comment]
Yes.  This should allow me to categorise help documents into two different sections, so that they show up in two different sections in the left hand side list view

**Comment by RomanValihura** [comment]
@sives Yes, we can make the field multiple

**Comment by RevelsGit** [comment]
@sives should we limit sections to only 2? if there is two sections does one one them has to be in FAQs section? How it should behave when the user selects a document which has 2 sections? Should both sections open like in nc/risks filtered by departments or only a current one?

**Comment by sives** [comment]
Let's put this on hold until Mike gets back.  It's getting too complicated.
