### ISSUE TITLE
Attachments with "?" character in file name do not upload

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#420]
In the Standards screen and in the Help center, any file with the "?" character at the end of the file name will not upload properly (red error box).   This is a valid character, so the file should be able to be uploaded.

**Comment by RevelsGit** [comment]
@sives It is not a valid character for the file name or at least for the windows. The majority of users are windows users.

**Comment by sives** [comment]
OK, let's put this enhancement on hold

**Comment by sives** [comment]
However we need a better formatted error message when a user uploads a file with a non-permitted file name (not the cryptic technical red box)

**Comment by sives** [comment]
So let's just fix the error message for now.

**Comment by RomanValihura** [comment]
Fixed in PR #422

**Comment by Praxie** [comment]
**Plio version 0.2.77**

**Comment by sives** [comment]
I tested it with a file that had a question mark (?) in the file name and it worked fine.

**Comment by markokruustuk** [comment]
Closed from GitHub
