### ISSUE TITLE
Need to refresh RHS cards after search completion

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#421]
When you go into a screen (e.g. Risk register) and search on an item using the LHS search box (e.g. RK16) then after the search operation has completed, we need to update the card on the RHS side with the first card in the list of search results.

At the moment, the user interface just leaves the original card in place.   This confuses the user, because they've searched for RK16 (in Southwind) and after completing the search operation the LHS list view has changed but they still see RK18 on the right hand side (when they are expecting to see RK16)

**Comment by Praxie** [comment]
An update: 
We don't need to update the card on the RHS side with the first card in the list of search results.

(The text label in the RHS card isn't confirmed yet)
![screen shot 2017-01-11 at 11 33 13 am](https://cloud.githubusercontent.com/assets/2095940/21842995/dd0f70f0-d7f1-11e6-8385-f460b1d27af4.png)

**Comment by sives** [comment]
We don't need to, but it would be more convenient and more intuitive for the user if we did update the card on the RHS automatically.

**Comment by Praxie** [comment]
**Plio version 0.2.79**
