### ISSUE TITLE
Can't upload files in the discussion in the staging application

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#427]
mike@jssolutionsdev.com
![57b28d5fdca4a9d158ae768560f1090d](https://cloud.githubusercontent.com/assets/2095940/21820579/eda0c852-d778-11e6-9329-e8498a8b90f3.gif)

**Comment by Praxie** [comment]
**Plio version 0.2.78**

**Comment by sives** [comment]
Works fine when I tested it

**Comment by markokruustuk** [comment]
Closed from GitHub
