### ISSUE TITLE
Action reminders have incorrect wording

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#437]
Reminders are being sent out by Plio with incorrect wording relating to how many days before or after the due date.  I received this notification today (on Jan 18th - 4 days after the due date of Jan 14th) about PA27 when it was 4 days past due, but in the notification the email stated it "This action is 4 days before due".

**Comment by Praxie** [comment]
**Plio version 0.2.82**

**Comment by sives** [comment]
Still seeing this issue in a notification email I received at 5am this morning (see below).

![screen shot 2017-01-20 at 09 36 20](https://cloud.githubusercontent.com/assets/2330529/22143988/06597074-def4-11e6-88e3-1423ed26dfb3.png)

**Comment by sives** [comment]
The wording should be:  "This action is 2 days overdue"

**Comment by Praxie** [comment]
@sives I've created a few actions on Wednesday. 
The wording is correct.  

Today, Jan 26th:
![Uploading Screen Shot 2017-01-26 at 11.12.11 AM.png…]()

Yesterday, Jan 25th
![screen shot 2017-01-26 at 11 12 42 am](https://cloud.githubusercontent.com/assets/2095940/22325800/86409574-e3b8-11e6-90de-285d2e3fe939.png)

Second action that is overdue:
![screen shot 2017-01-26 at 11 14 12 am](https://cloud.githubusercontent.com/assets/2095940/22325809/a5405e96-e3b8-11e6-8225-dbd6d6389387.png)

A spacing line bug is related to another issue.

**Comment by markokruustuk** [comment]
Closed from GitHub
