### ISSUE TITLE
Incorrect ordering of Deleted list views

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#439]
The ordering of deleted Standards documents in the "Standards - deleted" list view is incorrect.  The ordering (see Screen spec v1.2) should be in chronological order with the most recently deleted at the top.  The actual ordering at the moment seems to be alphabetical.

![ordering of deleted standards bug](https://cloud.githubusercontent.com/assets/2330529/22101766/b0d31b04-de2c-11e6-9eed-3ea838609fcb.png)

The ordering of deleted actions documents in the Work Inbox is incorrect.  The ordering should be chronological with the most recently deleted at the top.  The actual ordering is not in conformity with the spec (see screenshot below).

![ordering of deleted actions bug](https://cloud.githubusercontent.com/assets/2330529/22101822/eda7090a-de2c-11e6-9ce6-7adf4ffd63f7.png)

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/443

**Comment by Praxie** [comment]
**Plio version 0.2.82**

**Comment by sives** [comment]
Just spotted that ordering of deleted Risks is not quite correct (RK35 should be above RK 34 in the Risks - Deleted list view)

![screen shot 2017-01-20 at 09 44 36](https://cloud.githubusercontent.com/assets/2330529/22144373/67a519d6-def5-11e6-92d1-d0e075a4de34.png)

**Comment by Praxie** [comment]
**Plio version 0.2.83**

**Comment by markokruustuk** [comment]
Closed from GitHub
