### ISSUE TITLE
Deleting a document in the Standards screen - odd side-effects

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#440]
In the Southwind Capital Management demo organization, I deleted the Standard titled "7.1 New client onboarding".  When I switched to the "Standards - deleted" list view, I could not see this document in the left hand side list.  

Also, deleting any single Standards document seems to mess up the display of file attachments in other Standards documents, so that the file attachment is now incorrect, referring to a different document to the one that was originally attached.  I'm now seeing quite random file attachments in the Southwind Standards screen (see below - before this got messed up, the naming of file attachments matched the title of the Standards document).

![file attachment incorrect name bug](https://cloud.githubusercontent.com/assets/2330529/22102247/a734d75c-de2e-11e6-8c38-a3197cce3776.png)

![screen shot 2017-01-19 at 10 02 48](https://cloud.githubusercontent.com/assets/2330529/22102251/ab925f4a-de2e-11e6-91a5-90e5428fe9f8.png)

**Comment by RevelsGit** [comment]
> In the Southwind Capital Management demo organization, I deleted the Standard titled "7.1 New client onboarding". When I switched to the "Standards - deleted" list view, I could not see this document in the left hand side list.

I tested this in both the local and live app and it seems to be working fine.
The second part is a bug confirmed.

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/442

**Comment by sives** [comment]
Try deleting and adding back a document multiple times.  I had deleted and then added back a document three times when I spotted the bug.

**Comment by RevelsGit** [comment]
Can't reproduce. Maybe you just accidentally permanently deleted the file instead of restoring it.

**Comment by sives** [comment]
I can't reproduce it either, so let's not worry about this first part of the bug.  However the second part can be reproduced

**Comment by Praxie** [comment]
**Plio version 0.2.82**

**Comment by markokruustuk** [comment]
Closed from GitHub
