### ISSUE TITLE
Add an option to disable Email notifications to My Preferences

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#444]
![screen shot 2017-01-20 at 12 40 45 pm](https://cloud.githubusercontent.com/assets/2095940/22146552/b35ad15a-df0d-11e6-8bf3-649a9ae2a626.png)

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/452

**Comment by Praxie** [comment]
@RevelsGit Here is a list of notification types: 
1. Invitations (Added, Invited, Accepted).
2. Daily recaps.
3. User account related notifications (Reset password, Verify email).
4. Action reminders.
5. Root cause analysis reminders. (It's related to #4).
6. Workflow reminders.
7. Notify changes notifications.
8. ”You have been assigned to <do something>" (to do a root cause analysis/complete an action/verify an action)
9. Org transfer notification.

1, 3 and 9 shouldn't be blocked by My preferences because they are of great importance.
Currently, 1 and 9 notifications are blocked by this feature. It should be fixed.
Maybe we should add a new argument to NotificationSender - isImportant. Important notifications can't be blocked by the user.

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/455

**Comment by Praxie** [comment]
**Plio version 0.2.89**

**Comment by sives** [comment]
Tested and it works fine.
