### ISSUE TITLE
Customers screen infinite loading on production

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#448]
It seems to have stopped working.  Also, the "Plio customers" option in the dropdown menu used to only appear when I was in the Plio Limited workspace, now it is appearing when I switch into other workspaces.

(Once you opened Plio Ltd, the "Plio customers" item won't disappear in other organizations because of the cached data)

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/449

**Comment by Praxie** [comment]
**Plio version 0.2.84**

**Comment by markokruustuk** [comment]
Closed from GitHub

**Comment by markokruustuk** [comment]
Reopened from GitHub

**Comment by markokruustuk** [comment]
Closed from GitHub
