### ISSUE TITLE
Importing document collections

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#457]
Many compliance consultants have created collections of compliance documentation that represent "best practices" i.e. they describe procedures that are regarded as being correct and effective.  As part of their consulting service they make these documents available to their clients, either free or on a chargeable basis.  These might include a best-practice Compliance manual (possibly 50 or more individual Standards documents) and a best-practice Risk register (possibly 50 or more example Risks).

For a compliance consultant that wants to use Plio with their clients, it will be time-consuming to set each client with a standard starter set of best practice documents if they each have to be added manually.

Plio already makes it possible for a consultant to set up one or more "example organizations" (actually, just standard Plio organizations) within their Plio account, each of which would contain a different collection of best practice documents intended for a client in a specific industry sector.  What I want to add as a new feature is the ability - for administrators only - to import documents into a Plio organisation from one of their pre-existing organizations.

The option to import documents would be made available to the consultant administrator user when they go into an empty Standards or Risks screen, and after they click on the Add button.  They would then be given the option (using the Add modal multiple selection user interface pattern - see the sketch titled "3.19 Add modal with multiple selection v1.2"  on Basecamp) to either add a single document or to import documents from an existing organization.  

For example, let's imagine a consultant (called "CM Partners") who works in two different industry sectors (financial services and healthcare) has registered a Plio account and then created 2 model organizations in their workspace called "CMP - Financial services", and "CMP - Healthcare".  For each model organization they create a Standards manual with approx 50 sector-specific compliance standards documents and a Risk register with approx 50 sector-specific Risk records.

Lets imagine the consultant administrator user sets up a new organization in the consultant's workspace called "Brown Brothers Ltd" which is one of his clients in the financial services sector. The first time that the consultant administrator user enters the Standards screen, when it is completely empty, he clicks on the Add button and then he is given the option to either add a single document or to import documents from an existing organization for whom he acts as administrator, in other words from either "CMP - Financial services" or "CMP - Healthcare".  He selects the "CMP - Financial services" option, he is then presented with the number of documents and asked if he want to confirm the bulk copy operation.  If he clicks "Yes", he is prompted to enter his password, and then the collection of 50 existing Standards documents from this organization is loaded into the Brown Brothers Ltd Standards screen in a batch process.   

The same thing happens when the administrator user first enters the Risk register.  On clicking the Add button, he is presented with the option to Add a single Risk record or import from either of the two other existing Organisations. 

There should be no option presented to the administrator user to add documents from another Organization when the Standards screen or the Risk register already contains documents - it has to be done at the beginning, when there are zero Standards documents in the Standards screen or zero Risk records in the Risk register screen.

(Note - a Plio administrator for a specific organization is any user that has the Edit user superpowers permission enabled in User Superpowers in that organization)

**Comment by Praxie** [comment]
When the user opens an empty screen (Screen with no documents at all) and clicks on the "Add" button, the modal appears.
![screen shot 2017-02-03 at 10 41 37 am](https://cloud.githubusercontent.com/assets/2095940/22821461/d0cb82c6-ef83-11e6-87b5-875b16b79eef.png)

**Comment by Praxie** [comment]
We agreed that the second item should be collapsible. It will contain a list of all organizations where the current user is Owner.
![screen shot 2017-02-10 at 11 37 44 am](https://cloud.githubusercontent.com/assets/2095940/22821807/66e5a3b2-ef85-11e6-81d4-ff9330094a7b.png)

**Comment by Praxie** [comment]
@RevelsGit Please notice, that if the user deletes all documents from the screen permanently, then the modal window displays again after clicking on the Add button.

**Comment by Praxie** [comment]
@RevelsGit Also notice, that we don't need to import deleted documents. (Deleted listview)

**Comment by Praxie** [comment]
@sives there is a problem.
We can't import fields that contain a reference to another data. (Types and sections are defined in Org setting, so in the Standard document there is a reference (id) to that value in Org settings)

**Comment by Praxie** [comment]
![screen shot 2017-02-14 at 6 48 31 pm copy](https://cloud.githubusercontent.com/assets/2095940/22939359/15599c6e-f2e7-11e6-8063-d13eff1fb464.png)

In this screenshot I illustrated which fields can't be exported. 
Owner can be replaced with the user that initiated import.
It will be a bit hard to clone files because the url is stored in the File document. The Standard document contains only a reference to that File document (it's ID).

**Comment by Praxie** [comment]
The content of all these subcards won't be exported too.

![screen shot 2017-02-14 at 6 57 56 pm](https://cloud.githubusercontent.com/assets/2095940/22939523/aced3ee6-f2e7-11e6-8546-12e3e09c965e.png)

**Comment by Praxie** [comment]
It doesn't make sense to import "Initial risk analysis" data.
![screen shot 2017-02-14 at 7 02 59 pm](https://cloud.githubusercontent.com/assets/2095940/22939687/3977cae8-f2e8-11e6-9966-aa87c1a5a268.png)

So basically we can easily import only top fields with raw data. (Name, description etc)

**Comment by sives** [comment]
Let's remove import of Risks from the requirements for this milestone.
For Standards, it's OK to not import those fields that you have indicated, that can't be exported.
Owner should be replaced by current user, as you suggest.
File attachments will need to be cloned.
URL links and video's should be retained, still pointing to the same locations.
Its OK to not import the sub card data.

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/462

**Comment by sives** [comment]
User interface does not conform to the specification - see screen sketch "3.19 Add modal with multiple selection v1.2" on Basecamp.

The selection options should be labelled as follows:
Instead of "Add a first standard document" it should simply say "New standard"
Instead of "Setup a bulk insert from other organization" it should simply say "Import from..."

The second option should only appear if the user is an administrator of another organisation that has at least one Standards document in its database.

Finally, the message on the right hand side should be:
"There are no standards yet.  Click on the "Add" button to add your first standard."

**Comment by Praxie** [comment]
**Plio version 0.2.93**

**Comment by sives** [comment]
This needs to be tested with the documents in the Plio Limited organization, before I start testing.  I have assigned ownership of this organization to Mike, so he can test it.

**Comment by sives** [comment]
Tested and working as specified.

**Comment by sives** [comment]
Just spotted one issue.  If document is uncategorized in LHS list view, do not label it as "UNC" but just leave out the category label completely.

**Comment by sives** [comment]
After importing a set of Standards documents from Plio Ltd into Alfaholics, they are not displaying properly in the default list view, which should be categorized by section. 

If they were displaying properly there would be a well-ordered listing, categorized by section, from section 1 to section 10 in the LHS list view.   

Also, the category label in the left hand side list view should not be displayed as "UNC", it should simply be left blank.

**Comment by Praxie** [comment]
@sives 
> The category label in the left hand side list view should not be displayed as "UNC", it should simply be left blank.
Fixed in **Plio version 0.2.96**
