### ISSUE TITLE
Add an Email address field to Org settings

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#459]
![screen shot 2017-02-10 at 3 21 47 pm](https://cloud.githubusercontent.com/assets/2095940/22828202/ac79e112-efa4-11e6-8255-adb4bb3068ea.png)

It should be disabled. It should contain current org owner's email.

**Comment by RevelsGit** [comment]
https://github.com/Pliohub/Plio/pull/460

**Comment by Praxie** [comment]
**Plio version 0.2.90**
