### ISSUE TITLE
Email notifications getting delayed

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#465]
We have a new customer Hiab Ltd (CU156) who is reporting the following problem.  Email notifications are not happening immediately when they should, e.g when a Corrective action is updated, but are coming through in a batch a few days later.  I will forward you some of these delayed notifications by email. This is an urgent one to fix.

**Comment by Praxie** [comment]
@sives Dmity couldn't reproduce this bug in his development environment. I've re-deployed the background application that may fix this bug. Please let me know if this issue will appear again. I can't reproduce it too (locally and on production).

**Comment by sives** [comment]
We need a ping-type monitor that runs once every hour to check that each background process is still running.  If the process is not running for any reason then everyone in the Plio organization gets notified via email.

**Comment by Praxie** [comment]
**Plio version 0.2.99**
