### ISSUE TITLE
Mis-labelling of Plio organizations screen

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#467]
In the LHS dropdown menu in the Home screen, the Plio organizations screen is currently mis-labelled as "Plio customers".  It should be labelled as "Plio organizations" as in the Step 3a specification document in Basecamp, to match the existing header labels in this screen.

**Comment by Praxie** [comment]
**Plio version 0.2.94**

**Comment by sives** [comment]
Looks good.

**Comment by markokruustuk** [comment]
Closed from GitHub
