### ISSUE TITLE
Numbering issue in Plio organizations screen

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#468]
Small cosmetic issue - The numbering of items in the left hand side List view category header is not formatted according to the normal item numbering layout rule that we use in subcards.  The number of items should be shown as a number at the right hand side of the collapsible List view category header  e.g. 
"Paying subscriber                  6"
 "Free trial                              25" 

and not with the current format (see attached screenshot).

The font size of the number should be the same as the font size of the text label.  The positioning of the number should follow the existing pattern when we display item numbers in subcard headers (e.g. in the Nonconformities card, Edit mode).

![screen shot 2017-02-25 at 10 25 49](https://cloud.githubusercontent.com/assets/2330529/23330469/52720bb0-fb46-11e6-89d3-46f86c6ac714.png)

**Comment by Praxie** [comment]
**Plio version 0.2.94**

**Comment by sives** [comment]
Looks good.
