### ISSUE TITLE
Enhancements to Nonconformity record card

### ISSUE THREAD

**Issue by RomanValihura** [Pliohub/Plio#473]
Instead of fields for Identified by and Identified date, we replace with the following fields:

Originator: (current user, but can be changed, defaults to current user)
Owner: (current user, but can be changed)

Neither of these fields can be left blank.

The Owner is typically someone in the front line of the business, in a business department, that is assigned to investigate and deal with the problem.  The Originator is typically someone in a Compliance or Quality role.

The Identified date field is no longer required (we still keep track of the Created by and Created date in the card footer).

Field help is provided on the Originator and Owner fields, which explains the difference between the Originator and Owner roles.

Finally, Hiab wish to make the requirement to link a Nonconformity to a Standard optional instead of mandatory.  I think this may be difficult, given the current design.  Perhaps we could create a default Standard called "Unspecified" which users could link to if they have no specific Standard in place to link the nonconformity to?   This needs to be discussed further.

**Comment by RomanValihura** [comment]
Where I can find help text for "Originator" and "Owner" fields?

**Comment by RomanValihura** [comment]
#476

**Comment by Praxie** [comment]
@RomanValihura There should be Originator and Owner fields there.
![screen shot 2017-03-24 at 11 55 19 am](https://cloud.githubusercontent.com/assets/2095940/24289177/cc67734a-1088-11e7-9257-2bf910d671a3.png)
