### ISSUE TITLE
Enhancements to Nonconformity workflow

### ISSUE THREAD

**Issue by RomanValihura** [Pliohub/Plio#474]
The new desired workflow in the 6 step case is illustrated in sketch 1.2a v1.22. There are no changes needed to the 3 step workflow;

Summary of steps:

- [x] - Non-conformities (or Risk) is logged by an Originator.
- [x] - An Owner of the Non-conformity (or Risk) is also assigned when the Nonconformity is first logged. 
- [x] - The Owner is then responsible, by default, for carrying out the next step in the workflow -  the Root Cause analysis - together with any Corrective or Preventative actions.  
- [x] - The Owner can delegate carrying out the Root Cause Analysis and any Corrective Actions to others, but they still remain the Owner of the Nonconformity.
- [x] - Once actions have been completed they need to be verified as effective.  This defaults to the Nonconformity Owner, but can be delegated to a different person
**One action can be linked to multiple Non-conformities so "To be verified by" can't have a default value**

- [x] - Once all actions have been verified as effective, the Nonconformity enters the Approval stage. A request is sent to the Originator to approve an update to the relevant Standard.  The Originator can reassign this approval request to someone else in a Quality or Compliance role or to the Standard owner, but not to anyone else. Once complete and approved, the Nonconformity would then be classified as closed
**Reassign to any other user**

- [x] - the system does not force an update to the relevant standard, but it does notify the existing Owner of that standard that the approval to update has been made by the Originator
**Notify all users from the Notify changes list**

- [x] This is the existing set of possible statuses of a Non-conformity (6 step workflow):

Open - just reported, awaiting analysis (amber)
Open - analysis due today (amber)
Open - analysis overdue (red)
Open - analysis completed, action(s) need to be added (amber)
Open - analysis completed, action(s) in place (amber)
Open - action(s) due today (amber)
Open - action(s) overdue (red)
Open - action(s) completed, awaiting verification (amber)
Open - verification due today (amber)
Open - verification past due (red)
Open - action(s) verified as effective, awaiting update of standard(s) (amber)
Open - action(s) verified as effective, update of standard(s) due today (amber)
Open - action(s) verified as effective, update of standard(s) past due (red)
Open - action(s) failed verification (red)
Closed - action(s) verified, standard(s) reviewed (green)
Deleted (no colour)
(16 in total)

This is the desired new set of possible statuses of a Non-conformity (6 step workflow).  All changes are in indicated in bold.

Open - just reported, awaiting analysis (amber)
Open - analysis due today (amber)
Open - analysis overdue (red)
Open - analysis completed, action(s) need to be added (amber)
Open - analysis completed, action(s) in place (amber)
Open - action(s) due today (amber)
Open - action(s) overdue (red)
Open - action(s) completed, awaiting verification (amber)
Open - verification due today (amber)
Open - verification past due (red)
Open - action(s) verified as effective, **awaiting approval (amber)**
Open - action(s) verified as effective, **approval due today (amber)**
Open - action(s) verified as effective, **approval past due (red)**
Open - action(s) failed verification (red)
Closed - action(s) verified, **approval given, and notification(s) sent to Owner(s) of standard(s) to remind them to update standards  (green)**
Deleted (no colour)
(16 in total)

### sketch 1.2a v1.22.
![1 2a problem handling corrective action workflow - full - v1 22](https://cloud.githubusercontent.com/assets/17511584/24037656/36b66382-0b07-11e7-87f6-d9b034e5ca10.jpg)

**Comment by sives** [comment]
Mike - I've updated the screen sketch 1.2a so that the last box (number 6) in the workflow is now titled "Final approval (to close)".  I've also changed the user descriptions under boxes 2,3,4 and 5 to allow for the reassignment of these steps in the workflow to other users if needed (e.g. someone leaves the company, or is sick).

**Comment by sives** [comment]
Mike - here are the text strings you requested:

Work inbox - Quick action panel (pink panel) wording:
To do
Give your approval that non-conformity NC11, which is currently open, can now be closed.

Work inbox - LHS list view item 2nd line of text wording:
NC11 - Request for approval to close this non-conformity

To do item model dialog wording:
Title: Request for approval
Help text: Give your approval that this non-conformity, which is currently open, can now be closed.

Similar wording applies to the text strings that relate to approval of risks, simply replace the word "non-conformity" with the word "risk".

**Comment by sives** [comment]
Now awaiting testing by customer which is starting at the end of this week.

**Comment by sives** [comment]
Seems to be working fine, no issues reported from customer testing.
