### ISSUE TITLE
Can't edit superpowers

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#478]
Steve Ives can't check/uncheck superpowers for other users while being an org owner.
It seems that the action is not passing the validation process after security refactoring.

**Comment by Praxie** [comment]
It can be reproduced only in Plio Ltd

**Comment by sives** [comment]
This bug happens if you are a member of multiple organisations and you switch organisations.
Workaround is to refresh the page to change the superpowers.

**Comment by sives** [comment]
Tested and is now working fine
