### ISSUE TITLE
Incorrect NC & Risk owner field

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#485]
When you create a new Nonconformity or Risk, and as part of this process set the Owner to be a different user to yourself (with yourself as the Originator), and then click on the Save button, the expanded version of the Nonconformity or Risk card is then displayed with the incorrect Owner field.   The expanded version of the card is showing the original Owner that was previously displayed before you had changed the Owner to be a different user.

**Comment by Praxie** [comment]
**Plio version 0.2.110**

**Comment by sives** [comment]
This is still not working correctly.  The expanded version of the card is showing the original Owner that was previously displayed before you had changed the Owner to be a different user.  Only when you click on "Close" and move back to the Edit mode of the card does it display the correct Owner.

**Comment by sives** [comment]
Tested and now working fine.
