### ISSUE TITLE
Desktop notifications not appearing in Notifications Center

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#488]
When a Plio desktop notification arrives for a user, it appears as a desktop notification on screen but unlike the normal desktop notification behaviour it is not getting stored in the Notifications Center history pane (on my Mac running OSX 10.11.6).   However, notifications that arrive as email notifications do get stored in the history pane.  

Let's investigate if there is a setting that needs to be set in the message format to enable this to happen.

(This would be a logical behaviour if the user has set his Plio preferences to receive both desktop and email notifications, because it prevents two copies of each notification item being stored in the Notifications Center history pane.  However, if the user has set their Plio preferences to receive just desktop notifications and not email notifications, then they would wish them to be stored in the expected way in the history pane. This would allow them to review them later.)

**Comment by Praxie** [comment]
https://apple.stackexchange.com/questions/57611/disappearing-alerts-notification-center-not-working-as-per-preference-setting

@sives It looks like we can't resolve this issue due to some issues with Notifications Center.

**Comment by sives** [comment]
This would explain why notifications are not getting stored in the Notifications Centre.  However it doesn't explain why we are getting duplicate notifications (issue 490)

**Comment by Praxie** [comment]
@sives I agree. It has nothing to do with #490.
