### ISSUE TITLE
Improvements to Risk and NC cards (customer request)

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#489]
When a new Risk or NC card is first filled out, the user is presented with a cut-down version of the card.   This cut-down version should include the Description field below the Risk or Nonconformity name field (just as in the larger version of the card).

And if possible....
If the Description text is filled in at the beginning in the new version of the smaller card, then this text should be included in the first email notification to the Owner user that they have been assigned ownership of the Risk or NC (put in brackets after the Risk or NC title).

**Comment by Praxie** [comment]
**Plio version 0.2.110**

**Comment by Praxie** [comment]
@sives I couldn't find an easy way to add the description to the notification.

**Comment by sives** [comment]
Great - works as specified
