### ISSUE TITLE
Duplicate notifications problem

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#490]
When I create a new NC or Risk record, setting the Owner to be a different user,  that user gets sent 3 desktop notifications which get displayed in rapid succession on the screen, see image below.  Two of these appear to be duplicates ("Steve Ives set root cause analysis...").   They are displayed too quickly to be remembered, even by an attentive user. None are being saved in the Notifications Center history panel on my Mac (running OSX 10.11.6) so I can't review them after receiving them.

When I look at the email notifications associated with the same events, I expect to see one email notification relating to the assignment of the NC or Risk to me as an Owner, and one email notification relating to the request to carry out a Root Cause Analysis.  However, I am not seeing the first assignment email, even though it does appear as one of the desktop notifications.  I am only receiving the second notification to carry out the Root Cause Analysis.

The desktop notification duplicates issue and the missing email issue both need to be fixed, because they are bugs that are very visible to the user.   

Desktop notifications need to get saved by the Notification Center so I can review them later, hopefully this is something that we can control by structuring the notification messages appropriately.  This needs to tested to work for both Mac and Windows users.

![screen shot 2017-04-20 at 13 16 44](https://cloud.githubusercontent.com/assets/2330529/25230620/8e3225a8-25cc-11e7-89be-3fdf1eaa6794.png)

**Comment by Praxie** [comment]
There should be only two notifications after creating NC:
1. About doc ownership
2. About RCA assignment

**Comment by sives** [comment]
Mike has been able to reproduce this issue

**Comment by sives** [comment]
It working better, but still not perfect.  

When I create a new NC or Risk record, setting the Owner to be a different user, and assigning the Root Cause Analysis to that different user, then that user now gets sent 4 desktop notifications which get displayed on the screen in 3 second intervals, see images below.  2 of these notifications relate to the assignment of ownership of the NC and 2 of them relate to the assignment to do the root cause analysis.  The expected behaviour of the system is to display just 2 desktop notifications, rather than 4.

The other problem is that when I set up a new NC record and I DON'T set the Owner to be a different user, and then I save the NC record, and then go and set the Owner to to be a different user in a subsequent step, neither a desktop nor an email notification is sent out.

 
![screen shot 2017-05-26 at 09 21 03](https://cloud.githubusercontent.com/assets/2330529/26487083/da229980-41f5-11e7-9825-91eef82b796d.png)

![screen shot 2017-05-26 at 09 21 08](https://cloud.githubusercontent.com/assets/2330529/26487085/de5faf7e-41f5-11e7-94fd-32282e6d5812.png)

![screen shot 2017-05-26 at 09 21 13](https://cloud.githubusercontent.com/assets/2330529/26487087/e0f90212-41f5-11e7-9219-eeec2f7d9446.png)

![screen shot 2017-05-26 at 09 21 18](https://cloud.githubusercontent.com/assets/2330529/26487088/e398712e-41f5-11e7-81e9-037fa0d7f0fb.png)

**Comment by Praxie** [comment]
@sives from what I see, If you will change the owner to a different user, that user will receive a desktop notification (if he's online) OR an email notification (if he's offline). Is it a desired behaviour? We decided to do that to decrease a number of spam email notification.

**Comment by sives** [comment]
@Praxie I didn't see either a desktop notification or an email notification when I tested it and set the Owner to be a different user.  As you state, the desired behaviour is that the user receives just a desktop notification if he is online and just an email notification if they are offline.

**Comment by sives** [comment]
Tested and working fine now.
