### ISSUE TITLE
Review dates in Org settings do not line up with dates in Risk & Standards subcards

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#494]
![screen shot 2017-05-09 at 13 03 26](https://cloud.githubusercontent.com/assets/2330529/25850226/5aa8526a-34b9-11e7-9488-116891e9a06c.png)
In Plio Ltd, the annual review date for both Standards and Risks is set to April 2nd.

When you open the Standards or Risks cards, you see different scheduled review dates (e.g. May 9th, May 11th) but you don't see the correct scheduled review date, which should be April 2nd.

**Comment by Praxie** [comment]
Hi @sives. It's not a bug. We have 3 days review frequency in this organization. The starting point is 3 Apr so the schedule of reviews will look like this:
3 Apr, 6 Apr, 9 Apr, 12 Apr, 15 Apr, 18 Apr, 21 Apr, 24 Apr, 27 Apr, 30 Apr, 3 May, 6 May, **9 May**.
But we use 3-days/1-week frequencies only for testing purposes.
I remember that we decided to rename the Annual review field.

**Comment by sives** [comment]
OK, I understand
