### ISSUE TITLE
Standards book screen - improvement plan notification

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#60]
When you select an Owner of the Improvement Plan in this sub card, this person needs to be notified by email that they have been selected as Improvement Plan owner for the named Standards document, and also notified of any review dates.  Reminders will also need to be sent before the review dates  (Add the option "Improvement plans" to the Reminders sub card in the Org Settings)

**Comment by Praxie** [comment]
@sives I imagined it to be a part of the Milestone 3.

**Comment by sives** [comment]
@Praxie Yes, we can push this to Milestone 3.  Suggest that you create a Milestone 3a milestone on Github and link this issue to that milestone.   Also I suggest the following naming scheme for milestones:  The first number in 3a i.e. the number 3 refers to the milestone that is referenced in the Plio JSS contract document.  The following letter "a" is the first release made at that milestone point, "b" is a bug-fixed release that includes all the fixes that we jointly agree should be in that release, and "c" is a hopefully-final release for that milestone that includes fixes to anything that still didn't work (or was a regression) in the  "b" release.  Sound good?

**Comment by Praxie** [comment]
Completed partially. On hold until the Review implementation.

**Comment by Praxie** [comment]
**Plio version 0.2.86**

**Comment by sives** [comment]
I added an improvement plan to a Standard in Plio Ltd and in Southwind, assigned it to myself, but didn't receive any email notification.

**Comment by sives** [comment]
Testing and working fine.
