### ISSUE TITLE
New standard's attachment gets added in 2 places

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#626]
When you add a new Standard, and add a single file attachment, this attachment gets added in 2 places, under Source file (which is where it should be added) and under Improvement plan - Means statement (where it should not be added).  The expected behaviour is just to add the attachment in a single place, under Source file. Once the attachment has been added in two places, the Add button seems to stop working, so that no more Standards can be added.   The correct operation of the Add button can only be restored by doing a complete screen reload in the browser, using the refresh button.

![screen shot 2018-01-04 at 7 04 50 pm](https://user-images.githubusercontent.com/2095940/34575087-2e2baaa8-f182-11e7-84fd-e69415cd1f38.png)

![screen shot 2018-01-04 at 7 04 57 pm](https://user-images.githubusercontent.com/2095940/34575090-2fbc03a4-f182-11e7-9b0f-ed9e74e87cdf.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/630

**Comment by Dartv** [comment]
Although this issue doesn't seem that big, it was really hard to debug. The publication was mutating `fileIds` field of improvement plan even when there were no `fileIds` in the database. Another reason to always use functional programming.

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 01/05/18 - 01/05/18
Work session total: 3:34:34

Grand total: 3:34:34
