### ISSUE TITLE
4. Adding a new key goal

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#705]

**Comment by Praxie** [comment]
Hi @sives, what fields should be included in the "Add key goal" modal window?
Should it look like this?
- Key goal name
- Description
- Owner(s)
- Start date
- End date
- Priority
- Color

**Comment by Praxie** [comment]
@sives as for the Owner(s) field, do we really need to have multiple owners linked to the Key Goal document? Does it mean that we need to change all other "Owner" fields to "Owner(s)" and allow to select multiple users there?

**Comment by sives** [comment]
@Praxie - the Key goal card is specified in Section 4 of the Plio Step 4 requirements document.

See paragraph 3 of Section 4:  "The design of the Key Goals card is shown in Screen sketch 4.10.1 and described further in Screen Spec version 1.3.  The new Milestones subcard is shown in Screen sketch 4.10.2 and described in the Standard subcard spec 1.3. document."

Screen sketch 4.10.1 can be viewed here: https://basecamp.com/1896845/projects/11083679/uploads/40125313?enlarge=310850042#attachment_310850042

**Comment by sives** [comment]
I will ask Jack to create a color picker, so that we can standardise this user interface element

**Comment by Praxie** [comment]
@sives thanks, I saw requirements for the Edit modal window, but there was no information about the smaller version for adding a new document. 

Please take a look at the following examples before asking Jack to create a color picker from scratch:
https://casesandberg.github.io/react-color/

**Comment by sives** [comment]
@Praxie - ah, now I understand the question.  Yes, the small version should contain the 7 fields that you have listed above.

**Comment by sives** [comment]
Regarding the color picker, the simple one marked "Github" looks good

**Comment by Dartv** [comment]
#725
#713

**Comment by sives** [comment]
There should be a new Superpower called "Create & edit Key goals", placed in the list of Superpowers just underneath "Create & edit Standards documents".   This Superpower should be enabled by default for all new users, but an administrator can remove this Superpower for specific users if he wishes.   All users should be allowed to add, edit and delete Milestones, without restriction.

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 01/30/18 - 01/30/18
Work session total: 1:46:40

Grand total: 1:46:40
