### ISSUE TITLE
Replace SelectInput with react-select

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#716]
Current component is too old and getting out of control. It is very hard to add or change something in it. We should create a new component that will use `react-select` library or build new one with `reactstrap` components (any other variants?). It should look identical to the current one but with fixed styles.
Caret icon styling is broken and clicking on it should actually toggle the dropdown (currently it's bugged)
![](https://i.gyazo.com/28c018852205937f49fe275d2229eac0.png)

**Comment by Dartv** [comment]
It should also allow for async data loading

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/763
