### ISSUE TITLE
Fix colorpicker styling

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#726]
Checkmark is not showing for some reason and the background is getting out of boundaries

**Comment by Dartv** [comment]
https://i.gyazo.com/997d72aefe05c76c6497d80c02d307fa.png

**Comment by Dartv** [comment]
It should look like the one here http://ui2.isometrica.io/ui1-3/canvas.html
Click on any plus sign and it should pop up modal with colorpicker in it

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/759
