### ISSUE TITLE
4. Goal edit modal

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#730]

**Comment by Dartv** [comment]
@sives can we move `status` and `statusComment` fields to the bottom of top section? So they are below `color`. Current ordering will mess up reusability of components.

**Comment by Dartv** [comment]
@sives Also, how should "Mark as complete" button behave? Should it open confirmation popup first?

**Comment by sives** [comment]
@Dartv It's fine to move the status and statusComment fields to the bottom of the top section?  No problem at all.

**Comment by sives** [comment]
@Dartv   The "Mark as complete" button should behave in an identical way to the "Complete" button in the Corrective action card (see images below).  The only difference is the text labels.  The button label is "Mark as complete" and the label in the comments field is "Enter any completion comments".

![screen shot 2018-02-07 at 19 21 12](https://user-images.githubusercontent.com/2330529/35936838-58e21dfc-0c3c-11e8-8b75-bd3cb958144f.png)
![screen shot 2018-02-07 at 19 22 17](https://user-images.githubusercontent.com/2330529/35936846-606eb044-0c3c-11e8-8ea2-f8ce9ce9941e.png)

**Comment by Dartv** [comment]
@sives when the goal is completed, should we display `completedBy`, `completed date` fields? Will the user be able to change them? Also, should we add undo functionality?

**Comment by sives** [comment]
@Dartv Yes, we should. It should mimic the behaviour of the Corrective action completion.  This includes the ability for the user to Undo, for up to 60 mins after completion. (Have a play with the Corrective action completion and you will find out exactly how it works)

![screen shot 2018-02-08 at 17 58 52](https://user-images.githubusercontent.com/2330529/35989808-1c1e6baa-0cfa-11e8-910d-36012f655e1f.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/886
https://github.com/Pliohub/Plio/pull/866
https://github.com/Pliohub/Plio/pull/861
https://github.com/Pliohub/Plio/pull/848
https://github.com/Pliohub/Plio/pull/847
https://github.com/Pliohub/Plio/pull/841
https://github.com/Pliohub/Plio/pull/812
https://github.com/Pliohub/Plio/pull/790

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/05/18 - 03/27/18
Work session total: 43:57:24

Grand total: 43:57:24
