### ISSUE TITLE
4. Key goal dropdown menu

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#733]
![](https://i.gyazo.com/1b352e2e55c06162bc411298024a7d8b.png)
When clicking on individual key goal item it should open dropdown menu.
Don't make menu items functional, just markup.
It's not easy to do because all timeline components are svg elements.
Refer to http://formidable.com/open-source/victory/guides/custom-components/ for the example.
Maybe we can use `foreignObject`?

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/784

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/05/18 - 02/05/18
Work session total: 1:36:34

Grand total: 1:36:34
