### ISSUE TITLE
4. Goal edit modal - Milestones

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#737]

**Comment by Dartv** [comment]
@sives I stumbled upon an interesting issue. When changing milestone's `linked to` field, we need to check that the current milestone's `Completion - target date` is in bounds between linked goal start and end dates. Otherwise the data will be inconsistent and render incorrectly in the chart. Take a look at the following example:
We have two key goals:
"KG1 Foo" with start date `01 Feb 2018` and end date `10 Feb 2018`
"KG2 Bar" with start date `20 Feb 2018` and end date `29 Feb 2018`
And a milestone "Buzz" with `Completion - target date` of `25 Feb 2018` linked to KG2
We can't link "Buzz" to KG1 because its `Completion - target date` will be after KG1 end date.
And we can't change `Completion - target date` to be `05 Feb 2018` while it's still linked to KG2
How are we gonna deal with that?

**Comment by sives** [comment]
@Dartv   You make a good point!   How about this relatively simple solution?  Make the "Linked to" field read only and not changeable via a selector.  Then the user has to delete that Milestone and re-create a new one linked to a new Key goal.  Milestones don't have much data associated with them, so this is not a big inconvenience for the user.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/790

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/15/18 - 03/02/18
Work session total: 40:29:26

Grand total: 40:29:26
