### ISSUE TITLE
4. Add help text to goal edit modal

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#756]

**Comment by Dartv** [comment]
@sives what help text should be displayed in goal edit modal?

**Comment by sives** [comment]
@Dartv Here is the Key goal help text:
"In Plio, key goals are defined as your important operational objectives. These can include both shorter and longer term objectives. Key goals should have an owner, plus a target date for completion, with optional milestones and one or more linked actions. Normally, it’s useful to focus on managing a relatively small number of key goals at a time, typically in the range of 5 to 20."

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/14/18 - 02/14/18
Work session total: 0:51:11

Grand total: 0:51:11
