### ISSUE TITLE
4. Change the default number of goals displayed in the top panel

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#769]
Should be 10

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/782

**Comment by Praxie** [comment]
@Serhiy91 
![screen shot 2018-03-07 at 8 10 38 pm](https://user-images.githubusercontent.com/2095940/37109784-ac448396-2243-11e8-8ad4-0924cdffb529.png)
No default value. No collapsible panel.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/809
