### ISSUE TITLE
4. Delete key goal permanently

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#770]
Should also:
1. Permanently delete linked milestones
2. Unlink all linked actions
3. Unlink all linked risks
4. Permanently delete all linked lessons
5. Permanently delete all linked files

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/781

**Comment by Praxie** [comment]
@Serhiy91 Replace "Success" title with 
title: 'Deleted!',
text: `The key goal "${title}" was removed successfully.`,

Milestones removal should be similiar.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/806

**Comment by Praxie** [comment]
@Serhiy91 there is still a Success alert after removal.
Replace "Success" title with
title: 'Deleted!',
text: The key goal "${title}" was removed successfully.,

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/949

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/25/18 - 04/25/18
Work session total: 0:46:51

Grand total: 0:46:51
