### ISSUE TITLE
4. Restore deleted goal

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#771]

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/778

**Comment by Praxie** [comment]
@Serhiy91 

1) To be restored
text: `The key goal "${title}" will be restored!`,
confirmButtonText: 'Restore',

2) Restored

title: 'Restored!',
text: `The key goal "${title}" was restored successfully.`,

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/807
