### ISSUE TITLE
4. "View all items" button for "Completed & deleted goals" list

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#773]

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/779

**Comment by Praxie** [comment]
@Serhiy91  Don't see such button

**Comment by Praxie** [comment]
i730-goal-edit-modal

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/809

**Comment by Serhiy91** [comment]
https://drive.google.com/file/d/14z1M5PNCD6X3LlnkDmDnKLJzSgP6g2Tu/view
