### ISSUE TITLE
Critical bug. Search Standards

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#775]
One of our users has reported the following bug in the Standards screen, which I have been able to reproduce, and here is my evaluation of it below.

> 1. If I search for documents and get multiple results, I find I can only click on the first result to focus on it. Clicking on the second (or third) the focus momentarily flashes to the second but immediately refocuses on the first result. True on both Chrome and Safari on a MacBook and in Chrome on an iPad.

This is a bug.  It seems to happen only in the Standards screen, if you try and do it in the Risks screen and Nonconformities screen it works fine.

Could we fix this bug as soon as possible and get the fix into the live system as soon and as safely as possible?

https://gyazo.com/96fa3d06693c0d2af26037694c90eb90

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/21/18 - 02/21/18
Work session total: 0:32:15

Grand total: 0:32:15
