### ISSUE TITLE
6. Org settings - Workspace subcard

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#787]
refer to https://basecamp.com/1896845/projects/11083679/documents/12951593 for documentation

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/795

**Comment by Praxie** [comment]
@Serhiy91 it takes a very long time to update a Workspace defaults value.

**Comment by Dartv** [comment]
This is super strange. It's hard to debug locally because everything works fast, but the problem may be that the chart rendering blocks the thread, or the subscription is too slow. This section still uses meteor subscription, the actual graphql mutation is fast (200ms on live servers)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/968

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/27/18 - 04/30/18
Work session total: 3:59:54

Grand total: 3:59:54
