### ISSUE TITLE
6. Org settings - Key goals subcard

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#789]
There is a new subcard in Org settings called Key goals.  It allows the user to do two things.  Firstly, switch the scale for the Key goals display between the following 5 options in a standard dropdown menu (labelled "horizontal scale"):
- 1 month, 3 months (default), 6 months, 9 months, 12 months
Secondly to change the default number of Key goals displayed by default in the top panel.  Thirdly to change the number of Key goals displayed by default in the bottom panel (containing completed and deleted Key goals).

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/793
