### ISSUE TITLE
Can't permanently delete documents. SweetAlert: Missing "title" argument!

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#805]

**Comment by Praxie** [comment]
![screen shot 2018-03-07 at 8 22 12 pm](https://user-images.githubusercontent.com/2095940/37110359-582f9410-2245-11e8-8727-66fafdbb27da.png)

**Comment by Dartv** [comment]
Can't reproduce

**Comment by Praxie** [comment]
@Dartv https://staging.pliohub.com/182/standards/ujr4m5JNuWhxSz5MS?filter=3

**Comment by Dartv** [comment]
This is fixed already I think
