### ISSUE TITLE
Key goals section issues

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#808]
1. Don't display "completed & deleted goals" section if there no completed & deleted goals.
![screen shot 2018-03-09 at 10 50 24 am](https://user-images.githubusercontent.com/2095940/37198692-da9e5d80-2387-11e8-8efc-bbfed9d23c07.png)

2. Don't display a "+" button if the user has no "Add/Edit Key Goals" superpower.

3. Don't display the whole Key Goals section if there are no Key Goals and the user has no "Add/Edit Key Goals" superpower.

**Comment by Serhiy91** [comment]
@Praxie 
1. I can not reproduce it. "completed & deleted goals" title is not visible for me if there no completed & deleted goals. Can you retest?

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/820
