### ISSUE TITLE
The "Create & edit Key goals" superpower should be enabled by default

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#852]
It should default to Yes (green tick) for all users. This will ensure that anybody can add a Key goal as a default property of the system.  The Plio org adminstrator can easily edit this superpower if they want to restrict rights to create/edit/delete Key goals.

**Comment by Dartv** [comment]
It is enabled by default. Rerun your migrations

**Comment by Praxie** [comment]
Okay, thanks

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 03/23/18 - 03/23/18
Work session total: 0:09:22

Grand total: 0:09:22
