### ISSUE TITLE
Goal edit modal - optimize forms performance

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#854]
Take a look at https://codesandbox.io/s/32r824vxy1

**Comment by Praxie** [comment]
@Dartv we can't change the way we validate forms. We need to keep the design consistent.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/861

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 03/26/18 - 03/26/18
Work session total: 3:05:28

Grand total: 3:05:28
