### ISSUE TITLE
Key Goal "Close" button should be secondary, not primary

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#856]
![screen shot 2018-03-23 at 11 50 53 am](https://user-images.githubusercontent.com/2095940/37822911-97278c48-2e90-11e8-83b3-deb7983c40ed.png)

Just follow our general rule:
![screen shot 2018-03-23 at 11 52 06 am](https://user-images.githubusercontent.com/2095940/37822945-aead3200-2e90-11e8-8f25-aab979702eca.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/859
