### ISSUE TITLE
Key Goal modal. Display a "Saving..." state after click on the Close button while being focused on the input with updated value

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#857]
https://gyazo.com/c966981a94be761b86b2c3ad233039b0

**Comment by Dartv** [comment]
Should leave this until https://github.com/Pliohub/Plio/issues/881

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1183

**Comment by Dartv** [comment]
Note: this will not work for goal modal, only for action and milestone modals. Need to do some refactoring to make it work with goal modal.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1185

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 07/05/18 - 07/06/18
Work session total: 3:38:27

Grand total: 3:38:27
