### ISSUE TITLE
4. Key goals section - sorting

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#864]
@sives How should goals be sorted? By `start date` or `creation date`? Descending or ascending?

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/869

**Comment by Dartv** [comment]
@sives we already have a field labelled "Priority" for key goals

**Comment by sives** [comment]
That's right, we do.  The allowable values are Critical, Major and Minor (Just like Nonconformities).  This would let us order the Critical ones at the top, then the Major ones, then the Minor ones.  Within each category (e.g. within the Critical ones) we should then list them by target completion date, with the earliest listed first, at the top of the list, followed by Key goals with later target completion dates.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/869
