### ISSUE TITLE
Swal error blocks standards import

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#867]
![screen shot 2018-03-27 at 4 51 08 pm](https://user-images.githubusercontent.com/2095940/37971659-2ebdd692-31df-11e8-9015-228c66caf69b.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/compare/i730-goal-edit-modal...i867-swal-error-blocks-standards-import?expand=1

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 03/27/18 - 03/27/18
Work session total: 1:00:28

Grand total: 1:00:28
