### ISSUE TITLE
List of Milestones/General Actions under the timeline

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#871]

**Comment by Praxie** [comment]
Hi @sives, 
1. How we should order the list? By date from latest to oldest?
2. Should we display Milestones and GActions mixed together, by only changing the shape of the label on the LHS depending on their status?
3. What should we display on click? We can display the same tooltip with Complete(Verify)/Edit/Delete options.

**Comment by Praxie** [comment]
@Serhiy91 @Dartv do you have any other options?

**Comment by sives** [comment]
Please note that Jack Herbert is working on some detail changes to the UI for milestones and General actions under the Key goals timeline (as I mentioned on Friday).  These should be ready very soon.  I will indicate ordering rules when I have these changes from Jack

**Comment by sives** [comment]
@Praxie 

Answers to your questions of 3 hours ago:
1. By date from earliest target completion date to latest target completion date
(if they are completed they drop out of the list)
2. Yes, display mixed together as Jack has shown in the prototype, just changing the shape and colour of the label on the LHS depending on their status
3. Display the same tooltip with Complete(Verify)/Edit/Delete options

**Comment by sives** [comment]
Yes, we can remove them provided that there is an alternative way to access these functions

**Comment by Praxie** [comment]
Hi @sives, I'm asking you to simplify the list of Actions/Milestones:
![screen shot 2018-04-10 at 5 19 40 pm](https://user-images.githubusercontent.com/2095940/38562568-9167f692-3ce3-11e8-95fa-f43c070af795.png)

- For Milestones, having the name of the user after the Milestone title doesn't make sense.
- For Actions, it's complicated to get the name of the user because there may be a different user for each action's state (to be completed, to be verified, completed by, verified by).
- Overall, it'll require us to fetch more data that will have an impact on the performance.

**Comment by Praxie** [comment]
Can we make it this way?
![screen shot 2018-04-10 at 5 28 08 pm](https://user-images.githubusercontent.com/2095940/38563018-8edfbb16-3ce4-11e8-8374-c08d53c89503.png)

**Comment by sives** [comment]
Mike - it's a deliberate design decision to have the user name attached to the Action/Milestone title.  When you are running through the list of actions and milestones in a operational review meeting, it's important to know at a glance who is responsible for carrying out any specific action, that's the only way to know who to ask if it is completed or not (without opening the whole card or sub card).   

For General actions there is only a 3 step workflow, General actions can never have a 6 step workflow, so there is never any need for a verification step. A 3 step workflow is i) Problem/issue reported ii)  Action created  iii) Action completed. I remember mentioning this early on in the project in one of our calls.  It is stated explicitly in the Standard subcard spec specification v1.41 in Section SC5 as follows: "Note - General actions cannot be part of a 6-step workflow, only a 3-step workflow"

**Comment by Praxie** [comment]
@sives I understand your point. It would help a lot if you would clearly state where we can get the user name from. For milestones, there are no "To be completed by" user as well as no "Completed by" user.
For actions, we should always display "To be completed by" user, as I understood.

**Comment by sives** [comment]
Actually, there is no need to display the username or date to the right hand side of the Milestone item, this is only a requirement for General Action items, where we should display the "To be completed by" user.  Hopefully this simplifies the implementation.

**Comment by Serhiy91** [comment]
via Hubstaff
User: Serhiy Zinchuk

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/11/18 - 04/11/18
Work session total: 4:46:57

Grand total: 4:46:57
