### ISSUE TITLE
Close the subcard after saving it (Don't re-open it)

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#874]
It should work like this when we create new document that will populate a new subcard or edit the existing one. Also, it should work like this for Blaze and React subcards.

**Comment by Praxie** [comment]
@Dartv are there any drawbacks?

**Comment by Dartv** [comment]
@Praxie I implemented this for react subcards because we had this exact functionality for blaze. It's an easy fix for react, but I'm not sure about blaze

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/927

**Comment by Serhiy91** [comment]
via Hubstaff
User: Serhiy Zinchuk

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/17/18 - 04/18/18
Work session total: 1:25:36

Grand total: 2:08:43

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/18/18 - 04/18/18
Work session total: 0:43:07

Grand total: 2:08:43
