### ISSUE TITLE
SelectInput is stuttering if multi and loadOptionsOnFocus options provided

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#884]
![peek 2018-04-05 15-28](https://user-images.githubusercontent.com/10619987/38365730-1d88ba82-38e6-11e8-9a97-fedaa786285b.gif)

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/918

**Comment by Serhiy91** [comment]
via Hubstaff
User: Serhiy Zinchuk

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/17/18 - 04/17/18
Work session total: 0:02:57

Grand total: 0:02:57
