### ISSUE TITLE
SelectInput triggers loadOptions when onRemoveMultiValue is called

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#885]
![peek 2018-04-05 15-32](https://user-images.githubusercontent.com/10619987/38365873-9ce5a074-38e6-11e8-8053-c423b35bcaf7.gif)

**Comment by Serhiy91** [comment]
via Hubstaff
User: Serhiy Zinchuk

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/17/18 - 04/17/18
Work session total: 1:16:49

Grand total: 1:16:49
