### ISSUE TITLE
Clicking on the Standard label doesn't open the correct Standard document

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#889]
https://i.gyazo.com/093e4b2bf02ed3d333314a4a6ac5485f.gif

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/892

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/06/18 - 04/06/18
Work session total: 1:28:06

Grand total: 1:28:06
