### ISSUE TITLE
7. Default field values

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#904]
>When creating a new Review (to a Standard or to a Risk), ensure that the actual date field defaults to today's date.  Currently there is no default date, the user always has to enter a date manually.  When creating a new Standard, ensure that the default value for "Type" is initially set to "Standard Operating Procedure" (also change "Chart" to "Org chart" in list of Types).

**Comment by Dartv** [comment]
@sives 

- every organization has it's own "Standard Operating Procedure" type with different `id` and can remove it / change it's name or abbreviation in the org settings. That means we can only set this type as default for organizations that hasn't removed/changed it.
- >also change "Chart" to "Org chart" in list of Types

We don't have any default standard type "Chart"

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/905

**Comment by sives** [comment]
Is it possible to hardwire one of the types only i.e. Standard Operating Procedure to be always present, which the user cannot change and cannot remove, and this is always shown as the default type (I don't mind it this will only work for new organisations)

**Comment by Dartv** [comment]
@sives yeah sure

**Comment by sives** [comment]
OK, let's go with this as the solution.  List of standard types can stay as it is (I forgot that I changed the list for the Southward demo organisation).   However, the grey text label in the right hand side field should be "Short name", not just "Short".    This field should not be displayed for the special case of type = Section header, since it doesn't make sense to have short name code for a section header.

**Comment by Praxie** [comment]
@Dartv wrong error message is displayed when I try to remove the Standard Operating Procedure type. Let's just remove the "X" button to prevent users from deleting this type. What do you think?

**Comment by Praxie** [comment]
![screen shot 2018-05-18 at 7 16 01 pm](https://user-images.githubusercontent.com/2095940/40246120-463fef70-5ad0-11e8-9875-2fa46d70945f.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1139

**Comment by Praxie** [comment]
![screen shot 2018-05-30 at 7 51 16 pm](https://user-images.githubusercontent.com/2095940/40735053-d91910bc-6442-11e8-8ba9-e2219e2aba5f.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/12/18 - 04/13/18
Work session total: 3:52:49

Grand total: 3:52:49
