### ISSUE TITLE
Make Standard Operating Procedure type unremovable and unchangeable

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#907]
https://github.com/Pliohub/Plio/issues/904#issuecomment-380874077

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/909

**Comment by Praxie** [comment]
@Dartv I just removed the Operating Procedure type in the Apiko organization.

**Comment by Dartv** [comment]
@Praxie it only works for new organizations

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/13/18 - 04/13/18
Work session total: 2:20:03

Grand total: 2:20:03
