### ISSUE TITLE
Remove short name field for Section header type

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#908]
And change placeholder to "Short name".
https://github.com/Pliohub/Plio/issues/904#issuecomment-380874077

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/910

**Comment by Praxie** [comment]
![screen shot 2018-05-16 at 7 53 18 pm](https://user-images.githubusercontent.com/2095940/40131524-d4e21a12-5942-11e8-9cb0-4419cba1bed3.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/13/18 - 04/13/18
Work session total: 1:23:36

Grand total: 1:23:36
