### ISSUE TITLE
7. Searching for documents in Standards screen

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#912]
>It should be possible to search for documents by the unique document prefix and/or ID number e.g.  "SOP56".  Also, we should provide a list view which displays these documents in ID number order (categorized by document prefix)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/914

**Comment by Dartv** [comment]
We already have a list view which displays standards categorized by document prefix (standard type abbreviation?).

**Comment by Praxie** [comment]
![screen shot 2018-05-16 at 7 51 08 pm](https://user-images.githubusercontent.com/2095940/40131380-7e59a782-5942-11e8-803c-3a2488143b87.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/13/18 - 04/16/18
Work session total: 3:12:52

Grand total: 3:12:52
