### ISSUE TITLE
Notify changes for Milestones

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#934]
When a user adds, removes or changes a Milestone other users should be notified, depending on which users are listed in the Notify changes subcard.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/942

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/23/18 - 04/24/18
Work session total: 5:34:54

Grand total: 5:34:54
