### ISSUE TITLE
Data export UI issues

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#941]
![screen shot 2018-04-23 at 3 30 14 pm](https://user-images.githubusercontent.com/2095940/39126536-637a58c4-470b-11e8-824d-2c61d8c0da39.png)
![screen shot 2018-04-23 at 3 30 27 pm](https://user-images.githubusercontent.com/2095940/39126538-66665236-470b-11e8-9b52-d843944380f2.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/943

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/24/18 - 04/24/18
Work session total: 3:31:37

Grand total: 3:31:37
