### ISSUE TITLE
There are no Org owner/email values in the Organization settings card

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#945]
![screen shot 2018-04-24 at 9 33 58 pm](https://user-images.githubusercontent.com/2095940/39207160-ee4faed4-4807-11e8-913f-238e6d50afa4.png)

**Comment by Dartv** [comment]
related issue: https://github.com/Pliohub/Plio/issues/893

**Comment by Praxie** [comment]
![Uploading Screen Shot 2018-05-16 at 7.56.04 PM.png…]()

**Comment by Praxie** [comment]
![screen shot 2018-05-16 at 7 56 04 pm](https://user-images.githubusercontent.com/2095940/40131653-3af0da8c-5943-11e8-9e7f-cc83bf1ac7ff.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/25/18 - 04/25/18
Work session total: 1:37:58

Grand total: 1:37:58
