### ISSUE TITLE
There is no Delete button in the Milestone modal window

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#958]
![screen shot 2018-04-26 at 5 16 56 pm](https://user-images.githubusercontent.com/2095940/39311471-aca8b83a-4975-11e8-9177-b6c332cf51f0.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/960

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/26/18 - 04/26/18
Work session total: 0:21:42

Grand total: 0:21:42
