### ISSUE TITLE
There is no Delete button in the GA modal window in the Key Goals section

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#959]
![screen shot 2018-04-26 at 5 21 46 pm](https://user-images.githubusercontent.com/2095940/39311708-52e56072-4976-11e8-9668-8f8045363d89.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/26/18 - 04/26/18
Work session total: 0:29:12

Grand total: 0:29:12
