### ISSUE TITLE
Remove the "Cancel" button from the permanent deletion confirmation alert

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#962]
![screen shot 2018-04-26 at 7 52 39 pm](https://user-images.githubusercontent.com/2095940/39319990-72f7250c-498b-11e8-8434-7e08f9408701.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/27/18 - 04/27/18
Work session total: 1:22:21

Grand total: 1:22:21
