### ISSUE TITLE
Home screen - change icon label of Nonconformities to Nonconformities & gains

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#975]
>In the Step 4a system, the "Non-conformities" icon label on the home screen icon will change to "Nonconformities & gains"

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/976

**Comment by Praxie** [comment]
![screen shot 2018-05-18 at 7 14 19 pm](https://user-images.githubusercontent.com/2095940/40245934-b13db13c-5acf-11e8-9a67-85248890367d.png)
