### ISSUE TITLE
No error when clicking on save button in subcard with empty fields

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#979]

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/980

**Comment by Praxie** [comment]
![screen shot 2018-05-16 at 7 57 35 pm](https://user-images.githubusercontent.com/2095940/40131712-69ae6768-5943-11e8-8802-33a1186442fd.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/30/18 - 05/01/18
Work session total: 0:49:25

Grand total: 0:49:25
