### ISSUE TITLE
"Online" users aren't shown

### ISSUE THREAD

**Issue by Ulfhar** [Pliohub/Plio#981]
Preconditions:
Two or more users should be online.

Expected result:
The "user online" tab should show actual information about users in the system.

Actual result:
The user sees only himself.

![online users bug](https://user-images.githubusercontent.com/25507879/39432188-7e3fce6a-4c9b-11e8-9ecb-99d7bf87b8d6.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/984

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/01/18 - 05/02/18
Work session total: 2:05:56

Grand total: 2:05:56
