### ISSUE TITLE
 Counters don't updates [Home Page]

### ISSUE THREAD

**Issue by Ulfhar** [Pliohub/Plio#982]
Steps to reproduce:
1. Invite a new user to the project
2. Sign In as just created user

Expected result: 
All documents which have been created before the user signed up shouldn't be marked as "new"

Actual result:
All documents marked as "new". Users can't change this status (even if they were reviewed).

![counters](https://user-images.githubusercontent.com/25507879/39433843-9dfbacac-4c9f-11e8-9ad2-5fc42f958132.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/983

**Comment by Dartv** [comment]
P.S: counters update every minute

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/01/18 - 05/01/18
Work session total: 2:44:33

Grand total: 2:44:33
