### ISSUE TITLE
Can not change the quantity of days in the "Workflow reminders" subcard [FireFox]

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#986]
**Steps to reproduce:**

1. Open the "Workflow reminders" subcard in the Org settings
2. Change the quantity of days 
3. Go out from settings
4. Again open the "Workflow reminders" subcard

**Expected result:** 

User can change the quantity of days successfully

**Actual result:**

Can not change the quantity of days for nonconformity, risk, improvement plans. See below 
https://drive.google.com/file/d/1RWjzuKZ0BnkM_ctKs7QLXYiA4paiFGO4/view?usp=sharing

**Comment by Dartv** [comment]
Firefox doesn't focus on input if arrows are clicked https://bugzilla.mozilla.org/show_bug.cgi?id=1012818
Because of that, onfocusout event never fires

**Comment by Dartv** [comment]
console.log('mousedown', e.target.value, e.target);

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/995

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/03/18 - 05/03/18
Work session total: 1:17:47

Grand total: 1:17:47
