### ISSUE TITLE
Owner of the organization doesn't have all rights

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#987]
**Steps to reproduce**:

1. Open the "Apiko Alpha Testing" organization
2. Open the "tester R Smit" profile

**Expected result:**

An owner of the organization has all rights

**Actual result:**

An owner can not : 

1. Create & delete Key goals
2. Complete any action

![image 7](https://user-images.githubusercontent.com/34645257/39563951-ce36f652-4eba-11e8-97b0-79078517fae1.png)
**P.S. Bug reproduces time to time**

**Comment by Dartv** [comment]
Shouldn't happen anymore for new organizations. It was probably because of migrations.
We can delete these migrations to ensure this never happens again, but I don't think this is necessary

**Comment by Praxie** [comment]
Yes it doesn't happen for new organizations.

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/03/18 - 05/03/18
Work session total: 0:14:52

Grand total: 0:14:52
