### ISSUE TITLE
The occurrence doesn't open [FireFox]

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#988]
**Steps to reproduce:**

1. Open the nonconformity 
2. Create the several occurrences at least four 
3. Open and close each one of them 

**Expected result:**
 
An occurrence subforms open successfully

**Actual result:**

An occurrence subform doesn't open (for instance NC6 of the "Apiko Alpha Testing" organization)

https://drive.google.com/file/d/1GxNvPwbrc3D1o9K8pndZYM7Kl3gY8aaw/view?usp=sharing

**Comment by Praxie** [comment]
Actually, this bug appears only during stress testing. The regular user won't be clicking a subcard multiple times as fast as he can. @sives let me know if you'll eventually reproduce this bug .

**Comment by sives** [comment]
We don't want the modal to be opening for ages.  I will evaluate this issue when I do my next testing, but I would say don't refactor the code for now and don't do the easy fix either.
