### ISSUE TITLE
The "Login" or "Home" page doesn't load

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#989]
**Steps to reproduce:** 

1. Open the browser
2. Enter in the URL field: https://staging.pliohub.com
3. Click "Enter" 

**Expected result:**

Should be opened the "Login" page if user isn't logged or "Home" page of the relevant organization if user is logged

**Actual result:**

The empty page is displayed, see below 

![image 1](https://user-images.githubusercontent.com/34645257/39571139-344fe5a8-4ed3-11e8-9c80-3615b71a43e9.png)

**Comment by Dartv** [comment]
This is not a bug, it's intentional design decision
