### ISSUE TITLE
The PA page and CA page do not load 

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#990]
**Steps to reproduce:**

1. Open the "Risk" that has the PA (CA)
2. Click to open PA  

**Expected result:**

The PA (CA) page loads successfully

**Actual result:**

The PA (CA) page doesn't load and the loader is shown all the time. 
The same situation if we open the  "Standarts"

https://drive.google.com/file/d/1t6-7J4A-ltbLhro3Ocu4TMMFYa1F_9HO/view?usp=sharing

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1004

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/04/18 - 05/04/18
Work session total: 3:15:51

Grand total: 3:15:51
