### ISSUE TITLE
Wrong redirection the "NC" button 

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#992]
**Steps to reproduce:**

1. Open the "Work inbox"
2. Click to "Work - team current" in he header 
3. Select the CA with status "overdue" 
4. Click to  "Linked to" button (NC) (for instance CA 7 of the "Apiko Alpha Testing"  organization)

**Expected result:**

The "NC" button has to redirect to the relevant page of NC

**Actual result:**

"NC" button redirect to another CA 
The same situation with PA

https://drive.google.com/file/d/148vDeI4lO7dt7qLrGXhCMrAx20nn-ovU/view?usp=sharing

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1004

**Comment by Praxie** [comment]
@Dartv I still can reproduce this bug - https://gyazo.com/03840f954d7e58dbdfd72dc8ad9c608d

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1126

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/23/18 - 05/24/18
Work session total: 0:20:13

Grand total: 0:20:13
