### ISSUE TITLE
The guideline text goes out of border of the "Nonconformity"  form

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#993]
**Steps to reproduce:**

1. Open the "Nonconformity guidelines" in Org settings
2. Add the continuing text to the  "Nonconformity guidelines"
3. Open the creation "nonconformity" form and click to active text "Guidelines"

**Expected result:**

The continuing text is transferred to several lines down

**Actual result:**

The continuing text goes out of the border 

![image 3](https://user-images.githubusercontent.com/34645257/39574339-78750e82-4edf-11e8-8985-08912ff041d2.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1005

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/04/18 - 05/04/18
Work session total: 1:02:57

Grand total: 1:02:57
