### ISSUE TITLE
The double header is displayed after opening "CA"("PA")

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#994]
**Steps to reproduce:**

1. Open the new tab (sometimes browser)
2. Open the "Risks" page
3. Select the existed risk that has a "CA" or "PA" and to click to one of them

**Expected result:**

The page is opened with the default header 

 **Actual result:**

The page is opened with double header

![the double header](https://user-images.githubusercontent.com/34645257/39574868-40a0d05c-4ee1-11e8-8759-907b254f7485.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1004
