### ISSUE TITLE
The error message is displayed in the edit "Key Goal" form after clicking twice to button 

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#996]
**Steps to reproduce:**

1. Open the edit form of some "Key Goal" 
2. Click "Mark as completed"
3. Click twice to "Complete" button

**Expected result:**

The "Key Goal" is completed without error message 

**Actual result:**

The "Document cannot be completed" error message is shown 

![image 2](https://user-images.githubusercontent.com/34645257/39583785-905dd6fe-4ef9-11e8-87a1-2923d43c823a.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1007

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/04/18 - 05/04/18
Work session total: 0:18:21

Grand total: 0:18:21
