### ISSUE TITLE
The calendar window slides away in the "Add action" form

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#997]
**Steps to reproduce:**

1. Open the "Add action" form of the key goal
2. Try to slide the months into the future or past

**Expected result:**

The calendar displays the months on the one place

**Actual result:**

The months slide away if we switch them

https://drive.google.com/open?id=1sLNB-P-AN5G5JqVqNWdNvAheXMqpyWaL

**Comment by Dartv** [comment]
This happens to any calendar if it is placed upwards

**Comment by Dartv** [comment]
Seems like a bug with library itself. https://reactdatepicker.com/ they have the same bug

**Comment by Dartv** [comment]
Nevermind, found a way to fix this

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/compare/i505-update-meteor...i997-the-calendar-window-slides-away?expand=1

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1008

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/04/18 - 05/04/18
Work session total: 0:18:31

Grand total: 0:18:31
