### ISSUE TITLE
The subcard error message is duplicated in the main card

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#998]
Steps to reproduce:

1. Open a key goal card.
2. Try to create a new Milestone with invalid date.

https://gyazo.com/98721797b6f452efa628ed7928523f70

**Comment by Dartv** [comment]
Already fixed there: https://github.com/Pliohub/Plio/pull/991

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/04/18 - 05/04/18
Work session total: 0:21:39

Grand total: 0:21:39
