### ISSUE TITLE
The milestone card doesn't handle error messages

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#999]
Steps to reproduce:

1. Open a Create Milestone card by clicking on the "Add milestone" link under the timeline.
2. Enter invalid completion date (too small or too big).
3. Click on the Save button.

The card will close itself, but the Milestone won't be created. Instead, when you'll open a Key Goal card, you'll see the error message on top.

**Comment by Dartv** [comment]
already fixed there https://github.com/Pliohub/Plio/pull/991

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/07/18 - 05/07/18
Work session total: 0:11:13

Grand total: 0:11:13
